### ISSUE TITLE
White screen when launched as cia

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#1]

**Comment by weirdal3333** [comment]
When I try to load a It says some console stuff (too fast to read) after the ds(i) logo flashes, and then hangs at a white screen. 

I would be happy to test and report release loga made to dump important low-level info. I have an O3DS and a N3DS to test with :D

**Comment by weirdal3333** [comment]
When I try to use moonshell 2 to launch a .nds file, there's some sort of dump like on a wii crash.

**Comment by weirdal3333** [comment]
![img_20161207_112407221](https://cloud.githubusercontent.com/assets/3537180/20976203/c499c266-bc6f-11e6-8077-06bfefd4ea2a.jpg)

**Comment by ApacheThunder** [comment]
FYI, MoonShell 2, DSi4DS, and any app that can launch other NDS files will likely fail to do so if launched off SD with nds-bootstrap. That's because they lack the same kind of patch system nds-bootstrap uses to make these apps work. This is not a problem with nds-bootstrap and a fix is not going to happen.

**Comment by weirdal3333** [comment]
When I launch moonshell, there is other stuff that pops up as well. I thought that some of the info in these pictures might be useful to this project, so that's why I'm posting them. I also noticed that it looks for a nonexistant nds file when booting back to firmware. Its in the last photo.

> ![img_20161207_123715_01](https://cloud.githubusercontent.com/assets/3537180/20979212/f7d13434-bc79-11e6-962e-676c8f58d02e.jpg)

> ![img_20161207_123713_01](https://cloud.githubusercontent.com/assets/3537180/20979208/f30e27a4-bc79-11e6-8f5e-d9e7c5d7326b.jpg)

> ![img_20161207_123718_01](https://cloud.githubusercontent.com/assets/3537180/20979216/ffdfc8ac-bc79-11e6-9416-9ab51db6d773.jpg)
> ![img_20161207_123721_01](https://cloud.githubusercontent.com/assets/3537180/20979222/03ed38d0-bc7a-11e6-9645-d314a1242797.jpg)

> ![img_20161207_124504657_burst001](https://cloud.githubusercontent.com/assets/3537180/20979473/13c75438-bc7b-11e6-95bc-fae17d9c5b99.jpg)

**Comment by ahezard** [comment]
Now fixed I found the bug completing the switch to devKitArmR46. Run nds-bootstrap as cia does not have so much advantages though.
