### ISSUE TITLE
jEnesisDS doesn't show up the directory.

### ISSUE THREAD

**Issue by Bl1tzkrieg** [ahezard/nds-bootstrap#10]
Greetings, I already reported this on Gbatemp but I'll report it here as well.

Here's a screenshot:
https://i.imgur.com/1ZZJcBY.jpg (Sorry for the bad quality).

That's the only thing that shows up after opening the emulator when it should show me the folders of my sd card.

I hope this is usefull for you :)

**Comment by ahezard** [comment]
I confirm it remains frozen instead of showing the folders. Thanks for the feedback.

**Comment by shutterbug2000** [comment]
I tested an older version(NeoFlash competition version, 0.5?) and it works. More evidence towards newer libnds compatibility issues.

**Comment by ahezard** [comment]
ApprenticeMinusDS_0.2.6.nds have a similar issue

**Comment by NightYoshi370** [comment]
So what's the story regarding this?
Didn't we fix this issue using RAM Disks?
