### ISSUE TITLE
[Suggestion] Activate 3DS IR-Sensor for a few games

### ISSUE THREAD

**Issue by naendow** [ahezard/nds-bootstrap#106]
Hey

There are some games (like Pokemon HG & SS or Personal Trainer: Walking) that have an IR sensor in the cartridge. Would it be possible to activate the IR sensor that is built into the 3DS? I'd love to use my Pokewalker again!

**Comment by Robz8** [comment]
Nope. TWL_FIRM will have to be hacked to use the 3DS IR-sensor instead of the one in the cartridge.

**Comment by ApacheThunder** [comment]
Yeah doesn't arm9 ultimately handle communication with IR/Wifi and such while in CTR mode? That hardware is likely not accessible once in legacy mode and it would either be really difficult to hack into TWL_FIRM or perhaps impossible due to hardware limitations.

**Comment by shutterbug2000** [comment]
Technically, one could use another IR enabled cartridge I think(i.e. use Pokemon B/W for the Pokewalker), but I'm not sure on that. This would still require an IR enabled cartridge though.

**Comment by Rhlp-Engineering** [comment]
how do i do that?
