### ISSUE TITLE
Pokemon Diamond Not working on 0.5.0

### ISSUE THREAD

**Issue by VegaCrow** [ahezard/nds-bootstrap#108]
I recently got nds bootstrap 0.5.0, I saw that it supported pokemon diamond so I got the rom. To my surprise when I tried to start it I got a white screen. I tried a second time with this one having console output on, still I got a white screen. (Please tell me if I was supposed to put this on TWLoader).

**Comment by Robz8** [comment]
You have to set Mario Kart DS as donor ROM.

**Comment by VegaCrow** [comment]
Ah I see, Thank you
