### ISSUE TITLE
Animal Crossing: Wild World issues

### ISSUE THREAD

**Issue by NinelivesBobcat** [ahezard/nds-bootstrap#109]
It seems that only the US version works as of now. When I stay on the title screen for a while, the game starts lagging and stuttering horribly until I load my save data. From there, audio will be crackly (until I use the phone to change the sound to stereo, which fixes that issue). The game crashes whenever I go inside the town gate (bottom screen goes red, top screen stays black).

**Comment by piratesephiroth** [comment]
Data reads are much better than they were a few months ago but they're still slow.
All games will inevitably stutter whenever they load new data. They behave normally after that data is cached in RAM though.
