### ISSUE TITLE
How close are we to running full retail DS titles?

### ISSUE THREAD

**Issue by Stack3r** [ahezard/nds-bootstrap#11]
Hello ahezard, I just wanted to say you are doing any awesome job with the bootstrap. I do want to ask how close are we to running full retail titles via sd and launcher?

**Comment by Robz8** [comment]
Well, we're not far.

**Comment by Stack3r** [comment]
Not far from complete or not far in the project

**Comment by ahezard** [comment]
Well to be honest we are still quite far.

**Comment by FerrazaDazzle** [comment]
4 months later... How is the progress going? im not trying to rush you or anything like that, im just curious on how far progress is.

**Comment by Robz8** [comment]
So far, we have good speed, with DSi WRAM being data cache. The next step is to add pre-fetching.
