### ISSUE TITLE
[Question] Some pokemon games work, others don't.

### ISSUE THREAD

**Issue by Dysproh** [ahezard/nds-bootstrap#110]
I have noticed that, of the 5 gen4 games, only D/P work, while Pt/Hg/Ss dont. Why is this? I would guess the reason BWB2W2 dont work is because they are TWL, but why dont games from the same generation work?

**Comment by manderly2** [comment]
They use different cards reads that are not yet in bootstrap. And I'm willing to bet there's AP (Anti-piracy) checks as well.

**Comment by Robz8** [comment]
Platinum, HeartGold, and SoulSilver will work in the next version of nds-bootstrap.
