### ISSUE TITLE
Spectrobes - easy async testing

### ISSUE THREAD

**Issue by NWPlayer123** [ahezard/nds-bootstrap#112]
The original Spectrobes (Beyond the Portals seems to corrupt/crash on boot) would be a good test since it does a lot of data streaming, takes forever to load each area and boot movie buffers every second or so

**Comment by dubbz82** [comment]
Movie buffering is now significantly improved (still not perfect) and load times are a lot more reasonable for this game now.  I think this is okay to close out?
