### ISSUE TITLE
Megaman Battle Network 5 Double Team Bug

### ISSUE THREAD

**Issue by midniteday** [ahezard/nds-bootstrap#116]
Every time you JACK IN the screen is lagging, if the games lagging so much you have to restart the game or else it will freeze most often while you are battling virus. Some of the area in the Game such as Oran4 is completely black. You cannot see anything besides your character. Another area called Oran3 is completely destroyed, the area looks like a mirror that has been cut up and shifted so nothing lines up the correct way. I stop playing after Oran area because i cannot navigate past that area.

**Comment by Robz8** [comment]
Should be fixed in versions 0.6.0 and later.
