### ISSUE TITLE
Just a few games I've tried

### ISSUE THREAD

**Issue by cjm86** [ahezard/nds-bootstrap#117]
Noticed a few missing from the compatibility list:
Big Bang Mini works perfectly, with force nds bootstrap
GRID boots to a red screen with writing
Assassin's Creed Altair's Chronicles boots to white screen
Lock's Quest boots to white screen
The Simpsons Game boots to black screen
N+ boots to black screen
Ninja Gaiden Dragon Sword boots to white screen

**Comment by Minxxe** [comment]
_Didn't want to open a new "issue"_

Pokémon Pearl EUR boots into first a white but changes to a red one after a couple of seconds.
Pokémon Diamond EUR works just like the USA one only with slightly longer load times.

**Comment by Unreal4project** [comment]
@Minxxe 
Weird, mine works just fine.
Note : Pokemon Pearl does not have a EU version, but is country specific (UK,ESP,FR...)

The world ends with you (EU) boots to a red screen
999 - 9 Hours, 9 Persons, 9 Doors (U) works.

**Comment by Minxxe** [comment]
@Unreal4project aight, didn't knew that. it is the German version of Pearl

**Comment by cjm86** [comment]
"999 - 9 Hours, 9 Persons, 9 Doors (U) works."
Nice! Another game that works.

And Big Bang Mini, which is another one that works (and sorry all the games I've mentioned above) were EUR versions. Except for The Simpsons Game and GRID which were both US.

**Comment by cjm86** [comment]
Brain Age 2 - More Training in Minutes a day - Works perfectly, with saving (US)
Ivy the Kiwi - Doesn't work, white screen (US)
9 Hours, 9 Persons, 9 Doors - Seems to work, but very very slow (maybe just the intro/cutscenes) (US)

**Comment by RinMaru** [comment]
Dementium 2 works as of now but you cant load your save game

**Comment by cjm86** [comment]
What are the UN Builds? Are they updated often? Where can I download the UN Builds? Because it is starting to look like this project is dead.

**Comment by Robz8** [comment]
Go to page 4 of settings in TWLoader.

**Comment by RinMaru** [comment]
Yea they are good but Dementium 2 needs to be fixed or patched.


All the games I've tested are in NTSC & Have been tested Using both Clock Speeds and Donor Settings
UN Ver. 7f438e2 

Rayman Raving Rabbids- Works with save support
Aliens Infestation- Boots to black screen
C.O.P. The Recruit- White Screen
Kim Possible Global Gemini- Works with save support
Kim Possible Kimmunicator- Works with save support
Legend Of Spyro a new beginning- Works with save support
Legend Of Spyro Dawn of Dragon- Works with save support
Legend Of Spyro The Eternal Night- Works with save support
Rayman DS- Works with save support
Robots- Works with save support
Spongebob's Atlantis Squarepantis- - Works with save support
Spryo Shadow Legacy- Works with save support
Tomb Raider Legend- Works with save support
Viewtiful Joe Double Trouble- Works with save support but text is missing in cut-scenes and stutters a bit
Tak Great Juju Challenge- Red screen after Opening Dialog 
Yoshis Island DS- Works with save support

**Comment by BtheDestroyer** [comment]
Lost Magic (US) works perfectly with save support without a donor cart. Completed the tutorial, saved, closed, and loaded. There was only a slight pause in the opening cutscene and I'm pretty sure that happens on cart, too.

**Comment by ahezard** [comment]
please restest with the latest cersion and report issues in relevant issues.
