### ISSUE TITLE
 A few games I've tried

### ISSUE THREAD

**Issue by WhiteFenix19** [ahezard/nds-bootstrap#118]
I tried this games in 0.5.1b version
***Pokemon Diamond** EUR - works fine with mario kart DS as donor
 
***Pokemon Ranger Shadow of Almia** EUR  - Cannot boot (Red Screen) Alone or with Mario kart DS as donor (On mode and force-use mode)

***Pokemon Ranger Guardian Signs** EUR - Cannot boot (Red Screen) Alone or with Mario kart DS as donor (In ON mode and force-use mode)

***Pokemon Mystery Dungeon: Explorers of Sky** EUR - Works fine with Mario kart DS as donor

***Pokemon Conquest** EUR - Cannot boot (White Screen) Alone or with Mario kart DS as donor (In ON mode and force-use mode)

**Im sorry for my bad english**

**Comment by Robz8** [comment]
This should be in the compatibility list.
