### ISSUE TITLE
Megaman Zero Collection gives me a white screen when starting

### ISSUE THREAD

**Issue by fighuass** [ahezard/nds-bootstrap#119]
Game:

Release number: 5007
Title: Megaman Zero Collection
Region: EU
nds-bootstrap: (That's the blue text on the bottom left of the top screen on the settings menu, right? It says: Pre-release v0.5.1b)

Donor ROM:

Release number: 5763
Title: Plants vs Zombies
Region: EU

**Comment by Robz8** [comment]
That game is broken for now.
