### ISSUE TITLE
Latest commit of GameYob DS fails to start

### ISSUE THREAD

**Issue by autofire372** [ahezard/nds-bootstrap#12]
After compiling the last commit of GameYob DS Drenn ever made, the resulting emulator does not start via nds-bootstrap. Instead, nds-bootstrap locks up after displaying "TWL mode enabled".

**Comment by ahezard** [comment]
Is it running on a flashcart? Can you share the .nds?

**Comment by autofire372** [comment]
Well, it works on DeSmuME, at least...

As for the .nds file, here you go:
[gameyob.zip](https://github.com/ahezard/nds-bootstrap/files/542895/gameyob.zip)

**Comment by ApacheThunder** [comment]
GameYob is a GB/GBC emulator right? As I recall it supports DSi SD with no patches. I have it installed as a CIA and it works fine so you don't really need to use bootstrap for that one.
