### ISSUE TITLE
Random Game Crash [Mario Kart DS]

### ISSUE THREAD

**Issue by CCF100** [ahezard/nds-bootstrap#120]
View [https://github.com/Robz8/TWLoader/issues/350](https://github.com/Robz8/TWLoader/issues/350) this issue.

**Comment by Robz8** [comment]
Can you try the latest unofficial bootstrap build, and see if the issue is fixed?

**Comment by CCF100** [comment]
Forgot to post: Issue has seemed to resolved itself after microSD upgrade to this card: https://www.amazon.com/gp/product/B00XWPB85Q/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

**Comment by Robz8** [comment]
Pretty sure the latest bootstrap fixed it.
The issue isn't caused by what SD card you're using.
