### ISSUE TITLE
Connection to wii

### ISSUE THREAD

**Issue by Nemilad** [ahezard/nds-bootstrap#122]
Need connection to wii. Pokemon diamond sees wii but stuck on white screen after connection attempt.

**Comment by Sarayalth** [comment]
Same thing happens with v0.10.0

**Comment by Antonio231102** [comment]
I can't wait to see this feature become a thing!

**Comment by MidnightWolfang** [comment]
I can't wait to use this feature! I'm also wanting to connect Pokémon Diamond to the Ranch, crossing my fingers to this be fixed soon!
