### ISSUE TITLE
adjustable cache settings

### ISSUE THREAD

**Issue by piratesephiroth** [ahezard/nds-bootstrap#123]
The cache settings (at least the recent ones) seem to be very dependent on each game.

Let's take Mario Kart DS, for example,
It works near perfectly, with super short loading times if we use commit b792301's settings (READ_SIZE_NDMA7 0x8000 and RAM_CACHE_SLOTS 0x18) though they crash many other games.

If we set READ_SIZE_NDMA7 to 0x6000 or 0x4000, performance starts to degrade and the bottom of the top screen starts to become corrupted, though other games may work better

With READ_SIZE_NDMA7 set to 0x3000, the loading times become very long.

So wouldn't it be better to add that setting to the individual game's options?
This dynamic cache thing isn't helping much, if at all.

**Comment by Robz8** [comment]
Did you try the latest commit with MKDS?

**Comment by Robz8** [comment]
Btw, cache settings are dynamic.

**Comment by piratesephiroth** [comment]
yeah I tested it well after I posted this message, lol.

**Comment by ahezard** [comment]
Every settings in nds-bootstrap can be "per-game", this is more a twloader issue
