### ISSUE TITLE
Super Mario 64 Title Screen Yoshi Bug

### ISSUE THREAD

**Issue by Josh19002** [ahezard/nds-bootstrap#124]
In the latest unofficial build of bootstrap (The RAM cache one, BTW great update) when loading Yoshi on the title screen it creates a bugged version model of it that causes it to stretch across the bottom screen.
![img_0066](https://user-images.githubusercontent.com/31605243/30009740-ebb60ed4-90e7-11e7-99fe-64cfc8740154.JPG)
![img_0067](https://user-images.githubusercontent.com/31605243/30009742-ee5c5a6c-90e7-11e7-9574-8a39825b34be.JPG)

I mainly discovered it when i was testing the new ram loading feature. I got it from going into adventure and going back to the title screen. Though I have to admit the speed of it is incredible.

**Comment by Josh19002** [comment]
I mainly discovered it when i was testing the new ram loading feature. I got it from going into adventure and going back to the title screen. Though I have to admit the speed of it is incredible.

**Comment by Robz8** [comment]
New commit has been pushed! It fixes that issue.
