### ISSUE TITLE
Compatibility list errata

### ISSUE THREAD

**Issue by DMSalesman** [ahezard/nds-bootstrap#125]
Good day.

While I was browsing the [compatibility list](https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit?usp=sharing), I noticed that the entry for `Freshly-Picked Tingle's Rosy Rupeeland` lists a wrong region.

The game has never been released to the USA region, being instead limited to JPN and EUR.

As of now, I was able to run the EUR version off the SD card. It **required Mario Kart DS as donor**, and the startup time is pretty long if using bootstrap release `0.5.1b`. In-game wise, the areas need a moderate loading time, and the game lags a bit, whilst being playable.

The performance is much better as of unofficial bootstrap 3e76575, both in terms of booting and moving the protagonist around, as the first scene does not require as much loading and caching time as with the official bootstrap. Unfortunately, the game freezes with dark grey screen immediately upon exiting the abovementioned area. Waiting, no matter how much, does not help.

**Comment by piratesephiroth** [comment]
yeah, the unofficial bootstrap makes it work very well but it seems to crash at certain points, like when we collect the map and also when we leave his house after loading a save file.

Loading speeds are pretty fast right now but nothing beats commit 6039ef3. It sure broke a lot of games but even  streamed videos played pretty good, buffering like every 3 seconds instead of every second like it is right now.

**Comment by DMSalesman** [comment]
I'm glad that it's a known issue, after all.

Is there someplace for me to find a binary of the commit you quoted, so that I can see for myself? I'm unable to set up a build environment as of now.

**Comment by piratesephiroth** [comment]
here, https://files.catbox.moe/uy2r8w.zip

**Comment by DMSalesman** [comment]
Ah, many thanks.

By the way, even `Rune Factory: A Fantasy Harvest Moon` needed the donor ROM, but this detail wasn't specified in the spreadsheet. I suggest that someone with a bit of patience tests the already listed ROMs in order to fill in the missing details and rectify mistakes, if any.

**Comment by piratesephiroth** [comment]
yeah, the donor rom is pretty much a requirement for every game that uses save data

**Comment by DMSalesman** [comment]
Good to know.

**Comment by piratesephiroth** [comment]
Tingle seems to work on the latest unofficial bootstrap (with long load times)

**Comment by Robz8** [comment]
Ah, nice!
