### ISSUE TITLE
Main Pokemon Games DS Wireless Does Not Work

### ISSUE THREAD

**Issue by MistieKitteh** [ahezard/nds-bootstrap#127]
Local trading, battling, underground, or other local wireless features do not work at the moment. With either errors or black screen crashes.

**Comment by skullkeeper94** [comment]
I believe wireless link in general doesn't work =/

**Comment by Gnarmagon** [comment]
it does work at least for NSMB and Mario Kart DS :D

**Comment by piratesephiroth** [comment]
those games are small and get loaded entirely into RAM though so they run perfectly.

**Comment by BtheDestroyer** [comment]
Perhaps an option could be added (either to this or front ends like TWLoader) to block all wireless communication by intercepting the poll and returning blank dummy information? At least if that were possible things like the Underground would be playable solo.

**Comment by pikachuk** [comment]
why would the online functionnalities be removed ? it should instead be fixed for people who want to use AltWFC

**Comment by BtheDestroyer** [comment]
"Fix it" is some thing that's *very* easy to say but *incredibly* difficult to do, ESPECIALLY when it comes to networking and even more so with a project like this where you don't know how much of the required data is going to be loaded and how each game handles networking differently.

**Comment by pikachuk** [comment]
i know about it
i just said that it shouldn't be removed though

**Comment by ahezard** [comment]
Is this working with latest release?

**Comment by ahezard** [comment]
So for now there is no more issue. If this is specific to only one game please states it, Main Pokemon Games is way too vague.
