### ISSUE TITLE
DSOrganize 3.2 DLDI error

### ISSUE THREAD

**Issue by thejsa** [ahezard/nds-bootstrap#13]
So I just installed the latest version of nds-hb-menu and nds-bootstrap but DSOrganize 3.2 won't boot (I get an error message telling me to ensure that I have DLDI patched it: 

> You are not using a card that is compatible with Chishm's FAT library. Please make sure that you have properly DLDI patched DSOrganize!

Am I missing something vital or does DSOrganize just not work right now?

**Comment by thejsa** [comment]
This seems to work in TWLoader for some reason but not NDS HB menu?

**Comment by Robz8** [comment]
Try changing some settings, and see if you can get the error to appear when running from TWLoader.

**Comment by Robz8** [comment]
It works, because LOCK_ARM9_SCFG_EXT is set to 1. This can be set/unset in TWLoader.
