### ISSUE TITLE
Soul silver. Save error. 

### ISSUE THREAD

**Issue by Dropper101** [ahezard/nds-bootstrap#130]
Not able to save. Gives error about not enough back up memory.

**Comment by takeshineale128** [comment]
I'am getting the same error and mine is a european rom.

**Comment by MistieKitteh** [comment]
Do you have the MKDS rom on your SD card and set as a donor rom?

**Comment by takeshineale128** [comment]
did that and sill get the error

**Comment by Dropper101** [comment]
Will try that solution

**Comment by Dropper101** [comment]
that solved my issue thnks MistieKitteh
