### ISSUE TITLE
Rhythm Heaven weird input behaviour.

### ISSUE THREAD

**Issue by Jostreator** [ahezard/nds-bootstrap#131]
In the game `Rhythm Heaven` ,the touch screen input works incorrectly. It doesnt accept presses in quick succession. This makes most of the minigames impossible to complete. For example if i try to play the minigame "Lockstep" i can only tap the first beat, then it stops accepting inputs. Slower games like "Built To Scale" or "Fillbots" are completable. The game also has lags now and then which make the game harder, but not impossible. The lags glitch out the music, and the lags are completely random. I have no idea if the button inputs are affected as the game is pretty much completely played by the touch screen.

**Comment by Jostreator** [comment]
Input seems to be fixed, which is good. The sound issues have come back though. (The song loading seems to lag a bit, game doesnt hang but tickflow does)

**Comment by ahezard** [comment]
Can you please retest using the latest release?

**Comment by Jostreator** [comment]
It works perfectly now. Thank you.
