### ISSUE TITLE
Compatibility Report

### ISSUE THREAD

**Issue by Lego6245** [ahezard/nds-bootstrap#132]
Pokemon Pearl (USA) [NTR-APAE-USA] - Dumped from Retail Cart using Godmode9 - Blue compatibility (loading lags, some stuttering when moving about in the overworld). Used donor rom.

Lostmagic (USA) [NTR-AM9E-USA] - Dumped from Retail Cart using Godmode9 - Green compatability. Everything seems to be working properly, overworld and battle screen. Used donor rom.

**Comment by mariogamer2** [comment]
You should post this on gbatemp thread (the twloader or the nds-bootsrltrap one).

**Comment by Robz8** [comment]
or the compatibility list.
