### ISSUE TITLE
SM64DS sleep problem

### ISSUE THREAD

**Issue by ClammyMantis488** [ahezard/nds-bootstrap#133]
So on the latest commit as of writing this (06a4558), putting the ds into sleep mode and letting the "buh-bye!" sound effect finish playing will cause the screens to be black when reopened. However, if you get into the options while the screen is still black and disable then enable the backlight, the screen will turn back on until you go into sleep mode again.

**Comment by Robz8** [comment]
You have to set clock speed to NTR mode for SM64DS.

**Comment by ClammyMantis488** [comment]
Oh. sorry for wasting your time then
