### ISSUE TITLE
Digimon World Championship issues

### ISSUE THREAD

**Issue by CJXXxxUnknown** [ahezard/nds-bootstrap#134]
I've tried everything, changing versions from unofficial, release, and even an old version, v 0.5.1b which is the version stated to work on the compatibility list. Nothing I've tried gets the game to load, it sticks to a white screen, and the console output is completely useless. I've tried multiple different settings with no avail. There has only been one time when the game properly loaded, and even then, the game gave an error about unable to access the save data. Help?

**Comment by piratesephiroth** [comment]
Many games have that problem.
Even though there's been some amazing progress, compatibility is still far from perfect.

**Comment by CJXXxxUnknown** [comment]
Is there nothing I can do? I just wanna play Digimon World Championship...

**Comment by CJXXxxUnknown** [comment]
Well, it suddenly started working after spending hours yesterday trying to get it to work... so, I'm just going to call this issue closed since it seems to be something out of general control.

**Comment by CJXXxxUnknown** [comment]
Managed to get the game to work, but when i try to start a new game, it gives the error i was talking about, "The save data could not be accessed. Please turn the power off and reinsert the DS Card."

**Comment by Robz8** [comment]
Is Mario Kart DS set as donor ROM?
If not, check the instructions here: https://gbatemp.net/threads/twloader-ctr-mode-nds-app.448375/

**Comment by CJXXxxUnknown** [comment]
@Robz8 Making Mario Kart DS the donor worked! Much appreciated!
