### ISSUE TITLE
for new update 

### ISSUE THREAD

**Issue by paulxzzero99** [ahezard/nds-bootstrap#136]
There is a issue when i play sonic rush the game gliches and frozzed ate the second zone of the game is there a way to fix this probleme?
And.... 
So is it possible that on the next nds-bootstrap be possible to play the kingdom hearts games on the twloader app?

**Comment by Robz8** [comment]
For the Sonic Rush issue, set it to use NTR clock speed.
As for the next nds-bootstrap version, only time will tell when it's playable.
