### ISSUE TITLE
Something peculiar happened

### ISSUE THREAD

**Issue by CCF100** [ahezard/nds-bootstrap#137]
I was trying to start Mario and Luigi: Bowser's Inside Story, and [this](https://imgur.com/9snEYS4) happened (I know it's listed as incompatible)

**Comment by Robz8** [comment]
That's normal. It's triggered by an exception handler.

**Comment by CCF100** [comment]
Can you elaborate?

**Comment by Robz8** [comment]
When a crash occurs, a red screen with dots is brought up by the exception handler.
The exception handler is set on first card operation.

**Comment by CCF100** [comment]
Can I use the exception handler to find out what happened? If so, how?

**Comment by Gericom** [comment]
The dots represent the location of the crash. It was the easiest to do it with dots xD

**Comment by piratesephiroth** [comment]
> Can I use the exception handler to find out what happened? If so, how?
first we need to talk about paralel universes

**Comment by xorinzor** [comment]
Pretty curious now why you'd choose dots over some kind of stacktrace :P
