### ISSUE TITLE
How to compile on windows?

### ISSUE THREAD

**Issue by xorinzor** [ahezard/nds-bootstrap#138]
So I'm trying to compile master:e67b5c4 (according to Travis that should be a valid build to compile), I installed the DevKitPro with DevKitARM for Windows.

But when I run build_cia.sh I get this:
```
Nintendo DS rom tool 2.0.3 - Jul 14 2017
by Rafael Vuijk, Dave Murphy, Alexei Karpenko
failed to open input file: 'nds-bootstrap.arm9.elf'
Dynamically Linked Disk Interface patch tool 1.24.0 by Michael Chisholm (Chishm)

Trying "dldi/dsisd.dldi"
Cannot open "dldi/dsisd.dldi" - No such file or directory
./build_cia.sh: line 5: python: command not found
[!] Is not a valid TWL SRL file
[!] Failed to retrieve data from Content0: bootstrap.nds
[!] Input Error, see 'C:\<snip>\Desktop\New folder (4)\make_cia.exe -h' for more info
[!] Failed to generate cia
```

and running `make` in Powershell returns this:
```
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/c/<snip>/Desktop/New folder (4)/"c:/devkitPro/msys/bin/make.exe" -C cardengine_arm7'
make.exe": *** [cardengine_arm7] Error 2
```

I also downloaded the latest release of `libdns` and copied these contents into `/devkitPro/libnds` (some files were already existing, I replaced them with the newer ones). Still getting the same issue however.

What am I missing here?

**Comment by piratesephiroth** [comment]
I use ahezard's libnds and I can compile it fine

**Comment by Robz8** [comment]
ahezard's libnds isn't needed, though.

**Comment by xorinzor** [comment]
Tried installing cygwin with `make` and all devel packages for `gcc / c++`, now it throws this error when I run `make`:
```
$ make
make[1]: Entering directory '/cygdrive/c/Users/me/Desktop/New folder (4)/cardengine_arm7'
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `make --no-print-directory -C build -f /cygdrive/c/Users/me/Desktop/New folder (4)/cardengine_arm7/Makefile'
make[1]: *** [Makefile:102: build] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/me/Desktop/New folder (4)/cardengine_arm7'
make: *** [Makefile:159: cardengine_arm7] Error 2
```

I can't find a 1.4.6 of libnds, the lowest release seems to be 1.5.5 and the newest 1.6.2 (https://github.com/devkitPro/libnds/releases), and where should I place the contents of this?
Should I overwrite the existing libnds directory in devkitPro with it?
