### ISSUE TITLE
TWEWY (EU) Red Screen

### ISSUE THREAD

**Issue by Unreal4project** [ahezard/nds-bootstrap#139]
The world ends with you (Europe) boots to a red screen

**Comment by Robz8** [comment]
Compatibility reports go here: https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=0

**Comment by Robz8** [comment]
The US version only works, btw.
