### ISSUE TITLE
Weird SD Card Error

### ISSUE THREAD

**Issue by piratesephiroth** [ahezard/nds-bootstrap#140]
TWLoader crashes to the home menu and seems to break the system when we select a ROM if we run it after using an application that uses the SD card without exiting it properly, like FBI (exiting through Home button, not START button) or MicroSD Management (errors on exit when started from the Home Menu).

It happens after using DevMenu too but I don't think there's any way to close it other than using the Home button.

I suppose this is a bug in TWLoader's SD card initialization because it doesn't seem to happen in any other homebrew.

**Comment by Robz8** [comment]
Wrong repo. :P

**Comment by piratesephiroth** [comment]
oh, I had both tabs opened, lol
