### ISSUE TITLE
Summon Night Twin Age Chapter 5

### ISSUE THREAD

**Issue by fernandofbsb** [ahezard/nds-bootstrap#141]
I was playing summon night twin age and i found a issue. Until the chapter five the game works perfectly, but when a sound dialogue triggers at chapter five a red screen appears and froze the game glitching audio.

**Comment by ahezard** [comment]
Is this still happening with the latest release?

**Comment by fernandofbsb** [comment]
Now it's working perfectly, Thx ^^
