### ISSUE TITLE
Advance Wars Dual Strike Wireless Mode Hangs

### ISSUE THREAD

**Issue by bronozoj** [ahezard/nds-bootstrap#142]
Tested on latest official and unofficial build

Everything else is buttery smooth but anything related to wireless mode (multiplayer w/ or w/out download play) makes the game hang when trying to find another player

Is there any way I could extract more information? (logs perhaps from both 3ds trying to connect with each other?) I am willing to provide if requested

**Comment by Robz8** [comment]
Wireless is known to have some issues.
Also, it's not just this game. It's some others as well (except for Mario Kart DS).
