### ISSUE TITLE
Pokemon distribution roms

### ISSUE THREAD

**Issue by KofiMatson123** [ahezard/nds-bootstrap#145]
Everytime I try to load a pokemon distribution rom it keeps crashing. My mds bootstrap is up to date. Soulsilver works so I dont know why thks one isnt working.

**Comment by BtheDestroyer** [comment]
By distribution rom, do you mean those used in distribution events? Because those aren't compatible yet: https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=0

**Comment by Robz8** [comment]
They should work now, just be sure to turn off donor ROM, as it may cause issues.

**Comment by KofiMatson123** [comment]
I cant find v0.8.0 only that latest one

**Comment by Robz8** [comment]
Re-update bootstrap in TWLoader.

**Comment by KofiMatson123** [comment]
How do i do that? Does it do it automatically? Since my twloader is Ver6.6.4

**Comment by Robz8** [comment]
Go to page 4 in TWLoader settings, then press X and Y.

**Comment by KofiMatson123** [comment]
Okay its updated. Thank you very much!

**Comment by KofiMatson123** [comment]
Can I ask a question? Does PPSE-DS save editor for Pokemon ds games work on Twloader?

**Comment by Robz8** [comment]
Not sure.

**Comment by KofiMatson123** [comment]
It keeps freezing

**Comment by Robz8** [comment]
The distribution ROM?

**Comment by KofiMatson123** [comment]
No. The other thing

**Comment by Robz8** [comment]
Ah, ok.

**Comment by KofiMatson123** [comment]
The distribution roms works though😁

**Comment by Robz8** [comment]
Nice! Good to know.
