### ISSUE TITLE
Screen close causes sound loop

### ISSUE THREAD

**Issue by grint87** [ahezard/nds-bootstrap#146]
Hardware: Original 3DS
ROM: Super Mario 64 DS [EUR]

Closing the device at any point in the game causes a sound loop.
It acts as though the device is continually being closed and reopened, as the Mario SFX are for pausing and resuming the game when the user closes and opens the device.

I have tried with both the official and unofficial releases of nds-bootstrap.

**Comment by Robz8** [comment]
For now, you'll need any type of Slot-1 card inserted to fix the bug.
