### ISSUE TITLE
New Super Mario Bros. Broken Again

### ISSUE THREAD

**Issue by grint87** [ahezard/nds-bootstrap#147]
This game was fixed but is now broken again on 0.6.0 Rev 2 (likely also Rev 1).

**Comment by Robz8** [comment]
Did you set Mario Kart DS as donor ROM?
Also, make sure the NSMB ROM is USA.

**Comment by grint87** [comment]
The requirement of a donor ROM and that the region be USA shouldn't be intended behaviour. I don't think this issue should be labelled "invalid" until a fix is implemented.

**Comment by Robz8** [comment]
Game still works fine for me on 0.6.0 Rev 2.
Have you tried the latest unofficial bootstrap? If so, in case if you switched SD cards, you might need to format it to FAT32 with 32kb cluster size.

**Comment by grint87** [comment]
Can confirm this game works (even EUR region) with Mario Kart donor ROM.
Thank you for your help, please close.
