### ISSUE TITLE
Sound channel missing. (Pokemon HeartGold)

### ISSUE THREAD

**Issue by Caboosium** [ahezard/nds-bootstrap#151]
Problem: Sound channel missing during intro.
Game: Pokemon HeartGold
Launcher: SRloader
Bootstrap Version: "v0.6.1 (Rev 00)"

First time launching the game ans noticed the music did not sound quite right in the intro. Part of the theme is there but the other part is not.

I'll play the game past the intro and see what happens.

**Comment by Caboosium** [comment]
I'm also having the same problem in mario kart. Music is gone but many of the effects stay.

**Comment by Robz8** [comment]
That's normal for the DSiWare version.
Because ARM7 SCFG_EXT is locked, bootstrap can't switch from the DSi BIOS to the DS one, in order for the sound to play correctly.
RocketLauncher version has this fixed, since ARM7 SCFG_EXT isn't locked there.

**Comment by Caboosium** [comment]
How do I get into rocketlauncher? It crashes on start.

**Comment by Robz8** [comment]
It's not released yet.

**Comment by Caboosium** [comment]
You mean the button is just there waiting for the release of rocketlauncher?

**Comment by Robz8** [comment]
Yes.

**Comment by Caboosium** [comment]
Do GB games need Rocketlauncher?

**Comment by Robz8** [comment]
No. They work fine without RL.

**Comment by Caboosium** [comment]
I can't launch them in SRLoader but putting the emulator's .nds in my nds rom folder, running the gb emulator by pressing Y, then selecting my game in the emulator works.
