### ISSUE TITLE
Change 3DS status LED while loading

### ISSUE THREAD

**Issue by BtheDestroyer** [ahezard/nds-bootstrap#153]
Many games (like the mainline Pokemon titles) need to be dynamically loaded during gameplay which causes the game to pause/freeze temporarily. It'd be nice if the status LED could be set to a different color (or show some breathing effect) to show that the game hasn't permanently crashed, but is just loading.

**Comment by piratesephiroth** [comment]
He can only do this on the DSi version.
I think the "virtualized" DS mode doesn't have direct control of the LEDs.

**Comment by Robz8** [comment]
^
