### ISSUE TITLE
Pokémon Platinum and SoulSilver Loading Times

### ISSUE THREAD

**Issue by CrazyOrbitz** [ahezard/nds-bootstrap#155]
Are the loading times on TWLoader for Platinum and SoulSilver better on a N3/2DS? If not, every time it loads a new area, it freezes for a brief 4-5 seconds. I understand my 2DS doesn’t have the processing power it needs, but it could also be a compatibility issue with nds-bootstrap.

Anyway, is there a way to fix this? It just doesn’t feel the same as it used to back when I first played it because of this extremely annoying issue.

Thanks for any help in advance.

**Comment by CrazyOrbitz** [comment]
Ok, thanks.

**Comment by CrazyOrbitz** [comment]
Ok wait. Before this issue gets closed, which R4 card would you recommend? Also a recommended website would be nice too. 

I’d like to have a cheap one without a timebomb, but durable enough for regular/extended use. I just hope I don’t have horrendous shipping times, I’ve seen people order them and not get them for months. 

So if you could help me with this, I’d definitely appreciate it.

 Thanks.

**Comment by piratesephiroth** [comment]
you could get one of the cards recommended in https://3ds.guide/ntrboot

**Comment by Ember2528** [comment]
Plays at cart speeds now on 0.9 on a dsi
