### ISSUE TITLE
I don't think sleep mode is functioning properly on 3ds in the latest builds.

### ISSUE THREAD

**Issue by gooeywreck408** [ahezard/nds-bootstrap#157]
I updated today to the latest official release today while updating twloader and i that noticed now when i shut the lid while playing newer super mario bros ds(a rom hack) it keeps saying "mario time ... come back". on the earlier version of bootstap this was not an issue.it seems like the 3ds thinks it being open and shut repeatedly as it would say those voice lines normally when opening and shutting it before the latest update.

**Comment by gooeywreck408** [comment]
Thanks in advance for all you guy have done on this project and continuing to update it, hope this new issue wont be to hard to fix.

**Comment by Robz8** [comment]
Actually, it's an issue with all bootstrap versions.
You need a Slot-1 card inserted to fix sleep mode.

**Comment by piratesephiroth** [comment]
yeah, even a 3DS cart works

**Comment by gooeywreck408** [comment]
but it wasnt an issue till the latest update. i have a 3ds card inserted. why would it act like the lid is being open and shut ?

**Comment by gooeywreck408** [comment]
I am sorry i even made an issue report. it was happening because i set cpu speed to 133mhz. i never thought that would be the reason for it to happen.

**Comment by piratesephiroth** [comment]
It always happened here, in all versions. Games are never suspended if I don't have a cart inserted in the console. They just run slower because of this open/close loop.
