### ISSUE TITLE
Yu-Gi-Oh Crashes

### ISSUE THREAD

**Issue by Sinon-AnnaTheFurry** [ahezard/nds-bootstrap#160]
I have this issue sometimes, it may crash in some specific situations, for example any time when fighting yugi's grandpa, sometimes even at the end of the battle, sometimes when fighting someone and then encountering Joey (crashes in battle)

And rarely when some monsters are summoned

Also Sonic Rush sometimes crashes in water palace, after making it past that point the game doesn't crash anymore

Also sometimes in pokémon after exiting a battle there might be a strange light effect and characters may look glitchy when walking in the grass, fixes when entering a builiding or changing area

Wario Ware has some graphical issues but it works, screens look duplicated at the very botton and letters look a little strange, not something game breaking

Zelda Spirit Tracks Crashes after the Nintendo logo

Pokémon B/W crashes when the proffesor shows up (game needs an AP patch applied?)

**Comment by Robz8** [comment]
Sonic Rush: Set NTR clock speed to fix that bug.

Pokemon HGSS: The game contains a synchronization error between the VRAM upload and VSync process.

WarioWare Touched: It's actually a TWL_FIRM issue, and not a TWLoader or bootstrap issue. 

Spirit Tracks: Turn off donor ROM for it, and insert a donor cart with a FLASH save chip to get past the title screen.

Pokemon B/W: Even with an AP patch, that issue still isn't fixed.

**Comment by Sinon-AnnaTheFurry** [comment]
Thanks

**Comment by piratesephiroth** [comment]
WarioWare Touched has a dsiware version so you don't really need TWLoader.

**Comment by Robz8** [comment]
^ for it, anyways.

**Comment by Sinon-AnnaTheFurry** [comment]
I'll continue in using TWLoader for this game anyway
