### ISSUE TITLE
Partners In Time Black Screen

### ISSUE THREAD

**Issue by ghost** [ahezard/nds-bootstrap#161]
I'm trying to play Mario & Luigi: Partners In Time through TWLoader, but when I go and try to start a game or load a save, my game black screens. I can still exit the game through the home button, and the title screen works fine (if a bit slow to load), but the game itself doesn't load.

TWLoader Version: v6.6.2
nds-bootstrap Version: v0.7.3
Using MKDS: Yes

**Comment by Robz8** [comment]
Try force-using donor ROM.

**Comment by Duder963** [comment]
I did try that and got the same result.
