### ISSUE TITLE
Constant "SD init failed!" error message

### ISSUE THREAD

**Issue by ClementNerma** [ahezard/nds-bootstrap#162]
Hi,

I tried to play several games with nds-bootstrap with TWLoader but when I launch it, after the health & safety screen, I keep getting the same "SD init failed!" error message.

I tried with MarioKart DS and Mario & Luigi : Partners in Time. I reset my 3DS a few minutes ago and TWLoader is the first app I installed.

I'm currently using TWLoader v6.6.2 (which bundles nds-bootstrap v0.7.3), boot9strap and Luma3DS. My console is up-to-date. My SD card is a 64 Gb formatted in Fat32.

I tried to look for this error on the internet but found nothing, if someone could help me with this that would be nice ;)

**EDIT :** Just tried with Dragon Quest IX and got the same result. However, with Sonic Colors, I just get the blank screen that comes just before the error message (but I don't get this error, the console stucks on the blank screen). I am still able to come to my console's home menu though.

Also, I'm only playing with EUR games.

**Comment by ahezard** [comment]
Is this still true? Try to format the sd card with SDFormatter 4.0.

**Comment by ClementNerma** [comment]
I formatted my 3DS a few days ago so I can't tell, but at my last try the problem was still not fixed.

I have formatted my SD card using MiniTool Partition Wizard in Fat32, so I don't think this is the problem - the console was accepting the SD perfectly too.

On my new New 3DS XL, I don't have this problem, though.

**Comment by ahezard** [comment]
Minitool Partition Wizard is not SDFormatter 4.0, please try what I am suggesting, the fact that the console itself accept the sd is not relevant.
