### ISSUE TITLE
Megaman ZX Advent Chronoforce White Screen 

### ISSUE THREAD

**Issue by Rosquash** [ahezard/nds-bootstrap#164]
This only happens with the US version. Trying to turn into Chronoforce results in the game staying on a white screen and you have to exit out of the game. This happens any time when trying to turn into Chronoforce and only him. You cannot progress through the game without him since you need Chronoforce to open a gate to the next area.

**Comment by Robz8** [comment]
Issue should be fixed in v0.9.0-RC1 now.
