### ISSUE TITLE
Bakugan Battle Brawlers runs with a black screen.

### ISSUE THREAD

**Issue by WodsonKun** [ahezard/nds-bootstrap#166]
SRLoader version: 3.4.2
nds-bootstrap version: 0.7.3
FW ver: 1.4U

Description: When I select the Bakugan Battle Brawlers, it boots on two black screens, but it keeps running (in this case, audio and gameplay).

**Comment by Robz8** [comment]
It black screens, because donor ROM turned on.

**Comment by WodsonKun** [comment]
I'll try Off and Force-use... Wait...

**Comment by WodsonKun** [comment]
Off: Don't boot
Force-use: Same as on (obviously)

**Comment by ahezard** [comment]
Is this still happening with the latest unoffical build?

**Comment by Robz8** [comment]
Probably not, since the black screen issue was due to using donor ROM.
