### ISSUE TITLE
Chrono Trigger: occasional slowdowns

### ISSUE THREAD

**Issue by rrooij** [ahezard/nds-bootstrap#168]
Chrono Trigger starts up and works but has some quirks that make it unpleasant to play:

* Without patching, the anti piracy detection will freeze the game at the teleporter scene (this is not an issue that needs to be solved, as the user can patch the game)
* The games cut-scenes aren't played back properly, they occasionally pause for no reason
* There is a long delay between game rooms. The music hangs a bit before it switches to the next track.

I've also tried setting the clock speed higher, but this does not solve the problems I mentioned. The issues seem similar to that of Final Fantasy IV in the compatibility list.

It seems that stuttering videos are a common issue in other games. Any explanation why this is?

Version 0.7.3 with TWLoader as GUI.

**Comment by Robz8** [comment]
The videos actually do pause for a reason. It's because of the latency between arm9 and arm7, where arm7 does the data loading.

**Comment by Robz8** [comment]
Issue fixed in v0.9.0-RC1.
