### ISSUE TITLE
[DSi] Sound outputs both from speakers and headphone jack

### ISSUE THREAD

**Issue by khang06** [ahezard/nds-bootstrap#170]
Happens on DSi, not sure about 3DS.

For some reason, right channel doesn't work on the headphone jack, either.

**Comment by Robz8** [comment]
That issue is exclusive to the DSi version.

**Comment by Robz8** [comment]
No, it doesn't.

**Comment by Robz8** [comment]
Can confirm this bug does not happen on 3DS.
Also, for DSi users with CFW, this issue has been fixed, starting with nds-bootstrap v0.8.0, and SRLoader v4.1.0.
