### ISSUE TITLE
NiNoKuni slowly...

### ISSUE THREAD

**Issue by tetradog** [ahezard/nds-bootstrap#173]
please can add compatibility?

**Comment by piratesephiroth** [comment]
The game is pretty massive, Even if it's possible to make it run it will have very long loading times, like the Pokemon or Tingle games.

**Comment by Robz8** [comment]
What do you get when trying to run it? A white screen or an error before that even appears?

**Comment by tetradog** [comment]
White screen and other error if use sav from flashcard  cant load...

**Comment by tetradog** [comment]
Mini game appear
