### ISSUE TITLE
Pokemon Black 2

### ISSUE THREAD

**Issue by felipecds** [ahezard/nds-bootstrap#174]
First, thank you for your great work.

I have this scenario:
 1. New 2ds XL, 11.6-39 firmware running TWLoader.
 2. I have a pokemon black 2 cart

With new version, is it possible to boot up hacks like Blaze black 2, using my cart as donor, or even with cart I cant play the game yet (the main reason is the possibility of catch all pokemon and transfer to my ultra sun game)

**Comment by Robz8** [comment]
Even with a cart, it won't work yet.

**Comment by BtheDestroyer** [comment]
I don't think this should be closed until it's functional. Until it's working, I feel that leaving the issue open as a reminder is a good practice.

Not my project though, so do what you like - just a suggestion.

**Comment by ahezard** [comment]
My understanding is that Pokemon Black 2 uses thumb code on arm9. But I have not checked myself. In such case it needs the addition of thumb arm9 card read patches. This will be done at some point in the future.

**Comment by Stack3r** [comment]
This might can be closed for the other issue opened.
