### ISSUE TITLE
RPG MAKER DS

### ISSUE THREAD

**Issue by Grendelia** [ahezard/nds-bootstrap#175]
you read the title. does it work yet. if not will it soon?

**Comment by piratesephiroth** [comment]
you could test it  and then tell us

**Comment by Grendelia** [comment]
aighty

**Comment by ahezard** [comment]
Is this still title working with the latest unoffical build?

**Comment by ahezard** [comment]
Well this game (RPG Tkool DS (Japan)) is actually using thumb so it is not supported currently but will be. closed in favor of #194
