### ISSUE TITLE
3DS Wireless Mode on AW:Dual Strike Does Not Work

### ISSUE THREAD

**Issue by legoboy0109** [ahezard/nds-bootstrap#176]
Ironically enough, it works fine on my dsi with srloader and HiyaCFW, but not on my 3DS using TWLoader. If you try to start a game on the 3DS, it freezes, but if you do it on the dsi it works without problem. If you try to join the dsi hosted game on 3DS, it also freezes, I would like to have another dsi to test and see if 2 dsis could link successfully.

**Comment by legoboy0109** [comment]
I also tried using SRLoader on my 3ds and ALMOST got tit to work, but it went to a "lost connection to the host" screen on both dses.

**Comment by ahezard** [comment]
Is this still happening with the latest unoffical build?

**Comment by Robz8** [comment]
It's already fixed.
