### ISSUE TITLE
Get rid of donor roms for SDK3-4

### ISSUE THREAD

**Issue by shutterbug2000** [ahezard/nds-bootstrap#177]

**Comment by piratesephiroth** [comment]
whoa

**Comment by mariogamer2** [comment]
Just to know, now, which sdk type games need a donor rom ingeneral?

**Comment by piratesephiroth** [comment]
> Just to know, now, which sdk type games need a donor rom ingeneral?

SDK ver. 3 and ver. 4

**Comment by mariogamer2** [comment]
Ok thanks. That would be cool.

**Comment by dubbz82** [comment]
This can probably be closed out?  Still some work to ditch the need of donor roms but that should be a separate issue.

**Comment by piratesephiroth** [comment]
well it's not finished yet

**Comment by RinMaru** [comment]
so is the plan to have games save to SD as well and not just needing a Cart in place of rom?

**Comment by piratesephiroth** [comment]
since yesterday it already works for a ton of games

**Comment by Robz8** [comment]
We have saves working for all SDK1-4 games without a donor now.
