### ISSUE TITLE
Yoshi's Island DS/The Legendary Starfy fails with donor rom

### ISSUE THREAD

**Issue by OmeletHopper** [ahezard/nds-bootstrap#184]
As of 0.8.0, Starfy freezes on a white screen when a donor rom is used. With donor rom off, it does boot but saving both read/write does not work without a physical cart. I should also note it works on 0.7.4.

**Comment by filthycoding** [comment]
The same happens with USA and EU versions of Yoshi's Island DS, apparently.

**Comment by NightYoshi370** [comment]
Donor ROM is gone and out of here. If the game is SDK 1 or 2, it should already have save patches. Some SDK 3-4 games have save patches, but not all. Please test if these games work with the latest bootstrap release.

**Comment by OmeletHopper** [comment]
I can confirm Starfy works as of the latest dev release, thanks to [@shutterbug2000's amazing saving code](https://github.com/ahezard/nds-bootstrap/commit/b40e2fecad640789640ecae92321067c20f32abe). Woohoo!
