### ISSUE TITLE
NSMB5 Clone Tag Team 1 crashes

### ISSUE THREAD

**Issue by YYoshi241** [ahezard/nds-bootstrap#186]
NSMB Hack, NSMB5 Clone Tag Team 1 (the second has no issues) crashes after intro no matter the bootstrap version.

**Comment by OmeletHopper** [comment]
Have you tested it on a flashcart?

**Comment by YYoshi241** [comment]
Don't own a flash cart yet.

**Comment by YYoshi241** [comment]
Clone Tag Team 2 suffers from crackles (48Khz) 
(0.9.2 is better than 0.7.4)

**Comment by YYoshi241** [comment]
CTT2 also echoes on Pause Screen (0.9.2; not on 0.7.4 though) (48kHz)

**Comment by YYoshi241** [comment]
AS OF THE LATEST BOOTSTRAP (0.9.2) THIS ISSUE NO LONGER SEEMS TO OCCUR :)
BUT Suffers from an always present echo.
(like MHUMB does https://github.com/ahezard/nds-bootstrap/issues/245)
