### ISSUE TITLE
Tingle's Rosy Rupeeland - long loading time

### ISSUE THREAD

**Issue by piratesephiroth** [ahezard/nds-bootstrap#188]
I'm not sure if it's even a real issue but "Freshly Picked - Tingle's Rosy Rupeeland" has the same long initial loading time as before the recent changes (about 1 minute of whitescreen after the game boots). 

It's also able to read the save on the SD but unable to write it, but that's probably caused by the incomplete save support for SDK 3 games.

It's the only game I've seen with such a behaviour. Even "Ripened Tingle's Balloon Trip of Love" loads instantly.

**Comment by Robz8** [comment]
Bomberman 2 also has this issue.
Selecting Story Mode just goes to a black screen, but after having it using the old IRQ method to run cardEngine, it's only stuck on the black screen for 15-30 seconds. Doing anything else just gives more slow load times.

**Comment by Stack3r** [comment]
This might can be closed for the other issue opened.
