### ISSUE TITLE
Mario Party DS needs donor cart

### ISSUE THREAD

**Issue by LeddaZ** [ahezard/nds-bootstrap#189]
Mario Party DS (EUR) needs a donor cart to save (tested with DSi, DSiMenu++ 4.2.0, nds-bootstrap 0.9.0-RC2 and Super Mario 64 DS (EUR) as donor cart.

**Comment by Robz8** [comment]
Any cart that uses the EEPRROM chip, which SM64DS uses, will work as donor for MPDS.
Also, this issue will be resolved soon.

**Comment by ahezard** [comment]
Is this still true?

**Comment by Robz8** [comment]
Nope. It reads my save from SD now.
