### ISSUE TITLE
Chrono trigger

### ISSUE THREAD

**Issue by mcamacho97** [ahezard/nds-bootstrap#190]
Im using the last version of nds-bootstrap(0.9.0RC2) and the game stuck in the screen "initializing save file memory. Do not power off the console", I dont know why happened that because in the version 0.7.2 the game works, anybody can explain me why?? Thanks

**Comment by Robz8** [comment]
There's issues with saving in that version.

**Comment by mcamacho97** [comment]
Oh thanks for solve my query, I hope in the future version this works again and great work with the fix of the Game card speed in the games, it's really awesome!.

**Comment by ahezard** [comment]
Is this still happening with the latest unoffical build?

**Comment by mcamacho97** [comment]
what is the latest unofficial build?? Im using the last version of the repo from DSiMenu++ v 4.2.0,DSiMenu++ Launcher v 1.1.0 and nds bootstrap v 0.9.0 RC2.

**Comment by Robz8** [comment]
Latest unofficial is there: https://github.com/Robz8/DSiMenuPlusPlus-update

**Comment by mcamacho97** [comment]
I will test it

**Comment by mcamacho97** [comment]
I tested with the unofficial build and nothing, the game is still frozen in the "Initializing save file memory. Do not turn the power off"

**Comment by Robz8** [comment]
Don't have that issue on my end, so that's fixed.

**Comment by mcamacho97** [comment]
maybe I installed bad your repo, I will test again
