### ISSUE TITLE
Thumb arm9 card read patches

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#194]
In order to make some game works, this is needed.

eg: Diddy Kong racing needs this.

**Comment by Robz8** [comment]
Known games that have thumb card functions:
* Grand Theft Auto: Chinatown Wars
* Diddy Kong Racing
* Kingdom Hearts: Re:Coded (true?)
* Kirby: Canvas Curse/Power Paintbrush
* Pokemon Black 2/White 2 (true?)
* Star Fox Command
* Girls Mode (JAP)/Style Savvy (USA)/Style Boutique (EUR)
* Transformers Decepticons (true?) (v1.1 works)

**Comment by RinMaru** [comment]
will this fix Dementium 2?

**Comment by piratesephiroth** [comment]
it will fix the games that show the red X error on the initial loading screen

**Comment by RinMaru** [comment]
ah. I wonder whats wrong with Dementium 2. you can start a new game and save but you cant load

**Comment by piratesephiroth** [comment]
I"ll see if I can fix it

**Comment by ahezard** [comment]
Lock's Quest is a confirmed thumb game

**Comment by Stack3r** [comment]
Can someone check if touch the dead is thumb? It did boot to a black screen before but recently it goes to the red X, just wanted to confirm

**Comment by ahezard** [comment]
red X is thumb

**Comment by ahezard** [comment]
5265 - Lufia - Curse of the Sinistrals (USA) is thumb as well

**Comment by Stack3r** [comment]
Pokémon black 2 and white 2 is thumb also

**Comment by dubbz82** [comment]
Lufia doesn't show the red X at boot which is why I presumed there was something else going on with it.

**Comment by ahezard** [comment]
the red X is shown on the latest nightly release

**Comment by RinMaru** [comment]
Spiderman 3

**Comment by dubbz82** [comment]
Geometry Wars Galaxies

**Comment by RinMaru** [comment]
Spiderman Shattered Dimensions

**Comment by RosalinaFan573** [comment]
the unreleased game Gauntlet requires THUMB

**Comment by Robz8** [comment]
We have our first thumb game working, as Pokemon Black 2/White 2 now works as of 9b74efb and 65007a8!

**Comment by ZahrasTV** [comment]
Robz8 ,  the Pokemons   Black 2  and White 2 ,  open here , but, after you put a name in a caracter , the game frozen in black screen ,   and if you no go to  new game , and go to option and back , frozen in White  Screen,  i test here.

**Comment by Kalanyr** [comment]
Have you tried with an AP patched ROM  ?  eg I know that Pokemon Black needs AP patches to function correctly in the late game, as the ability to battle gets disabled at some point otherwise (it works on a new game on Route 1 but doesn't on an old game in Opelucid City I had).

**Comment by Kalanyr** [comment]
It seems to work for me unAP patched but not AP Patched (when it breaks at the end of the section where you select character and enter name, where the 3D would normally start) . Which is weird. I'm just going to go double check I didn't misname stuff.

**Comment by Kalanyr** [comment]
To Summaize: 
Clean ROM dumps work but the AP is still active (so no Exp is earned) and there's still some instability that may lead to crashes (which may also be AP). 

Properly AP patched roms for DS Flash Carts do not work , they break after the Appearance / Name section where the 3D engine would initialize.

**Comment by Robz8** [comment]
Closed, since they're now implemented.

**Comment by RinMaru** [comment]
well damn I guess donor roms for those still need to be worked on?

**Comment by Robz8** [comment]
We're not bringing back donor ROMs.
Thumb save redirection is planned.

**Comment by RinMaru** [comment]
whats up with some games having issues starting when I cart is inserted? I keep a game in there to keep dust out

**Comment by ahezard** [comment]
This is due to  #254 , not yet implemented. We are working on it.

**Comment by RinMaru** [comment]
ok I was just curious ^^
