### ISSUE TITLE
Sleep mode does not work without Slot-1 card

### ISSUE THREAD

**Issue by Robz8** [ahezard/nds-bootstrap#195]
For example, in SM64DS/NSMB, Mario says "Buh-Bye" and then "It's a me, Mario", then keeps looping there.

**Comment by piratesephiroth** [comment]
Funny that the game doesn't sleep when we press the home button without a slot-1 card inserted either.
It seems to have the same bug but the sound is muted.

**Comment by theclashingfritz** [comment]
I love and hate this bug. It's kind of entertaining and annoying at the same time.

**Comment by LautaroCuello** [comment]
In Advance Wars: Dark Conflict w/o slot-1 sleep is fine, but when I insert the card it started looping between music/no-music.
