### ISSUE TITLE
Spiderman 2 unknown sdk

### ISSUE THREAD

**Issue by RinMaru** [ahezard/nds-bootstrap#196]
Spiderman 2 on DS NTSC shows up as "SDK ?" and dosnt boot

my setup is
N3DS XL Latest FW
B9S with Luma3DS latest
Using a 128GB MicroSD

**Comment by lorilith** [comment]
have you tried re-dumping the cart. this is common for roms that are not actually dumped to the system.

**Comment by dubbz82** [comment]
I can confirm some games do pull with a ? For SDK.  Trauma center (original version - us region) also pulls with an unknown SDK version, however in that case the game works.

**Comment by ahezard** [comment]
I think this is a dsimenu+ issue

**Comment by ahezard** [comment]
No the game works fine using the latest dsimenu++

**Comment by RinMaru** [comment]
nope it doesn't work it boots now but freezes on the opening video

**Comment by ahezard** [comment]
I was able to play. Can you test the latest nightly?

**Comment by RinMaru** [comment]
where's the nightlys at?

**Comment by ahezard** [comment]
https://github.com/Robz8/DSiMenuPlusPlus-update

**Comment by RinMaru** [comment]
I guess the better question is how do I build it lol

**Comment by ahezard** [comment]
Download and install devkitpro https://github.com/devkitPro/installer/releases. Dowload or use git to get the sources then type make.

**Comment by RinMaru** [comment]
oh buy I hate cmd

**Comment by RinMaru** [comment]
it either freezes on the vid or the Vicarious Visions Logo

**Comment by ahezard** [comment]
So you do not see the start game /credits menu ... strange it works for me, even on latest release. Can you describe a bit your setup? DSI/3DS model, sdcard type and size, etc

**Comment by ahezard** [comment]
Ok, I was able to reproduce the issue on my o3ds but it does not freezes on my dsixl

**Comment by ahezard** [comment]
On my IS-TWL (a dev dsi so with the same extra ram as 3ds) it is freezing exactly like on 3ds

**Comment by ahezard** [comment]
Ok I was not testing the same rom, the EU version does not have any issue while the USA one freeeze, guess you use that for now. But the EU version also shows ? as sdk version.

**Comment by ahezard** [comment]
I did a bit of investigation on the US rom, this game is very different from anything else out there, the arm7 patching fail completely and even the arm9 patching is only half complete (no swi halt patching, card id not found). Thanks for reporting the issue, it will help improve compatibility.

**Comment by RinMaru** [comment]
my setup is 
N3DS XL Latest FW
B9S with Luma3DS latest
Using a 128GB MicroSD

**Comment by ahezard** [comment]
I do not see this anymore (freezes on the USA version) with 0.10.2 on 3ds and dsi. Closed.
