### ISSUE TITLE
Pokemon Black / White 

### ISSUE THREAD

**Issue by Kalanyr** [ahezard/nds-bootstrap#197]
Just reporting the issues on these on v0.9.1 (Rev 01)

Noticeable lag on the intro (particularly the 3D segments).  This seems to result in the music desynchronizing in the 2D section (it finishes first). The music also cuts out on the Pokemon Musical section after the 3D section. 

In Opelucid City in Black there's noticeable lag on the internal transitions. (not far enough through White to compare it's different layout).

Battles White Screen after the overworld splash screen effects finish (ie just before the battles start) for both Trainer and Wild battles. 

This happens both with an old dump for NDS flashcarts  and a new DSi Enhanced dump of the ROMs. 

(Not sure how much of this is AP vs SDK5 issues. Though I don't remember any of these being reported as AP issues back when these came out that may be that these would have been the easy to fix ones unlike the more subtle no Exp from battles etc AP, that got all the attention. )

**Comment by ahezard** [comment]
How did you pass the first battle in black? I have black screen with music playing.

**Comment by ahezard** [comment]
Are you using an AP patched rom?

**Comment by Kalanyr** [comment]
No, I dumped my save from being at Opelucid city from my real card. I still
white screen on any battle , so I wouldn't be able to get past the first
battle.

On 21 Jun. 2018 09:43, "ahezard" <notifications@github.com> wrote:

Are you using an AP patched rom?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ahezard/nds-bootstrap/issues/197#issuecomment-398931430>,
or mute the thread

**Comment by Kalanyr** [comment]
I just started a new game and can say that I do black screen on the first battle.

**Comment by ahezard** [comment]
The battle / lag issue is fixed in the last pushed version. Thanks shutterbug.

**Comment by Kalanyr** [comment]
While better there's definitely still issues.  I'm not using any AP issues and this is the new dump which means it's running in full DSi Enhanced Mode   but so far: 

Intro is totally fixed. 

Loading my old save: Battles do load but don't work, the lower screen is "alive" ie the clock updates but the Fight brackets and word Fight never materialize and the touch screen doesn't respond to the cursor, nor do the buttons work. Sometimes freezes when C-Gear is on when crossing these transition points. 

New Game: Battles work.  XP is recieved from battles. 

Both: Area transitions both internal and external still have a discernible lag (though greatly reduced).  Noticeable audio pops even with volume right down at those transitions and some other events (such as initiating a battle). 

I'll try and do some more testing eg saving the new game and seeing if it's loading the game that causes the battle issues or whether it's something to do with more advanced X-transceiver features and if using the old DS dump that doesn't have the DSi Enhanced stuff dumped properly works any better but I'm going on vacation soon and won't be back for a month.

**Comment by Robz8** [comment]
DSi Enhanced games do not run in DSi mode yet.

**Comment by Kalanyr** [comment]
I wonder if my issues are from using a new dump with the DSi Enhanced Mode data instead of the old dumping method. I'll recheck with the old dump as a priority then.

**Comment by Kalanyr** [comment]
Did some more testing.  

The old save (Opelucid City) definitely works on a real cart,  ie the Fight option appears after battle starts. 

Using NDS clock speed or the old dumped for DS flashcard ROM doesn't seem to make any difference at all (not really unexpected since it doesn't boot in DSi mode anyway) but better to be sure. 

Next up - 
New game works fine even after loading from a save.   Even duplicated as much as I could the situation in Opelucid City (starting in Building), leaving , going to new route and entering battle after loading and starting a battle. The fight engine kicks up fine and I can do stuff.   

I'm guessing that means that whatever is causing the issue is something that happens later in the game.  Unfortunately it's like 30 hours playing normally from the start to Opelucid which is close to the end of the main story.  Or it might even be an issue with the Wifi data stored on the old save since I haven't used it on this system before.

**Comment by Kalanyr** [comment]
Okay ,  the inability to battle from the old save is caused by AP that must kick in at a certain point in the game..  I used an AP Patch and battles work properly even from my old save.

There's still audio popping even on mute , and some lag on internal area transitions (like moving from one side of Opelucid to the other) but these seem to have been reduced too (though these may be because of other improvements since I updated my nightlies right before testing again).
