### ISSUE TITLE
Kingdom Hearts 358/2 Days not working properly

### ISSUE THREAD

**Issue by FerrazaDazzle** [ahezard/nds-bootstrap#198]
Hi All
I would like to report a bug with the comparability worksheet. Kingdom Hearts 358/2 days has been marked as playable, however, it isin't. i have done the following tests and adhered to the settings recommended and have done AP Patches:
Once you confirm a New Game, hangs on forever black screen
(Used a save file to try this next method)
Loading a mission after i have loaded a save file (Day 358 Believe), animation plays for 3 secs, before freezing, however music continues to play, sound from animation doesn't however.

**Comment by Robz8** [comment]
You need an AP patch or a Slot-1 cart inserted to play this game without freezing.

**Comment by FerrazaDazzle** [comment]
Would that mean i need to insert the actual physical gamecard for it?

**Comment by Stack3r** [comment]
The game will now load a save but new game still doesn’t work

**Comment by FerrazaDazzle** [comment]
thats odd. it always did load a save for me. its just something to do with cutscenes i think. game always freezes/crashes when something happens with cutscreens
