### ISSUE TITLE
Pokemon Conquest 

### ISSUE THREAD

**Issue by Kalanyr** [ahezard/nds-bootstrap#199]
(This is an SDK5 Dsi-Enhanced game on v0.9.1 (Rev 01))

Loads without error but white screens immediately after boot. No sound begins to play or anything.

**Comment by ahezard** [comment]
this rom have a 2 version, have you tested both original 6093 and revision 1 6583?

**Comment by Stack3r** [comment]
This game does have AP that causes not to boot

**Comment by ahezard** [comment]
Do you confirm it works wit han AP patched rom?

**Comment by Stack3r** [comment]
I haven’t tested on bootstrap but on flashcart it needs it

**Comment by Stack3r** [comment]
You still need the AP patch for dumps

**Comment by Kalanyr** [comment]
Sorry was replying to an earlier comment from my email and responded to the
wrong comment.

**Comment by Kalanyr** [comment]
I can confirm the standard AP patch doesn't allow my dump to boot.

**Comment by ahezard** [comment]
Please test again with the latest sdk5 commit

**Comment by shutterbug2000** [comment]
It appears to be working after AP patching and using the latest nightly. Might need to use a pre-made save file, or at least one that's only 256kb, otherwise it hangs "trying to recover Gallery data".
