### ISSUE TITLE
Homebrews frozen on white screen at launch?

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#2]

**Comment by ahezard** [comment]
From https://gbatemp.net/threads/ds-i-mode-hacking-progress-thread.413015/page-121#post-6725519

diagnoseds ws
WOLVESLAYER ws

**Comment by ahezard** [comment]
Gameyob

**Comment by ahezard** [comment]
Gameyob is recent and does not even need dldi patch at all. For this kind of homebrew the dldi patch break them because the libfat/libnds internal sd driver conflict with the dldi driver. It could be the same with nesDS.

**Comment by ahezard** [comment]
WolveSlayer and diagnoseds are 2 homebrews made in 2007. I may have a problem with a specific version of devkitpro/libnds.

**Comment by metroid-maniac** [comment]
LemmingsDS 7.04 freezes on a white screen at launch.

**Comment by ahezard** [comment]
Thanks for the feedback metroid-maniac . LemmingsDS is open-source so this is very useful 👍

**Comment by ahezard** [comment]
Version V0.0.2 have improved the compatibility with some of the homebrews above. Please updated and retest.

**Comment by autofire372** [comment]
0.0.3 re-broke GameYob.

**Comment by ahezard** [comment]
I have GameYob 0.5 working with V0.0.3, please try to set BOOST_CPU = 0

**Comment by autofire372** [comment]
Changing that setting worked; Thanks!
