### ISSUE TITLE
Cheat codes not working

### ISSUE THREAD

**Issue by piratesephiroth** [ahezard/nds-bootstrap#200]
Codes are getting added to nds-bootstrap.ini kinda fine (DSiMenu++ won't accept subfolders in the code list) however they never seem to be applied correctly to the game.

Only 'constant write' codes are working as expected (codes beginning wth 0, 1 or 2).
Patch codes have no effect at all and conditional codes seem to malfunction as well.
More info about code types [here](http://doc.kodewerx.org/hacking_nds.html#arcodetypes) and [here](http://www.kodewerx.org/forum/viewtopic.php?t=98).

**Additional information**
(for using with DSiMenu++, the GUI for nds-bootstrap)
- The file is called "cheats.xml" and should be placed in the `_nds` folder.
- It has no option for enabling or disabling cheats so it will just read all you put there for the game.
- At the moment the maximum length is 255 characters so it can accept up to 15 code lines (8 bytes/16 characters each) per game.
You can create the file with [ARDS Code Editor](http://projects.sappharad.com/tools/ards_editor_exe.zip) or [R4CCE](http://hp.vector.co.jp/authors/VA013928/bin/r4cce086.zip) (save it as XML Cheat DB).
It can't have subfolders so you must add the codes right after adding the game.

**cheats.xml example**
```
<?xml version="1.0" encoding="UTF-8"?>
<codelist>
	<game>
		<name>Castlevania - Dawn of Sorrow (U)</name>
		<gameid>ACVE 9a6b468a</gameid>
		<date>2018/06/20 15:01</date>
		<cheat>
			<name>Unlock everything</name>
			<codes>0210AA88 008F7F7F </codes>
		</cheat>
		<cheat>
			<name>Moon Jump</name>
			<note>Only works on Default button mapping</note>
			<codes>94000130 FFFD0000 020CA96C FFFFB1D5 D2000000 00000000 </codes>
		</cheat>
		<cheat>
			<name>Speed modifier (4x Speed)</name>
			<codes>521F6854 E0800006 021F6854 E0800106 D2000000 00000000 </codes>
		</cheat>
		<cheat>
			<name>Patch code test</name>
			<note>Replace "Start Game" with "CHEAT game" on the data management menu description</note>
			<codes>E2219056 00000005 21252823 00000034 </codes>
		</cheat>
	</game>
</codelist>


```
all the codes get added fine to the ini file.

`CHEAT_DATA = 0210AA88 008F7F7F 94000130 FFFD0000 020CA96C FFFFB1D5 D2000000 00000000 521F6854 E0800006 021F6854 E0800106 D2000000 00000000 E2219056 00000005 21252823 00000034 `

**Comment by ahezard** [comment]
I have been reported here #57

**Comment by piratesephiroth** [comment]
added the info from the other issue's comments

**Comment by ahezard** [comment]
The problem could be linked to the handling of the 00000000 values since code starting by 0 1 or 2 does not have 00000000 in the middle or at the end

**Comment by ahezard** [comment]
Are cheat code even working in v0.11.0 ? I have some doubt about the loadCheatData function code

**Comment by piratesephiroth** [comment]
nope, cheat codes don't work at all on v0.11.0

**Comment by ahezard** [comment]
I am reworking it

**Comment by ahezard** [comment]
Ok using your CHEAT_DATA values example there is a lot of wrong values copied into memory (not all of them but almost half of them). The problem should be on the CHEAT_DATA option parsing code itself into main.cpp.

**Comment by ahezard** [comment]
The problem is confirmed to be with the conversion from string to u32 :
cheat_data[i] = strtol(("0x"+cheats[i]).c_str(), NULL, 16);

**Comment by ahezard** [comment]
Can you try the latest master build piratesephiroth  ?

**Comment by ahezard** [comment]
By the way Nitrohax allow a maximum of 64kb of cheat code, I will try to implement the same limit into nds-boostrap instead of the current 1KiB limit
#define CHEAT_MAX_DATA_SIZE (64 * 1024)			// 64KiB

**Comment by ahezard** [comment]
Can you please try again with the latest master build piratesephiroth ?

**Comment by damianoamatruda** [comment]
With b69338a “Press B To Moon Jump” works on “Super Mario 64 DS”.

**Comment by ahezard** [comment]
Select for weapon type of code works in mario kart
Please try also to add more code for one game to test that the new limit (32KB, 8192 hex values) is properly implemented.

**Comment by piratesephiroth** [comment]
Whoa it's really working now.
Conditional codes are working fine but patch codes are borked.

**Comment by piratesephiroth** [comment]
Only the first 2 bytes were written so the code values are being read as u16 instead of u32?

**Comment by piratesephiroth** [comment]
proper patch:
`10 11 12 13 14 15 16 17 18 19`

current patch:
`12 13 14 15 16 17 XX XX 18 19`

**Comment by Stack3r** [comment]
So are cheats working now? Like anti piracy ones?

**Comment by piratesephiroth** [comment]
yeah, everything seems to be working now

**Comment by jvhellraiser** [comment]
i really need help:
i am just doing a simple test:

<?xml version="1.0" encoding="UTF-8"?>
<codelist>
	<name>User cheat code v1.0</name>
	<game>
		<name>Megaman ZX Advent</name>
		<gameid>YZXE 59DB331C</gameid>
		<date>2018/10/03 21:00</date>
		<cheat>
			<name>Have all Forms Selectable</name>
			<codes>1212127E 0000F7CF</codes>
			<codes>02121280 F7F7F7FF</codes>
		</cheat>
	</game>
</codelist>

is this correct? or codes got to be side by side?

like this one:
<?xml version="1.0" encoding="UTF-8"?>
<codelist>
	<name>User cheat code v1.0</name>
	<game>
		<name>Megaman ZX Advent</name>
		<gameid>YZXE 59DB331C</gameid>
		<date>2018/10/03 21:00</date>
		<cheat>
			<name>Have all Forms Selectable</name>
			<codes>1212127E 0000F7CF 02121280 F7F7F7FF</codes>
		</cheat>
	</game>
</codelist>

this one wont work for me in dsimenu++ not sure  what i am doing wrong any help? pointers?

**Comment by piratesephiroth** [comment]
use r4cce to build your cheats.xml, as I said ni the first post

**Comment by jvhellraiser** [comment]
I have use R4cce v0.84 to build the XML file add cheat.xml to _nds folder on the root of my SD card.
i start a new game in Megaman Zx Advent with twilight menu latest version  i have check if the codes 
are enable but it seem that the All form selectable codes are not being enable by using R4cce 0.84,
i have try many times and codes don't seem to enable them self with twitlight menu using cheat.xml
please help.

Have all forms selectable (DS) North America
1212127E 0000F7CF
02121280 F7F7F7FF

**Comment by piratesephiroth** [comment]
works fine here

```xml
<?xml version="1.0" encoding="UTF-8"?>
<codelist>
	<name>CMP NDS Cheat Database 190315</name>
	<game>
		<name>MegaMan ZX: Advent (U)</name>
		<gameid>YZXE 59DB331C</gameid>
		<date>2018/10/05 22:31</date>
		<cheat>
			<name>Have All Forms Selectable</name>
			<codes>1212127E 0000F7CF 02121280 F7F7F7FF</codes>
		</cheat>
	</game>
</codelist>
```

make sure your file is named **cheats.xml**

**Comment by jvhellraiser** [comment]
Please tell me your trying to pull my leg with this : <name>derp</name> XD lol
when doing the XML do you enable any options? like Enable Codes before you save it to cheats.xml?
how many codes/ games can you add to cheats.xml? usually i use 2 to 3 codes at a time per game.
can i use  1 XML for multiple games or  for now is one at a game at a time in cheats.xml?

**Comment by piratesephiroth** [comment]
You need to put all codes for all games in the same cheats.xml.
All the codes are always enabled.
The cheat limit is 32768 characters of codes per game so you can pretty much add as many codes as you wish.

**Comment by devian95** [comment]
It looks like cheats with more than 15 code lines aren't working even in the latest release of nds bootstrap,
I tried different cheat codes with Pokemon Black and the most complex ones (such as event codes) break the game (it gives back white screen once loaded in TW Menu). The same does not happen with item codes. The .ini file correctly report the codes I have prepared with R4cce so I am pretty sure I did not make any kind of mistake. 

Here's what I did:
<codelist><name>User cheat code v1.0</name><game><name>Pokemon - Versione Nera (Italy)</name><gameid>IRBI 639C2678</gameid><date>2018/10/08 18:05</date><cheat><name>View IVs/EVs (L/R/Start)</name><note>While viewing a Pokemon's stats, press L to see IVs, press R to see EVs, or press Start to see the normal stats</note><codes>521D5264 E82AF661 E2002000 00000068 29016DA9 2108D12D D1074208 42080189 0849D10A D0244208 E006200D 20A04911 390A7008 E0051D02 1CC22046 7008490D 70083154 3001315E 280F7008 2848D003 28A3D001 3001D101 2812E7F4 284BD003 28A6D001 3803D100 D1EB4290 65A92100 47702010 021D9FD8 021D5264 FECCF62C D2000000 00000000</codes></cheat></game></codelist>

**Comment by piratesephiroth** [comment]
The problem is with the code itself.
This part writes a block of code to 0x2002000
```
E2002000 00000068
29016DA9 2108D12D
D1074208 42080189
0849D10A D0244208
E006200D 20A04911
390A7008 E0051D02
1CC22046 7008490D
70083154 3001315E
280F7008 2848D003
28A3D001 3001D101
2812E7F4 284BD003
28A6D001 3803D100
D1EB4290 65A92100
47702010 021D9FF8
```
And then this one makes some code in the game jump to the block that the patch code above wrote
`021D5284 FEBCF62C`

The problem is that the code was made for flashcard and emulators so that area of RAM is definitely empty in those case.
If the code causes  a crashit's because that area of memory is being overwritten by nds-bootstrap.

**Comment by devian95** [comment]
Thank you for the quick reply! So It seems those kind of codes will be unavalaible for a while, I hope you fix this issue soon, the nds bootstrab is working flawlessly in every other aspect.

**Comment by Antonio231102** [comment]
I had no idea about it was possible to use cheat codes on nds bootstrap!

I tried using a lot of codes on MKDS and everything worked fine, except for one small issue: only the first 5 codes are loaded.
If this is an issue I hope it gets fixed soon, and if it's a limitation I hope the amount of codes can be expanded in the future!

**Comment by piratesephiroth** [comment]
>I tried using a lot of codes on MKDS and everything worked fine, except for one small issue: only the first 5 codes are loaded.

did you test other codes and in different order to confirm that?

**Comment by SvenDaHacker64** [comment]
You gonna add usrcheat.dat cheat database support too? It has every cheats for most games in an R4.

**Comment by Garebear1903** [comment]
What About New Super Mario Bros. DS?
