### ISSUE TITLE
Fire Emblem Heroes of Light and Shadow

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#204]
Icons on the top screen (when showing info regarding units) aren't displayed properly, they are bugged (no problem with the same rom on desmume)

nds-bootstrap - 0.9.1 bye bye donor rom

**Comment by bennyman123abc** [comment]
What about actual gameplay? Is gameplay affected?

**Comment by hubert-skowronek** [comment]
@bennyman123abc I haven't played much but the beginning seems very smooth and fully playable! As of version 9.2.0 the top screen is displayed correctly.
