### ISSUE TITLE
Lufia - White Screen at boot

### ISSUE THREAD

**Issue by dubbz82** [ahezard/nds-bootstrap#205]
Lufia Curse of the Sinistrals (USA Region) white screens at boot and has for as many builds back as I've attempted to run it on.  I'm using latest unofficial.  AP patching applied.

**Comment by ahezard** [comment]
Thumb game
no$gba output :
ERR_LOAD_OTHR
game uses thumb

closed in favour of #194

**Comment by dubbz82** [comment]
Might I request that this be re-opened, as the game still doesn't boot after THUMB code was added?

**Comment by piratesephiroth** [comment]
nah it corrected like 2 or 3 games only

**Comment by ahezard** [comment]
lufia is not using thumb on arm7

**Comment by ahezard** [comment]
Some function are not patched currently in arm7 sdk5 (bot thumband not thumb), cardRead and cardid

**Comment by ahezard** [comment]
swiHalt is also not properly patched for lufia

**Comment by ahezard** [comment]
this is now fixed

**Comment by dubbz82** [comment]
Hate to request that this be reopened again, however this once again seems to boot to white screen on 10.0 release.
