### ISSUE TITLE
Pokemon Black save cannot be found on dsi

### ISSUE THREAD

**Issue by robzombie91** [ahezard/nds-bootstrap#206]
Works fine on 3ds verison but dsi cannot find the save file and wont let pokemon black get past the save couldnt not be found screen

https://dl2.pushbulletusercontent.com/LQd6d3Ut78qRDhlOoH0mRxzw5O0hn6oR/IMG_20180620_212722.jpg

It says The Save data could not be accessed. Please turn the power off and reinsert the Game Card.

I am on the latest version of nds-bootstrap

**Comment by Robz8** [comment]
Are you sure it's the latest on both 3DS and DSi?

**Comment by robzombie91** [comment]
yes. i was on 0.9.1 on both

**Comment by Robz8** [comment]
Latest is 0.9.2.

**Comment by ahezard** [comment]
Would it be possible to attach you save here?

**Comment by robzombie91** [comment]
its a clean save. i deleted it and it does the same thing on the 0.9.2

**Comment by robzombie91** [comment]
https://drive.google.com/open?id=15MWoQQecDgtA-MkhmkW3vkGFucQt6Ch4

**Comment by Stack3r** [comment]
Is this still a problem?

**Comment by robzombie91** [comment]
The latest nds-bootsrap fixed the issue. Sorry for not updating
