### ISSUE TITLE
Pokemon White low sound/music

### ISSUE THREAD

**Issue by mcamacho97** [ahezard/nds-bootstrap#207]
I downloaded the last nightly version and the game works very good, but the sound and the music are very low compare with other games that I tested it.

**Comment by ahezard** [comment]
Which system are you using exactly? DSI / DSI XL / 3DS / N3DS?

**Comment by mcamacho97** [comment]
I have a 3DS

**Comment by mcamacho97** [comment]
I just updated the DSiMenuPlusPlus to version 4.3.0 and the pokemon white sound already sounds good and the game works very good.
