### ISSUE TITLE
freeze when returning to DSiMenu++

### ISSUE THREAD

**Issue by piratesephiroth** [ahezard/nds-bootstrap#212]
now the L+R+B+down shortcut just freezes the game (instantly, no need to hold the buttons down)

**Comment by Kalanyr** [comment]
The Restart (L+R+Statrt+Seleect) shortcut doesn't work either. It either freezes the game or crashes to home menu).

**Comment by Sarayalth** [comment]
For me l+r+down+b sometimes freeze after 2 seconds holding the buttons and other times it restarts the 3ds and then luma crash screen appears

**Comment by ahezard** [comment]
is this also happening for sdk5 games?

**Comment by Kalanyr** [comment]
It is for me. I noticed this on Pokemon Black. Sometimes the reset would
even hard lock requiring power off.
