### ISSUE TITLE
[Offtopic] Compatibility list has been vandalized 

### ISSUE THREAD

**Issue by Valeri0p** [ahezard/nds-bootstrap#213]
Hi, sorry for using github for this issue, but seems that only four games are still present on the Rom compatibility table. 

Probably someone with full access didn't know how to use it, or simply wanted to do some griefing.

Personal opinions: this isn't the first time that something like this happens, but since we need to keep the list updated after the recent progress, here is my proposal: 
someone could make a public Google form for semi-automatize the process of adding informations; some fields can be hard-coded (example:release numbers, title ID, Name of the game, NTR/TWL mode, status-color-scheme, release number) and some other can be open (description, bugs, final notes, made by). Every entry should be authenticated, adding a new game to the list should be done with a manual request, and, if possible, a history of compatibility should be maintained.

Sorry for the long post, but it was an urgent issue, and I hope that my suggestions will make maintaining the list more easy and faster.

**Comment by legoj15** [comment]
did you check the tabs at the bottom of the doc? seems like everything has been categorized somewhat (idk though, don't know what it looked like before)

**Comment by piratesephiroth** [comment]
the old list is useless now anyway

**Comment by theclashingfritz** [comment]
Can say this, While it's sad it got vandalized. It's really outdated. You can see this in the fact the New Super Mario Bros DS. Demo version now works on latest build which is awesome by the way.

**Comment by dubbz82** [comment]
I believe (per discussion on discord) this was an intentional purge, as the compatibility suddenly went through the roof the old list was deemed basically worthless.

**Comment by Robz8** [comment]
Yeah, I've decided to clear the compatibility list, since most of it was outdated.
