### ISSUE TITLE
Prepatched spirit tracks room Gui train controls removed?

### ISSUE THREAD

**Issue by Swampat** [ahezard/nds-bootstrap#214]
The AP checks are responding on the latest version of the bootstrap do I need to just get the rom again?

**Comment by ahezard** [comment]
I cannot found any AP check implemented currently in the code for spirit track. You need to apply the AP patch manually.

**Comment by Swampat** [comment]
I can't play dpad rom hack so I won't bother trying to everyone play. The rom I'm using is trimmed so it would be a waste to even try. Thank you for responding I guess.
