### ISSUE TITLE
Tingles Balloon Trip Of Love crashes at credits 

### ISSUE THREAD

**Issue by DarthVitrial** [ahezard/nds-bootstrap#216]
The game works flawlessly right up until you complete page 14 and the credits are about to roll, then it just hangs indefinitely, making it impossible to access the postgame. Using nds-bootstrap 0.9.2

**Comment by DarthVitrial** [comment]
Bug is still present in 0.10.0 - after finishing page 14 and tapping to go to the next page, it hangs forever.

**Comment by DarthVitrial** [comment]
Some additional testing: 
Just tried again on dsimenu++ 5.3.0 r1, ndsbootstrap build cddd8d7.
Crash occurs regardless of if async is on or off, regardless of whether you’re in ntr processor speed or twl processor speed, regardless of which girl you dance with at the end, and regardless of whether you choose to stay or leave.
No matter what, it always hangs after you touch the screen to exit page 14 and roll the credits, and accessing post game content remains impossible.

**Comment by DarthVitrial** [comment]
Would it help if I provided a save file or any sort of logs?

**Comment by ahezard** [comment]
A save file would help yes. Are you using a dsi or a 3ds?

**Comment by ahezard** [comment]
Which region of the game are you using?

**Comment by DarthVitrial** [comment]
a 3DS on the most recent Luma build.
Save file is here https://mega.nz/#!FssVHBAS!w1lmOjnejcxdYb8kiV9f6Zo_i7TvbBcJzJFgzPvzDWE
And it's a japan exclusive game, so unless there are different regions within Japan that have different versions I guess just the Japanese version? 
I'm using the translation + repaired rom from here: https://tingletranslation.blogspot.com/

**Comment by DarthVitrial** [comment]
Still broken in TWiLightMenu 6.4.3/bootstrap 0.12.2.
Is there anything I can do to help? Any logs?

**Comment by DarthVitrial** [comment]
Still broken on TWIlightMenu 7.1.0 and bootstrap 0.15.0.

**Comment by RocketRobz** [comment]
If this still persists in later versions, then it might be a soft-reset issue.

**Comment by DarthVitrial** [comment]
It's fixed!

**Comment by NightYoshi370** [comment]
Great. Please open a new issue if you need anything else
