### ISSUE TITLE
Legend of Zelda Spirit Tracks

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#218]
nds-bootstrap 0.9.2

Running LoZ Spirit tracks with new version of bootstrap caused the save file to be created anew, thus deleting previous one.

The sound in select save menu is crackling

**Comment by RinMaru** [comment]
I cant even get the game to run beyond the Nintendo logo

**Comment by Robz8** [comment]
@RinMaru Make sure your save is 1MB.

**Comment by hubert-skowronek** [comment]
@RinMaru I've applied AP patch

**Comment by RinMaru** [comment]
how you do this patch?

**Comment by hubert-skowronek** [comment]
@RinMaru Please refer to https://gbatemp.net/threads/nds-bootstrap-loader-run-commercial-nds-backups-from-an-sd-card.454323/

**Comment by Uupo03** [comment]
@RinMaru the patch only makes it so the train controls show up (they dont normally due to anti-piracy), anyway if your save file (in your rom folder on your sd) is anything other than 1mb delete  it and the game should work

**Comment by RinMaru** [comment]
Hope patching becomes an automatic thing

**Comment by legoj15** [comment]
That, or the bootstrap becomes 1:1 with an actual DS

**Comment by hubert-skowronek** [comment]
@legoj15  do you mean that by becoming 1:1 with an actual DS the patching wouldn't be even needed? Is that even feasible?

**Comment by hubert-skowronek** [comment]
Never encountered save issue after removing 512 KB save.
