### ISSUE TITLE
somes game are slow and sluggish

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#222]
Metroid pinball is one of the first game released (number 142). It works properly but it very slow. Rom size 32MB.

This seems to indicates that in some cases read code may still be slow and inneficent.

**Comment by Stack3r** [comment]
Hmm I guess that makes sense

**Comment by Robz8** [comment]
Seems to also be the issue with Bomberman 2 and Tingle's Rosy Ruppeland.

**Comment by Stack3r** [comment]
Pokemon HG/SS seems to be having some slight loading issues, it is nowhere close to the speed at DPPt are even with higher ram readded

**Comment by RinMaru** [comment]
Sonic Genesis Collection runs slow aswell

**Comment by dubbz82** [comment]
using 133mhz will speed up the sonic collections game considerably, though I did still notice at least a little bit of lag on this.  Not sure if it's present with a cart running on a DSi system, however.

**Comment by RinMaru** [comment]
Spider-Man Web of shadows and Battle for new York also suffers

**Comment by shanepm** [comment]
For the mostpart NSMB and MKDS have been running at full speed for me, but I did notice a brief slowdown in NSMB in the first castle in level 1 and occasional frame drops in MKDS.

**Comment by dubbz82** [comment]
Grand Theft Auto Chinatown Wars also suffers from this to some extent, though probably not as badly as some of the others mentioned.

**Comment by hubert-skowronek** [comment]
nds-boostrap 0.11.0 - Pokemon Black needs async to be turned off, it is really sluggish even with TWL speed. Game hangs for few seconds when moving main character around.

**Comment by Kalanyr** [comment]
Are there any particular games that need testing ?  I have a fairly extensive collection of Turn-based (S)RPGs and some Action-ish JRPGs / Strategy games that I can test.

**Comment by Robz8** [comment]
[This](https://github.com/Robz8/DSiMenuPlusPlus-update/raw/2b262380e3b45c68c4f54d75c9cf5122d6b77a07/nds-bootstrap-nightly.nds) nightly bootstrap build provides a slight boost to load speeds, by lowering the cache chunk size from 128KB to 32KB. Should be notable in some games that run sluggish (GTA Chinatown Wars, for example).

**Comment by Stack3r** [comment]
It appears caching 32 has fixed Metroid prime pinball loading issues and HGSS runs 100% or super close to cart speeds now

**Comment by RinMaru** [comment]
its close but still some audio stuttering when compared to DeSmuMe

**Comment by ahezard** [comment]
Please test with this build : https://mega.nz/#!Wc0QQYSR!MsiTfrpCXo_E7g6qz0w5NTWoJVQL3IcVJpOq_1FJPhQ

**Comment by RinMaru** [comment]
looks like Metroid Pinball is fullspeed now no audio stuttering

**Comment by ahezard** [comment]
What is the status in v0.14.1?

**Comment by ahezard** [comment]
Could be linked for some games to #517

**Comment by ahezard** [comment]
This have been fixed either by the cachedce option / heap shrink mechanism or the in the branch min_card_read_dma that will soone be merged in master
megaman battle network 5 : no more stuttering with min_card_read_dma 
gta Chinatown wars : no more slowdown in game with min_card_read_dma 
animal crossing wild world : speed fixed by cachedce in master
Metroid prime pinball : speed fixed by cachedce in master

**Comment by zurgeg** [comment]
By the way, this appears to have regressed as of 0.72.1, Pokemon White is slow, regular stutters and hangups on dialouge and area loading.

**Comment by RocketRobz** [comment]
> By the way, this appears to have regressed as of 0.72.1, Pokemon White is slow, regular stutters and hangups on dialouge and area loading.

Make sure you're starting the game with C-Gear turned off.
