### ISSUE TITLE
Dragon quest v wont load 

### ISSUE THREAD

**Issue by DummyTitan** [ahezard/nds-bootstrap#224]
when i put the game the image is a cuestion mark and when i try to play it it just wont load it says error

**Comment by ahezard** [comment]
This game have an ap patch. Have you pa patched your rom with DS-Scene_Rom_Tool_v1.0_build_1215?

**Comment by DummyTitan** [comment]
No it is not ap patched

**Comment by dubbz82** [comment]
Follow issue #194 for this, as this is the same issue, regardless of AP patch (though once that issue is resolved, you will still need AP patch for the game to work correctly)
