### ISSUE TITLE
Some games have sound issues such as loud popping, static, echoing, etc.

### ISSUE THREAD

**Issue by Stack3r** [ahezard/nds-bootstrap#225]
Various games have sound issues such as double audio (echoing), loud sounds even with volume off, and static sounds.

Confirmed games with issues:
Pokemon Black/White
Pokémon Black2/White2
New Super Mario Bros
Super Mario 64 DS
Mario Kart DS
Lunar Knights
Animal Crossing Wild World

**Comment by bennyman123abc** [comment]
I have no issues in SM64DS and NSMB on the latest build of bootstrap.

**Comment by bennyman123abc** [comment]
Both US releases btw

**Comment by FM1337** [comment]
Tested on latest nightly, Pokemon Black and White no longer seem to have this issue.

**Comment by bennyman123abc** [comment]
I don't think this is an issue anymore. If it is, only some people seem to encounter it.

**Comment by piratesephiroth** [comment]
it's still an issue but in a few games

**Comment by dubbz82** [comment]
yugioh 5ds world championship 2011 over the nexus was reported in discord to still be affected by this issue.

**Comment by entonghibang** [comment]
The legend of zelda phantom of hourglass has occasional annoying sound bug, dont know how to describe it.

**Comment by Stack3r** [comment]
So with async prefetching readded, a lot of the sound issue has been fixed, issues such as popping on certain games that require surround sound are still present though

**Comment by Stack3r** [comment]
No it still needs to be opened until audio issues are completely fixed

**Comment by Kalanyr** [comment]
Is there a list of games that still need testing ?

**Comment by RinMaru** [comment]
Resident Evil DS still has sound issues allot of crackling in some areas

**Comment by ahezard** [comment]
The changes in the non_blocking_io may help with this kind of issues even it does not fix it for all games. If you can compile and test with this branch please report here the results (with the commit id to identify the version).

**Comment by ahezard** [comment]
Please test with this build : https://mega.nz/#!Wc0QQYSR!MsiTfrpCXo_E7g6qz0w5NTWoJVQL3IcVJpOq_1FJPhQ

**Comment by RinMaru** [comment]
Resident Evil DS still has crackling

**Comment by Stack3r** [comment]
This is apparently only an issue now with a handful of games such as animal crossing wild world

**Comment by Stack3r** [comment]
Closing this issue due to the majority of the games being fixed

**Comment by cristobalruffo** [comment]
Hello, at this date I'd like to add that both korg ds-10 and korg m01 have serious sound issues like abrupt popping. Mainl when you change to another instruments, the game seems to not being able to handle it. A trick that I've found to work around this is changing to another instrument until it comes back to normal.

**Comment by xhxaxzxaxhx** [comment]
For several of this games mentioned I can confirm this issue is fixed by going into the in game options and selecting "Stereo" instead of "Surround".

**Comment by RinMaru** [comment]
> For several of the games mentioned I can confirm this issue is fixed by going into the in game options and selecting "Stereo" instead of "Surround".

That means theres still a problem

**Comment by cristobalruffo** [comment]
I can't really tell when it stopped having this issues since I'm updating as TWLMenu updates, but at some point stopped and started again after I updated to TWLMenu 16.1.0. I thought I could make it work again but I've tried downgrading until 13.0 but I'm still getting abrupt sound issues mainly with the apps/games I mentioned before (Korg DS10, Korg M01), so at this point I can't really tell if it's my console's issue, the SD Card or something else. Sorry for not bringing specifics about the version of nds-bootstrap involved on this but I wanted to address it anyway. I will keep trying different versions of TWLMenu and its correspondent nds-bootstrap to bring more specific about this problem.

**Comment by RinMaru** [comment]
yea the problem has come back in the Main Menu mostly happens when going through folders. as for games im not sure ive noticed

**Comment by rafaelpernil2** [comment]
I can confirm I am experiencing the same issues with KORG DS-10 and KORG M01

**Comment by Caio-Branco** [comment]
Experiencing the same issues with KORG DS-10 and KORG M01 on the latest. There is also the DS-10+ (DSi enhanced) version.

**Comment by HazNut** [comment]
Experienced buzzing audio issues in Resident Evil: Deadly Silence, in the music, have commented details in #762.
