### ISSUE TITLE
Problems with Pokemon HeartGold  

### ISSUE THREAD

**Issue by NagasakiGG** [ahezard/nds-bootstrap#228]
Hi,

I have noticed problems with Pokémon Heart Gold

- sometimes when a fight starts it stucks  in Animation (when a Battle starts your poke balls twist, and with that they twist infinitely. So no freeze)
- when I enter a house (sometimes) the game stucks. (The music keeps playing, so I guess no freeze.)

Is there a way how to provide logs ?

I’m running a New 2DS XL latest fw with b9s and a German HeartGold file.
As injector I’m using the installed DSiMenu++ cia (latest version )

**Comment by Robz8** [comment]
You need to AP-patch your ROM.

**Comment by NagasakiGG** [comment]
Are you sure? The rom is already AP-Patched. Also on iPhone using iNDS no problems so far

**Comment by Robz8** [comment]
What bootstrap version are you using?

**Comment by NagasakiGG** [comment]
The latest,v0.9.2

**Comment by WalaRocks18** [comment]
I had the same problem, just use 0.9.1 rev01, the latest is broken

**Comment by Robz8** [comment]
Yeah, next version will have that fixed.

**Comment by WalaRocks18** [comment]
and will have thumb card patched?

**Comment by Robz8** [comment]
Yes.

**Comment by WalaRocks18** [comment]
but you think Black n' White 2 will work on the go or it will need an update to work properly like Black or White?

**Comment by Robz8** [comment]
They work properly like Black and White.

**Comment by WalaRocks18** [comment]
as of now or in probably 0.9.3?

**Comment by Robz8** [comment]
They work on the latest bootstrap nightly.
https://github.com/Robz8/DSiMenuPlusPlus-update

**Comment by WalaRocks18** [comment]
interesting...
