### ISSUE TITLE
Dragon Quest Monsters Joker 2 Anti-Piracy issue.

### ISSUE THREAD

**Issue by SaulJoker** [ahezard/nds-bootstrap#229]
The game plays through like normal up until a point in the main story where you have to go back down to the Engine room, and as you exit the Captain's room, a cutscene is supposed to play out. However, when you exit, instead what you will find is that all of the NPCs of the game are now gone, and that it is impossible to progress through the story.

This is due to an anti-piracy check the game has (a quick google search made me realize this).

**Comment by dubbz82** [comment]
Confirmed this does not happen if your rom is patched with nds-scene tool.  Used a clean US rom and patched with it.

**Comment by Stack3r** [comment]
Closed due to AP
