### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by mariogamer2** [ahezard/nds-bootstrap#23]
Hy,

I'm experimenting some error with python,under Arch linux. At the begining,it was only print that miss parentheses. Then I got this:

Traceback (most recent call last):
  File "patch_ndsheader_dsiware.py", line 23, in <module>
    parser.add_argument('file', metavar='file.nds', type=file, help='nds file to patc
NameError: name 'file' is not defined

(I think this wasn't the same thing on ubuntu)

**Comment by Robz8** [comment]
You need version 2.7 of Python.

**Comment by Margen67** [comment]
Why not something newer like 3.6?

**Comment by Gericom** [comment]
Python 3 and python 2 are like 2 different worlds

**Comment by ahezard** [comment]
Yes and this is not the core of the project anyway but an helper script. Python 2.7 is still the default in most linux environment and is supported.

**Comment by mariogamer2** [comment]
I have both installed but I don't think I installed python 2 firstly... Anyway it work when using python2

**Comment by mariogamer2** [comment]
Also it should use ndstool now it's support dsi nds creation.
