### ISSUE TITLE
Pokemon B2W2 - Triggers AP / AP Patches don't work. 

### ISSUE THREAD

**Issue by Kalanyr** [ahezard/nds-bootstrap#233]
Just following up from Thumb patches thread now that it's closed

As of commit:
https://github.com/ahezard/nds-bootstrap/commit/a6c7f864f8f2e3fba1e239d0c53e35ce8d77c40b

Unpatched ROMs boot fine but trigger the AP measures in the cart (so no Exp) , going into the Pokemon screen and leaving it (either back to the game or into details for Pokemon) will crash to a Black Screen. 

AP Patched ROMs (which do work on Flash Carts) boot but break at the point after the character / name input where the 3D engine would normally cut in  where they black screen.

**Comment by piratesephiroth** [comment]
Most of these AP issues could probably be solved if the Cheat system was functional

**Comment by hubert-skowronek** [comment]
@piratesephiroth would it solve AP issues for all games? And how could it be implemented? Would nds-bootstrap contain AP patches embedded or user would have to point specific file in configuration or somehow else?

**Comment by Kalanyr** [comment]
Pretty much all AP patches also have equivalent Action Replay codes that achieve the same thing, nds-bootstrap has partial support for these cheats at the moment (the cheat engine is a bit broken).  So getting the cheat engine working would allow for the in memory AP patches to be used again , which would serve as a stop gap. While the AP patching for nds-bootstrap was worked on.

**Comment by ZahrasTV** [comment]
nothing new ,  and same erros , for now....    nds bootstrap 23/06

**Comment by piratesephiroth** [comment]
AP-Patched Pokemon Black 2/White2 work on the latest commit

**Comment by Kalanyr** [comment]
Confirmed. On an AP patched ROM the issue with leaving the Pokemon Party
screen crashing the game is solved too.

**Comment by Stack3r** [comment]
So starting a new game now results to loading the starting town with an AP patched rom?

**Comment by Kalanyr** [comment]
Yep.

**Comment by Stack3r** [comment]
This issue has been resolved
