### ISSUE TITLE
Spongebob Boating Bash gets white screen on start

### ISSUE THREAD

**Issue by Dragonracer21** [ahezard/nds-bootstrap#237]
If I start Spongebob Boating Bash (DSi Enhanced game), I get a white screen. I'm using DSiMenu++ 4.3.1 (Rev 02) and NDS-Bootstrap 0.9.2, thank you.

**Comment by Dragonracer21** [comment]
Btw another game named Age of Mythologies is giving me X error screen at start. Hope this can be fixed if possible.

**Comment by Stack3r** [comment]
@Dragonracer21 Please try booting the game with the latest unofficial bootstrap

**Comment by ahezard** [comment]
please test again with latest commit

**Comment by Dragonracer21** [comment]
@ahezard still nothing changed. White screen on boot. I used the latest commit 1e89045. If this is important information: I'm using an o3ds.

**Comment by ahezard** [comment]
I have the impression that this is more a dsimenu++ issue, I got a red screen like if dsimenu++ try to use sdk1-4 bootstsrap instead of the proper sdk5 bootstrap required here ( this a twl enchanced game)

**Comment by Dragonracer21** [comment]
@ahezard can you fix the white screen issue or is this eventually an issue from dsimenu++ that it doesn't start?

**Comment by Robz8** [comment]
What SDK version does DSiMenu++ show?

**Comment by Dragonracer21** [comment]
@Robz8 It shows SDK version:5 (TWLSDK)

**Comment by Robz8** [comment]
What's the release number?

**Comment by Dragonracer21** [comment]
Release number is: 5975

**Comment by Dragonracer21** [comment]
SpongeBob Boating Bash is now working with bootstrap 0.10.1 without any problems and with cart speed (both versions of the game work Englisch-Spanisch and German version). I will close this
