### ISSUE TITLE
Age of Empires Mythologies - game cannot access save

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#238]
The game shows text about not being able to access save and that it has to be turned off.

nds-bootstrap 9.2.0

**Comment by Dragonracer21** [comment]
Which Version do you use of Age of Empires Mythologies? I use Europe Version and get every time I try to start Mythologies an error screen.

**Comment by hubert-skowronek** [comment]
@Dragonracer21 sorry, I've tested that particular game on nightly bootstrap, so I think we can close this one :-)

**Comment by hubert-skowronek** [comment]
@Dragonracer21 surely they can, I believe in them, those guys are incredible ;)

**Comment by Stack3r** [comment]
@hubert-skowronek Please test this with the latest unofficial build that was added today

**Comment by Dragonracer21** [comment]
@Stack3r tried Age of Mythologies with the latest commit. Nothing changed for me. It's still giving me the cannot access save issue

**Comment by hubert-skowronek** [comment]
@Stack3r game still hangs on accessing save screen with the newest commit 148ae3e

**Comment by Dragonracer21** [comment]
@hubert-skowronek Same

**Comment by hubert-skowronek** [comment]
So let's just give the guys some time :-)

**Comment by Dragonracer21** [comment]
@hubert-skowronek You are right, let's give the Devs some time :). And also I am a very patient person so waiting won't be a problem ;)

**Comment by Dragonracer21** [comment]
There is now another issue in Age of Mythologies. I tested it with latest commit 1e89045 and now it hangs on the following text: "Saving Game Data... Do not turn off the power or remove the DS Card." If this is important for the devs: I'm using an o3ds.

**Comment by ahezard** [comment]
Ok so the commit 91c31dd was definitevely needed for Age of mythology. Something is  still wrong in the offset obtained by the patcher though.

**Comment by hubert-skowronek** [comment]
@ahezard I had that screen for few recent days already, since the first commits which allowed thumb games to run, I am not sure whether that game is thumb or not but it was around that time I have tested it for the first time
