### ISSUE TITLE
COP the Recruit Freezing

### ISSUE THREAD

**Issue by RinMaru** [ahezard/nds-bootstrap#239]
COP the Recruit NTSC will boot and show logos but once it starts the loading bar on the top screen it goes black and wont move beyond that.

My setup is b9s/ Luma3ds latest
n3ds xl

**Comment by RinMaru** [comment]
there isn't one

**Comment by dubbz82** [comment]
I can confirm that this game gets past the black screen if AP is patched out for this game.  This should be closed out, as it's an AP issue, not a bootstrap issue.

**Comment by RinMaru** [comment]
well the tool I used didn't have a AP patch in its database

**Comment by dubbz82** [comment]
The copy I have is not in fact EUR.  There's a pre-AP cracked copy of the game floating around the net that works without a hitch.

**Comment by RinMaru** [comment]
Yea im not finding anything from a simple search its always EUR. but I guess this could be close and referenced in the AP Patches thread but ill wait for one of the devs to see.

**Comment by ahezard** [comment]
If there is an AP patched rom working fine we can close this indeed.

**Comment by RinMaru** [comment]
I looked online and there is no USA patched version even in a AP patch database its not listed all there is is EUR so he's either lying or its well hidden

**Comment by RinMaru** [comment]
Well I guess I wont be playing it anytime soon a site had a link to a US patched one but its gone.
