### ISSUE TITLE
Double image on bottom of both screens

### ISSUE THREAD

**Issue by klunkee** [ahezard/nds-bootstrap#241]
I have noticed that sometimes the image on the screen has a glitch where the very bottom (maybe 5%) is doubled and slightly offset which results in a kind of double image. This seems to happen on both screens and strangely also disappears sometimes with a reboot but it does happen often enough.

I have noticed it both on 2DS and New 3DSXL on a much older version of nds-bootstrap and the latest one.

**Comment by Kalanyr** [comment]
Yes, I've noticed this too. I haven't worked out any particular common cause.

**Comment by dubbz82** [comment]
This is a TWL bug and it happens on retail carts sometimes too.
