### ISSUE TITLE
Nine Hours, Nine Persons, Nine Doors - Game freezes on first escape room

### ISSUE THREAD

**Issue by klunkee** [ahezard/nds-bootstrap#242]
Game loads fine but seems to freeze in the first escape room when trying to interact with anything. The sound keeps repeating the last sound played and nothing responds to buttons or touch, have to press the Home button and quit manually. I tried at least two scenarios, after tapping the photo in frame and exiting, a crash occurs. Also a crash instantly occurs if you try to tap the water heater. 

This happened on an older revision of bootstrap and the latest.

**Comment by piratesephiroth** [comment]
isn't that the anti-piracy protection

**Comment by Stack3r** [comment]
@klunkee Please test this with the AP patch

**Comment by piratesephiroth** [comment]
yeah it is. the AP make the game freeze after some minutes

**Comment by dubbz82** [comment]
Nds scene tool can patch a clean rom for this.  I played for around  20 minutes last night with no freezes.

**Comment by RinMaru** [comment]
@dubbz82  Nds scene tool don't have all patches

**Comment by dubbz82** [comment]
It does have one for this game, if using a clean rom (at least for the US version).  I know COP doesn't exist there however this one certainly does...

**Comment by Stack3r** [comment]
Closing this issue due to AP being the problem
