### ISSUE TITLE
Grand Theft Auto - Chinatown Wars

### ISSUE THREAD

**Issue by dubbz82** [ahezard/nds-bootstrap#243]
This game starts to boot, there is a quick flash of text on the screen (so quick that it's not really readable) then the game dies to a black screen.

**Comment by Robz8** [comment]
Using a donor cart with an EEPROM save chip gets past the black screen.

**Comment by Robz8** [comment]
Fixed in 66418e9

**Comment by ahezard** [comment]
Is this working now?

**Comment by Stack3r** [comment]
Still doesn’t work without a cartridge inserted
