### ISSUE TITLE
Echo and Mission Hurry Up Mario Bros. Issues

### ISSUE THREAD

**Issue by YYoshi241** [ahezard/nds-bootstrap#245]
THIS IS A NSMB DS Hack
Bootstrap 0.7.4 crashes in 1-tower (sewer 360)
Bootstrap 0.9.2 has an ever-present ECHO-EFFECT
(Both Audio 48kHz, ARM9 67MHz; o3DS XL TWLoader 6.7.0)

**Comment by NightYoshi370** [comment]
Do you have a link to the thread on NSMBHD?

**Comment by YYoshi241** [comment]
Extending NSMB5 CTT1 TO THIS (echo issue)

**Comment by YYoshi241** [comment]
here's the thread:
https://nsmbhd.net/thread/4175-mission-hurry-up-mario-bros-finished/

**Comment by YYoshi241** [comment]
SM64DS also included (0.9.2/ECHO)

also d33t (L0L)

**Comment by Stack3r** [comment]
Closed in favor of sound issue thread here #225
