### ISSUE TITLE
Another Super Mario 3D now crashes when loading save files

### ISSUE THREAD

**Issue by YYoshi241** [ahezard/nds-bootstrap#247]
This issue only occurs on 0.9.2 (as far as I've tested) and doesn't occur on 0.7.4
Does this relate to the fact that TWLoader can't detect an SDK version?
(Setup: TWLoader 6.7.0, 3DSX; Audio 48kHz; ARM9 67MHz; o3DS XL)
(THIS IS A PATHED USA ROM, I think v1.1)

**Comment by YYoshi241** [comment]
0.7.4 will still RARELY freeze when loading a new room. Much less crashes than 0.6.0 though :)

**Comment by YYoshi241** [comment]
ASM3D Crash: THIS DOES NOT EFFECT THE ACTUAL SM64DS.
Also: 48kHz music issue: File Select Music is off (aka. sounds wrong). You'll know if you hear it. AND ECHO.

**Comment by Stack3r** [comment]
@YYoshi241 please test this with the latest unofficial and dsimenu++, do not use twloader it is obsolete
