### ISSUE TITLE
"dldi + card working" commit breaks...uhh...games and homebrew

### ISSUE THREAD

**Issue by TheArcadeStriker** [ahezard/nds-bootstrap#25]
The title kinda explains it.
This commit: https://github.com/ahezard/nds-bootstrap/commit/60dd5c38f5138fb8446114e97e4b6dd8102e3d06
Even if it seemingly would be to use homebrew and games, what it does is that whatever you try to load stays in a white screen (Tried with Mr Driller that works in card.v2, and NDS_TGM which worked in 0.0.3 but not in card releases, even then it showed a error screen).
Still I'm sure you will fix that pretty quick.
Good luck and thanks for this!

**Comment by Robz8** [comment]
With console output (Debug) on, it'll be stuck on "Running ndsfile with 1 parameters".

**Comment by ahezard** [comment]
Ok thanks for the feedback. Some games may be detected as homebrew and homebrew as games. In this case it does not works. It may also be linked to some preliminary work I have done on save patches. I will have a look.

**Comment by ahezard** [comment]
Ok everything was broken on HW. My latest commit fix that. I can run both NDS_TGM  and Mr Driller using the same bootstrap nds file now.
