### ISSUE TITLE
Kingdom Hearts 358/2 Days black screen

### ISSUE THREAD

**Issue by RS55** [ahezard/nds-bootstrap#250]
The game starts and works perfect but at the time of loading some cinematics (And sometimes when moving between options) is frozen with black screens, on the other hand the game starts well in any of its three versions (JAP, USA and EUR) having a cartridge of the same game inserted in the slot, if you take it out the same thing that I said before will happen

**Comment by Robz8** [comment]
It can be any NTR cartridge, not just of the same game.

**Comment by RS55** [comment]
Oh my bad them.

**Comment by RS55** [comment]
Oh, bad mine then
