### ISSUE TITLE
Dementium II Cant Load Save

### ISSUE THREAD

**Issue by RinMaru** [ahezard/nds-bootstrap#251]
Dementium II NTSC works great but only one problem. You cant Load your saved game the game will have a message "Unable to access save data please re insert cart and reset the system."

N3DSXL Luma3DS

**Comment by piratesephiroth** [comment]
This is weird. Load was working when I added the AP patch days ago.

**Comment by RinMaru** [comment]
unless it was included in the latest nightly then no it didn't work. I even deleted my old save and had it create a new one just incase it was corrupted

**Comment by piratesephiroth** [comment]
I tested on both USA and EUR versions. Got to the save point, saved, left the game, went back and loaded fine.

**Comment by RinMaru** [comment]
Not even Desmume loads the game >.<

**Comment by piratesephiroth** [comment]
3DS

**Comment by RinMaru** [comment]
That's strange then. do you still have the bootstrap it was working on?

**Comment by RinMaru** [comment]
It works in latest lol nvm
