### ISSUE TITLE
Mario & Sonic at The Winter Olympics Currupted save

### ISSUE THREAD

**Issue by RinMaru** [ahezard/nds-bootstrap#253]
When you start the game and press start the game will say "Corrupted data was found press A to delete it and try again." once its deleted the cycle repeats preventing you from getting past the title screen

**Comment by RinMaru** [comment]
nope

**Comment by Robz8** [comment]
I kept trying, and eventually, the save screen shown up, but since I did a soft-reset, and even re-created the .sav file, the save corrupted screen came back.

**Comment by piratesephiroth** [comment]
yeah that's definitely AP

**Comment by piratesephiroth** [comment]
patch it with https://gbatemp.net/threads/repack-ds-scene-rom-tool-v1-0-build-1215-includes-cmp-and-ap-database.477193/

**Comment by RinMaru** [comment]
Are trimmed roms safe? if it saves space I want to use it but will it corrupt roms?

**Comment by RinMaru** [comment]
AP patch doesn't work

**Comment by piratesephiroth** [comment]
yeah it works

**Comment by RinMaru** [comment]
what trimmed roms or the patch cause the AP patch didn't fix it

**Comment by piratesephiroth** [comment]
yeah the patch works I tested the game and it ran fine, so save errors

**Comment by RinMaru** [comment]
OH it does work lol sorry forgot to delete the save

**Comment by piratesephiroth** [comment]
ah yeah, forgot to warn about that

**Comment by DeathStarCommander** [comment]
Hllo, as I am far from my pc and I can't do it myself ftm, could someone give me the already patched rom please?? Tysm

**Comment by dubbz82** [comment]
How about we not promote piracy here?
