### ISSUE TITLE
Thumb arm7 saves read/write patches

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#254]
Sone games not only uses thumb on arm9 but also on arm7 side, so it is needed to patch that as well. Games with thumb arm7 :
- Sonic & Sega All Stars Racing
- SEGA Superstars Tennis 
...

**Comment by ahezard** [comment]
So it is done in the SDK5 branch. It remains to be done in the master branch (SDK2-4).

**Comment by ahezard** [comment]
diddy kong racing seems to need that

**Comment by ahezard** [comment]
As per latest commit everything should be ok now for all sdks and thumb games should properly save. Please test and report.

**Comment by Okirihayato** [comment]
Dubbz82 referenced Front Mission to this issue but it is still not working.

**Comment by ahezard** [comment]
I just pushed an improvement on this regard for sdk 1-4

**Comment by ahezard** [comment]
I consider this as completed, none of the rmaining issues are linked to arm7 thumb patching
