### ISSUE TITLE
Touch still semi-broken on 3DS

### ISSUE THREAD

**Issue by piratesephiroth** [ahezard/nds-bootstrap#255]
Touch input seems to be stuck on the top left of the screen under normal usage.
It only works if we use the "Start last-ran rom" option in the Launcher.

**Comment by Robz8** [comment]
Did you install the latest DSiMenu++ CIAs?

**Comment by piratesephiroth** [comment]
yup, everything is the latest

**Comment by piratesephiroth** [comment]
seems fixed on the latest commit
