### ISSUE TITLE
Front Mission 1st doesn't load

### ISSUE THREAD

**Issue by Lumipikma** [ahezard/nds-bootstrap#257]
Get Error on screen when trying to load it.

There is no AP documented so that doesn't seem to be the issue

**Comment by dubbz82** [comment]
Possibly related to #254 ?

**Comment by Stack3r** [comment]
@Lumipikma Please test this with the latest unofficial build of bootstrap

**Comment by Okirihayato** [comment]
With build 1ade937 it loads but stays in white screen, this also happens to Transformers game

**Comment by ahezard** [comment]
This games works in master. Please retest with the latest nightly.
