### ISSUE TITLE
Retro Game Challenge (US) crash after creating character

### ISSUE THREAD

**Issue by jdfr228** [ahezard/nds-bootstrap#258]
System: DSi
Loading method: DSiMenu++

After making a character, going through the intro, and starting the game, the game remains frozen on a black screen.  Wifi LED remains lit, and it doesn't seem to be a hard crash since the console turns off with a short press of the power button.  Tested with NTR and TWL speeds.

Game doesn't appear to have any AP patches that I can find.  It could be a THUMB title- if there's a simple way to determine that in say an emulator I'll put in the work to find out, sorry for not knowing in advance.

**Comment by ahezard** [comment]
could be linked to #554 that have been fixed. Please retest with the latest nightly.

**Comment by jdfr228** [comment]
If someone happens to compile nightlies I will happily take a look, but I don't have the means to compile it myself at the moment.

**Comment by arraystock** [comment]
The latest nightly is available [here](https://github.com/TWLBot/Builds/releases/tag/v20190306-022137).

**Comment by jdfr228** [comment]
Still broken as of latest nightly (b2b208f)

**Comment by RocketRobz** [comment]
Does the issue still persist on v0.19.1?

**Comment by Inorizushi** [comment]
Issue is no longer present as of v0.19.1
