### ISSUE TITLE
Fix Soft Resetting

### ISSUE THREAD

**Issue by Stack3r** [ahezard/nds-bootstrap#259]
So games that have to go back to the title screen won’t crash

**Comment by dubbz82** [comment]
I'm sure this is already a given, but this is for the 3ds side of things.  This reportedly works correctly on the DSi.

**Comment by Robz8** [comment]
Nah, when trying to go back to the title screen in both Kingdom Hearts DS games, it's stuck on black screen.

**Comment by manujedi** [comment]
Hello, 

Soft reset works on dsi xl E (dsimenu installed to sysnand) with kingdom hearts for me.

**Comment by aatj887** [comment]
Me too :( Always
I got one O3DS with US Firmware and the soft reset never works

**Comment by Robz8** [comment]
This issue is about games not going back to the title screen, not soft-resetting via the L+R+START+SELECT combo.

**Comment by NightYoshi370** [comment]
For those wondering: This is also why NSMB Minigames don't work

**Comment by ahezard** [comment]
we have to embed a minimal bootloader into card_engine that allows to load and boot nds-boostrap from the sd into card_engine_arm7 since we have place there and since it have direct sd access
we have to catch the function call reset, which is most probably an arm9 call

**Comment by ahezard** [comment]
The soft reset parameter address is 0x27FFC20

**Comment by ahezard** [comment]
Wood softreset patching code is there
https://github.com/ahezard/woodrpg_forwarder/blob/e0280c91b21e28443c23f98a171012ef8a301b0c/akloader/arm9/source/patches_sr.cpp

**Comment by hubert-skowronek** [comment]
Just wanted to mention that after completing M&L BiS it stucks on white screens after presenting achievements at the end, probably related to this issue as well

**Comment by MasterGamingYT** [comment]
Oof, will probably be hard, just saying

**Comment by piratesephiroth** [comment]
By the way, how many games have functional soft resets?
The only one I have seen here is Mega Man ZX Advent.

**Comment by MasterGamingYT** [comment]
idk

**Comment by eku** [comment]
Is anyone working on this?

**Comment by UnbelievablySimpish** [comment]
Sorry if I’m being bothersome, but is this still being worked on by chance?

**Comment by ahezard** [comment]
@RocketRobz just completed the work on the softreset branch, it is now part of the nightly build and under test. Expect it soon on the next release.

**Comment by NightYoshi370** [comment]
Isn't this already completed? Shouldn't this be closed?

**Comment by Stack3r** [comment]
Almost two years later lol, good work guys
