### ISSUE TITLE
self compiling nds bootstrap gives me error 2

### ISSUE THREAD

**Issue by Dragonracer21** [ahezard/nds-bootstrap#262]
I if try to compile with make, it will give me error 2:

make: *** [Makefile:154: cardengine_arm7] Error 2

**Comment by OmeletHopper** [comment]
I as well am getting errors; but I suspect it's because I'm on a Mac (hackintosh) and haven't updated devkit for a while. Nevertheless:
```
/Users/jack/Downloads/nds-bootstrap-master-2/bootloader/source/card_patcher.c:22:10: fatal error: cardengine_arm9_bin.h: No such file or directory
 #include "cardengine_arm9_bin.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [card_patcher.o] Error 1
make[2]: *** Waiting for unfinished jobs....
linking cardengine_arm7.elf
arm-none-eabi-gcc: error: sdmmc.o: No such file or directory
make[2]: *** [/Users/jack/Downloads/nds-bootstrap-master-2/cardengine_arm7/../data/cardengine_arm7.elf] Error 1
make[2]: *** Waiting for unfinished jobs....
/Users/jack/Downloads/nds-bootstrap-master-2/bootloader/source/debugToFile.c: In function 'dbg_printf':
/Users/jack/Downloads/nds-bootstrap-master-2/bootloader/source/debugToFile.c:34:2: warning: implicit declaration of function 'nocashMessage' [-Wimplicit-function-declaration]
  nocashMessage(message);
  ^~~~~~~~~~~~~
make[1]: *** [build] Error 2
make: *** [bootloader] Error 2
make[1]: *** [build] Error 2
make: *** [cardengine_arm7] Error 2
```
I will test on my laptop, then report back here.

**Comment by Dragonracer21** [comment]
If this is important for bug fix I will paste here the full error text:

make[1]: Entering directory '/home/oeter/Desktop/nds bootstrap/nds-bootstrap/cardengine_arm7'
make[2]: /home/oeter/Desktop/nds: No such file or directory
make[2]: *** No rule to make target '/home/oeter/Desktop/nds'.  Stop.
make[1]: *** [Makefile:102: build] Error 2
make[1]: Leaving directory '/home/oeter/Desktop/nds bootstrap/nds-bootstrap/cardengine_arm7'
make: *** [Makefile:154: cardengine_arm7] Error 2

It would be good if someone could help me with this error.

**Comment by Dragonracer21** [comment]
EDIT: Btw I'm using Laptop with windows 10

**Comment by piratesephiroth** [comment]
I don't think that's the full error log.

**Comment by piratesephiroth** [comment]
try
`pacman -Syu general-tools dstools ndstool libnds libfat-nds`

and then build again

**Comment by Dragonracer21** [comment]
I tried that command and tried to recompile it and it gives me the exactly same error log:

make[1]: Entering directory '/home/oeter/Desktop/nds bootstrap/nds-bootstrap/cardengine_arm7'
make[2]: /home/oeter/Desktop/nds: No such file or directory
make[2]: *** No rule to make target '/home/oeter/Desktop/nds'.  Stop.
make[1]: *** [Makefile:102: build] Error 2
make[1]: Leaving directory '/home/oeter/Desktop/nds bootstrap/nds-bootstrap/cardengine_arm7'
make: *** [Makefile:154: cardengine_arm7] Error 2

**Comment by ahezard** [comment]
https://github.com/ahezard/nds-bootstrap => Compîling. Did you followed this instruction? We are compiling every commit via travis (https://github.com/ahezard/nds-bootstrap/blob/master/.travis.yml) on linux and I compile myself on windows 10 (I also recently performed again the setup from scratch on another windows 10 pc without issues) and @Robz8  on windows so I do not think there is any issue here. 

Just one thing I noted : if you had devkitpro already installed on your pc before pacman based releases (3.0.x installer on windows), delete/uninstall everything and reinstall from scratch.

**Comment by piratesephiroth** [comment]
yeah I just ran the latest devkitpro updater on a fresh windows 8.1 installation and I compiled ndsbootstrap fine.

**Comment by piratesephiroth** [comment]
Can you build a functional nds-bootstrap with the latest tools?

Only the sdk5 branch works here, after building on Windows. The master branch always results in white screens,

**Comment by Exagone313** [comment]
Same problem (only tested for sdk1-4, not sdk5), but we should open a new issue.

**Comment by piratesephiroth** [comment]
it seems to be something new/wrong within the toolset because it breaks DSiMenu++ as well.
