### ISSUE TITLE
Final Fantasy IV problem

### ISSUE THREAD

**Issue by Hokutten** [ahezard/nds-bootstrap#263]
I'm trying to play Final Fantasy IV, but I'm not able to start the game. In fact, the game does start but as soon as the game starts some yellow text flashes and dissapears and then the screen goes black and nothing happens. My 3ds does not freeze and I can close dsimenu ++ and go back to my 3ds main screen. Other games work just fine. I checked the compatibility list and it is listed as a working title.

**Comment by Robz8** [comment]
Latest nightly bootstrap should fix the issue.

**Comment by Hokutten** [comment]
It did!. Thank you so much robz!
