### ISSUE TITLE
Touch Screen doesnt work

### ISSUE THREAD

**Issue by mcamacho97** [ahezard/nds-bootstrap#266]
Im testing the last version of nds-bootstrap (0.10.0) and the last DSIMenu++(4.4.0 Rev1) and in all the games that I have doesnt work the touch screen, in the previous version I dont have this issue.

**Comment by Robz8** [comment]
If you're using a 3DS, install the latest CIAs.
If you're on DSi, overwrite the `title` folder on SD root, with the one from `CFW - SDNAND root` folder from latest .7z.

**Comment by mcamacho97** [comment]
It's truee!! very very sorry, my fault, Im just replace the folder _nds but I forgot install the new cia.
