### ISSUE TITLE
Lufia Curse of the Sinistrals

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#269]
Loads, after few dialogs during the initial cutscene it hangs on the black screen.

nds-bootstrap 0.10.0

**Comment by dubbz82** [comment]
Weird...I can't even get that far on mine.

**Comment by hubert-skowronek** [comment]
@dubbz82 to the extent of my knowledge I should have clean, unpatched rom

**Comment by dubbz82** [comment]
Ah...mine is AP patched.  Maybe the AP patching is somehow interfering with the boot process in my case.

**Comment by dubbz82** [comment]
I've confirmed with a clean dump, this game will boot just fine however the AP is tripped as described in the first post, however patching this with either NDS Scene Tool or DSATM causes a white screen at boot.  Although this is an AP related issue, this may make sense to look into a little bit further, as it's rendering the game unusable either way.

**Comment by dubbz82** [comment]
DSATM also breaks the rom if you try and embed the AP code to the rom, I'll give open patch or dicastia a stab.

**Comment by piratesephiroth** [comment]
Also looking at old threads I see that the game froze in transitions during gameplay, not during the intro.

I suspect this is a nds-bootstrap issue indeed.

**Comment by hubert-skowronek** [comment]
As of version 0.11.0 the game boots only to white screen, so it's worse than before

**Comment by ahezard** [comment]
Could be caused by #554

**Comment by ahezard** [comment]
please restest with the latest nightly

**Comment by hubert-skowronek** [comment]
@ahezard now it works

**Comment by gondelfino** [comment]
> please restest with the latest nightly

Even after doing that It won't even boot to the start sequence. Just white or black screen freeze.
