### ISSUE TITLE
Compatibility regression with homebrews

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#27]
Some homebrews that were running V.0.0.3 are no more running using V0.1.0

eg : Aperture Science DS (portal ds)

**Comment by maorninja** [comment]
Why not make a seperate homebrew branch, and make that use 0.0.3?

**Comment by XXLuigiMario** [comment]
Meteora 0.9.2 no longer works in recent versions, but used to work in older versions, like 0.1.0.

**Comment by ahezard** [comment]
There is now a separate homebrew branch (hb)

**Comment by NightYoshi370** [comment]
Since the Homebrew branch now uses 0.0.3, we can close this

**Comment by NightYoshi370** [comment]
is based off*
