### ISSUE TITLE
Inazuma eleven 2 blizzard

### ISSUE THREAD

**Issue by renatosk** [ahezard/nds-bootstrap#270]
Tested version: 0.10

The game loads , but when theres transitions the game may frozen in a black screen , it happens like in 3 ,5 minutes of play

**Comment by Robz8** [comment]
Sounds like this game needs an AP patch.

**Comment by dubbz82** [comment]
If this is the European English version, there should be an AP patch available with nds scene tool.

**Comment by renatosk** [comment]
Fixed using nds scene tool to aplic the AP patch , Thanks for the help guys
