### ISSUE TITLE
Inputs not registering / registering incorrectly

### ISSUE THREAD

**Issue by davslinker** [ahezard/nds-bootstrap#273]
Hi there,

So I'm on the newest NDS Bootstrap (V 0.10) and now I'm having issues with the inputs. For instance, Kirby: Power Paintbrush, no inputs appear to be detected, including the touch screen. In Magician's Quest, the buttons are sensed but not the touch screen, and the joystick is constantly pulling to the top-left. These two did not boot before this version.

As a control test, I also ran Super Mario 64 DS, and noted that while the D-pad and joystick worked, the start button, touch screen and A button didn't work. However, this only happens SOMETIMES and sometimes it works perfectly (the other two games consistently have input issues). 

Other games tested likewise had issues with the touch screen not detecting any inputs.

**Comment by Robz8** [comment]
You have to install the latest DSiMenu++ CIAs.
