### ISSUE TITLE
Phantasy Star 0 USA (AP Patched) Freezes on Boot

### ISSUE THREAD

**Issue by Mintybangs** [ahezard/nds-bootstrap#277]
The NDS ROM loads just fine, the game (not AP patched) boots and works just fine with an occasional glitchy screen that disappears after a bit. But when you apply the AP patch that prevents you from playing locally and online, your 3DS freezes after the ROM loads.
This doesn't seem to be an issue with the patch since the method applied and ROM used are correct. 
nds-bootstrap 0.10.0

**Comment by dubbz82** [comment]
The AP patch in DSATM was working as of a nightly or two before 10.0.  I can try this again later today and see if I can replicate this issue

**Comment by dubbz82** [comment]
Make sure your rom is a clean rom, and patch with DSATM.  I've confirmed this works fine as of nightlies past 0.10.0 as well as pre 0.10.0
