### ISSUE TITLE
[Request] Compatibility for r4i-sdhc flashcard autoboot

### ISSUE THREAD

**Issue by ValentiMS** [ahezard/nds-bootstrap#278]
My current flashcard uses R4.dat to boot, but when I try to use any of the flashcard 
(https://i.imgur.com/t3SUWJ5.jpg) autoboot files it brings up this error: https://i.imgur.com/q7rFB2P.png
If I use any file that isn't from the web page itself, it also brings up that error. I know it's possible to compile for this flashcard because I recently found a file which allows you to autoboot YSMenu and it works perfectly.
Also, when I boot the default.nds file from YSMenu or my flashcard official firmware, when loading a game it gets stuck on a white screen :/
PS: The flashcard's web is r4isdhc.com although r4i-sdhc.com firmware boots but doesn't load.

**Comment by Robz8** [comment]
Anything involving flashcard autoboot goes to the DSiMenu++ repo.
