### ISSUE TITLE
Zelda Phantom Hourglass freezing after purchasing shield 

### ISSUE THREAD

**Issue by Stack3r** [ahezard/nds-bootstrap#280]
I played up to the point to where I was almost off the first island and when I purchased the shield the game froze with link holding an invisible item and the music in the background still playing

**Comment by dubbz82** [comment]
If this is AP, it's undocumented AP.  I'm guessing something else is going on here that's causing it to lock up.

**Comment by Doom9138** [comment]
Same thing is happening to me. I'm playing a control hacked version and not the regular rom. Stack3r are you playing the regular rom?

**Comment by Stack3r** [comment]
Mine should be the normal version, it doesn’t have the dpad hack

**Comment by Robz8** [comment]
@LuisSant Just send the patch.
It is illegal to share commercial ROMs here.

**Comment by LuisSant** [comment]
Ok
I Will Send The Patch If I Can Find It, Do You Know How To Patch It?

**Comment by dubbz82** [comment]
As stated earlier in this issue, this game has no known AP measures....

**Comment by LuisSant** [comment]
Well It Could Work...

**Comment by LuisSant** [comment]
Well Your Kinda Screwed

I Cant Find The AP patch
I Can Try To Find It, But It Going To Take Some Time...

I Searched For Hours The Kirby Mass Attack Ap Patch
It Took Me Like 5 Days To Find It, So Yeah

**Comment by piratesephiroth** [comment]
nah this is an old game, I never heard of it having any AP protection

**Comment by shiftythefox** [comment]
On version 6.0.0, set the ARM9 CPU speed to 133mhz (TWL). It fidex the problem for me on a regulag 3DS with luma.

**Comment by shiftythefox** [comment]
@DeathTBO: If you don't have train controls in Spirit Tracks, then you need the rom patched. It's an AP measure in the game.

**Comment by DeathTBO** [comment]
@shiftythefox Thanks, I never had issues on DeSmuME or No$GBA. It's working like a champ now.

Phantom Hourglass tho...

**Comment by Plausible0Bug** [comment]
It seemed as of https://github.com/ahezard/nds-bootstrap/releases/tag/v0.14.0RC1

I can play this game properly.

I used to be stuck right after shield purchasing and later entering the shrine for the phantom sand.

Now I'm at the place where I search for a way to pass the fog, no problem so far.

I'm using twilight menu on my n3ds with luma3ds.
