### ISSUE TITLE
Ermii Kart hack Red Screen

### ISSUE THREAD

**Issue by iamnotthelegend27** [ahezard/nds-bootstrap#282]
A hacked custom Mario Kart ROM with DSiMenu++ doesn't work. It loads the pong game then goes to a red screen with hex values.The spreadsheet says that it "blackscreens after a few minutes," but I can't load it at all.

**Comment by dubbz82** [comment]
Hard to debug without the name.  Can you at least get a picture of the screen with the hex values?

**Comment by NoName432** [comment]
Oh and I just wanted to let you know that on the spreadsheet it says that it’ll black screen on the demo version. It doesn’t say anything about the beta version.

**Comment by FlameKat53** [comment]
Ermii Kart DS Legacy Edition works, make sure theres no cheats and its in DS Mode, 67MHz and VRAM Boost off

**Comment by NightYoshi370** [comment]
According to Kaisaan on our Discord Server, this error appears to be fixed on the latest version. That's why this was closed
