### ISSUE TITLE
Loading Screen displays "Error" when trying to play Pokemon Volt White 2

### ISSUE THREAD

**Issue by TheMCNerd2017** [ahezard/nds-bootstrap#284]
I am using the latest version of DsiMenu++ and NDS Bootstrap. Whenever I try to load the Pokemon Volt White 2 rom from my microSD card, it stays on the normal loading screen for a few seconds, then displays "Error" on the screen as well as a red X on top of the loading graphic. I am not sure why this is happening, or how I can fix this issue.

I am using a New Nintendo 3DS XL, with a 64GB Sandisk microSD Card.

**Comment by Robz8** [comment]
Does unhacked White 2 work for you?

**Comment by TheMCNerd2017** [comment]
Yeah, I am able to load unhacked Pokemon White 2.

**Comment by Robz8** [comment]
You need to update nds-bootstrap then, even if you think you're at the latest.

**Comment by CarterLiebman** [comment]
I can also vouch for this error -- I updated to the newest version as of today and can also load a clean White 2 version.

Is there a debug display for these kinds of load errors?

**Comment by TheMCNerd2017** [comment]
OK, I updated nds-bootstrap again, like you told me to do, and the issue is still happening. Something I should point out is that the game icon for Volt White 2 is garbled/glitched for some reason.

**Comment by cybershell12** [comment]
Blaze Black 2 also doesn't work. But regular Black 2 Works.

**Comment by Burningocean2012** [comment]
This is also my problem!Blaze Black and Volt White both work no problem but not the ones for 2.

**Comment by Mr-Gela** [comment]
I've got the same issue. This is the banner in the Forwarder3DS, it also looks corrupted in DSMenu++, and fails to run it. I am on the lastest version.

**Comment by Mr-Gela** [comment]
Is there anything that can be done about it? Is it something the developer could help with? Their Twitter: https://twitter.com/Drayano60

**Comment by piratesephiroth** [comment]
Well you could start by asking what the hell did he use to compress that arm9 binary because nds-bootstrap and all the tools I have used fail to decompress it.

**Comment by piratesephiroth** [comment]
I think I found a way to fix the roms. Just open them with Tinke and save.

**Comment by Mr-Gela** [comment]
The developer confirmed to me via Twitter that they used CrystalTile2, if it matters in order to understand the compression of the files.

**Comment by piratesephiroth** [comment]
I just made a pull request fixing this

**Comment by Mr-Gela** [comment]
Using this build I found a new crash related to Volt White 2, but might happen in regular White 2: After unlocking the Key System (first 5 minutes of the game) I saved my game and soft-reseted as the Key System must be accessed from within the main menu. After doing so and saving my changes, instead of returning to the main menu, I got a whitescreen.

**Comment by RocketRobz** [comment]
Issue has been fixed for a while.
