### ISSUE TITLE
Jump Ultimate Stars (english patched) white screen on start

### ISSUE THREAD

**Issue by Dragonracer21** [ahezard/nds-bootstrap#285]
If I try to boot it, it gives me a white screen. I already tested it on pc with ds emulator desmume and it works properly there. Hope you can fix this. I'm playing on o3ds DSiMenu++ 4.4.0 Rev 01 and nds bootstrap 0.10.1. SDK Version is 3 and release number is: 0696, thank you.

**Comment by piratesephiroth** [comment]
You need to repack the game (with ndstool, for example).
I think the tools they used to insert the translated files back then were kinda broken.

**Comment by Dragonracer21** [comment]
Ok I will try and report back, thank you.

**Comment by Dragonracer21** [comment]
Hey, I'm thinking... If the game is brocken then why does it work perfectly on pc with desmume emulator. And also I don't know how to use ndstool. I open it there comes a window with black inside and then in a half second it closes itself.

**Comment by piratesephiroth** [comment]
Here's the latest ndstool.
I also added a bat file. Just drag and drop the rom onto it and a repacked file will be created.

[ndstool.zip](https://github.com/ahezard/nds-bootstrap/files/2161160/ndstool.zip)

**Comment by piratesephiroth** [comment]
(I reuploaded the file to fix a mistake in the bat file, please download again)

**Comment by Dragonracer21** [comment]
Ok

**Comment by Dragonracer21** [comment]
@piratesephiroth hey sry I have been away for a while. Repacking Jump Ultimate Stars with ndstool helped. Game is now working properly with nds bootstrap. I will now close this issue.
