### ISSUE TITLE
Ghost Trick: Phantom Detective -  Save game data becomes corrupt

### ISSUE THREAD

**Issue by JourneyOver** [ahezard/nds-bootstrap#287]
Running Ghost Trick: Phantom Detective with AP patch (AP patch is needed otherwise you get blank text). Ended up playing through the whole entire game in one go without closing out of the game any and upon beating the game and having it save and do the whole intro sequence it throws a message about the "game save data has become corrupt" and that it's going to delete itself.. When checking the .sav file seems to still be there but upon relaunching the game it's like the game doesn't even read the save anymore..

Don't know if it happens if you end up exiting the game at any point or not since as I mentioned I played through without closing out of the game any, and I just don't feel like replaying chapter 1 again and the only way it seems that you can save is only at the end of each chapter.

**Comment by Stack3r** [comment]
Can this be tested and see if it’s still an issue

**Comment by hubert-skowronek** [comment]
@ahezard @RocketRobz @Stack3r I didn't attempt to complete the game without closing it even once, but I didn't encounter any issues with saves and I'm already at Chapter 8 (saved/loaded the game many times) - not sure if being near the end of the game has anything to this issue.

**Comment by ahezard** [comment]
So this seems fixed. I am closing it.
