### ISSUE TITLE
Touchscreen broken on nds-bootstrap v0.10.1

### ISSUE THREAD

**Issue by Megahaosguy** [ahezard/nds-bootstrap#288]
nds-bootstrap 0.10.1
DSI Menu ++ 4.3.1
o3DS latest luma and sys firmware

The touchscreen does not function in the game.

edit: While originally posted for Wario: Master of Disguise, I have noticed that no touchscreen operations function anywhere in dsi menu ++ nor any game loaded from it. Worked fine on version v0.10.0

**Comment by Robz8** [comment]
Anything involving touch input was not changed.
Try re-installing the latest DSiMenu++ CIAs.

**Comment by Megahaosguy** [comment]
That fixed it. Thanks!
