### ISSUE TITLE
Regression on the game Anno 1701 (unlisted)

### ISSUE THREAD

**Issue by Exagone313** [ahezard/nds-bootstrap#290]
Hi,

I switched from TWLoader v6.6.2 shipped with nds-bootstrap v0.7.3 to DSiMenu++ and latest nds-bootstrap (tested only with v0.10.0 and v0.10.1).
The game Anno 1701 (that is not listed in the Spreadsheet) is almost stable on TWLoader and that nds-bootstrap version, just having minor graphical glitches.
But I get a regression on latest nds-bootstrap: a lot of images on the top screen are not loaded and thus the top screen looks like frozen (on start menu and in-game). I reinstalled TWLoader like I had before and it's not affected.
I'd like to debug this, but I guess the way nds-bootstrap is loaded has changed between these versions, because replacing nds-bootstrap alone is not working (it freezes on white screen when loading the rom), so I can't use the usual way to find what version/commit causes the regression.
Do you have a better idea for debugging?

Thanks for your help.

**Comment by Robz8** [comment]
Have you tried TWLoader with nds-bootstrap v0.10.1?

**Comment by Exagone313** [comment]
Oh nice it can load nds-bootstrap (with the same issue)!
So I'm going to try all released versions.
One problem I may have is that my builds are not working, I get white screens (but I tried with DSiMenu++, not TWLoader yet). If I could use the builds from travis it would help, if there are stored somewhere..?

**Comment by Robz8** [comment]
There's nightly builds here: https://github.com/Robz8/DSiMenuPlusPlus-update
They're all compiled by me.

**Comment by Robz8** [comment]
I've fixed the issue. The missing graphics are loaded again.
Thanks for your feedback!

**Comment by Exagone313** [comment]
I can confirm it fixed the issue.
