### ISSUE TITLE
Random freezes on Pokemon Heart Gold/Soul Silver

### ISSUE THREAD

**Issue by noraa11** [ahezard/nds-bootstrap#291]
From recent searches this appears to have been closed quite a while ago but is still present. 

The game will lock up while still playing music. I’m using the latest bootstrap as of writing.

**Comment by Robz8** [comment]
Is your ROM AP-patched?

**Comment by noraa11** [comment]
Yes it is.

**Comment by Dayranlite** [comment]
I'm using tus latest bootstrap and still present the random freezes. I'm playing Pokemon Heart Gold and I think It don't work because It's EUR version
