### ISSUE TITLE
Spider-Man: Friend or Foe missing bottom screen and freezes on new game

### ISSUE THREAD

**Issue by GoddamMeme** [ahezard/nds-bootstrap#292]
The game will start up, but after the intro credits it gets stuck on the title screen without a bottom screen.
Nintendogs: Dalmatian and Friends is also a sdk3 game but it runs just fine.

**Comment by dubbz82** [comment]
Release numbers (no intro numbering) are 1472 and 1493 for US and Europe, respectively.  This most likely is not an AP issue.

**Comment by GoddamMeme** [comment]
Still has the same issue as before. The release number checks out. When I start up this game, the bottom screen is either black or white, and attempting to start a new game makes both screens black, at which point I have to reset the system. Am I missing something?
