### ISSUE TITLE
Dogz DS

### ISSUE THREAD

**Issue by iamnotthelegend27** [ahezard/nds-bootstrap#293]
Running Dogz (a nintendo DS game) causes the Pong loading screen to turn RED and not end until exiting DSiMenu++ 3DS.

**Comment by iamnotthelegend27** [comment]
The ball and the paddles turn red and the game still works but the ROM never loads.

**Comment by Robz8** [comment]
Are you using the latest nds-bootstrap (v0.10.1)?

**Comment by iamnotthelegend27** [comment]
Latest FW with the bootstrap that came with the latest DSiMenu++. I updated DSiMenu++ but it still said 4.2.0. Using the 3dsx launcher. Overwrote the _nds folder and installed the CIAs, launched the 3dsx.

**Comment by Robz8** [comment]
Re-download the latest DSiMenu++.

**Comment by iamnotthelegend27** [comment]
I re-updated and the new DSiMenu++ is there now. Instead of getting stuck on a red pong screen, the pong game fades. The game never loads, though.

**Comment by ahezard** [comment]
There is no more issue with the latest nightly.
