### ISSUE TITLE
Kirby: Canvas Curse Not Saving

### ISSUE THREAD

**Issue by rafagamaxima** [ahezard/nds-bootstrap#294]
I tried out the game with version 0.10.1 of bootstrap and DSIMenu++ 4.4.0 in a 2DS, but after making a new save, leaving the game (going to the 2DS main menu), and coming back... the save disappears... I tried out saving in slot 1, 2, and 3, with the same results.

**Comment by Robz8** [comment]
Does the same issue occur in v0.10.0?

**Comment by rafagamaxima** [comment]
Unfortunately the issue also ocurs in V0.10.0... I tried just by replacing the bootstrap files in the _nds folder, and also by reinstalling DSiMenu++ with the bootstrap files replaced.. both having the save issue... Thanks for your time, I hope it can be sorted out

**Comment by rafagamaxima** [comment]
The issue is still present in DSiMenu++ 5.3.1 and NDS bootstrap 0.10.2.. am I doing something wrong?

**Comment by Robz8** [comment]
No, you're not. It's an issue for everyone.

**Comment by rafagamaxima** [comment]
Ohh ok, I hope it is eventually fixed, thanks for your work

**Comment by ahezard** [comment]
There is a specific patch in wood for the Kirby: Canvas Curse saves https://github.com/ahezard/woodrpg_forwarder/blob/e0280c91b21e28443c23f98a171012ef8a301b0c/akloader/arm9/source/patches_sd.cpp

**Comment by ahezard** [comment]
Fixed in latest nightly
