### ISSUE TITLE
Spider-Man: Web of Shadows gets stuck on a black screen (purple LED)

### ISSUE THREAD

**Issue by GoddamMeme** [ahezard/nds-bootstrap#295]
Spider-Man: Web of Shadows (U) 2821 gets stuck on a black screen and on my DSi the power LED turns purple. I think I read somewhere that a purple LED color means the rom is not supported. What qualifications does a rom need in order to be supported?

**Comment by ahezard** [comment]
this issue is no more present with latest nightly
