### ISSUE TITLE
bunch of supported games do not work

### ISSUE THREAD

**Issue by seipou** [ahezard/nds-bootstrap#297]
aliens infestation: tried the US/EUR rom, on latest nds-bootstrap and dsimenu++ 5.0.0 but it gives me a black screen
Inazuma eleven patched w/ japanese voices do not load at all and gives an error if you try to start it
phantasy star 0 does not load and gives a white screen

**Comment by dubbz82** [comment]
Aliens infestation (5837 and 5863 for US and European versions) actually are NOT reported to be AP protected, and I was able to replicate black screens for these.  I do not have the copy of Inazuma eleven in question to try and replicate the issue.

**Comment by dubbz82** [comment]
The Inazuma Eleven issue may be related to #281 if the base rom used is the remastered version.

**Comment by seipou** [comment]
Yes that's the version, it's the EUR rom patched with japanese audio and subtitles for cutscenes. It doesn't boot and gives an error if you try to start it

**Comment by dubbz82** [comment]
http://www.mediafire.com/file/syse0pk68h3j5o8/5535+-+Inazuma+Eleven+%28E%29+REMASTERED.7z link to the patch to convert a clean rom to the remastered version.

**Comment by dubbz82** [comment]
POSSIBLE that this is the same deal as the Pokemon romhacks where arm9.bin fails to properly decompress?

**Comment by gentlecolts** [comment]
Tried Phantasy Star 0 on nds with a freshly installed dismenu++ and it whitescreens (booting from rom off sdcard).  Using the release builds and not nightly though, if that matters.  Find it odd that it's not working considering black2 works and that didn't get support until apparently 0.10.  Also unsure if that's a dsimenu++ bug or nds-bootstrap bug, apologies if I'm posting in the wrong place.
