### ISSUE TITLE
Professor Layton and the Last Specter stuck on white screen

### ISSUE THREAD

**Issue by edo9300** [ahezard/nds-bootstrap#298]
I'm using a dsi xl with dsimenu++, latest version, and when i launch the european version of this rom, as title says it's stuck on a white screen

**Comment by edo9300** [comment]
updated, i tried this game with a previous version of the bootsrtap, the 0.9.2 and it works

**Comment by DMSalesman** [comment]
Can reproduce with an untouched ROM.

Regarding the AP patched ROM, it's stuck on a white screen from v0.10.0 onwards, while it freezes on nds-bootstrap's splash screen on v0.9.2.

**Comment by DMSalesman** [comment]
Update: the freeze at splash was due to an incorrect AP patch. Everything works under v0.10.1.

@edo9300 Is your ROM AP patched or original?

**Comment by edo9300** [comment]
Tested with 10.1 and it's working fine, I'm closing the issue
