### ISSUE TITLE
Homebrews frozen on black screen at launch?

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#3]

**Comment by ahezard** [comment]
From https://gbatemp.net/threads/ds-i-mode-hacking-progress-thread.413015/page-121#post-6725519

notepaint bs
homebrewwifi bs
streetfighterds bs

**Comment by Robz8** [comment]
I recompiled DSi4DS with devkitPro32, and it goes black after 2 seconds of white screen.

**Comment by ahezard** [comment]
Interesting, the arm7 patcher may  have a problem with homebrew compiled with this version of devkitPro. By the way why are you recompiling DSi4DS? You want to fix it?

**Comment by Robz8** [comment]
Trying to get it to read .nds files from a folder instead of the SD's root.
As for fixing it, if the black screen problem is resolved, I might get it to work with your bootstrap for booting nds files.

**Comment by ahezard** [comment]
You recompiled with devKiPro32 but which version of libnds? I suggest you to use the version delivered originally with devkitpro32.

**Comment by Robz8** [comment]
Duyumania (a game that almost made it to DSiWare) is another game that black screens.

**Comment by RocketRobz** [comment]
The issue with Duyumania is fixed in v0.15.0, though some graphics are missing.
Same issue happens when launching the homebrew directly on a flashcard using hbmenu or TWiLight Menu++.

**Comment by NightYoshi370** [comment]
Why not have a seperate issue for every homebrew, instead of one issue for all?
