### ISSUE TITLE
Compile error: 'REG_MBK_2' undeclared

### ISSUE THREAD

**Issue by jpmac26** [ahezard/nds-bootstrap#30]
Every time I've tried to compile the "card" branch of nds-bootstrap, I get a bunch of "{variable name} is undeclared" errors. These specific errors are new, only appearing after I completely deleted my old installation of devkitARM r45 and made a fresh install of devkitARM r46, but I've been getting similar errors no matter when I try, or what branch/revision of the code I've currently checked out, and it's been driving me nuts! I figure I must be doing something terribly wrong if no-one else has reported compilation issues by now, so any help would be much appreciated!

The exact error I'm getting is:
```
/home/james/git/nds-bootstrap/cardengine_arm9/source/cardEngine.c:88:5: error: 'REG_MBK_2' undeclared (first use in this function)
     REG_MBK_2=0x8185898D;
     ^~~~~~~~~
/home/james/git/nds-bootstrap/cardengine_arm9/source/cardEngine.c:88:5: note: each undeclared identifier is reported only once for each function it appears in
/home/james/git/nds-bootstrap/cardengine_arm9/source/cardEngine.c:89:5: error: 'REG_MBK_3' undeclared (first use in this function)
     REG_MBK_3=0x9195999D;
     ^~~~~~~~~
```

**Comment by Robz8** [comment]
You still need devkitARM r45 plus ahezard's libnds.

**Comment by jpmac26** [comment]
Thanks a bunch, now it works fine! Also, if that info (or any compilation info for that matter) could be added to the README file or something, that would be really helpful too, since I'm not really sure how I could have found that info out if I didn't ask directly ;)
