### ISSUE TITLE
Builds of recent commits (even tagged) causing white screens

### ISSUE THREAD

**Issue by Exagone313** [ahezard/nds-bootstrap#302]
Hi,

All my builds of nds-bootstrap (master branch, not tested sdk5) of recent commits (I didn't track since what commit it does this) cannot be launched from DSiMenu++: I get white screens when launching any game.
This doesn't happen for builds of older commits, like the builds I've done for finding a regression earlier (meaning I correctly install nds-bootstrap builds).

Since tags (e.g. v0.10.0) are affected too and these are supposed to be tested, I think only the environment of compilation matter.
I use Arch Linux with devkitpro+arm installed with pacman, everything up-to-date. I haven't tried to compile on Windows to see the difference.

Is it possible to have some verbosity to understand what's the issue?

**Comment by piratesephiroth** [comment]
yeah,  even DSiMenu++ is giving the  same white screens. Only the sdk5 branch of nds-bootstrap still works as expected.

I noticed that the "roms" built with the most recent toolset are noticeably smaller.
They have about 100KB less than the [nightly builds](https://github.com/Robz8/DSiMenuPlusPlus-update) compiled by @Robz8

**Comment by piratesephiroth** [comment]
I ran pacman to update the packages yesterday and it seems to be work fine again now

**Comment by ahezard** [comment]
I do not see this issue on windows at all, I use the latest devkitpro updated with pacman.

**Comment by piratesephiroth** [comment]
As I commented a week ago, it's been fixed already. I think it was a problem with some compression tool.
