### ISSUE TITLE
Pokemon HG/SS still freeze

### ISSUE THREAD

**Issue by Dayranlite** [ahezard/nds-bootstrap#303]
I'm using tus latest bootstrap and still present the random freezes. I'm playing Pokemon Heart Gold and I think It don't work because It's EUR version

**Comment by Megahaosguy** [comment]
What console are you playing on and are you using a patched ROM?

**Comment by Dayranlite** [comment]
I'm playing on 2ds and yes, that's it

**Comment by Verakin** [comment]
My SoulSilver is freezing from time to time, even with the latest v0.10.1 bootstrap and v5.1.0 DSIMenu
tried 2 different SoulSilver roms. Randomized and normal, both gives me freezes / crashes.

**Comment by WalaRocks18** [comment]
Just AP patch em

**Comment by Megahaosguy** [comment]
I've played the first hour of Heart Gold USA with an AP patch on my o3DS running nds-bootstrap v0.10.1 and I experienced zero issues. Try and see if a USA rom with an AP patch will work for you.

Just to make sure, are you using an EUR patch for that EUR rom?

**Comment by WalaRocks18** [comment]
Or aimply use the DS Scene tool

**Comment by NinjaJonte** [comment]
I also experience issues while playing soul silver (us version) unpatched, and I think I know why. 

The game seems to randomly freezes in loading screen, and sometimes when I traverse a world, it stops loading the map showing a black void before crashing the game.

To me, these are signs of the game data not loading correctly into ram, however as I'm not very familiar with ds code at all, I can't help further than that.

I've played through most of the game now, I just make a habit of saving often, and it works tremendously.

**Comment by NightYoshi370** [comment]
AP patching the ROM has proven to fix the issue.
Closing
