### ISSUE TITLE
How I Install Homebrew ?

### ISSUE THREAD

**Issue by LuisSant** [ahezard/nds-bootstrap#304]
Im On A DSi
I Need Help For Installing Homebrew
All The Homebrew I Install Just Shows A Black Screen, White Screen, Infinite Loading,etc
I Tried Everything

**Comment by LuisSant** [comment]
**THIS IS NOT AN ISSUE**

**Comment by Robz8** [comment]
Homebrew support is low priority for now, so some will not work.

**Comment by Multimegamander** [comment]
@LuisSant first, you hardmod, then when you plug it in to PC, it will ask if you want to format, press yes to format homebrew onto it

**Comment by Multimegamander** [comment]
WhO dIsLiKe? Valeri0p
