### ISSUE TITLE
Dragon Quest IX White Screen

### ISSUE THREAD

**Issue by FinalFate615** [ahezard/nds-bootstrap#310]
Using Luma3DS 9.0 on O3DS
nds-bootstrap 0.10.1, DSiMenu++ 5.1.0 through DSiMenu Launcher 1.1.0

Game loads but displays a white screen and doesn't respond apart from pressing the home button
Tested with USA and EUR versions of the game, both with AP patches applied and without.

**Comment by FinalFate615** [comment]
Now working with latest nightly version.

**Comment by FinalFate615** [comment]
Was a problem with DSIMenu++, working now after updating to the latest release

**Comment by dualdragoon** [comment]
I'm using the newest version of DSiMenu++ (6.2.1), and DSiMenu++ Laucher (2.0.2) with whatever version of nds-bootstrap is bundled DSiMenu++. I've got the same problem as mentioned. Any help would be appreciated.
