### ISSUE TITLE
Super Mario 64 DS Sleep Issues

### ISSUE THREAD

**Issue by MarioKartFan** [ahezard/nds-bootstrap#311]
Created an account to post this.  Super Mario 64 DS goes to a black screen when waking from sleep mode.  The black screen never goes away until you close out and relaunch.  

Tested on a 2DS, a 2DS XL and a 3DS using the latest release, as well as nightly bootstrap builds.  Wonder if its related to the sound that Mario makes when you close the system?  Not having any issue with the other games I have tested, all of which wake from sleep mode fine.

**Comment by Robz8** [comment]
To fix the issue, set NTR clock speed for that game.

**Comment by MarioKartFan** [comment]
That was...the fastest response I have ever received.  What you all have done with NDS-Bootstrap and DSIMenu++ is nothing short of miraculous.  Thank you so much.

**Comment by RinMaru** [comment]
this issue still happens regardless of the speed you use
