### ISSUE TITLE
Professor Layton and the Curious Village EUR - Cutscene lagging

### ISSUE THREAD

**Issue by DMSalesman** [ahezard/nds-bootstrap#313]
Inside the Professor Layton and the Curious Village game, there's a cutscene involving a ferris wheel pursuing the protagonists; when the wheel jumps into the water, the cutscene slows down to a crawl, while artifacts are visible and the audio seems muted.

Once the cutscene ends, everything returns to work flawlessly.

-----

Device: New3DS
nds-bootstrap: v0.10.1 (release)

**Comment by jamieluckett** [comment]
How fast is your SD card?

**Comment by DMSalesman** [comment]
It's a Class 10 microSDHC from Lexar, holding up to 32GB, formatted to FAT32 with clusters of 32kB from within GodMode9.

Possibly worth noting that none of the 3DS games installed on it lags, as well as none of the other .nds files (for now).

**Comment by ahezard** [comment]
Could be linekd to #517

**Comment by ahezard** [comment]
Should be fixed in latest nightly release please re-test
