### ISSUE TITLE
The World Ends With You - Laggy locations 

### ISSUE THREAD

**Issue by MatFTW** [ahezard/nds-bootstrap#315]
When trying to scan certain places and also going to certain places like Towa Records or AMX, It's pretty laggy and sometimes the bottom screen would glitch out with a clone on the bottom...

Device : Old 3ds 
NDS Bootstrap 0.10.1

**Comment by ahezard** [comment]
Can you try with 0.10.2 with async prefetch disabled and enabled, it should still be laggy probably but i want to know if the glitch are still there

**Comment by MatFTW** [comment]
Ahh now its all good with async, glitch is gone, minimal lag but more playable than the last version of bootstrap...
