### ISSUE TITLE
[Quick question] Does the nds-bootstrap support the 3DS: NDS pixel-perfect mode?

### ISSUE THREAD

**Issue by WalaRocks18** [ahezard/nds-bootstrap#316]
you know, when you press a + start (or select) on the menu screen of the 3DS an then it appears in the original resolution.
https://en-americas-support.nintendo.com/app/answers/detail/a_id/179/~/how-to-play-nintendo-ds-and-dsi-games-in-their-original-resolution
Here is a link for references.
If isn't on the bootstrap, could you program it?

**Comment by WalaRocks18** [comment]
https://www.google.cl/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwj9uK6xhJ_cAhWimOAKHVFUBlEQjRx6BAgBEAU&url=https%3A%2F%2Fkotaku.com%2F5785954%2Fhow-the-3ds-alters-ds-games-and-what-you-should-do-about-it&psig=AOvVaw1c7KvASEKc1B4vmaM4uUCr&ust=1531672909353583

**Comment by WalaRocks18** [comment]
nevermind, it is possible

**Comment by WalaRocks18** [comment]
yust press start and select when selecting to open dsi menu or last ran rom and it should work.

**Comment by WalaRocks18** [comment]
Keep this open to the poeple to know more about the capacities about this bootstrap

**Comment by Uupo03** [comment]
ANYTHING running in NTR/TWL (DS/Dsi) mode running on a 3ds will support it.
