### ISSUE TITLE
New Super Mario Bros.

### ISSUE THREAD

**Issue by maorninja** [ahezard/nds-bootstrap#32]
So, as we all know, NSMB doesn't work on this project. However, I think a great team of developers found the reason for the compatibility issue...

So, lets start off by Skawo's research: Here is a PM about the NSMB projects

https://cloud.githubusercontent.com/assets/18664762/22337794/adcf99b4-e39a-11e6-9164-c10ab13f271c.png

Now lets get onto the research I found at TCRF, AKA @xkeeper0 's site.

> There is a hidden crash dump screen in the game. To access the crash dump screen hold L + R + A + Left, let go, hold Down + B, let go, and finally hold Start + Select.

> The top screen shows the reason for the crash, while the bottom screen shows a stack dump.

@WTails358 actually followed these steps and here are the screenshots he got:

http://gbatemp.net/attachments/image-jpg.76169/ Top screen
http://gbatemp.net/attachments/image-jpg.76170/ Bottom Screen

I just edited those 2 images to just make loading times better and have a better look.

This screenshot was taken on 0.3.0beta1.

This screenshot is taken on the latest commit: https://cdn.discordapp.com/attachments/283769550611152897/329109906265210880/WIN_20170626_21_05_08_Pro.jpg

The main site for NSMB hacking is here: http://nsmbhd.net/ It is a site thats ran by amaizing NSMB hackers, mainly @StapleButter, @Dirbaio and @MarioMaster. Just post your issue there and they should help...

Unfortunately, I am banned there and requesting an unban didn't exactly work (I got banned because of a fight with a moron, but maybe I can request an unban just for this discussion???), so please don't restrict all activity there, as I know some NSMB hacking info that can help with this....

**Comment by ahezard** [comment]
This is very interesting, thanks. 
does this 2 screenshot 
http://gbatemp.net/attachments/image-jpg.76169/ Top screen
http://gbatemp.net/attachments/image-jpg.76170/ Bottom Screen
have been taken with the v0.3.0beta1? 

A crash report without the exact version of nds-bootstrap (official release or commit id) is kinda useless.

**Comment by maorninja** [comment]
Yes. Those 2 screenshots were taken with v0.3.0.

**Comment by StapleButter** [comment]
there's another grammar mistake: you misspelled Kuribo64.

**Comment by maorninja** [comment]
I made that "spelling mistake" on purpose...

**Comment by StapleButter** [comment]
http://rhcafe.us.to/?page=t&id=10&from=2260#post6658

you're 21, do I need to remind you?

**Comment by maorninja** [comment]
No?

I already know my age...

But you're right. I shouldn't let our drama conflict between us get into serious buisiness. Its very childish of me...

**Comment by ApacheThunder** [comment]
Mmmm Ok, so why exactly did you bring an argument over politics into an unrelated issue thread? Please don't do that. It will never end well. It would benefit all of us if you kept that discussion on the forum you started it in. ;)

**Comment by maorninja** [comment]
And thats why I actually removed the arguement.

**Comment by StapleButter** [comment]
I won't get into shit like 'X was the one who started it', but I will say that I don't like the idea that 'drama' should be avoided at all costs. Being able to resolve issues ends up better than letting them rot unresolved to try keeping public space 'clean'.

Regardless, thank you maor.

**Comment by ApacheThunder** [comment]
Yeah I haven't read all of the details on the drama you two are into. I'm not against avoiding all drama everywhere. But there are some places I'd like to not see it spread into. That aside it's good to see you've worked it out at least. :P

**Comment by maorninja** [comment]
Your welcome staple. Anyways, lets back on topic,

So, mainly, the problem is Download Play, according to the fuction name. However, if you remove the DLP, you'll find that it has a problem in CARD_READ, according to card.v.0.1. I'll wait for wait for Skawo's Newer DS to be released as this ROM Hack actually removed the DLP function and the CARD_READ function has mainly been fixed in both NDS bootstrap and Newer DS, with only slight bugs left...

That being said, it will be nice if Skawo can make a new video on running Newer DS with both the latest bootstrap beta release (0.3.0beta1) and the stable release (0.2.0)

**Comment by ApacheThunder** [comment]
Yeah I was concerned this would devolve into the drama I'm used to seeing on GBATemp. As long as it's civilized (which it has been for the most part I think but who am I to judge. :P ) then I don't have too much of an issue with it then. :P

But as for the subject of this issue thread, some DLP games have been reported to work. I suppose there's still some bugs with the games that still work but have issues like this.

**Comment by maorninja** [comment]
Anyways, I have a bunch of support bug fixes for other games, should I just:

A) cramb them all here?
B) Make 1 issue per game here?
C) Make 1 issue per game on another repo?

I honestly think the third one is the best option.

This is what I made last night **just as an example:**

https://github.com/maorninja/nds-bootstrap-game-compatibility/issues

**Comment by ahezard** [comment]
You can make one issue per game. Why another repo? I prefer to have it here

**Comment by maorninja** [comment]
> Why another repo? I prefer to have it here

You're right... I'll make 1 issue per game...

I'll BRB and delete my repo...

**Comment by ahezard** [comment]
I was able to get the debug screen using the manip you described. Thanks

**Comment by ahezard** [comment]
Ok so first thing I notice : this game requires arm7 swapping with the current version

**Comment by ahezard** [comment]
Arm7 swapping via the classic "MaxCrass" method breaks the game so it will require more works on the patcher in order to improves arm7 patching. Do no expect that it will works soon.

**Comment by maorninja** [comment]
Okay, so, since the MaxCrass method is now obsolete, can you test the game again with a donor ROM and show here the results?

**Comment by ahezard** [comment]
Do not bother too much the donor ROM option break New Super Mario Bros (at least with mario kart as donor rom).

**Comment by WTails358** [comment]
So does this mean that It will take a little bit longer than expected for NSMB to work?

**Comment by maorninja** [comment]
Well, we need ARM7 swapping...

The Donor ROM @ahezard tested is MKDS, but maybe it might just work with other games...

I just need a list of games that run without a Donor ROM so I can test NSMB with them...

**Comment by Robz8** [comment]
I tested NSMB on a DSi, and I can confirm that only one ROM read occurs, then it just stops, staying on white screens.
@ApacheThunder said that perhaps the rom read function for that game isn't patched right. So it tries to read something, returns garbage/null and the game immediately hangs.

**Comment by maorninja** [comment]
Well, we just fixed a bit of compatibility.

It's still broken, but now, it crashes much later into the code.

[9:12 PM] NightYoshi370: The old starting address was 02089820
[9:13 PM] NightYoshi370: The new one now starts at 020962eo

**Comment by shutterbug2000** [comment]
This game is fixed as of the latest commit.
