### ISSUE TITLE
Legend of Zelda Spirit Tracks audio issues

### ISSUE THREAD

**Issue by Sagametroid** [ahezard/nds-bootstrap#320]
nds-bootstrap: 0.10.1
Console: old 3ds
in caves and dungeons the sound sometimes just mess up.
only happens in the left speaker (also happens with earphones meaning is not hardware related problem)

**Comment by ahezard** [comment]
Please test with this build : https://mega.nz/#!Wc0QQYSR!MsiTfrpCXo_E7g6qz0w5NTWoJVQL3IcVJpOq_1FJPhQ

**Comment by Stack3r** [comment]
This is no longer an issue
