### ISSUE TITLE
Pokemon B2/W2 work, but BB2/VW2 don't 

### ISSUE THREAD

**Issue by ismailhasannnnnn** [ahezard/nds-bootstrap#321]

**Comment by legoj15** [comment]
People have already stated this in another issue.

**Comment by ahezard** [comment]
Ok so this is a rom hack. What error do you have? white screen? black screen?

**Comment by ismailhasannnnnn** [comment]
A white screen

**Comment by Robz8** [comment]
Really? I've heard bootstrap's error screen just shows up, which happens for me.
It's a result of bootstrap failing to decompress it's arm9 binary.

**Comment by ismailhasannnnnn** [comment]
Well, using DSiMenuPlusPlus, the little loading game just turns red, and everything else is just white

**Comment by Robz8** [comment]
Ah, so you have a minigame set as your loading screen.
When the graphics turn red, that means an error has occurred.

**Comment by ismailhasannnnnn** [comment]
Ohhh gotcha. Sorry I didn’t know. Is it something that’ll be able to be fixed?

**Comment by damianoamatruda** [comment]
Duplicate of #284
