### ISSUE TITLE
Inazuma Eleven 2: Firestorm - Annoying bug

### ISSUE THREAD

**Issue by vondock** [ahezard/nds-bootstrap#326]
Random freezes in transitions of areas or movies. What I can do to play this game without this problems? Without this issue, works fine.

**Comment by Robz8** [comment]
AP-patch the ROM.

**Comment by vondock** [comment]
How I can do this? Sorry I'm kinda of a noob.
Awesome homebrew tho!!

**Comment by Robz8** [comment]
Find the patch and the patching program here: https://www.odrive.com/s/8443cc3a-862e-41d7-b064-09378f79f6b3-5965a89a

**Comment by vondock** [comment]
Thank you very much! I'm playing without any crash issue.
