### ISSUE TITLE
Spirit Tracks - Screen Distortion

### ISSUE THREAD

**Issue by MarioKartFan** [ahezard/nds-bootstrap#327]
@Robz8 

I noticed a strange issue that occurs when Spirit Tracks is launched from a forwarder rather than from DSIMenu++.  This issue does not occur if you launch Spirit Tracks from DSIMenu++. 

The very bottom (maybe 1/4 to 1/8 of an inch) of both the top and bottom screens is doubled.  It looks sort of blurry and doubled up, like something with double vision.   

Here's the strange thing.  This does not occur if you launch it in Pixel Perfect mode (holding down select at launch).  Of course, that leaves a big chunk of the screens unused.  

This also does not occur with Phantom Hourglass.

**Comment by Robz8** [comment]
The screen duplication issue is from TWL_FIRM, not nds-bootstrap.
This issue also happens with retail carts and flashcards, even those without CFW.
