### ISSUE TITLE
Pokemon Diamond Issue

### ISSUE THREAD

**Issue by RyanTheInkling** [ahezard/nds-bootstrap#331]
The consoles I have that use nds-bootstrap are a DSi XL, and a 2DS. Whenever I play Pokemon Diamond and I connect to a Wii U by using My Pokemon Ranch, I get a white screen, and the Wii U never detects the DSi or 2DS. Can someone help me?

**Comment by Stack3r** [comment]
This is not working yet

**Comment by KuraiKokoro** [comment]
Worth mentioning
Duplicate of #122
