### ISSUE TITLE
Tomodachi Collection

### ISSUE THREAD

**Issue by LordOfDarknezzz** [ahezard/nds-bootstrap#333]
When I try to play Tomodachi Collection on DSiMenu++, it always white-screens when I need to create my first Mii. This also happens while playing the English translation.

**Comment by Robz8** [comment]
You need to AP-patch the ROM.

**Comment by MrKarrot36** [comment]
@RocketRobz and where can i find that

**Comment by RocketRobz** [comment]
@MrKarrot36 Use DS-Scene ROM Tool to AP-patch the ROM.
The tool contains a database of AP-patches.

If your ROM is the english translation, go to my AP-patch thread at GBATemp, and find the patch in one of my links.

**Comment by Samyuerus-Gemukyubuz** [comment]
https://drive.google.com/file/d/1YfqhTV8fzEmroc78ofHCozE0mnDAdaBx/view
I AP Patched, Then Re-Patched with This.
