### ISSUE TITLE
Spectrobes White Screen

### ISSUE THREAD

**Issue by RinMaru** [ahezard/nds-bootstrap#338]
Spectrobes NTSC doesn't boot anymore I haven't tried it in awhile, like since TWL-Loader but no amount of setting tweaking seems to get past a white screen

N3DSXL Latest FW
B9S Latest
Luma3DS Latest
DSiMenu++ v5.3.1

**Comment by Robz8** [comment]
Not even turning off async prefetch fixes it?

**Comment by ahezard** [comment]
Could be linked to #517

**Comment by ahezard** [comment]
Spectrobes (911, USA version) Works for me in master.

**Comment by RinMaru** [comment]
cant get passed the white screen on mine
