### ISSUE TITLE
Suggestion: log game's file usage

### ISSUE THREAD

**Issue by mariomadproductions** [ahezard/nds-bootstrap#339]
Suggestion: Add a feature like the one that exists in various emulators (Desmume, Dolphin and Cemu) and in the "plugin framework" fork of Luma3DS: write the files a games uses to a text file on the SD Card. Its a bit of a niche feature with limited usage, but...

**Comment by dubbz82** [comment]
This sounds like a possible idea for enabling within the ini, as opposed to being an always on thing, as this really doesn't have a lot of use for the average user.

**Comment by ahezard** [comment]
There is already in the code the capability to log the access to the rom (roms offset in hexadecimal) this is not exposed to end users because this causes a important general slowdown. You have to recompile with the Debug option.

**Comment by NightYoshi370** [comment]
Closed since this is already implemented
