### ISSUE TITLE
Does Pal Park work on Pokémon HG/SS or D/P/Pl?

### ISSUE THREAD

**Issue by WalaRocks18** [ahezard/nds-bootstrap#341]
or how do you make it work?

**Comment by dubbz82** [comment]
Try it and find out?

**Comment by FM1337** [comment]
No, there is no slot-2 emulation for nds-bootstrap.

**Comment by dubbz82** [comment]
Ah, didn't realize this was the gba portion of it.  I know this is something the dev's have made mention of implementing eventually, not sure where that lays in terms of priority though (I'd guess getting some of the remaining broken games working is of higher priority though...)
