### ISSUE TITLE
Suggestion: enable access to 3DS-specific hardware

### ISSUE THREAD

**Issue by mariomadproductions** [ahezard/nds-bootstrap#343]
I'm not sure if this is possible, but could nds-bootstrap enable DS software to access 3DS-exclusive hardware like the motion sensor? This could be used to simulate GBA cart tilt sensors for the DS and GBA (through gbarunner2) games that use them.

**Comment by ahezard** [comment]
This is most probably not possible. The 3ds HW access is blocked while in ds/dsi mode.
