### ISSUE TITLE
Dragon Quest V still not working

### ISSUE THREAD

**Issue by pun-pun** [ahezard/nds-bootstrap#344]
Even though the update is claiming that "Dragon Quest V now works". It doesn't nevertheless. Can't get past the boat cutscene.

**Comment by Robz8** [comment]
It may need an AP-patch.

**Comment by dubbz82** [comment]
V works with AP patch though it triggers the opening cutscenes at point when it's not supposed to...it's really odd but I've personally sank like an hour into it, and otherwise functional.
