### ISSUE TITLE
Dragon Quest IX White Screen On Boot

### ISSUE THREAD

**Issue by Xianthus** [ahezard/nds-bootstrap#345]
New 3DS XL Running Luma v9.0/ DSIMenu++ v5.3.1/ DSIMenu++ Lancher v1.1.0/ Have an AP Patched version of the game file.

I believe I have everything updated that needs to be, other games work just fine. DQIX is the only one that crashes. I have also tried a fresh install of DSIMenu++ and updated to current but still no progress.

Let me know if you need any other information.

**Comment by Robz8** [comment]
Disable async prefetch for this game.

**Comment by Xianthus** [comment]
Okay, 1 sec, let me see if that fixed it.

**Comment by Xianthus** [comment]
Okay, that fixed it. Thank you very much, and thanks for the quick reply's. :)
