### ISSUE TITLE
MKDS Demo 2 White Screens After displaying message

### ISSUE THREAD

**Issue by YYoshi241** [ahezard/nds-bootstrap#346]
this MKDS Demo Here
https://www.dshack.org/store.php?page=file&fid=447
is what I'm talking about.

After you beat a cup / level 1 missions a message shows up. After it fades the game hangs on a white screen.

My setup: o3DS XL, DSiMenu++ 5.3.1, Release Bootstrap 10.2, DSiMenu++ Launcher 1.1.0

**Comment by YYoshi241** [comment]
NOT REALLY RELATED BUT RELATES TO NDS BOOTSTRAP:

Mariokart 0 works. (sometimes freezes) and CTGP DS doesn't boot. Also first post, read it.

**Comment by YYoshi241** [comment]
Still occurs on latest bootstrap (11.0b)

**Comment by YYoshi241** [comment]
And 11.1. Could this be a similar issue to NSMB DS Minigames? Since it is still broken.

**Comment by dubbz82** [comment]
The link for the romhack is broken, and this was last commented on over a year ago...my vote is to close this out, until we can get an updated link and confirmation that this is still an issue.
