### ISSUE TITLE
Ace Attorney Investigations 2 text error

### ISSUE THREAD

**Issue by Silver217** [ahezard/nds-bootstrap#347]
Hello, I'm trying play AAI2 with a english patch, but the texts don't show correctly. Only a text without sense. Anyone know anything about this, and can help me?. (Using last DSImenu++ and last Bootstrap)

**Comment by Niklink** [comment]
Apply this patch on top of the english patch: https://app.box.com/s/a1g1gxrs9xwpmdsubfll
In case the patcher you're using won't let you, use this patcher: https://www.romhacking.net/utilities/704/
(You probably need to uncheck 'Checksum validation' in the settings)

**Comment by dubbz82** [comment]
This should probably be closed, but maybe linked to in the readme or something as it's a fairly common question that's been answered a number of times on discord.

**Comment by DMSalesman** [comment]
Applying the AP fix from the translation team after the traslation patch doesn't work, because the latter trims the ROM.

Instead, one should grab the AP fix from @Robz8's Odrive, patch the untouched JAP ROM and only then apply the translation.
