### ISSUE TITLE
Meteos, white screen crash

### ISSUE THREAD

**Issue by LaziestTomato** [ahezard/nds-bootstrap#348]
As the title says, meteos (the european version, game number 0103) crashes on a white screen every time i try to play it. (for clarity, i'm trying to boot it through the latest version of dsimenu++)
It used to work just fine, as the compatibility list also states (albeit the intro fmv lagged on the video side while the audio continued normally, causing a desync around the end); however, after updating nds-bootstrap, the game now crashes on a white screen on boot, regardless of settings.
I haven't tried the japanese or american releases of the game but i'm assuming they most likely have the same issue, being essentially the same game.

I'm pretty sure it first happened when i updated to v0.10.1, though it might have been an earlier version too. Point is, one of these newer versions broke the game at some point.

**Comment by Robz8** [comment]
Did you try with both clock speeds?

**Comment by Robz8** [comment]
Hmm, try repacking the ROM with DSLazy.

**Comment by LaziestTomato** [comment]
hm, i fiddled with the settings some more and apparently turning off async prefetch makes it work again? i was sure this didn't fix anything (but then again i've been downloading the newer bootstrap versions as soon as they came out, i guess one of those must've fixed that)
the intro fmv also doesn't lag anymore like it did in the previous versions

**Comment by ahezard** [comment]
Could be linked to #517

**Comment by ahezard** [comment]
When was the last release this game stopped to work?

**Comment by ahezard** [comment]
the metos ds rom eu (103) works on master
