### ISSUE TITLE
Screens don't re-intialize after going into sleep mode.

### ISSUE THREAD

**Issue by Lykie** [ahezard/nds-bootstrap#35]
Start up SM64DS, do a bunch of stuff, put into sleep mode for a while, come out of sleep mode to hear glorious sound and play blindly.

**Comment by ApacheThunder** [comment]
Sleep mode is broken for the most part unless you have a cart inserted. If you intend to use sleep mode, insert a cart. Not sure if a 3DS cart would work in this case or not though. Can't really test that myself. :P

**Comment by Lykie** [comment]
3DS cartridge does not work.

**Comment by Robz8** [comment]
Try NTR clock speed.

**Comment by Robz8** [comment]
This only happens with SM64DS, afaik.

**Comment by Robz8** [comment]
3DS cartridge also make sleep mode work correctly.
