### ISSUE TITLE
Allow to apply cheat patches

### ISSUE THREAD

**Issue by Volti-p** [ahezard/nds-bootstrap#350]
Is it Possible, to make a AP-Patch Feature to the nds-Bootstrap? This would be cool. :)

**Comment by piratesephiroth** [comment]
it will probably be possible when the cheat engine is fixed

**Comment by damianoamatruda** [comment]
Core system for cheat patches implemented in 1d58eb5bc527fe8781fca884c2cb286c9ec6b541.

**Comment by NightYoshi370** [comment]
https://github.com/ahezard/nds-bootstrap/issues/395
"I'd try it, but as it would get around AP measures, we might get caught by Nintendo. :P"

**Comment by dubbz82** [comment]
Since cheats can in fact be applied to roms, should this be closed out now?

**Comment by ahezard** [comment]
Is this still an issue? Is there some kind of cheats that does not works?
