### ISSUE TITLE
Apollo justice crash right after saving

### ISSUE THREAD

**Issue by Milanpsmp** [ahezard/nds-bootstrap#352]
The game itself loads fine but when saving, the game crashes when it should return to the title screen. Also crashes if one goes back to the title screen right after unlocking a new chapter

**Comment by Robz8** [comment]
Try turning off async prefetch.

**Comment by Milanpsmp** [comment]
Still crashes

**Comment by aphirst** [comment]
I am experiencing this issue too with the German release of Apollo Justice, on nds-bootstrap 0.15.0 and twilightmenu 7.10. I am unable to locate an "async prefetch" setting if it exists.

**Comment by aphirst** [comment]
@RocketRobz Issue persists with `twilightmenu 7.2.0` and `nds-bootstrap 0.16.0`.

**Comment by Stack3r** [comment]
Can someone test this again

**Comment by aphirst** [comment]
@Stack3r I had intended to wait until the next version before testing. Testing now with `twilight menu v7.4.1` and `nds-bootstrap v0.17.1`.

Yes, the issue still persists.

**Comment by Stack3r** [comment]
Thank you

**Comment by aphirst** [comment]
Issue persists in with nds-bootstrap `v0.18.0`, using twmenu `v8.0.0` (the newer fixed download).

**Comment by aphirst** [comment]
Issue persists with nds-bootstrap `v0.19.3`, using twmenu `v8.2.0`.

**Comment by RocketRobz** [comment]
This seems to be related to soft-reset not working.

**Comment by Stack3r** [comment]
I don’t remember this being an issue in the past, I almost completed the entire game on an earlier build of bootstrap

**Comment by aphirst** [comment]
I completed the game too - it's only a hindrance when saving, and as mentioned, it still does save fine.
@Stack3r Do you happen to remember which earlier version, or, are you able to reproduce the same behaviour on a recent version with your hardware?

**Comment by Stack3r** [comment]
@aphirst I honestly have no idea, it was back when the game still lagged constantly

**Comment by aphirst** [comment]
I just updated to twilightmenu v12.2.1, which contains nds-bootstrap v0.30.1.

After saving in-game, if you wait about 15-20 seconds (may depend on microSD card speed), it seems that Apollo Justice is requesting a deeper reset of the NDS mode, and eventually the game title screen comes up as expected.

It seems that there is still **some sort of issue**, however it is **not a crash**.
