### ISSUE TITLE
cardEngine.c - source code

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#353]
I was reading the code on master branch in order to get myself familiar with nds-bootstrap - why on the line 569 and 570 is assignment to the same element of array sharedAddr? Doesn't the second assignment overwrite the one in previous line?

There is also one parenthesis too much I suppose in the line 569

**Comment by damianoamatruda** [comment]
Thank you for your remark. I’ll see to it right away.

**Comment by damianoamatruda** [comment]
Bug fixed in 88e8c6d.
