### ISSUE TITLE
[Compatibility list] Okamiden EUR requires AP fix

### ISSUE THREAD

**Issue by DMSalesman** [ahezard/nds-bootstrap#356]
The EUR and possibly USA versions of Okamiden require an AP patch, otherwise the Power Slash technique won't work after exiting the Cavern of Nagi, and Kamiki Village won't be reachable. Please fix the compatibility list.

**Comment by Robz8** [comment]
You can request access to edit the compatibility list.

**Comment by DMSalesman** [comment]
@Robz8 If applying for editor permissions requires a Google account, I'm afraid I'll have to pass.
