### ISSUE TITLE
Is it normal to experience freezes even after applying an AP patch to Pokemon White 2?

### ISSUE THREAD

**Issue by NaturalHarmonia** [ahezard/nds-bootstrap#357]
Yesterday when I tried to exit Opelucid City from the left after Zinzolin had freezed the city I kept getting a permanent freeze. I also experienced temporary freezes after defeating the one Shadow Triad member to the right of the city.

**Comment by Kalanyr** [comment]
I'm not that far through but neither my early experience in White 2 or my late experience in Black suggest you should be getting permanent freezes (but a plot event like that might be doing something unusual and hitting a currently unknown bug). You aren't playing with communication features on right ? I've noticed having them on significantly increases the instability and can cause temporary freezes to be permanent instead. 

Temporary "freezes" / lag is normal (though not desirable), , something about the way Pokemon B/B2/W/W2 do their loading seems to cause caching issues.

**Comment by NaturalHarmonia** [comment]
I was playing with communication features occasionally but then I turned them off. I also experienced a permanent freeze when I exited Humilau Cities Gym after defeating Marlon when the avatar and the rival character were walking towards each other. I then had a temporary freeze once I defeated Marlon again (because I hadn't saved in a while when the permanent freeze happened.) during the exact same sequence.

**Comment by ahezard** [comment]
Please test with this build : https://mega.nz/#!Wc0QQYSR!MsiTfrpCXo_E7g6qz0w5NTWoJVQL3IcVJpOq_1FJPhQ

**Comment by takeshineale128** [comment]
> Please test with this build : https://mega.nz/#!Wc0QQYSR!MsiTfrpCXo_E7g6qz0w5NTWoJVQL3IcVJpOq_1FJPhQ

crackle sound on the Pokemon white 2 title screen

**Comment by Stack3r** [comment]
This should no longer be an issue with the latest bootstrap build
