### ISSUE TITLE
Switching touch mode to NTR without breaking volume control on DSiWarehax

### ISSUE THREAD

**Issue by RocketRobz** [ahezard/nds-bootstrap#359]
The code used to switch to NTR touch mode works as expected, but it has a side effect for DSiWarehax users.
The side effect is that the user cannot control the volume on the console, unless we check sound volume level on arm7 side, and adjust the master volume accordingly, which is what we're already doing, but it's a bad idea.

**Comment by ahezard** [comment]
Is there a lot of pure DSiWarehax users now that hiya cfw / unlaunch is widely available? Does this need to be kept?

**Comment by RocketRobz** [comment]
There's not a lot of DSiWarehax users now, so I'll close this.
