### ISSUE TITLE
Megaman zero collection - Megaman Zero 2

### ISSUE THREAD

**Issue by 0klux** [ahezard/nds-bootstrap#361]
Nds Bootstrap 0.10.2
Megaman Zero Collection - US version. The rom has been AP patched

The game freezes on the "WARNING" transition to the final boss of the Resue R. .mission on the forest of dysis

**Comment by Robz8** [comment]
Did you try with async prefetch on or off?

**Comment by NightYoshi370** [comment]
@0klux try on the latest release

**Comment by dubbz82** [comment]
Can this be replicated on more recent builds?

**Comment by RocketRobz** [comment]
I think this is probably fixed.

**Comment by 0klux** [comment]
Yeah, it is fixed on latest stabel
