### ISSUE TITLE
Rainbow Islands: Revolution 

### ISSUE THREAD

**Issue by PtolemyMagic** [ahezard/nds-bootstrap#365]
Bootstrap version: 0.10.2
Playing on: New 3DS XL
Whenever I play this game, it immediately whitescreens for me. The SDK version of this game is SDK3, according to what DSiMenu++ reports.

**Comment by Robz8** [comment]
Does turning off async prefetch fix this issue?

**Comment by PtolemyMagic** [comment]
Still whitescreens.

**Comment by Robz8** [comment]
Can you see if it works in v0.11.1 now?
My guess is that it's one of those later SDK3 games.

**Comment by ahezard** [comment]
Issue confirmed on latest nightly. Not linked to dma.

**Comment by ahezard** [comment]
The same issue is sill present on latest nightly

**Comment by ahezard** [comment]
Fixed as well in latest commit.
