### ISSUE TITLE
Mario & Luigi: Partners in Time hangs for 30 seconds before title screen.

### ISSUE THREAD

**Issue by Cynfelyn** [ahezard/nds-bootstrap#366]
When booting Mario & Luigi: Partners in Time, the screen showing "Nintendo" and "Alpha Dream" load quickly, but then there is a white screen that hangs for 30 seconds, before continuing onto the title screen. From there, the game runs fine (as far as I've been able to ascertain so far). This 30 second white screen also occurs when selecting "save & quit" (before again returning to the title screen).

This occurs with both the NTR and TWL clock speeds. 

Not a huge issue or anything, but I'm reporting it just in case it's useful at all for the future.

**Comment by Waninoko** [comment]
It's 10 seconds in 0.10.2 if the ROM is Untrimmed/Trimmed. It's 4 seconds if the game was repacked. It takes 10 seconds if the game is Rev 01 ieven if it's either Untrimmed, Trimmed or Repacked.

**Comment by Cynfelyn** [comment]
I see, so if I unpack and then repack the rom in DSLazy, it’ll decrease the load time? 

Do you know why repacking the rom would decrease the load time like that?

**Comment by Waninoko** [comment]
To the first question, yes. Second question, I don't know, sorry.

Tingle's Rosy Rupeeland suffers from the same issue. Untrimmed ROM loads the title screen in 88 seconds, while the Repacked one loads it in 24 seconds.

**Comment by piratesephiroth** [comment]
@Waninoko, are you talking about the original rom or the patched one.

**Comment by Stack3r** [comment]
I’m also having issues loading saves, I saved in game and when I go to load it’s gone

**Comment by NightYoshi370** [comment]
Did you try the latest nightly?

**Comment by Stack3r** [comment]
Closed due to the game working now
