### ISSUE TITLE
Updates to the list for 0.11.0

### ISSUE THREAD

**Issue by DerpBlerp** [ahezard/nds-bootstrap#369]
nds-bootstrap compatibility.
Bowser's Inside Story: Unplayable, freezes on save select screen.
Will keep updating with new info.

**Comment by ahezard** [comment]
there is already an issue for BiS, this is not an issue

**Comment by DerpBlerp** [comment]
@ahezard i have also found the system isn't frozen on twl clock speed now. The backlight option is just set to off mysteriously after opening the system while the game is running.
