### ISSUE TITLE
Super Mario 64 DS

### ISSUE THREAD

**Issue by maorninja** [ahezard/nds-bootstrap#37]
### Region Differences
<table>
<tr><th></th><th>USA</th><th>EUR</th><th>JPN</th><th>CHN/iQue (Shenyou Maliou DS)</th></tr>
<tr><th>Release number</th><td>37 for v1, 56 for v2</td><td>22</td><td>25</td><td>None</td></tr>
<tr><th>Title/Game ID</th><td>ASME</td><td>ASMP</td><td>ASMJ</td><td>ASMC</td></tr>
</table>
BootStrap version: 0.4.1<br>
Works: Yes<br>
Notes: The sound seems to crackle unless you put it at the stereo settings. Loading times might be longer than expected. It has a slowdown when you are shown your "High Score" after beating a level. Framerate takes a bit of a nosedive when swimming. Versus mode not functional. One main bug is that when booting with the DSI speed settings, when going back from sleep mode, it blanks out...

<hr>

## Debug info

While the latest release works with SM64DS, some users are still getting a crash. While there was a hacking community going on, not enough people were innovated to release a crash debugger. Thankfully, Nintendo added their own little debug screen.

> This game has a crash debugger triggered similarly to the one in AC:WW and NSMB. This one is a bit less technical and more informative, but a lot less in-depth.

> To access the crash dump screen, crash the game. After doing so...
> Hold L + R + A + Left, then release.
> Hold Down + B, then release.
> Hold Start + Select.

> This screen was used by the developers to debug crashes and other errors in the game, since it helps pinpoint exactly where an issue occurred in the code.

>Here's an explanation of some of the info on it:

- The BUILDTIME text file is printed on the top of the screen.
- StageNo: Internal name of the stage.
- PlayerID: The character that was being used at the time.
- LayerNo: Unknown.
- RoomNo: Unknown.
- LoopProc: Which part of the main loop was running at the time of the crash; corresponds to a specific virtual function on the problem actor.
- ProfName: Identifies which actor type caused the problem. The first number is the type ID (in the above screenshot it is 3, which corresponds to STAGE). The second number is unknown.
- file-id: Unknown, may be the last file ID that was read from the ROM's file system.

## Bomb-Omb battlefield in 0.1.0/cardv.2

> UF 2004-10-15 23:29:24 Administr
> StageNo   6:Bombhei Map
> Player ID   0
> LayerNo    1
> RoomNo   0

> ProfName 300:5:YAJIRUSI-R
> file-id      02c1

> IRQ IE: 00140009 IF:00240009

At the bottom left, it says "GameHeap Broken"...

## cardv.1 booting up a game

> UF
> StageNo   0:Test Map
> Player ID   0
> LayerNo    0
> RoomNo   -1

> LoopProc  1:CONNECT
> ProfName 0:0:BOOT

> IRQ IE: 00040000 IF:00000000

On the bottom right corner, it says 85...

<hr>

## SM64DS Hacks

So currently, according to @WTails358, the hack called Another Super Mario 3D doesn't boot, and when I tested Super Grand Dad 64 DS, it didn't work.

Here is a crash dump of when @WTails358 did the above debug steps...

http://tinypic.com/r/2yns16x/9

This test was done on 0.4.1. Howver, with the latest commit as of June 21st, 2017, ([2cb9f8](https://github.com/ahezard/nds-bootstrap/commit/2cb9f8b1aa0447a94e186ba72c9a3a86403b39b3)) Super Grand Dad 64 DS works properly.

**Comment by ahezard** [comment]
I have hardly any crash with it using latter version, i had some crash in card.v2 version when I was using a slowser sd card, then I bought a new 32GB micro sd I formatted it with 32kb cluster size and it never happened again. If someone experience a crash with 0.3.0beta1 and submit I crash report I will look at it. I need also detailed information to reproduce the crash (location in the game, save file ...)

**Comment by maorninja** [comment]
> detailed information to reproduce the crash (location in the game, save file ...)
This means that all you need is that screen...

Because that will tell you everything you need to know.

**Comment by maorninja** [comment]
I updated my main post with new info that comes from @WTails358, so a huge thanks for him testing the hacks...

**Comment by WTails358** [comment]
When I did the debug screen without a cartridge inserted, the numbers kept flashing like that in the video, but I'll take a picture of it as well. I just hope that just cause I have a cartridge the info doesn't change.

**Comment by maorninja** [comment]
Wait, um, Here is a question I have? Do you have a donor ROM set? And if yes, does it also crash in the original SM64DS?

**Comment by WTails358** [comment]
Yes I have a donor rom set (MKDS) and I haven't tested if it crashes in the original SM64DS.
Should i test this with or without a cartridge in my 3DS?

**Comment by maorninja** [comment]
Cartridge doesn't matter as far as I know, but do disable the donor ROM setting temporarily just to test if there's anything different..

**Comment by Robz8** [comment]
Donor rom is only applied if save patching fails.

**Comment by maorninja** [comment]
@ahezard Mind taking a look into why things work in the original but not in ROM hacks?

**Comment by maorninja** [comment]
I edited the main post to show that this ROM Hack called 7 Grand Dad 64 DS doesn't work.

This is a link to the rom hack here: https://www.youtube.com/watch?time_continue=17&v=q4AuOQb7XxA

**Comment by maorninja** [comment]
...And I made my thread look much nicer now...

**Comment by maorninja** [comment]
So, lets update this thread with new info.

Basically, I tried out Super Grand Dad 64 on the latest commit and I can say that it works just like SM64DS does.

**Comment by shutterbug2000** [comment]
If anyone has anything else to add(or finds any more broken romhacks for this game), let us know. Otherwise, I'd say this is solved.

**Comment by NightYoshi370** [comment]
Alright, so Multiplayer gives me a problem on this game.

So that's something that needs to get patched

**Comment by anonymous-10** [comment]
So with the sleep mode issue, I tried turning off the backlight and turning it on when it was blanked out and the screen came back. Could a setting to force the backlight option to be put on and off fix this? I'm just wondering if it's theoretically possible.
