### ISSUE TITLE
Pokemon Black2/White2 currently broken

### ISSUE THREAD

**Issue by Stack3r** [ahezard/nds-bootstrap#371]
During any kind of trainer battle, when the player's pokemon is sent out the menu text becomes glitched and any interaction after that results into an error has occurred screen please turn off the system as of update 11.0

**Comment by Elduariaryon** [comment]
I did not have the issues you're experiencing. Are you using an AP patched version?

**Comment by Stack3r** [comment]
Last time I checked it was and the rom never had issues until the combined bootstrap was implemented

**Comment by CrystaltheGlaceon** [comment]
I don't think the ROM compatibility issues is related to the AP, it's completely related to the latest up

**Comment by Stack3r** [comment]
Async prefetch is causing this issue now

**Comment by Robz8** [comment]
Fixed in v0.12.0 and later.
