### ISSUE TITLE
The Idolm@ster: Dearly Stars not working on 0.11

### ISSUE THREAD

**Issue by 0klux** [ahezard/nds-bootstrap#375]
The game worked fine on previous releases, but on 0.11 it just hangs on a white Screen.

Tested changing the language to japanese, changing cpu clock speed and turning async prefetch on and off.
But it still hangs.

The game uses sdk5

**Comment by Robz8** [comment]
Can you see if it's fixed in v0.11.1?

**Comment by 0klux** [comment]
Just tested, and yes, it's working noe
