### ISSUE TITLE
Fix Surround Sound setting crackles/echoing/issues etc.

### ISSUE THREAD

**Issue by Stack3r** [ahezard/nds-bootstrap#377]
Certain games such as Animal Crossing Wild World have extremely bad audio issues while on the Surround Sound setting even with Async Prefetch enabled, this game also has these audio issues with normal Stereo sound settings enabled.

**Comment by ahezard** [comment]
What is the status in v0.14.1?

**Comment by RinMaru** [comment]
Only game I could test was Metroid hunters and pinball and it doesn't seem to be there anymore but pinball still has a VERY SMALL stutter in audio as it goes to the title screen and resident evil DS still crackles in certain rooms but this could be a diff issue I guess. on a side note Hunters is loading very very slowly

**Comment by RinMaru** [comment]
@ahezard  Resident evil DS crackling is gone as of the latest nightly bootstrap I haven't tested the others since I don't own them

**Comment by ahezard** [comment]
So resident evil ds still have Crackling?

**Comment by RinMaru** [comment]
yea not sure why the music crackles pretty bad as if it hit a high note it cant handle

**Comment by Stack3r** [comment]
Cannot reproduce sound issue on resident evil with latest nightly and I don’t hear any on hunters either, closing for now

**Comment by RinMaru** [comment]
> Cannot reproduce sound issue on resident evil with latest nightly and I don’t hear any on hunters either, closing for now

load it and listen to the music in the save room

[Resident Evil - Deadly Silence.zip](https://github.com/ahezard/nds-bootstrap/files/2929576/Resident.Evil.-.Deadly.Silence.zip)

**Comment by zurgeg** [comment]
I am able to reproduce this issue with Mario Kart DS and Super Mario 64 DS. Something odd is that this only seemed to happen when using forwarders on the DSi Menu?

**Comment by RocketRobz** [comment]
MakeForwarder doesn't have the fix, and only TWiLight Menu++ has the fix.

**Comment by zurgeg** [comment]
Ah! Thanks for the speedy response :)
I'm using the one from the TWiLight Menu++ Folder, is it fixed in nightly and not release?

**Comment by RocketRobz** [comment]
Nope. The fix is in TWiLight Menu++ itself, not nds-bootstrap.

**Comment by zurgeg** [comment]
Ah, alright!
