### ISSUE TITLE
Giana sister white screen

### ISSUE THREAD

**Issue by hatsue21** [ahezard/nds-bootstrap#379]
The game works fine for the first few stages, but hangs into a white screen when entering Level 1-4.
US version btw

**Comment by edo9300** [comment]
Highly probably, it's an anti piracy measure

**Comment by Stack3r** [comment]
Please AP patch the rom and test again

**Comment by ahezard** [comment]
Just fixed :-)

**Comment by ahezard** [comment]
Please retest
