### ISSUE TITLE
3DS won't load conformed compatible games

### ISSUE THREAD

**Issue by MaxChaos4** [ahezard/nds-bootstrap#381]
I have tried games confirmed to work on 3DS and continue getting a white and black screen (Diddy Kong Racing and Tetris DS).

**Comment by Robz8** [comment]
nds-bootstrap v0.11.0 unfortunately broke compatibility with some games.

**Comment by piratesephiroth** [comment]
Yeah, the refactoring of a patch file didn't go well.
Try this build. It contains all the latest modifications but uses the original patch file so it works great:

[nds-bootstrap-tempfix.zip](https://github.com/ahezard/nds-bootstrap/files/2306363/nds-bootstrap-tempfix.zip)

**Comment by Robz8** [comment]
Diddy Kong Racing confirmed working in v0.11.1. (Unknown about Tetris DS)
