### ISSUE TITLE
Etrian Odyssey Start Screen Issues

### ISSUE THREAD

**Issue by RRSlider** [ahezard/nds-bootstrap#383]
When booting Etrian Odyssey, the game runs but then it starts flickering and the bottom and top screen swap images. So what's on the bottom screen might appear on the top screen and freeze for instance. Sound tells me that I can still navigate the options but the screens don't react.

Using the latest release.

**Comment by NightYoshi370** [comment]
whats your config?

**Comment by carmangoo** [comment]
Hi, I changed the CPU to NTR and the game works, with default value (TWL) the screen flickers maybe that's the fix for your problem.

**Comment by Stack3r** [comment]
This needs to be tested again

**Comment by Kalanyr** [comment]
Tested: I don't seem to have this issue.  It doesn't specify how long you need for it to happen and if it's steps or game time.  I started a new game, made a party, went to the Labyrinth and wandered around until I got horribly maimed by a Giant Lynx and had to retreat without any nds-bootstrap issues.
