### ISSUE TITLE
ermii kart ds beta 1-r crashes at boot 

### ISSUE THREAD

**Issue by YYoshi241** [ahezard/nds-bootstrap#385]
When playing Ermii Kard DS Beta 1-r, I get a crash at the boot screen, independent of any settings. I am using nds-bootstrap v12.3.2 pr1 and TWLMenu++ 6.6.1 on my o3DS XL.
![0821181707_hdr 1](https://user-images.githubusercontent.com/36418671/44429287-e6113480-a564-11e8-9c83-28d5d1f4722d.jpg)

**Comment by YYoshi241** [comment]
Still occurs on 11.1

**Comment by YYoshi241** [comment]
Still occurs on 11.2

**Comment by YYoshi241** [comment]
Still occurs on 12.1 r2

**Comment by NightYoshi370** [comment]
In the future, no need to spam the comment section for which version you're using. Just edit the first post.

I think this is a duplicate of another thread, but let me make sure

**Comment by poudink** [comment]
it probably is. this issue has been known since the dawn of time. I heard Ermii Kart DS beta 2 will be compatible with nds-bootstrap, whenever beta 2 releases anyway.

**Comment by qamichele59** [comment]
Unplayable due to gets the error dump screen
