### ISSUE TITLE
Console turns off after sleep mode with card inserted

### ISSUE THREAD

**Issue by The12thDoctor** [ahezard/nds-bootstrap#386]
When playing any game on DSi and putting it to sleep mode with the card inserted , after a while opening the DSi turns the whole console off. This is without removing the cart.

**Comment by NightYoshi370** [comment]
Sleep mode isn't patched IIRC

**Comment by aphirst** [comment]
I don't see it documented anywhere (perhaps it is, and I'm just unobservant), but the condition isn't merely "if slot-1 is empty, sleep mode causes poweroff", but rather "if slot-1 was ejected at any point, sleep mode causes power off, even if the card was reinserted and present at that time". Tested on my n3DS.

**Comment by Stack3r** [comment]
Does this still occur?

**Comment by RocketRobz** [comment]
Ah, forgot this was still open.
