### ISSUE TITLE
Pokemon Ranger Guardian Signs Black Screen

### ISSUE THREAD

**Issue by ElectronicWizard** [ahezard/nds-bootstrap#387]
I've upgraded DSiMenu++ to the latest revision as of today, followed the update instructions, and the game launches fine. But when I hit New Game, it just has a black screen with what sounds like waves as audio.

**Comment by 0klux** [comment]
After doing a bit of research here, it seems to be an anti-piracy measure, so you need to ap patch the rom

**Comment by ElectronicWizard** [comment]
@0klux I understand this may not be the place to ask, but I can't find a solid bit of documentation on this - any tips/links you can offer?
