### ISSUE TITLE
Pokémon B2/W2 Random Freezes

### ISSUE THREAD

**Issue by Volti-p** [ahezard/nds-bootstrap#391]
Is it Possible, to fix the Random Freezes? These appear in the City, on the Routes and can lead to complete freezes :/

**Comment by Mr-Gela** [comment]
Seems like the same issue I posted a few hours ago myself at: https://github.com/ahezard/nds-bootstrap/issues/390
What nds-bootstrap version are you at? Did these freezes happen before? In my experience, they came with the last release but who knows?

**Comment by Volti-p** [comment]
I use the latest version (0.11.1) and this random Freezes came already on previous versions. I hope it can be fixed :)

**Comment by Stack3r** [comment]
Closing this issue in favor of #390
