### ISSUE TITLE
Proposition: running nds-bootstrap from emulator - manual

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#392]
It would make things far easier for potential contributors to have a short instruction/manual explaining how to run nds-bootstrap from emulator/make use of nocashmessages in order to debug the code by themselves.

**Comment by ahezard** [comment]
running nds-bootstrap from no$gba does not works currently due to no$gba (eg: ndma/sdmmc handling). I is needed to rely on the logging functions.
