### ISSUE TITLE
Does release 0.11.2 really include VRAM boost?

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#394]
I cannot see any difference in any sluggish game with VRAM boost (AW Days of Ruin, Pokemon B/W). Also I've pulled the newest changes which are said to be commited before release 0.11.2 and the project doesn't compile:

> /nds-bootstrap/arm9/source/conf_sd.c: In function 'callback':
/nds-bootstrap/arm9/source/conf_sd.c:144:9: error: 'configuration' {aka 'struct configuration'} has no member named 'boostVram'; did you mean 'boostCpu'?
   conf->boostVram = (bool)strtol(value, NULL, 0);
         ^~~~~~~~~
         boostCpu
make[2]: *** [conf_sd.o] Error 1
/opt/devkitpro/devkitARM/base_rules:84: recipe for target 'conf_sd.o' failed
Makefile:97: recipe for target 'build' failed
make[1]: Leaving directory '/nds-bootstrap/arm9'
make[1]: *** [build] Error 2
Makefile:161: recipe for target 'arm9/nds-bootstrap.elf' failed
make: *** [arm9/nds-bootstrap.elf] Error 2

I can see that travis have failed two times also with recent commits

**Comment by damianoamatruda** [comment]
Fixed in 19646a1ed9e2df86be377ba9a479156c75d955bb.

**Comment by Robz8** [comment]
VRAM boost doesn't fix loading issues.

**Comment by hubert-skowronek** [comment]
@Robz8 what issues does it fix then?

**Comment by Robz8** [comment]
Only performance issues that also happen on retail carts, if TWL clock speed isn't enough.

**Comment by hubert-skowronek** [comment]
@Robz8 thank you for the answer :-)
