### ISSUE TITLE
Below 8000h reads redirection is not working

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#395]
This code in nds-bootstrap/cardengine/arm9/source/cardengine.c:

```
	if(src <= 0x8000){
		src = 0x8000+(src & 0x1FF);	// Fix reads below 0x8000
	}
```
doesn's seem to work - I've compiled nds-bootstrap with additional code which should stop game from further execution (e.g. endless loop) if it encounters below 0x8000 read (which of course it does in many games with AP measurements, M&L:BiS is confirmed example):
```
	if(src <= 0x8000){
                while(true);
		src = 0x8000+(src & 0x1FF);	// Fix reads below 0x8000
	}
```
 but nonetheless this code is never executed.

**Comment by hubert-skowronek** [comment]
@Robz8 I've checked overlays once again looking for card read start and end signatures for normal, cached and dma reads and found none of them - overlays prepare B7 command for card read, but if I haven't found these signatures shouldn't we assume that card reads doesn't come from the overlays?

**Comment by Robz8** [comment]
The signatures for card read may not be the same in the overlays.
One would have to use IDA Pro to find the function.

**Comment by hubert-skowronek** [comment]
@Robz8 Ah, it explains a lot - thanks. Why one would have to use IDA Pro, aren't desmume/no$gba good enough for the job? Do you guys plan to attempt for patching overlays or it was classified as not feasible with nds-bootstrap already?

**Comment by Robz8** [comment]
IDA Pro is needed to find the offset of the card read function. DeSmuME/NO$GBA doesn't do that.
IDA Pro is what we used to find the card read function in the arm binaries and get the signature from it, so nds-bootstrap can patch them.

As for patching the overlays, I'd try it, but as it would get around AP measures, we might get caught by Nintendo. :P
@shutterbug2000 might know more about this, though.

**Comment by piratesephiroth** [comment]
Well this overlay patch seems like some basic functionality that doesn't really makes games work by itself. The user can add additional AP Fixes (arm9 patches) via cheats.xml

**Comment by hubert-skowronek** [comment]
@Robz8 shouldn't you be already caught by Nintendo, then? :P If I am not mistaken you've already done some patching which e.g. eliminated Chrono Trigger AP, haven't you?

**Comment by Robz8** [comment]
Yeah, but Chrono Trigger isn't Nintendo though.

**Comment by hubert-skowronek** [comment]
@Robz8 Ah, I understand your point of view. But nds-bootstrap patches card read functions in Nintendo's games also - why patching card read functions in overlays would be different still? I think redirection of below 8000h should be treated more like getting around AP measures, and still emulators patch it and are not sued for this

**Comment by piratesephiroth** [comment]
I think the big issue is the BiS remake coming next year.

**Comment by piratesephiroth** [comment]
Anyway I think pretty much all AP measures were implemented by Nintendo in their SDK,

Developers just had to choice of using them or not.

**Comment by hubert-skowronek** [comment]
@piratesephiroth I suppose all flashcards are bigger and more present threat than nds-bootstrap :-) what's more, the remake will be pirated by many using 3DS CFW

**Comment by hubert-skowronek** [comment]
@Robz8 out of curiosity, which version of IDA PRO have you used?

**Comment by Robz8** [comment]
v7.0

**Comment by ahezard** [comment]
Is this still needed? Which games are affected?

**Comment by hubert-skowronek** [comment]
@ahezard e.g. Bowser Inside Story - it wouldn't need AP patch then

**Comment by hubert-skowronek** [comment]
@ahezard if that feature is thrown away then maybe the part of code related to below 8000h reads should be removed as well?
