### ISSUE TITLE
Wario: Master of Disguise (USA/EUR) blank screen

### ISSUE THREAD

**Issue by lugia19** [ahezard/nds-bootstrap#397]
I'm using the latest version of nds-bootstrap with the latest version of Dsimenu++ and after the loading screen the game just hangs on a white screen. I've tried turning off the async thing to no avail. Other games work however.

**Comment by BlackRider59** [comment]
Yeah, I'm having the same issue. I think the compatibility list is wrong. The list says the USA version works but its the Japanese Version of the game that works. The EUR and USA versions don't.

**Comment by dubbz82** [comment]
I haven't tested this myself, but it's entirely possible that the USA and/or EUR versions DID boot in a previous build and no longer do?

**Comment by lugia19** [comment]
Still not working with the latest release.

**Comment by ahezard** [comment]
still observed with latest release

**Comment by ahezard** [comment]
[[ Fatal Error: ARM9CPU stopped running because "Undefined instruction exception" occurred. ]]

   Symbol: STATIC:0x00008004
   00008004:  F0002002       ???

   CPSR:4000001F   
     R0:00000000  R1:020AC970  R2:00000000  R3:00000000
     R4:00003FF8  R5:00000000  R6:020AC928  R7:00000001
     R8:023F4868  R9:04000000 R10:00000000 R11:00000000
    R12:00000002  SP:027E3AC8  LR:0207792F  PC:00008004

**Comment by Jerdo32** [comment]
As of July 19,2019 the game still acts the same.

**Comment by RocketRobz** [comment]
[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4095429/NDSBTSRP.LOG)
```
findCardIdEndOffsetThumb:
Card ID end thumb not found
```
Card ID function is not patched.

**Comment by RocketRobz** [comment]
Function is now patched by 6be69b6c, but still doesn't boot.
A card read does not occur.
