### ISSUE TITLE
Rune Factory 2 Undub issue

### ISSUE THREAD

**Issue by ShinRaikdou** [ahezard/nds-bootstrap#398]
Rune Factory 2 Undub version is hanging after new game or loading save.
I've tried to load rom in DeSmuMe (PC) or DraStic (Android) and they works fine.
Undub that I talking about is USA version with changed audio, [not this one translated jap with bugs](https://gbatemp.net/threads/rune-factory-2-full-undub.170118/)

**Comment by Robz8** [comment]
Did you try with async prefetch off?

**Comment by ShinRaikdou** [comment]
>Did you try with async prefetch off?

Yes I did.
I think part of the problem in a game+undub itself, because some people with [r4 and DSTT](https://gbatemp.net/threads/rune-factory-2-undub.117013/page-3#post-1635760) can't load it as well, but for some of them it works fine...

**Comment by piratesephiroth** [comment]
you should try repacking the rom with DSLazy

**Comment by ShinRaikdou** [comment]
>you should try repacking the rom with DSLazy

Already tried it. It is not like the rom is broken, because you can play it on emulators and some cartridges. For example Rune Factory 1 and 3 Undubs is working as it should.

**Comment by Stack3r** [comment]
Please test this again

**Comment by dubbz82** [comment]
I vote to close this as a re-test was requested more than six months ago and no further feedback was given.  If more information can be provided, or a link to an xdelta patch to test with, this can be reopened if it's still problematic.
