### ISSUE TITLE
Homebrews frozen during usage?

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#4]
Some homebrews are starting properly but freeze afterwards

**Comment by ahezard** [comment]
From https://gbatemp.net/threads/ds-i-mode-hacking-progress-thread.413015/page-121#post-6725519

hector le castor/peter the beaver; freezes in loading
futuracer; freezes after keysetting
dsftp - loads ok - but freezes (net init because net svc are not impl probably)

**Comment by ahezard** [comment]
Moonshell 1.71 freezes during DPG playback (but mp3 works)

**Comment by ahezard** [comment]
DSI4DS freezes when launching a .nds

**Comment by ahezard** [comment]
cf_ds.nds (dldi speed tester), works in no$gba

**Comment by ahezard** [comment]
DSDoom - Stays on "Welcome *username*".

**Comment by ahezard** [comment]
DSision2 - Hangs after trying to open a folder

**Comment by HumanKirby** [comment]
VNDSx has a weird behavior in the sense that:
1. Some VIsual Novels seems to correctly start and some do not (crash at the home menu of the novel, while the others seems to load fine)
2. It hangs when you try to use the load and save buttons and the options menu

I will try to give some more detailed feedback later

**Comment by Robz8** [comment]
AtlasFontaine at GBATemp tested jEnesisDS, and no folders are being shown.

**Comment by Robz8** [comment]
R4menu freezes with a black screen on top when launching a .nds file (one of the three selections).

**Comment by ahezard** [comment]
Thanks for the feedback Robz8!

**Comment by metroid-maniac** [comment]
eepinator freezes when you try to dump a DS save file to file. Did not attempt writing the the DS cart.

**Comment by ahezard** [comment]
Version V0.0.2 have improved the compatibility with some of the homebrews above. Please update and retest.

**Comment by HumanKirby** [comment]
Ok, more fun stuff for vnds. First, the good news. 
Most vn's now boot and you are able to read a bit into them. 

Bad news: there are still several commands which it can not recognise (even though they work on a ds flashcard just fine) and there are still several guru data abort errors (I think its connected to the larger ones, but i havent looked into it). Also, sound and visual (except for some missing ones which it couldnt load) seem to work fine. 

If I find some more stuff, I will post it here or on gbatemp. Also, I guess you did already see it, but here are some errors from version 0.0.1: https://gbatemp.net/threads/ds-i-mode-hacking-progress-thread.413015/page-128#post-6738546

**Comment by nl255** [comment]
Lonewolf DS book 1 (flight from the dark) freezes after you select your kai disciplines and tap the button to move onto the equipment part of character creation.  I have not tested the other books.

**Comment by NightYoshi370** [comment]
I think we should have one issue for each homebrew. No need to group them all into one
