### ISSUE TITLE
11.1+ broken for DSi

### ISSUE THREAD

**Issue by froggestspirit** [ahezard/nds-bootstrap#401]
I've noticed with 11.1 and 11.2, (not sure about 11.0) support for DSi appears to be broken? I am unable to launch any game (giving a white screen). My current setup is unlaunch booting the bootcode (no hiyacfw). Downgrading to a 10.x version fixes this

**Comment by Robz8** [comment]
11.1+ now requires HiyaCFW for it work, as 11.0 working without HiyaCFW was just a lucky chance.
