### ISSUE TITLE
Going to the end of Gen 3 portion of Gen 4's National Dex can freeze the game

### ISSUE THREAD

**Issue by 0klux** [ahezard/nds-bootstrap#403]
Title.
On Platinum it only happens on Latios/as. And only when you try to check these pokemon, skipping them allows you to acess the rest of the dex.
On SS it's either random or has a similar requirement to freeze the game (since it only happened once to me, but I didn't pay attention to where the cursor was or would be).

This might affect the whole gen 4 but I don't have acess to the other games at this time

**Comment by 0klux** [comment]
Just an update, it seems like the problem really only happens when trying to see certain pokemon's pokedex entries, but it's not isolated to gen 3 pokemon. Some other pokemon can also trigger the freeze, like Manaphy in Soul Silver

**Comment by ahezard** [comment]
could be linked to #554 that have been fixed. Please retest with the latest nightly.

**Comment by 0klux** [comment]
Still happening using b13fc7b

**Comment by Stack3r** [comment]
Can someone else verify this also

**Comment by Stack3r** [comment]
Apparently this issue also happens on other Pokémon games such as Gen 5

**Comment by RocketRobz** [comment]
Is this fixed in v0.26.1?
