### ISSUE TITLE
[Issues] Problem with Savedata

### ISSUE THREAD

**Issue by RS55** [ahezard/nds-bootstrap#405]
I was wanting to use some of my cartridge backups and some games do not work, Kingdom Hearts 358/2 days worked for me but others like Pokemon Mystery Dungeron Explorer of Sky, Pokémon Ranger: Guardian Signs or Blue Rescue Team nothing to do, a clean savedata is created in its place, thing that never happened to me before.

Another thing, I noticed that from a time here the savedata was not created as if it were from the cartridge, but the 512KB standard, if I wanted to re-write my 512KB savedata of what format should I transfer? Because it's the exit but not the entrance...

Excuse my english, if you do not understand something ask me

**Comment by NightYoshi370** [comment]
>if I wanted to re-write my 512KB savedata of what format should I transfer? 
.sav

>Kingdom Hearts 358/2 days worked for me but others like Pokemon Mystery Dungeron Explorer of Sky, Pokémon Ranger: Guardian Signs or Blue Rescue Team nothing to do, a clean savedata is created in its place, thing that never happened to me before.
Upload your save file please

**Comment by RS55** [comment]
@NightYoshi370 
1.- I was referring to the format of the savedata by default, the original R4 used 512KB to say an example: https://shunyweb.info/convert.php

2.- What do you mean by "update"? If with Kingdom Hearts 358/2 Days I just copy and paste and it worked, because with other games like the ones mentioned above, and instead create a new empty savedata for more than replace it?

It seems to me that this has been a regression to when I was an SRLoader, at that time the games I mentioned (and did not work) worked for me.
