### ISSUE TITLE
Warioware DIY doesn't save

### ISSUE THREAD

**Issue by SoulRepo** [ahezard/nds-bootstrap#406]
Can it be patched?

Or is it impossible.
Using DSiMenu++ on 3DS CFW, Luma 9.1

**Comment by SoulRepo** [comment]
How?

**Comment by Robz8** [comment]
By patching the function that saves to the cart's NAND chip.

**Comment by MarioMasta64** [comment]
i would like to see this patched too 🤔👌

**Comment by SoulRepo** [comment]
Any guides? Or is it something you have to do?

**Comment by Robz8** [comment]
It's something to do on our side.

**Comment by SoulRepo** [comment]
Ah, thanks.
Is it currently in work, or for the future?

**Comment by Robz8** [comment]
It's for the future.

**Comment by yanniboz** [comment]
I was looking up this same issue and just found out that the cart saves somewhere different and that there's a fix coming. Thanks for the update!

**Comment by ahezard** [comment]
duplicate #306
