### ISSUE TITLE
Harvest Moon DS white screen

### ISSUE THREAD

**Issue by Nerakami** [ahezard/nds-bootstrap#408]
When i want to start Harvest Moon DS, i have a white screen just after the loading screen of bootstrap, the game is not on the compatibility list :(

**Comment by Robz8** [comment]
Is it fixed in v0.12.1 (Rev 01)?

**Comment by hubert-skowronek** [comment]
@RocketRobz No, it is not, just checked with the newest version

**Comment by ahezard** [comment]
Fixed, please retest
