### ISSUE TITLE
Tomodachi Collection freeze

### ISSUE THREAD

**Issue by Validusername16** [ahezard/nds-bootstrap#409]
Release #:5298
Game: Tomodachi Collection
Card Type: NTR
TID: CCUJ
Region:JPN
SDK Version 4
Untrimmed: 64 MB
Tested system:3DS
nds-bootstrap Version 10.2
Recommended clock speed: N/A
No AP patch
Notes:
`Game freezes when you attempt to make a Mii`

**Comment by Antonio231102** [comment]
You need to apply an anti-piracy patch for the game, just search for it.

**Comment by NightYoshi370** [comment]
>Game freezes when you attempt to make a Mii

I wonder what the game would do if you had a save file already
