### ISSUE TITLE
NeoDS White Screen

### ISSUE THREAD

**Issue by SylarBRG** [ahezard/nds-bootstrap#410]
I tried to use the NeoDS application and when I open it, it keeps the screen blank and nothing happens

**Comment by dubbz82** [comment]
This is presumably related to #407 and most other homebrew not currently loading because of DLDI.

**Comment by piratesephiroth** [comment]
it starts fine with the current commit however it freezes when we try to run games

**Comment by NightYoshi370** [comment]
Maybe it needs a RAM disk?

**Comment by piratesephiroth** [comment]
it runs with a RAM Disk yeah, however Neo Geo roms are pretty big and some don't even fit under the 28MB limit, hehe.

Also it seems to not be affected by the 133MHz setting anymore (I'm not sure if that setting is affecting homebrew)
