### ISSUE TITLE
Puyo Puyo 20th Anniversary freeze

### ISSUE THREAD

**Issue by Antonio231102** [ahezard/nds-bootstrap#411]
I tried Puyo Puyo 20th Anniversary and it just freezes after SEGA logo even though it appears as working on the compatibility list.

**Comment by Robz8** [comment]
Does disabling async prefetch fix the issue?

**Comment by Antonio231102** [comment]
Unfortunately still no luck...

**Comment by Robz8** [comment]
Try [this](https://github.com/Robz8/DSiMenuPlusPlus-update/raw/master/nds-bootstrap-nightly.nds) nightly build.

**Comment by Antonio231102** [comment]
I only have to put the NDS file in the _nds folder, right?

**Comment by Robz8** [comment]
Yes, and set bootstrap to nightly in DSiMenu++ settings.

**Comment by Antonio231102** [comment]
Sadly, nightly bootstrap just made things even worse as the game now doesn't even boot.

**Comment by Robz8** [comment]
Is sound fix on or off?

**Comment by Robz8** [comment]
Ok, try [this](https://github.com/Robz8/DSiMenuPlusPlus-update/raw/2b262380e3b45c68c4f54d75c9cf5122d6b77a07/nds-bootstrap-nightly.nds) build. Should fix the game not booting.
If it still crashes after the SEGA, the ROM may need to be AP-patched.

**Comment by Antonio231102** [comment]
Indeed the game boots now, but still freezes after the SEGA logo.
Any idea of where could I find the AP patch?

**Comment by Robz8** [comment]
Find it [here](https://www.odrive.com/s/00ef5077-220c-47cc-8952-1b590c3f3cb6-5b8b4f4f).
It's in the DS-Scene Rom Tool folder.

**Comment by Antonio231102** [comment]
I can't believe it... after hours of searching and messing around a lot without any results I can finally play this game!
By the upload date I can guess you made it after I opened this issue, that is much appreciated, many many thanks! <3
