### ISSUE TITLE
Dragon's Quest V: Regression Post 11.2

### ISSUE THREAD

**Issue by MarioKartFan** [ahezard/nds-bootstrap#412]
@Robz8 I downloaded your latest nightly bootstrap build.  In DQV when the overworld map transitions from day to night, there is all sorts of graphical corruption at the edge of water tiles.  This corruption does not occur in 11.2.

**Comment by MarioKartFan** [comment]
@Robz8 Tested the latest nightly, and now I'm getting graphical corruption at the edge of water tiles during daytime.  Might be a placebo effect, but I think I'm also seeing a slight improvement in GTA Chinatown Wars framerate.

**Comment by Robz8** [comment]
Try turning on VRAM boost for the games with the graphical corruption.

**Comment by Robz8** [comment]
The change that caused this error has been reverted in v0.12.0.
