### ISSUE TITLE
SDK 3 sound issues? (Mario Kart DS + New Super Mario Bros)

### ISSUE THREAD

**Issue by zipplet** [ahezard/nds-bootstrap#413]
There are sound issues with the following 2 games:
* Mario Kart DS (USA)
* New Super Mario Bros (USA)

Issues:
* Audible crackling (with sound fix set to On - worse with it set to Off) - crackling is mild during music and worse during some sound effects.
* Sound will randomly change to what sounds like surround sound mode, actually it seems to add audio delay to one of the sound channels.

To reproduce this easily, open Mario Kart and let it sit on the demo for about 5 minutes. It happens every time.

Things I tried:
* Sound Fix On/Off (worse with Off)
* CPU speed NTR/TWL, no difference
* Async prefetch On/Off, no difference

Tested with:
* DSi (firmware v1.4.5-J, unlaunch v1.4, hiyaCFW v1.3.2, DSiMenu++ v6.0.0, nds-bootstrap v0.11.2)

Both games use SDKv3 and have the same sound issues, could that be related?

**Comment by Robz8** [comment]
No, they aren't related.

**Comment by ahezard** [comment]
Please test with this build : https://mega.nz/#!Wc0QQYSR!MsiTfrpCXo_E7g6qz0w5NTWoJVQL3IcVJpOq_1FJPhQ

**Comment by RocketRobz** [comment]
In later commits, the issue is fixed.
