### ISSUE TITLE
Romhacks Fail to launch without error screen.

### ISSUE THREAD

**Issue by Z4CH4R13** [ahezard/nds-bootstrap#417]
on an Old3DS trying to run Romhacks using dsimenu++ and upon launching any romhack they either stay on a white screen, or in the case of Mario's Holiday it simply blue screens on the top screen with some weird info. (roms work in emulators, and some used to work in previous builds) they seem to load up fine, getting passed the launcher loading screen.

**Comment by NightYoshi370** [comment]
What ROM hacks have you tried?

**Comment by dubbz82** [comment]
Without specific information on this one, I say this should be closed out.  Several romhacks have now been confirmed working within bootstrap since this issue was opened.  If more information can be provided, this can be reopened..
