### ISSUE TITLE
Pokémon HG/SS Random Freeze 

### ISSUE THREAD

**Issue by Arefu** [ahezard/nds-bootstrap#420]
I see on the spreadsheet it says it needs an AP patch I'm pretty confident that I've done this, however about 10 minutes into game play it just sits on a black screen after going through a door.

Any advice? I'm pretty sure I'm all up to date.

**Comment by Arefu** [comment]
Update; it just happened while walking

**Comment by NightYoshi370** [comment]
Are you using the latest nightly?

**Comment by Arefu** [comment]
It was me being stupid, never mind.
