### ISSUE TITLE
Latest version of NDS Bootstrap (using DSiMenu++), Drawn To Life games don't work

### ISSUE THREAD

**Issue by LittlePippy** [ahezard/nds-bootstrap#422]
I don't get it. They said they work with sound issues yet when I boot them up, it's a white screen. I use the latest version, 0.20.1. What gives?

**Comment by Robz8** [comment]
Try turning off sound fix (or vice-versa, if already done that).

**Comment by Robz8** [comment]
Try updating nds-bootstrap to the latest.

**Comment by DevonHess** [comment]
Turning sound fix off fixes the white screen problem for me.
