### ISSUE TITLE
AP Patched games no longer work

### ISSUE THREAD

**Issue by Cee123** [ahezard/nds-bootstrap#425]
Hi guys, is there any way to include AP patches into the boostrap. Because having to patch the roms yourself can be a nightmare. I've been trying to patch roms myself but they don't work and xdelta patcher always fails. So I found a site with prepatched roms and none of them seem to work either.

For example - games like Bowser's inside story, get past the initial save screen but then black screen after starting a new game
Alice in wonderland patched, boots and shows the logo but then goes to a black screen
The Legend of Zelda Spirit Tracks would start up but you couldnt see the train whistle and other things. This was an AP thing, but after applying the patch, the game will start and then go to a black screen.

So I'm not really sure what's going on with the compatibility. A lot of things I've tried dont seem to work. The Pokemon games seem to work patched and unpatched. Not sure what others.

**Comment by NightYoshi370** [comment]
> For example - games like Bowser's inside story, get past the initial save screen but then black screen after starting a new game

We already know.
Also, IIRC, Robz8 said that he won't due to not wanting Nintendo hunting him down

**Comment by dubbz82** [comment]
> Hi guys, is there any way to include AP patches into the boostrap. 

Probably not gonna happen.  Adding code for the explicit purpose of bypassing AP is a huge no-no and would put a gigantic target on the project

> For example - games like Bowser's inside story, get past the initial save screen but then black screen after starting a new game

BIS has some stuff other than what the existing AP patches even cover.  This may not actually be AP triggering, but may be some other functionality that isn't correctly accounted for within bootstrap currently.

> So I'm not really sure what's going on with the compatibility. A lot of things I've tried dont seem to work. The Pokemon games seem to work patched and unpatched. Not sure what others.

Not every patch that's out there accounts for every protection on the rom, and bootstrap still has some issues with certain games even if correctly patched.  Typically the preferred tool is DS Scene Tool (which I see you've stumbled upon) however there are some games which may not be able to be patched with it, depending on where you got them from, or if you've dumped the carts yourself.  You may also want to look into DS ATM if you come across games that can't be patched with DS Scene Tool, or the patching fails to work correctly.

**Comment by Cee123** [comment]
> Also, IIRC, Robz8 said that he won't due to not wanting Nintendo hunting him down[/q]

>  Adding code for the explicit purpose of bypassing AP is a huge no-no and would put a gigantic target on the project. 

Yeah I suspected that might've been the case. But I wasn't really sure. That does make sense. Nintendo seem to be cracking down on a lot of things lately, which sucks.

> The way that this is bypassed with emulators is to simply replicate the card reads in the same manner as they are on the console, so AP is never actually hit. From my understanding, this isn't at all easy to do at all within bootstrap, 

Oh ok, that makes a lot of sense. I never really knew that. As I thought that maybe emulators probably had some inbuilt AP coding as well.

> BIS has some stuff other than what the existing AP patches even cover. This may not actually be AP triggering, but may be some other functionality that isn't correctly accounted for within bootstrap currently.

Yeah, that seems to be one that doesn't work at the moment. And also Mario vs Donkey Kong Mini land mayhem. You are right, there's probably some other stuff going on with those games than just the usual AP.

>  Typically the preferred tool is DS Scene Tool (which I see you've stumbled upon) however there are some games which may not be able to be patched with it, depending on where you got them from, or if you've dumped the carts yourself. You may also want to look into DS ATM if you come across games that can't be patched with DS Scene Tool, or the patching fails to work correctly.

Nice!! Thanks so much. I was looking for a tool that worked better than this one. I did download it, still trying to figure out how to use it.

**Comment by Cee123** [comment]
Just confirming the patched games work with the DS Scene Tool. I was using the xdelta patcher before which didn't seem to work. /facepalm
