### ISSUE TITLE
No roms will boot (freeze on white screen after loading icon disappears)

### ISSUE THREAD

**Issue by SubsonicBeatz154** [ahezard/nds-bootstrap#427]
Title says it all.

I can't get any of the roms i've tried to boot

These games are: Mario & Luigi: Partners in Time, Metroid Prime Hunters and a homebrew game: (https://gamebrew.org/wiki/Super_Smash_Bros_Rumble) i ripped these roms from the Wii U VC versions if that means anything (had to rename them from .srl to .nds for them to show up)

I don't have any cartridge games to try atm so...

I'm using a DSi XL (Super Mario Bros 25th Anniversary edition on firmware version 1.4.5U)

Please help!

**Comment by Robz8** [comment]
You have to decrypt the ROMs using eNDryptS Advanced.

**Comment by SubsonicBeatz154** [comment]
I tried that but it tells me "Decryption / Encryption failed...". Also forgot to mention i'm using TWiLightMenu v6.3.0.

**Comment by Robz8** [comment]
Have you tried running eNDryptS as administrator?

**Comment by SubsonicBeatz154** [comment]
Running as admin didn't fix it.

**Comment by SubsonicBeatz154** [comment]
Wait... Even though it didn't fix the error running it as admin made Mario & Luigi: Partners in Time boot!

**Comment by SubsonicBeatz154** [comment]
Thanks for your help! I've spent about 6 hours trying to get these games to work! (Could care less about homebrew games) I just wanted to play the backups i made of my Wii U VC rips.

**Comment by legoj15** [comment]
Wow, never knew i had to decrypt these. I have so many Wii U VC DS games that I thought I'd never be able to play on my 3DS!
