### ISSUE TITLE
Mario Kart DS issue

### ISSUE THREAD

**Issue by Lykie** [ahezard/nds-bootstrap#43]
Commit b543cd2
VRAM on
NDS clock speed (probably DSi clock speed as well)

Sometimes during a race if you pause and go into sleep mode the game will close out and send you to home menu, no error message or anything else.

**Comment by Robz8** [comment]
The sleep mode function still needs it's card reads patched out.

**Comment by Lykie** [comment]
See the thing is, it's not every time I go into sleep mode though. Let's say it's about 1/20.

**Comment by maorninja** [comment]
Would you mind getting Ermii Kart DS and try booting it?

There is an added crash screen into the game. So please send the crash screen here too...
