### ISSUE TITLE
Newer DS fails to boot (white screens) on 12.1 r2

### ISSUE THREAD

**Issue by YYoshi241** [ahezard/nds-bootstrap#430]
just updated to TWLMenu++ 6.3.0 and 12.1 r2 on my 3ds xl.
no settings work. 
white screens every time.

**Comment by Robz8** [comment]
Is sound fix turned off?

**Comment by YYoshi241** [comment]
Yes.

I also tried older versions: 12.0 which works with sound fix off.
and 11.2 works with sound fix either on or off.

**Comment by Robz8** [comment]
NSMB also has the lag fix to fix the sound crackles, so it may be why it no longer works.

**Comment by YYoshi241** [comment]
Just tried again on 12.1 r2 and it seems to work. I must have just had something set wrong.
SOUNDFIX off is still required.

**Comment by YYoshi241** [comment]
An error has occurred, press and hold power button error after returning to TWLMenu++ on DS Mode, TWL Speed. Same game.

**Comment by YYoshi241** [comment]
NSMB works with soundfix though
