### ISSUE TITLE
dragon quest monster joker 2 need a AP Patch 

### ISSUE THREAD

**Issue by Jota867** [ahezard/nds-bootstrap#432]
The game I need the ap patch, you do not know if there is any, I really want to play it but I get caught in a cinematica of the princio of all, sorry for mi english is the google translate unu

**Comment by dubbz82** [comment]
This should be closed, as it's pretty well documented that games need to be AP patched before functioning correctly.  NDS Scene tool should be able to patch this one.

**Comment by dubbz82** [comment]
Bump.  AP patching fixes this game.
