### ISSUE TITLE
Mario And Sonic At the Olympic Winter Games data corruption

### ISSUE THREAD

**Issue by Mash0Star** [ahezard/nds-bootstrap#433]
When I tried to play Mario And Sonic At the Olympic Winter Games, it always says data corrupted!
I'm using a Dsi XL with HiyaCFW.
------------------------------------------------
Steps to recreate it.
1. Load Mario And Sonic At the Olympic Winter Games.
2. Tap the screen.
------------------------------------------------
It should just run normally but it always keeps saying data corrupted.

**Comment by piratesephiroth** [comment]
it's AP

**Comment by Robz8** [comment]
There's a low chance that you'll get past this message without an AP patch, but one you get past it, it works good.

**Comment by dubbz82** [comment]
Given that this is caused by AP, this should probably be closed out, as a patched copy doesn't have this issue.
