### ISSUE TITLE
Speed Racer: The Video Game Plays Intro Then Goes White

### ISSUE THREAD

**Issue by aaaaafuck** [ahezard/nds-bootstrap#434]
On the latest version when I try to play "Speed Racer: The Video Game" the full intro cut-scene will play and then the screen will go white.  I asked on the TWL Mode Hacking Discord server and they said to create an issue here because it was "most likely an issue with the bootstrap".  I had a friend test it on a different console (both on the latest version) and it didn't work for him either.  I have also tried roms from multiple places and using multiple settings configurations to try and get it to work.  Any help would be appreciated! :+1:

**Comment by Robz8** [comment]
What SDK version does the game use?
If it's 4 or 5, then the game may need to be AP-patched.

**Comment by aaaaafuck** [comment]
I honestly have no idea how to go about finding that out. I tried searching online for like a list of sdk5 games or how I would check and the only thing that came up was posts about Pokemon games not working from a few months ago. If you will forgive my ignorance I at least made an attempt.

**Comment by Robz8** [comment]
Press Y on the game in the ROM menu, if you're using the default DSi or 3DS theme in TWiLight Menu++.

**Comment by aaaaafuck** [comment]
This is fixed on the most recent version.

**Comment by RocketRobz** [comment]
Ah, so the debug 8MB RAM MPU fix indeed does fix some games.
