### ISSUE TITLE
Terms of Service take down...(Compatibility List.)

### ISSUE THREAD

**Issue by jvhellraiser** [ahezard/nds-bootstrap#437]
Compatibility list:
https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=0 

Link Not Working Anymore......

**Comment by Robz8** [comment]
Ok, I've reported an issue that this was improperly flagged.
Let's hope they fix this.

**Comment by RocketRobz** [comment]
I've made a copy of the list, so you guys can contribute to that one instead. ;)
https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit?usp=sharing
