### ISSUE TITLE
SpiderMan Battle for new york Issue

### ISSUE THREAD

**Issue by RinMaru** [ahezard/nds-bootstrap#438]
Spiderman BFNY _NTSC_- 
**TWiLightMenu v6.4.3**-now boots but cant get ingame due to "Could Not Read The Data"
**TWiLightMenu v7.4.1**- Boots to white screen
**Update TWiLightMenu v8.1.0**- Boots to white screen

Spiderman 3 _NTSC_- 
**TWiLightMenu v6.4.3**- now boots but cant get ingame due to "Could Not Read The Data"
**TWiLightMenu v7.4.1**- Boots to white screen
**Update TWiLightMenu v8.1.0**- Working

Spiderman Friend Or Foe _NTSC_- 
**TWiLightMenu v6.4.3**- boots but is stuck on black screen at start menu
**TWiLightMenu v7.4.1**- Boots and gets to start screen but bottom screen is completely black but still usable till the game locks up after selecting somthing
**Update TWiLightMenu v8.1.0**- Working

Spiderman 2_NTSC_-
**TWiLightMenu v7.4.1**- Boots to white screen as of now but worked on an earlier version
**Update TWiLightMenu v8.1.0**- Working

N3DSXL Latest FW
B9S Latest
Luma3DS Latest

**Comment by RinMaru** [comment]
Battle for new york is the last broken game on the list

**Comment by ahezard** [comment]
SpiderMan Battle for new york issue is no more present

**Comment by RinMaru** [comment]
Latest nightly build broke it again

**Comment by RocketRobz** [comment]
Try launching with L held?

**Comment by RinMaru** [comment]
nope just a white screen

**Comment by RinMaru** [comment]
wait after deleting fat table info and holding L it works
