### ISSUE TITLE
Resident Evil (EUR) TID:ABHP

### ISSUE THREAD

**Issue by w1lddog2** [ahezard/nds-bootstrap#439]
This game got a new issue with the latest nds-bootstrap.  After you got back to Mansion everytime you die, the game will crash. It will happen using either DS mode or DSI.
This doesn't happen with the US version (at least the one i tried), neither if you play the game from the cart or a flashcart.

N2DSXL Latest FW
B9S Latest
Luma3DS Latest
TWiLightMenu v6.4.3

**Comment by Stack3r** [comment]
This is an issue with the game not rebooting to title screen, it’s normal in this case for now, all bootstrap games do this
