### ISSUE TITLE
Minor graphical glitches in GTA: Chinatown Wars with TWL clock

### ISSUE THREAD

**Issue by TheShinyCookie** [ahezard/nds-bootstrap#440]
When using the 133MHz setting with GTA: Chinatown Wars, there are graphical glitches, the main one being that characters often lose their heads. Should be put as a note on the compatibility list (once it comes back from the evil corporation that is Google). VRAM Boost has no effect on this.

**Comment by ahezard** [comment]
So do not use TWL speed

**Comment by ahezard** [comment]
If the game does not support the faster CPU there is nothing we can do about

**Comment by TheShinyCookie** [comment]
Of course I'm not going to use TWL speed. I just wanted it put on the list, since there aren't any instructions on how to contribute to the list.
