### ISSUE TITLE
Draglade Not Booting

### ISSUE THREAD

**Issue by Omnija** [ahezard/nds-bootstrap#441]
Draglade doesn't seem to work/boot even though the compatibility list says otherwise.

o3DS Latest FW
B9S Latest
Luma3DS Latest
TWiLightMenu v6.4.3

**Comment by dubbz82** [comment]
At the moment the compatibility list doesn't say much at all...

**Comment by Omnija** [comment]
before it  was down, it said it was working

**Comment by NumbKnot** [comment]
I'm having the same issue on my DSi using the latest version of TWiLightMenu++ and nds-bootstrap.

**Comment by ahezard** [comment]
black screen confirmed

**Comment by ahezard** [comment]
not linked to dma

**Comment by Stack3r** [comment]
AP related?

**Comment by ahezard** [comment]
Could be, is this games known for having ap?

**Comment by ahezard** [comment]
There is a bug with the save patch on Eeprom page erase :

Arm7 (patch vAll)
Relocation src: 023801B0
Relocation dst: 037F8000
JumpTableFunc: 0238C200
Eeprom read:	0238C20C
Eeprom page write:	0238C224
Eeprom page prog:	0238C23C
Eeprom verify:	0238C254
Eeprom page erase:	00000008

**Comment by ahezard** [comment]
I fixed the savePatch bug but draglade still black screen

**Comment by ahezard** [comment]
Fatal Error: ARM9CPU stopped running because "Data access exception" occurred. ]]

   Symbol: STATIC:0x02056064
   02056064:  884A       LDRH           R2, [R1, #0x2]

   CPSR:800000BF   
     R0:027E3AD8  R1:FFFFFFF0  R2:00000000  R3:00000000
     R4:FFFFFFF0  R5:021BA7E4  R6:021BA7C0  R7:00000000
     R8:023F4868  R9:04000000 R10:00000000 R11:00000000
    R12:00000000  SP:027E3AD8  LR:02055CBD  PC:02056064

**Comment by dubbz82** [comment]
Black screen still confirmed on latest nightly.

**Comment by Keptjup** [comment]
Same. still black screen just checked today

**Comment by RocketRobz** [comment]
Reportedly works fine on latest nightly, by RetroGameFan.

**Comment by Keptjup** [comment]
> Reportedly works fine on latest nightly, by RetroGameFan.

What do i need to do to get it to work? help pls thank you, really want to play draglade
