### ISSUE TITLE
error in roms that loaded before (12.2)

### ISSUE THREAD

**Issue by jonaz8** [ahezard/nds-bootstrap#442]
List of roms that worked but no longer

-Nanashi there is no game
-Nanashi, I do not play
-Super mario galaxy (Gericom)
-Asassin's Creed
-The legend of kage (load but have an error that causes the screens to be exchanged or, rather, a graphic error)

Honestly, I do not know if there are more games that do not work. But good

have a nice day :)

**Comment by RocketRobz** [comment]
If you have sound fix or VRAM boost on, try turning either of them off.
Also, make sure DS mode is set, or else Assassin's Creed won't work.

**Comment by jonaz8** [comment]
Thanks you :)

**Comment by ahezard** [comment]
Assassin's Creed works on master

**Comment by ahezard** [comment]
The legend of kage 2 does not have issue on master

**Comment by ahezard** [comment]
THe first Nanashi game is black screening, but it should be ap, the second works.

**Comment by ahezard** [comment]
I close this for now
