### ISSUE TITLE
New Super Mario Bros. Origins (New Super Mario Bros. DS romhack) gets stuck on a white screen.

### ISSUE THREAD

**Issue by Omega944** [ahezard/nds-bootstrap#443]
The game shows the loading screen but gets stuck on a white screen afterwards. I can return to TWiLightMenu with the button combo. Changing settings doesn't help.
The game works fine on a flashcard.
I'm using nds-bootstrap Release v0.12.2 and TWiLightMenu v6.4.3.

**Comment by RocketRobz** [comment]
Is sound fix off?

**Comment by Omega944** [comment]
I tried turning it off, but it didn't work.

**Comment by RocketRobz** [comment]
What are your settings?

**Comment by Omega944** [comment]
At first, i had the following settings:
-Language: Default
-Run in: DSi mode
-CPU speed: 133mhz
-VRAM Boost: on
-Sound fix: on
These didn't work, so I changed them to:
-Language: English 
-Run in: DS mode
-CPU speed: 67mhz
-VRAM Boost: off
-Sound fix: off
These didn't work either.
I checked the compatibility spreadsheet, and the romhack is listed as non-working.

**Comment by Omega944** [comment]
I got the romhack working. I edited the TID of the rom using a program called "DSBuff". The TID of the romhack was "SKJ3" and i replaced it with "A2DE" (The original TID of the rom). The romhack now works after making this change, but I think that having do edit the TID is still an issue.

**Comment by dubbz82** [comment]
Can anyone confirm if this is still an issue without altering the title id?

**Comment by dubbz82** [comment]
I can confirm that this works with the latest bootstrap and latest version of the patch (Rev2).  Not sure if this was a problem with the hack itself, or with bootstrap, but this seems to be resolved.  This can be closed.
