### ISSUE TITLE
AP patched ROMs won't load.

### ISSUE THREAD

**Issue by TheRozitaKnight** [ahezard/nds-bootstrap#447]
I patched some ROMs with the DS-Scene ROM Tool and xdelta, but since v0.11.1, nds-bootstrap just hangs on a white bottom screen. v0.11.0 works fine.

I'm using an Old 3DS XL with Luma3DS and the latest TWiLight Menu++ (v6.4.4).

**Comment by RocketRobz** [comment]
What about v0.12.0 and later?
Also, what are the ROMs?

**Comment by TheRozitaKnight** [comment]
It only works with v0.11.0 - and earlier, I presume -, later versions just hang on a white screen.

I tested the following games:

Inazuma Eleven (Europe)
Kirby Mass Attack (USA)
Mega Man Zero Collection (USA)
Pokémon - White Version (USA, Europe)
Pokémon - Black Version 2 (USA, Europe)

All were AP patched and none worked. The clean ROMs load just fine.

**Comment by RocketRobz** [comment]
The listed games work fine for me on the latest version.
What are your settings?

**Comment by TheRozitaKnight** [comment]
I reinstalled TWiLight Menu++ and am using the default settings.

**Comment by RocketRobz** [comment]
Do the AP patched ROMs work on an emulator?

**Comment by TheRozitaKnight** [comment]
I just tested with RetroArch DeSmuME core on Android, and the patched ROMs do work.

**Comment by TheRozitaKnight** [comment]
I reformatted my SD card with GM9 and reinstalled everything, but it still doesn't work.
