### ISSUE TITLE
Ratatouille gets stuck on a black screen

### ISSUE THREAD

**Issue by GoddamMeme** [ahezard/nds-bootstrap#448]
On my n3ds XL, Ratatouille loads but does not even get to the title screen. It gets stuck on a black screen immediately after it finishes loading.

Edit: Here are some more details about my 3ds:

Model: n3DS XL
CFW: Luma3DS 9.1
TWiLightMenu ++ version: 2.1.0
nds-bootstrap version: Whatever was included in previous item's release

Edit 2: Hashes from my Ratatouille rom:
MD5	26347460222ed5d96c6a73dba27c2b6f
SHA-1	4a84efaabaa03ce45d11fcd8d261e3ad0600e552
SHA-256	a7bb445f3631c9458f13811fccb90caf2034eff0d1720357731c210f55963a58
SHA-384	4eaa42033eef32a4b64c41a40f919d074561b2314c6054d6015d9a94a9bcb4dc4f8eb7b23d5e67e3ce1d39e455bc605f

SHA-512	98b56b2a740585a8204a2341ba1ad6c1af8cdb1b31b667b9d40751579ec15b7042e6dd6900d4c3cb6dde6fd34ad23be1dd525562d84901acbce37798404bcd9d

this might be irrelevant though

**Comment by RocketRobz** [comment]
Sounds like the ROM needs to be AP-patched.

**Comment by ahezard** [comment]
I have observed a different issue. The title screen shows and I can start a game but the game freezes on black screen just after that. Could be ap.

**Comment by ahezard** [comment]
In latest nightly, the games goes to the title screen but get stuck on black screen a new game is created. Could be AP related.

**Comment by GoddamMeme** [comment]
Also, Ratatouille runs just fine in an emulator.

**Comment by dubbz82** [comment]
The absolute latest number associated with ANY copy of this game is just over 2000.  The earliest one is just over 1100.  AP seems extremely unlikely.  Earliest known AP protected game is 1981 - Houkago Shounen (Japan).  I suspect something else is going on with this one.

**Comment by GoddamMeme** [comment]
Here are the current settings applied to my copy via the per game settings:
- Run in: DS mode
- ARM9 CPU Speed: 67 mhz(NTR)
- VRAM Boost: Off
- Bootstrap: Nightly

I've been able to at least get to the title screen on both bootstrap releases. Also, in Twilight Menu global settings:
- Force sleep mode patch: off
- SCFG access in slot 1: off
-slot-1 access method: Direct

During the black screen, the game can only be exited by pressing the home button.

I've included a log file for this game.
[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/2990519/NDSBTSRP.LOG)

**Comment by dubbz82** [comment]
POTENTIALLY related to #540 as both games were developed by the same company, and both experience hard crashes.  Neither of which (as far as I can tell) have AP checks that are tripped.  Hopefully the log file helps in determining the exact cause.

**Comment by ahezard** [comment]
The game breaks when trying to use IPCSYNC register
4000180h  2  IPCSYNC - IPC Synchronize Register (R/W)
This is conflicting with nds-boostrap own use of IPCSYNC register

**Comment by ahezard** [comment]
The code is also checking the 27FFC04 register (NDS Gamecart Chip ID 2)

**Comment by dubbz82** [comment]
Same rom as OP has (verified checksums) now works correctly.  Not sure exactly when this started working, but something between June 10th and now has corrected this.  This can be closed.

**Comment by GoddamMeme** [comment]
After testing the latest nds-bootstrap and trying a clean install of TwilightMenu++ Ratatouille still black screens after starting a new game, loading a save game, or trying to play the cooking mini games. Any suggestions?

**Comment by RocketRobz** [comment]
Try turning off heap shrink.

**Comment by GoddamMeme** [comment]
It still black screens, and after reinstalling TwilightMenu++ again, the Updater crashes my 3ds

**Comment by SleepyLark** [comment]
Tested it on DSi, can also confirm that the game doesn't work.  It's able to launch to the title screen, but anything after that just black screens with the only way out being to hard reset the system.  I've tried turning heap shrink off and switching clock speed.

**Comment by RocketRobz** [comment]
Please test this on v0.30.0.

**Comment by SleepyLark** [comment]
Tested it on v0.30.0 and it boots!  Didn't go to far in game, but you're at least able to go _in game_ and actually control the character.  It also fixes the problem with trying to host multiplayer
