### ISSUE TITLE
DS Internet Browser support

### ISSUE THREAD

**Issue by zacchi4k** [ahezard/nds-bootstrap#449]
The DS Browser doesn't currently work as it requires the Expansion Pak, but the DS Mode on the 3DS and DSi can theorically use more RAM.
Also some homebrews too can take advantage of the Expansion Pak

**Comment by TheShinyCookie** [comment]
That would be interesting to see (even though there isn't much use for the DS Internet Browser today; even the DSi browser is very limited!)

**Comment by poudink** [comment]
keep in mind that expansion pack support wouldn't only benefit the browser, but homebrew too

**Comment by V10lator** [comment]
Not sure if I should open a seperate request for that but lately I got my hands on the DSi Browser (which doesn't need the expansion pack) in the form of a .cia file. If I install the file it just works but if I extract the .nds file and try to run it with TWiLightMenu++ I get an error message: "This game cannot be launched as a .nds file on 3DS/2DS". PictoChat also works just fine as .cia but once extracted and loaded through nds-bootstrap it errors out ("Connection error. The Nintendo DS-System is going to be turned off now" - freely translated from german). So for me it looks as there is code to use the 3DS WIFI/NIFI (else the .cia Installations would error out, too) but nds-bootstrap tries a different approach which fails.

**Comment by piratesephiroth** [comment]
> 
> 
> Not sure if I should open a seperate request for that but lately I got my hands on the DSi Browser (which doesn't need the expansion pack) in the form of a .cia file. If I install the file it just works but if I extract the .nds file and try to run it with TWiLightMenu++ I get an error message: "This game cannot be launched as a .nds file on 3DS/2DS". PictoChat also works just fine as .cia but once extracted and loaded through nds-bootstrap it errors out ("Connection error. The Nintendo DS-System is going to be turned off now" - freely translated from german). So for me it looks as there is code to use the 3DS WIFI/NIFI (else the .cia Installations would error out, too) but nds-bootstrap tries a different approach which fails.

nds-bootstrap can only run DSiWare in nds format on a DSi.

**Comment by V10lator** [comment]
> nds-bootstrap can only run DSiWare in nds format on a DSi.

Which is exactly my point: It looks like the 3DS has functions ready to give modern wifi access to  DSiWare stuff, else it wouldn't work when installed as a CIA, right? So all that's missing is nds-bootstrap hooking into that functions.

**Comment by zacchi4k** [comment]
@V10lator AFAIK they're already looking into that

**Comment by edo9300** [comment]
@V10lator dsiwares are dsi apps, so they natively support WPA encryption, for twilight, currently it is booting dsiwares via unlauncb, that's why it only works on dsi consoles

**Comment by piratesephiroth** [comment]
Remember that DS/DSi games run on the 3DS via "emulation" so there are additional restrictions.
Maybe they could be circunvented by modifying TWL_FIRM but I'm not sure.

**Comment by dubbz82** [comment]
This should probably be closed since it's now supported...
