### ISSUE TITLE
Mario Kart DS Hacks Don't boot?

### ISSUE THREAD

**Issue by WTails358** [ahezard/nds-bootstrap#45]
So I tried to play some Mario Kart DS hacks I found, and the only one that works is the demo version of Ermii Kart DS. If I try to launch the final release of the hack, I am given this error screen right before the Nintendo logo/copyright screen should appear.
http://tinypic.com/r/11v0fbt/9
If I try to boot any other hacks like Mario Kart Infinity, Mario Kart DS Beta Ultimate v1.1b (hack of the kiosk rom), Mario Kart Zero (hack of kiosk rom), and Mario Kart DS N64 Circuit, then I am just greeted with a white screen that never gets to the Nintendo/copyright screen.
Are these hacks unable to be played because they made with maybe a emulator/flashcard in mind or is it because there is additional code that's preventing them from being played?

**Comment by maorninja** [comment]
> If I try to boot any other hacks like Mario Kart Infinity, Mario Kart DS Beta Ultimate v1.1b (hack of the kiosk rom), Mario Kart Zero (hack of kiosk rom), and Mario Kart DS N64 Circuit, then I am just greeted with a white screen that never gets to the Nintendo/copyright screen.

Technically, all Mario Kart DS hacks will boot a white screen. The reason why Ermii booted something different is because it added a crash dump screen into MKDS.

**Comment by Gericom** [comment]
Yes, it's the exception handler I added. I wonder why it crashes though.

**Comment by maorninja** [comment]
@Gericom Are you the creator of Ermii Kart DS? You? Here?

/me runs and hides before doing something that I will regret...

Anyways, um, whoever here is a MKDS ROM hacker, please listen up and do a simple request....

I want you guys to take a custom character model into its own un-modified MKDS ROM and test it....
If it crashes there, tell it here
Then, take a custom track into its own un-modified MKDS ROM and test it with that...
If it crashes there, say it here also...

Also, Gericom, would you mind emailing me a Clean ROM of MKDS with your crash screen in it? It might help with bug crashing even more...

**Comment by Gericom** [comment]
I am not the creator of Ermii Kart DS, but I'm part of the team. I'll see if I can find out what went wrong from this dump first.

**Comment by Ermelber** [comment]
Lol I'm the creator :P But this is stuff only Geri can fix I think

**Comment by maorninja** [comment]
> I am not the creator of Ermii Kart DS, but I'm part of the team. I'll see if I can find out what went wrong from this dump first.

Whoops...

/me sad because I embarrased myself in front of a developer...

> Lol I'm the creator

Even more mistakes I have to learn from..

> Me sad even more for emarassing myself...

So anyways, Gericom, Id actually prefer if you can change your crash screen so the dump is on the bottom screen and the top screen does stuff like how SM64DS does it...

**Comment by WTails358** [comment]
So I should also mention that if I edit a rom of the Kiosk demo version to have the cheat code that lets you access the  debug menu, it will not load but the unedited rom will load.

**Comment by maorninja** [comment]
So basically, **any** edit to a ROM will not work?

Thats the message that all the hacks give...

**Comment by WTails358** [comment]
But I wonder why the Ermii Kart DS Demo works then, but other hacks don't?

**Comment by maorninja** [comment]
Wait, the Demo boots into gameplay, but the full hacks doesn't?

I'll go ask people at DSHack.org, AKA the official MKDS hacking board.

**Comment by WTails358** [comment]
Have you gotten any responses?

**Comment by Ermelber** [comment]
I have no idea why ekds demo works but the full one doesn't. It is true I've modified the arm9 but should it be a problem?

**Comment by WTails358** [comment]
What exactly did you modify in the arm9?

**Comment by Ermelber** [comment]
I added ASM hacks and various edits to some values

**Comment by Gericom** [comment]
Hmm, the error seems to be related to the loading of the sdat file. It occurs in NNS_SndArcGetPlayerInfo which is called by NNS_SndArcPlayerSetup. It seems like the info pointer in the sdat header is corrupted. So probably the read of the header went wrong.

**Comment by WTails358** [comment]
Is there a way to fix this error?

**Comment by Gericom** [comment]
I think I would have to make something to find out what the data looks like to see what got corrupted
