### ISSUE TITLE
Compatibility list document was taken down

### ISSUE THREAD

**Issue by Antonio231102** [ahezard/nds-bootstrap#451]
Looks like the spreadsheet of the compatibility list stored on Google Drive was taken down because according to Google it somehow violated the terms of service.

**Comment by RocketRobz** [comment]
I've re-uploaded it after that happened:
https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit#gid=0

**Comment by Antonio231102** [comment]
Excelent. Don't forget to update the link on the wiki!

**Comment by RocketRobz** [comment]
Done.
