### ISSUE TITLE
Wario Master of disguise White screen

### ISSUE THREAD

**Issue by RinMaru** [ahezard/nds-bootstrap#452]
Wario Master of disguise doesn't boot it says stuck on a white screen switching from twl to ntr doesn't fix it

N3DSXL Latest FW
B9S Latest
Luma3DS Latest
TWiLightMenu v6.4.3

**Comment by DerpBlerp** [comment]
when creating the data for MAster of disguise on the compatibility list someone put USA, instead of Japanese which to my knowledge is the only working version of the game.

**Comment by ahezard** [comment]
duplicate of #397
