### ISSUE TITLE
MySims on NDS Bootstrap isnt fully compatible.

### ISSUE THREAD

**Issue by Setherz6104** [ahezard/nds-bootstrap#453]
I'd like to leave a submission for it to be added to the compatibility list (Google Sheets). The game constantly freezes and stutters every few seconds. I can give footage if need be.

**Comment by RocketRobz** [comment]
What version of nds-bootstrap are you using?

**Comment by ahezard** [comment]
This issue seems fixed in the non_blocking_io branch. Please test and confirm with this build : https://mega.nz/#!Wc0QQYSR!MsiTfrpCXo_E7g6qz0w5NTWoJVQL3IcVJpOq_1FJPhQ

**Comment by ahezard** [comment]
Can you please retest with the latest v0.14.1 release?

**Comment by Setherz6104** [comment]
Newer NDS Boostrap build that you linked earlier fixed the issue. :)
