### ISSUE TITLE
Mario & Luigi: Partners In Time Softlock

### ISSUE THREAD

**Issue by HankDeTank05** [ahezard/nds-bootstrap#454]
Whenever I use a Bro Item in M&L: Partners in time the game doesn't continue. I don't quite know how to describe it. It doesn't freeze, because the sprites are still moving like normal and the music is still playing, but I don't get a button prompt to start the attack, and no button presses do anything other than the HOME button to close out of TWiLight Menu ++ and start over again. (Using nds-bootstrap v0.12.2 and TWiLight Menu ++ 6.4.4)

**Comment by NightYoshi370** [comment]
Is Sound Fix turned on?

**Comment by NightYoshi370** [comment]
I can't seem to reproduce this in the latest version. I can use bro items just fine

**Comment by MDHEXT** [comment]
My game softlocks after the kamek battle
