### ISSUE TITLE
Infinite white screen when launching Nanashi no Game (translation)

### ISSUE THREAD

**Issue by DarthVitrial** [ahezard/nds-bootstrap#455]
As the title says, when launching the translated rom of Nanashi no Game it just hangs on a white screen forever.

**Comment by DarthVitrial** [comment]
Oh, right. bootstrap 12.2, on n3DS 11.8 firmware, latest luma, Twilight menu 6.4.4.

**Comment by DarthVitrial** [comment]
Seems to be caused by turning on the Sound Fix.

**Comment by DarthVitrial** [comment]
Even if you turn off sound fix and get to the logos the game never loads though, after the logos it gets to an infinite black screen this time. and this one doesn't seem affected by settings.

**Comment by NightYoshi370** [comment]
Have you tried the non-blocking-io branch?

**Comment by piratesephiroth** [comment]
does the same happen with the original game?

**Comment by piratesephiroth** [comment]
have you tried repacking the rom with dslazy?

**Comment by DarthVitrial** [comment]
No, and sadly I can’t anymore. As of two minutes ago my sd card with all my games and saves on it died, so I can’t do any testing now.

**Comment by 0klux** [comment]
Just saying, all of these are known issues, they're even documented on the compatibility list, so no fix, really, as of now.

**Comment by ahezard** [comment]
This is AP right?

**Comment by 0klux** [comment]
According to the compatibility list.... But i can't really find any ap patch for this game.

**Comment by CebolaBros64** [comment]
I don't believe this is anti-piracy related. Looks like people are mistaking this game for the sequel, which indeed, does have AP. I can't find any info online about the AP patch for this game, and the DS-Scene tool doesn't recognize the game as having AP either.

**Comment by WychWitch** [comment]
I hope necroposting on this issue is okay, and if not I'm sorry.

I'm having this same issue as DarthVitrial did, logos and then infinite black screen. I tried repacking with dslazy as well and it still doesn't work.

TWiLightMenu+++ is v9.3.0 which is running nds-bootstrap v0.24.0 and this is all on my DSI XL
