### ISSUE TITLE
Chibi Robo Park Patrol Glitch after Tutorial 

### ISSUE THREAD

**Issue by RinMaru** [ahezard/nds-bootstrap#456]
Chibi Robo Park Patrol glitches and is unplayable after the tutorial
TWL and NTR both have the issue

N3DSXL Latest FW
B9S 1.3
Luma3DS Latest
TWiLightMenu v6.4.3

**Comment by RinMaru** [comment]
This issue is solved but only after allot of tinkering with settings 
Game MUST be in DS MODE
Game MUST be at NTR Speed
Lastly VRAM Boost MUST be OFF

if any of these are changed it will bug the game resulting in freezes and Graphical curruption

**Comment by RinMaru** [comment]
nvm the issue happened again with the same settings it worked on

**Comment by NightYoshi370** [comment]
Can you try it on the latest bootstrap?

**Comment by RinMaru** [comment]
sure
