### ISSUE TITLE
Newer Super Mario Bros DS doesn't load

### ISSUE THREAD

**Issue by ccccmark** [ahezard/nds-bootstrap#457]
I tried to load the Newer SMB DS, with the lastest bootstrap (0.12.3), using TWiLight Menu, but it just shows me a white screen, re-patched the original game? Done, still nothing. Deleting the savefile? Done, white screen.

This game ran very fine with previous bootstraps (before 0.1X.x) but now, just white screen.

My console is DSi, with Hiya installed.

**Comment by RocketRobz** [comment]
Make sure sound fix is off.

**Comment by ccccmark** [comment]
Done.

**Comment by MGislv** [comment]
I'm having the same problem, but I can't find the sound option in the TWiLight settings
