### ISSUE TITLE
Another Super Mario 3D (SM64DS Hack) Issue?

### ISSUE THREAD

**Issue by WTails358** [ahezard/nds-bootstrap#46]
So I tried playing Skawo's hack of SM64DS Another Super Mario 3D and it hangs on a white screen so I tried the debug crash and got these results:
http://tinypic.com/r/2yns16x/9
I didn't have a cartridge in my 3DS so the results may vary for some people.

**Comment by maorninja** [comment]
I'd actually like it if we kept everything SM64DS related issues within my thread, that means that it will be easier to bug fix.

**Comment by WTails358** [comment]
So should I just add the info as a comment to your thread?

**Comment by maorninja** [comment]
Nah, I'll add it myself... (I'll credit you though)

But by the looks of things, it has the exact issue as it was for my test with cardv.1.

What you can do, however, is close this issue...
