### ISSUE TITLE
Pokémon SoulSilver/Platinum crashing

### ISSUE THREAD

**Issue by Fackey** [ahezard/nds-bootstrap#461]
After saving once and then reloading, the games say "A communication error has occurred" after pressing a button the game crashes.

**Comment by RocketRobz** [comment]
Are you using DSiWareHax or HiyaCFW?

**Comment by Fackey** [comment]
DsiWareHax

**Comment by RocketRobz** [comment]
You need HiyaCFW installed to avoid that message, because with just DSiWareHax, the WiFi is still in DSi mode.
Follow this guide [here](http://dsi.cfw.guide/).

**Comment by RocketRobz** [comment]
Can you upgrade from Vista?

**Comment by Fackey** [comment]
Not atm

**Comment by Epicpkmn11** [comment]
On the osfmount download page it has links for the previous version right below the main download links. It says that version works on Vista

**Comment by Fackey** [comment]
I have to be online to finish this, don't I?

My PC is offline.

**Comment by Epicpkmn11** [comment]
If you've got OSFMount, Hiya Helper, and the HiyaCFW and (optionally)TWiLight Menu++ `.7z`s, then you shouldn't need the internet

**Comment by Fackey** [comment]
It says "downloading latest HiyaCFW release"
"ERROR: Could not get HiyaCFW"

**Comment by Epicpkmn11** [comment]
If you put [HiyaCFW's .7z](
https://github.com/RocketRobz/hiyaCFW/releases/download/v1.3.2/HiyaCFW.7z) in the helper's folder it should work (at least if you have the latest helper)

**Comment by Fackey** [comment]
It worked!
But now I have a new problem. 

"Copy the contents of the 'out' folder in your HiyaCFW Helper folder to the root of your SD card"

There is no out folder.

**Comment by Epicpkmn11** [comment]
In the latest helper it had you select a folder, the guide just hasn't been updated yet

Nov 25, 2018 9:08 PM、"Fackey" <notifications@github.com<mailto:notifications@github.com>> のメッセージ:


It worked!
But now I have a new problem.

"Copy the contents of the 'out' folder in your HiyaCFW Helper folder to the root of your SD card"

There is no out folder.

**Comment by Fackey** [comment]
So what should be there? Nand?

**Comment by Epicpkmn11** [comment]
There should be a bunch of folders like hiya, shared1, shared2, sys, title, and a few more

**Comment by Fackey** [comment]
No, where do I get that?

**Comment by Fackey** [comment]
I found it. It wasn't unpacked from the .7Z file.

**Comment by Epicpkmn11** [comment]
The helper should've put it there... it comes from Hiya's 7z

**Comment by Fackey** [comment]
One last thing. 
I'm following this guide:
https://dsi.cfw.guide/replacing-system-menu-with-twlmenu++

Launcharggen doesn't generate anything in the dsiware folder.

**Comment by Fackey** [comment]
When I get to the point where I replace with Twiloader it says 
"Start failed. Error 1
bootloader.nds not found"

**Comment by Epicpkmn11** [comment]
Check in the helper's folder or maybe 'for PC' in the helper's folder, and if you find it, put it in 'sd:/hiya'

**Comment by Fackey** [comment]
Did that and it sort of worked.
Except now it's crashing to a white screen.

**Comment by Epicpkmn11** [comment]
Try running this: https://github.com/Epicpkmn11/HBChecker/releases
it'll check for missing/corrupted files

**Comment by Fackey** [comment]
title/00030017/484e4145/content/00000002.app from HiyaCFW Helpers 'out' folder was missing

**Comment by Epicpkmn11** [comment]
Try running the helper again maybe... It didn't make the patched Launcher and put it in the right spot... (or maybe check in 'for PC', but even if it's there I'm not sure it'd be patched properly (HBChecker does check if it's patched correctly if you find 00000002.app and run it again))

**Comment by Fackey** [comment]
Nope. Not there.

**Comment by Epicpkmn11** [comment]
Try running the helper again then... maybe it'll work this time...

**Comment by Fackey** [comment]
Didn't work.

**Comment by Fackey** [comment]
The issue is resolved, thanks RocketRobz and a very special thanks to Epicpkmn11!
