### ISSUE TITLE
Theme Park not working

### ISSUE THREAD

**Issue by spidymame** [ahezard/nds-bootstrap#464]
Hi,
just wanted to let you guys know that Theme Park doesnt load on nds-bootstrap, it just gets to solid black screens and doesnt move from there, hopefully it will work someday :)

**Comment by RocketRobz** [comment]
What SDK version does the game use?
You can check by pressing Y on the game in the ROM menu of TWiLight Menu++.

**Comment by spidymame** [comment]
im using the forwarder instead of the menu system, can i check from there?

**Comment by RocketRobz** [comment]
nope

**Comment by spidymame** [comment]
ok, ill have to install it, may be a few days, sorry, will get back to you with sdk version soon

**Comment by spidymame** [comment]
hi, sorry it took so long, it used sdk version: 3

**Comment by spidymame** [comment]
just wondering if this will be added to the compatibility table?

**Comment by ahezard** [comment]
I was not able to reproduce any performance issue with the latest nightly, please retest

**Comment by spidymame** [comment]
sorry for the radio silence, tested on v 0.17.0 and v 0.17.1 and i feel the load time is slightly reduced and but obviously still hangs for me in spots, the opening it seems most apparent, and clicking new game has it just on a black screen

**Comment by ahezard** [comment]
Please test with latest nightly and report if the issue is fixed now that #517 have been implemented

I am still not able to spot any obvious slow down that affect the gameplay. Which region is you game?

**Comment by spidymame** [comment]
hi,
finally tried it again and replaced sd card files :) boots like a dream, it boots in chinese text, just gonna try ad figure my way around that, unless you guys know how to get around that one haha
