### ISSUE TITLE
Bowsers inside story still doesn't work

### ISSUE THREAD

**Issue by Cee123** [ahezard/nds-bootstrap#465]
Clean rom doesn't work, AP patched rom doesn't work. Both US and EUR versions.

Any chance this will be fixed in the future?

**Comment by Cee123** [comment]
Also want to say what an awesome job you guys are doing. All the other roms that I've tested work flawlessly! So much so, that I no longer need my flashcart anymore.

**Comment by hubert-skowronek** [comment]
@Cee123 there is already the issue for this: https://github.com/ahezard/nds-bootstrap/issues/249 maybe let's close this one and write there?

**Comment by Cee123** [comment]
OK, considering that thread was three months ago.. I see there's still no plan to get the game working. Thanks anyway.

**Comment by hubert-skowronek** [comment]
@RocketRobz well then -  @shutterbug2000 - I keep my fingers crossed!

**Comment by ozalex** [comment]
This was a my favorite child-hood game and was sad that it could not load on my R4 DS or on Emulators. If there are any possible fixes please let me know!

**Comment by Cee123** [comment]
@ozalex I agree. It's probably one of the best DS games I've ever played. It should work on R4 using YSMenu or Wood. It also works on Desmume including the Retroarch core, No$gba or even Drastic if you have Android.

**Comment by piratesephiroth** [comment]
it does now

**Comment by ozalex** [comment]
@Cee123 @piratesephiroth  well when I downloaded it from all types of websites it would get stuck on the save screen (on R4). where did you get your working versions? thanks for the responses

**Comment by Cee123** [comment]
You guys are legends!!! Keep up the fantastic work you guys are doing. It works now. As always, awesome work from these guys.

**Comment by Cee123** [comment]
@ozalex Download either YSMenu or Wood firmware for the R4 cart. Should be able to find those on Google.

**Comment by ozalex** [comment]
@Cee123 Yea I have tried but it ended up messing my R4 card up, I had to look for the right version again for 3 hours xD.

**Comment by ozalex** [comment]
@Cee123 I got the game working, you were right! just had to run it as a .nds file. Thanks!

**Comment by Cee123** [comment]
@ozalex No worries

**Comment by Davidchao23** [comment]
Not sure if it's only an issue with me but once I to the part where I play as Bowser, the next room in the forest has a glitched floor, and progressing further makes the game hang on a black loading screen, with the music still playing. Any fix for that?
