### ISSUE TITLE
Time Hollow crashes to white screen

### ISSUE THREAD

**Issue by piratesephiroth** [ahezard/nds-bootstrap#466]
![image](https://user-images.githubusercontent.com/10672233/49457996-0fcc2f80-f7d3-11e8-9981-eedb39b7993d.png)

It's an SDK 3 game. Saves fine and there's no stutter during the videos.
The problem is that it crashes to a white screen when we try to view the flashbacks menu when there's new content there.

Happens on both USA and EUR versions. Here's a sample save file. Just continue the game, press X to enter the menu and select the first option.
[2704 - Time Hollow (USA) (En,Fr) [b].zip](https://github.com/ahezard/nds-bootstrap/files/2645078/2704.-.Time.Hollow.USA.En.Fr.b.zip)
.

**Comment by piratesephiroth** [comment]
seems fixed in v0.14.0 RC1

**Comment by RocketRobz** [comment]
So the `non_blocking_io` branch does indeed fix some issues related to crashing.

**Comment by piratesephiroth** [comment]
the videos became a bit stuttery though

**Comment by RocketRobz** [comment]
I think the video stutters should be fixed in v0.14.1 now.
