### ISSUE TITLE
Changing the speed of a game

### ISSUE THREAD

**Issue by MaximeAnsquer** [ahezard/nds-bootstrap#468]
Hello, 

would it be possible to add the ability to change the speed of a game, particularly make it faster?

I love Final Fantasy Tactics Advance 2, but the combats are so slow ! 😆 

Thank you.

**Comment by poudink** [comment]
no

**Comment by RocketRobz** [comment]
While it's not possible to make it faster than normal, it should be possible to make it run slow.
