### ISSUE TITLE
No sound on some games when reseting the game.

### ISSUE THREAD

**Issue by WalaRocks18** [ahezard/nds-bootstrap#469]
yes, it has a AP patch in it.
I use the Spanish version of it.
Steps: Open the game, enter your save file and do L+R+Start+Select and sound is nowhere to be found. spooooooooky......

**Comment by piratesephiroth** [comment]
The same happens with Ni No Kuni

**Comment by RocketRobz** [comment]
I don't have this issue. :(

**Comment by WalaRocks18** [comment]
@RocketRobz, any idea on how to fix it?

**Comment by RocketRobz** [comment]
Try reinstalling the game booter CIA.

**Comment by WalaRocks18** [comment]
nope, still no sound

**Comment by piratesephiroth** [comment]
yep, reinstalled the game booter and Ni No Kuni is still mute after soft reset.

**Comment by WalaRocks18** [comment]
Still no sound on 0.13.0 :(

**Comment by RocketRobz** [comment]
I did the steps, and I still get sound.
What is the sound frequency set to? I have it set to 48khz.

**Comment by WalaRocks18** [comment]
I have 48khz too, may it be that i have the default arm9 speed to 133MHz?

**Comment by WalaRocks18** [comment]
Nope, it's not the speed.
But really, it's not a MAYOR or important issue so...

**Comment by WalaRocks18** [comment]
Now trying without VRAM Accel

**Comment by piratesephiroth** [comment]
yeah, sound frequency was set to 47.61kHz.

Apparently the bug doesn't happen if it's set to 32.73 kHz, at least on Ni No Kuni.

**Comment by WalaRocks18** [comment]
Yes, it was the sound frec.

**Comment by WalaRocks18** [comment]
Soo........ 48khz is  b r o k e n.

**Comment by RocketRobz** [comment]
idk why it's not broken for me though. :P
Others had issues with 48khz in previous TWLMenu++ versions.
So with that said, it's a TWiLight Menu++ issue, and not an nds-bootstrap issue.

**Comment by WalaRocks18** [comment]
It's strange that you say that @RocketRobz, because I have the latest TWiLightMenu++ (6.6.1)

**Comment by RocketRobz** [comment]
Try installing this CIA: [rungame.zip](https://github.com/ahezard/nds-bootstrap/files/2674528/rungame.zip)

**Comment by piratesephiroth** [comment]
still broken all the same

**Comment by RocketRobz** [comment]
This one?
[rungame.zip](https://github.com/ahezard/nds-bootstrap/files/2674559/rungame.zip)

**Comment by WalaRocks18** [comment]
still no sound.

**Comment by RocketRobz** [comment]
I give up. :P

**Comment by WalaRocks18** [comment]
oof.
