### ISSUE TITLE
Where can i find Mario & Luigi: BIS (EU) AP patch?

### ISSUE THREAD

**Issue by WalaRocks18** [ahezard/nds-bootstrap#470]
DS Scene Rom Tool doesn't have it, so if you can give me a link i'll be glad.

:)

**Comment by Uupo03** [comment]
https://www.odrive.com/s/8443cc3a-862e-41d7-b064-09378f79f6b3-5965a89a
Go into the "XPA's Game Patches" folder

**Comment by WalaRocks18** [comment]
Sorry @Uupo03, couldn't find a EU patch of it.

**Comment by Uupo03** [comment]
Oh whoops, looks like theres only a USA patch on odrive. sorry :P
