### ISSUE TITLE
Bowser's Inside Story - Graphical Glitching

### ISSUE THREAD

**Issue by dubbz82** [ahezard/nds-bootstrap#471]
Although the game now boots correctly, there are still places where graphical glitching occurs.  This can be seen very early in the opening scenes of a new game where there's a pot on the stove with glitched graphics (some other areas as well, this is probably the quickest one to occur, however)

**Comment by hubert-skowronek** [comment]
If you try my patch which I've developed https://www.file-upload.com/skrszw6dw79e then the pot is not glitched, maybe it will help at least to investigate

**Comment by RocketRobz** [comment]
Using that patch fixes this issue. Closing.

**Comment by largobell** [comment]
How do I download this patch? The website that supposedly hosts it says that it’s been removed.
