### ISSUE TITLE
M&L: BIS Errors, Bugs or Glitches

### ISSUE THREAD

**Issue by WalaRocks18** [ahezard/nds-bootstrap#472]
After burning down the trees in his tutorial the games top screen freezes but the song stays on.
Yes, it is an US AP-Patched Rom and I'm on the latest bootstrap (0.13.0).

**Comment by hubert-skowronek** [comment]
When using my patch I can burn down the trees and games proceeds further (please look into the gbatemp post or github issue relating ML BiS pot glitch)

**Comment by WalaRocks18** [comment]
k gonna try :)

**Comment by WalaRocks18** [comment]
Well, it solved it, but now when you Save & Quit, the game white screens.

**Comment by hubert-skowronek** [comment]
@WalaRocks18 you're right, haven't checked saved & quitting as I save and continue my entire life in every game B) such a no-life am I B) I've checked previously known patch and the behavior is the same. @shutterbug2000 do you think it is something on nds-bootstrap side?

**Comment by RocketRobz** [comment]
Yes, it's on nds-bootstrap side. Soft-resetting on game side doesn't work properly.

**Comment by hubert-skowronek** [comment]
@RocketRobz do you mean soft-resetting by L+R+select+start? It does work for me, by there is no sound afterwards, but the same thing is for other games like e.g. Ghost Trick

**Comment by WalaRocks18** [comment]
@hubert-skowronek , do you have it in 48kHz or 37kHz?

**Comment by hubert-skowronek** [comment]
@WalaRocks18 thanks, that was it!

**Comment by RocketRobz** [comment]
Using the new patch fixes the black screen crash. Closing.

**Comment by MasterGamingYT** [comment]
@RocketRobz I guess the soft resetting explains why nsmb minigames won't work

**Comment by RocketRobz** [comment]
@MasterGamingYT That's true.
