### ISSUE TITLE
White screen on two different AP-patched games 

### ISSUE THREAD

**Issue by gingerbeardman** [ahezard/nds-bootstrap#476]
### Your console

Tell us which console do you have:

- [x]  DSi (XL)

### CFW and configuration

Tell us which CFW do you have: 

DSi:

- [x]  Unlaunch+HiyaCFW _[1.8+1.3.2]_

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.13.0]_

### If this issue only affects a certain game, which game is it?

- Umihara Kawase Shun - Second Edition Kanzenban (4354)
- Puyo Puyo 20th Anniversary (5769)

### Expected behaviour

- Should launch

### Actual behaviour

- White screen
- AP-patch warning when launching Puyo Puyo 20th

### Steps to reproduce

1. Put ROMs on SD card
2. Try to launch using TWLM++ or Unlaunched
3. Observe white screen

### Other notes

- AP patched using _DS-Scene Rom Tool 1.0 (1215)_ with all current updates

**Comment by RocketRobz** [comment]
Do other games work?

**Comment by gingerbeardman** [comment]
That's a good point. 

I've only been able to get one game to work. 
`Nintendo Touch Golf`
And that only worked once. 

I've not switched on the loading screen (which is switched off for cosmetic reasons) and I can see that the loading bar completes and then I just sit at a white screen. 

I've since reformatted my SD card to FAT32 just to be sure. 

Any ideas?

**Comment by gingerbeardman** [comment]
OK I formatted my 2GB card again as FAT32 with 16K clusters and everything is working and loading is _much_ faster across everything!
