### ISSUE TITLE
Sonic Rush freezes in Water Palace

### ISSUE THREAD

**Issue by WalaRocks18** [ahezard/nds-bootstrap#477]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.13.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Sonic Rush

### Expected behaviour

Play Water Palace normally

### Actual behaviour

In the middle of gameplay the background textures glitch and the game freezes.

### Steps to reproduce

1.Open game.
2.Select Sonic.
3.Play Water Palace.
4.Play for a while and it freezes.

**Comment by RocketRobz** [comment]
In TWiLight Menu++, open per-game settings for that game, and set clock speed to NTR.
