### ISSUE TITLE
Blue Screen for (U) version of game; but (E) and (J) versions of game are playable

### ISSUE THREAD

**Issue by gingerbeardman** [ahezard/nds-bootstrap#478]
### Your console

Tell us which console do you have:

- [x]  DSi (XL)

### CFW and configuration

Tell us which CFW do you have: 

DSi:

- [x]  Unlaunch+HiyaCFW _[1.8+1.3.2]_

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.13.0]_

### If this issue only affects a certain game, which game is it?

- 0203 - Nintendo Touch Golf - Birdie Challenge U
- 0279 - Otona No DS Golf U
- 0294 - True Swing Golf U

### Expected behaviour

- Both should be playable

### Actual behaviour

_True Swing Golf_
- Top screen = White
- Bottom screen = Blue

_Nintendo Touch Golf_ & _Otona no DS Golf_
- playable

### Steps to reproduce

1. Put ROMs on SD card
2. Launch games
3. Observe screens

### Other notes

- no AP fix available in DS-Scene Roms Tool
- an original True Swing Golf cartridge works on my DSi XL

- maybe there's a way to figure out the differences between versions and increase compatibility?

**Comment by gingerbeardman** [comment]
It turns out that save games are compatible between all versions, so I have continued by save using the (E) version of the game. 

I'm intrigued what is breaking the (U) version?

**Comment by Stack3r** [comment]
Is this still an issue?

**Comment by gingerbeardman** [comment]
If you've not been able to reproduce it, I'll try soon.

**Comment by Stack3r** [comment]
Thank you

**Comment by dubbz82** [comment]
Has this issue been able to be reproduced?

**Comment by gingerbeardman** [comment]
Just tested with latest and (U) version now loads correctly! Cheers
