### ISSUE TITLE
White screen: Umihara Kawase Shun - Second Edition Kanzenban (4354) AP-fixed

### ISSUE THREAD

**Issue by gingerbeardman** [ahezard/nds-bootstrap#479]
### Your console

Tell us which console do you have:

- [x]  DSi (XL)

### CFW and configuration

Tell us which CFW do you have: 

DSi:

- [x]  Unlaunch+HiyaCFW _[1.8+1.3.2]_

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.13.0]_

### If this issue only affects a certain game, which game is it?

- Umihara Kawase Shun - Second Edition Kanzenban (4354)
- AP-fixed

### Expected behaviour

- Should launch

### Actual behaviour

- White screen

### Steps to reproduce

1. Put ROMs on SD card
2. Try to launch using TWLM++
3. Observe white screen

### Other notes

- AP patched using _DS-Scene Rom Tool 1.0 (1215)_ with all current updates
- I can launch other games OK, both AP-fixed and unpatched

**Comment by dubbz82** [comment]
Seems to work correctly on a 3ds.  Try running this with NTR cpu speeds if you haven't already.

**Comment by gingerbeardman** [comment]
Copied my ROM onto my SD card again. 

Works now, at both NTR and TWL speeds. 

Not sure what was wrong.
