### ISSUE TITLE
More subtle loading screen?

### ISSUE THREAD

**Issue by gingerbeardman** [ahezard/nds-bootstrap#480]
### Your console

Tell us which console do you have:

- [x]  DSi (XL)

### CFW and configuration

Tell us which CFW do you have: 

DSi:

- [x]  Unlaunch+HiyaCFW _[1.8+1.3.2]_

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.13.0]_

### Expected behaviour

Subtle loading screen like the one that appears as TWLM++ loads, with the small loading in the middle, small spinner in the lower right and a relevant message in the lower left

### Actual behaviour

HUGE loading, spinner, and progress bar

**Comment by Stack3r** [comment]
This has been added with another theme, also this is not a bootstrap issue

**Comment by gingerbeardman** [comment]
Rob advised me that it was a bootstrap issue

https://github.com/RocketRobz/TWiLightMenu/issues/287

**Comment by gingerbeardman** [comment]
@Stack3r how do I change this using a theme?
