### ISSUE TITLE
Powerful Golf (Konami): graphics corruption and odd behaviour (AP-fixed)

### ISSUE THREAD

**Issue by gingerbeardman** [ahezard/nds-bootstrap#481]
### Your console

Tell us which console do you have:

- [x]  DSi (XL)

### CFW and configuration

Tell us which CFW do you have: 

DSi:

- [x]  Unlaunch+HiyaCFW _[1.8+1.3.2]_

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.13.0]_

### If this issue only affects a certain game, which game is it?

- 5623 - Powerful Golf

### Expected behaviour

- Should be playable

### Actual behaviour

- course can be missing (result is "you cannot hit the ball form here")
- textures can be missing (result is white 3D objects including course)
- often pauses during level loading
- red screen crashes

### Steps to reproduce

1. Put AP-fixed ROM on SD card
2. Launch game
3. Start practice (bottom left option)
4. Play a hole or two

### Other notes

- AP fix applied using in DS-Scene Roms Tool

**Comment by RocketRobz** [comment]
Can you see if the issue is fixed in v0.14.1?

**Comment by gingerbeardman** [comment]
Problem seems to be fixed! Woop!

Tested running as DS and DSi

Thanks!
