### ISSUE TITLE
testing some unknown ds games

### ISSUE THREAD

**Issue by nabilhoche83** [ahezard/nds-bootstrap#483]
### Your console
old nintendo 3ds
### CFW and configuration

luma3ds 9.1

### nds-bootstrap version

0.13.0

###  tested games

mr bean ds : boots  but after the presentations of the companies that created the game upon reaching the title screen crashes

maplestory ds jp: white screen

the great giana sisters ds (eur):white screen

mario & luigi bowser inside story (demo) (eur):boots but when you press start game it crashes

New Zealand Story Revolution (eur):works

hack rom:mario kart zero:works

these are the games that I've tested in a 3ds
(Most are from Europe but at least I hope to give my grain of sand to improve nds-bootstrap)
sorry for my bad inglish

**Comment by nabilhoche83** [comment]
> Bowser's Inside Story needs to be AP-patched, but there is no AP patch for the EUR ROM.
> For now, use the USA ROM, and patch it with kinder_bueno's AP patch.


but I used the demo

**Comment by mariomadproductions** [comment]
I doubt they would have removed the AP for the demo.

**Comment by ahezard** [comment]
Could be linked to #517 at least for maplestory

**Comment by ahezard** [comment]
please retest maplestory with the latest nightly

**Comment by ahezard** [comment]
mr bean have no issue

**Comment by ahezard** [comment]
the great giana sisters does white screen indeed

**Comment by ahezard** [comment]
the great giana sisters  is already covered by  #379 and others games works now so I close this
