### ISSUE TITLE
Black screen after Phantom Hourglass intro

### ISSUE THREAD

**Issue by Icy-kitsune** [ahezard/nds-bootstrap#484]
### Your console

Tell us which console do you have:

- [x]  Old 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release v0.13.0

### If this issue only affects a certain game, which game is it?

The Legend of Zelda: Phantom Hourglass

### Expected behaviour

game should be playable

### Actual behaviour

Black screen / game is unplayable

### Steps to reproduce

1. put ROMs on sd card
2. Launch game
3. select save file
4. watch cinematic (or skip it)
5. screen turns black

**Comment by WalaRocks18** [comment]
Update to latest (0.13.0), it works over there for me.

**Comment by Plausible0Bug** [comment]
It seemed as of https://github.com/ahezard/nds-bootstrap/releases/tag/v0.14.0RC1

I can play this game properly.

I used to be stuck right after shield purchasing and later entering the shrine for the phantom sand.

Now I'm at the place where I search for a way to pass the fog, no problem so far.

I'm using twilight menu on my n3ds with luma3ds.

**Comment by Icy-kitsune** [comment]
> It seemed as of https://github.com/ahezard/nds-bootstrap/releases/tag/v0.14.0RC1
> 
> I can play this game properly.
> 
> I used to be stuck right after shield purchasing and later entering the shrine for the phantom sand.
> 
> Now I'm at the place where I search for a way to pass the fog, no problem so far.
> 
> I'm using twilight menu on my n3ds with luma3ds.

Hey it works! Thanks!
