### ISSUE TITLE
TWEWY glitches out on opening cinematics on 0.14.0 RC1

### ISSUE THREAD

**Issue by golf-player** [ahezard/nds-bootstrap#486]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release v0.14.0 RC1 as shipped with latest TWilightMenu
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

The World Ends with You. Tested on both E and U versions

### Expected behaviour

Cinematics should play normally

### Actual behaviour

They glitch out and the sound loops. 
![image](https://user-images.githubusercontent.com/35775018/50580129-c9d5ac00-0e10-11e9-87a5-d572c6232e76.png)

### Steps to reproduce

1. Fire up a new game on TWEWY
2. Get to the point in the tutorial where you have to flee the frogs. After this come the cinematics in question.
3. THey should glitch out after playing fine for 5-7 seconds. It's always a random point where it cuts out, but it's a long cutscene and I've never seen it end so far. 

Reproduced this 5 times. 3 on U, 2 on E

**Comment by RocketRobz** [comment]
Was it with NTR or TWL clock speed?

**Comment by golf-player** [comment]
How would I check?

I'm not running ntr, and I didn't explicitly do anything to the clock speed if that helps.

**Comment by RocketRobz** [comment]
Check the TWiLight Menu++ settings, and switch a page.

**Comment by golf-player** [comment]
Ah I had missed that. It was on ntr, but I changed it to TWl, and it still glitches. Trying the increased ram and bus option now.

**Comment by golf-player** [comment]
Works on 0.13.0

**Comment by RocketRobz** [comment]
Can you check if the issue is fixed on v0.14.1?

**Comment by golf-player** [comment]
Works great!

That was fast.
