### ISSUE TITLE
Pokémon White Freezing issue

### ISSUE THREAD

**Issue by Gumdradude** [ahezard/nds-bootstrap#487]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.14.0 RC1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokémon White (AP patched rom)

### Expected behaviour

Game should load

### Actual behaviour

Freezes on White Screen upon startup

### Steps to reproduce

1. Start up Pokémon White on nds-bootstrap 0.14.0 RC1 with Twilight Menu++ 6.8.3
2. 
3.

**Comment by takeshineale128** [comment]
Load the game using ds mode as this game is ds I rom
