### ISSUE TITLE
Pokemon dash does not boot

### ISSUE THREAD

**Issue by dubbz82** [ahezard/nds-bootstrap#488]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [x ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Game should boot

### Actual behaviour

Game freezes after bootstraps loading screen and stays on a white screen

### Steps to reproduce

1.load Pokemon dash with bootstrap (I used us region can provide ROM hashes later if needed)

### Other notes

This has been known for a while and at one point in time (>1 year ago) did boot.  I just want to make sure it's documented here as well.

**Comment by ahezard** [comment]
Could be linked to #517

**Comment by RinMaru** [comment]
Related to #286

**Comment by dubbz82** [comment]
I'll close this one as it's a dupe of #286  That one should be linked to #517
