### ISSUE TITLE
What does prevent nds-bootstrap to run Layton games?

### ISSUE THREAD

**Issue by riotalternis** [ahezard/nds-bootstrap#49]
I've heard that VN run better on this soft, but i'm not quiet sure i get why Layton games are listed as not working on the google document. Not here to complain, but to understand: These games are very similar to Visual Novels, so... why?

**Comment by Robz8** [comment]
They haven't been tested in a while, so the info is out of date.

**Comment by ahezard** [comment]
Every game may not work, this is not related to the type of game but rather to the code of the game. There is no operating system on the ds and each game have a similar but sligthly different code to read the card. So far I have counted at least 10 different variations of the code, I am patching properly only 3 of them, hence the bad compatibility so far. Please open issue related to a specific game not to a serie of game.
