### ISSUE TITLE
Mario & Luigi Bowser's Inside Story hangs when NTR card is in

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#491]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release 0.14.1
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

M&L Bowsers Inside Story

### Expected behaviour

Patched (kinder_bueno) game should allow to proceed past select save menu.

### Actual behaviour
When NTR card is inserted then AP seems to trigger on and the game hangs.

### Steps to reproduce

1. Insert NTR card into 3DS.
2. Launch the patched game via nds-bootstrap
3. Notice blocked controls on select save screen

### Other notes
@RocketRobz  @ahezard  @shutterbug2000 Could it be mitigated by nds-bootstrap or it would have to be patched in the rom? The "old" patch seems to be working even with NTR card inserted and then it doesn't have graphical bugs

**Comment by Stack3r** [comment]
Please test with new nightly, it has a new memory fix and a card removal fix

**Comment by hubert-skowronek** [comment]
The issue still occurs

**Comment by RocketRobz** [comment]
With the AP-patched ROM, there's no issue, if an NTR card is in.
