### ISSUE TITLE
WINTENDOS DLDI

### ISSUE THREAD

**Issue by Daemonspudguy** [ahezard/nds-bootstrap#494]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.14.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
WINTENDOS 2.5
### Expected behaviour
Launches without DLDI errors

### Actual behaviour

Errors occur

### Steps to reproduce

1. Download WINTENDOS rom
2. Put it on SD Card
3. Launch it with your preferred nds-bootstrap frontend

**Comment by RocketRobz** [comment]
I tried 3.0. Works fine there.
Extract this hb bootstrap nightly to `sd:/_nds`, and make sure Bootstrap is set to Nightly in TWLMenu++ settings.
[nds-bootstrap-hb-nightly.zip](https://github.com/ahezard/nds-bootstrap/files/2747328/nds-bootstrap-hb-nightly.zip)

**Comment by Daemonspudguy** [comment]
@Daemonspudguy 3.0 did not work with 0.15.

**Comment by RocketRobz** [comment]
Weird. Works fine with v0.15.0 on my end.
