### ISSUE TITLE
(request) Multiplayer error fixes

### ISSUE THREAD

**Issue by nabilhoche83** [ahezard/nds-bootstrap#496]
Hi, I've been thinking about an improvement for nds bootstrap which is to fix the multiplayer (in some games like Mario Kart ds that stays frozen) because some multiplayer games work well (like zela spirit tracks) but super mario games are left frozen in nintendo to be connected to a console from ds download play mode and it would be a good idea to get to the source of the problem of those games and patch them.
(if you get a translation error I'm sorry for my bad English is that I'm from another language)
(example with image about the error that happens with super mario bros games)
![example](https://user-images.githubusercontent.com/46081056/51018119-d5318180-154c-11e9-8bf6-24f20c079eba.png)

**Comment by NightYoshi370** [comment]
Clone of #553
