### ISSUE TITLE
Heartgold Kris patch dosen't work.

### ISSUE THREAD

**Issue by Office369** [ahezard/nds-bootstrap#497]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ /]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [/ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [/ ]  Release _[v0.15.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokemon Heartgold

### Expected behaviour

The game should boot as normal with the Lyra sprites replaced with the new ones.

### Actual behaviour

The game freezes upon booting to a white screen

### Steps to reproduce

1.Patching a working Heartgold .nds with the kris patch
2.Loading up the game
3.

### Other notes
This is the kris patch I used: https://www.reddit.com/r/PokemonROMhacks/comments/3wxqp9/krisgold_in_heartgold_soulsilver_decapitalization/

**Comment by Office369** [comment]
Fixed

**Comment by ZombHack1000** [comment]
El link del parche está caído
