### ISSUE TITLE
Pokémon SoulSilver graphical glitch

### ISSUE THREAD

**Issue by naphtha41** [ahezard/nds-bootstrap#498]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _v0.15.0_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokémon SoulSilver version
### Expected behaviour

No graphical glitches on previous release

### Actual behaviour

Small graphical glitch since startup, almost bottom top screen, somewhat thin horizontal band of pixels doubled.
### Steps to reproduce

1. Update nds-bootstrap 
2. Use TWiLight Menu++ to load Pokémon SoulSilver
3. Get the glitch

### Other notes

Using latest version of TWiLight Menu++, using the previous version of nds-bootstrap fixes the problem.

**Comment by dubbz82** [comment]
That sounds like the TWL Firm bug.  This happens on occasion with retail games as well.

**Comment by naphtha41** [comment]
I'm not familiar with the bug. Why does it fix when using earlier version though? Just because I rebooted?

**Comment by Volti-p** [comment]
This is random.

**Comment by piratesephiroth** [comment]
just close and open the 3DS again to fix that

**Comment by naphtha41** [comment]
Great, just used the latest version and experienced no problems. Thank you, closing this.
