### ISSUE TITLE
Homebrews that works?

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#5]
This is not a problem but it is useful to keep track of what is working.

Full list of ds homebrews : http://gamebrew.org/wiki/List_of_DS_homebrew_applications

Robz8 maintains a spreadsheet with the compatibility information : https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit?usp=sharing

**Comment by ahezard** [comment]
V0.0.1

- NDS backup tool
- MegaETK
- microcars
- ultimatebattleds
- mugends
- fpmikmod5

**Comment by ahezard** [comment]
It seems that most homebrews from 2008 works

**Comment by ahezard** [comment]
Now the compatibility seems to be around 70%

**Comment by weirdal3333** [comment]
A bunch of cart update *.nds roms work without any issues -- this fixed my r4-gold cart. TYVM!
