### ISSUE TITLE
pokemon blaze black doesnt work anymore (and clean gen5 games)

### ISSUE THREAD

**Issue by coolmccoolsons** [ahezard/nds-bootstrap#500]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[16.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokemon Blaze Black/ Blaze Black 2

### Expected behaviour

Game boots up to title screen

### Actual behaviour

white screen upon opening game

### Steps to reproduce

1.open game
2.
3.

**Comment by RocketRobz** [comment]
Make sure you aren't running the games in DSi mode.
Gen5 Pokemon still works for me.
