### ISSUE TITLE
Bubble Bobble Double Shot: Upper screen is black

### ISSUE THREAD

**Issue by FatKiwi** [ahezard/nds-bootstrap#501]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release 0.16.0
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Bubble Bobble Double Shot

### Expected behaviour

The game screens show normally

### Actual behaviour

Upper screen is completely black

### Steps to reproduce

1. Launch

### Other notes
[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/2779108/NDSBTSRP.LOG)

**Comment by ahezard** [comment]
Issue fixed in 19.2 release
