### ISSUE TITLE
Support for Wood or YSMenu?

### ISSUE THREAD

**Issue by Cee123** [ahezard/nds-bootstrap#503]
What about support for Wood or YSMenu to run via homebrew bootstrap?

What do you think?

**Comment by Cee123** [comment]
Tried creating an image file for both with the new ramdisk feature (which is very impressive by the way!) but neither seem to work that way nor does it seem very feasible. Just thought it would be interesting to try.

**Comment by RocketRobz** [comment]
Did you put the .img files in the `ramdisk` folder, which is in the same folder as the .nds files?

**Comment by Cee123** [comment]
Yeah I tried that it didn't seem to work. Ohh OK interesting. I'll try that then, see if it works. Thanks.

**Comment by Cee123** [comment]
I don't think it works because it's a firmware more than a homebrew.

**Comment by Cee123** [comment]
Not really needed. I've found that the nds bootstrap already does an awesome enough job to cover nearly all the roms I've tried.
