### ISSUE TITLE
Flashcard branch: can't start any game

### ISSUE THREAD

**Issue by TheRamsWay** [ahezard/nds-bootstrap#504]
Tell us which console do you have:

- [x]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### nds-bootstrap version

- [ ]  Release
- [x]  Nightly _[flashcart-wip branch, commit 9a94290d8b8f9e39b6e60561ce7d60110deacc11]_

### If this issue only affects a certain game, which game is it?

It looks like no game can boot, even AP-patched, except Bomberman
I tried with these games:
Bomberman (ABMP-EUR) (SDK 2)
Harry Potter and the Goblet of Fire (AHPP-EUR) (SDK 2, stuck on loading screen)
Pokémon Diamond (ADAF-FRA) (SDK3, loading screen)
Pokémon SoulSilver (IGPF-FRA) (SDK 4, white screen)
Mario Kart DS (AMCP-EUR) (SDK 3, loading screen)
New Super Mario Bros (A2DP-EUR) (SDK 3, white screen)
Tetris DS (ATRP-EUR) (SDK 3, black screen)
Trackmania DS (CTRP-EUR) (SDK 4, white screen)
Nintendogs (AD3P-EUR) (SDK 2, white screen)

### Expected behaviour

Each game should boot

### Actual behaviour

I'm either stuck on the loading screen or on a white (or sometimes black) screen after the loading screen

### Steps to reproduce

Try to boot any game in the list: they stay stuck

### Other notes

At first I thought that only SDK 3 and 4 games couldn't boot as Bomberman is SDK 2 but even Nintendogs and Harry Potter (which are SDK 2 as well) doesn't boot. I basically tried to boot every retail ROM I had on hand but Bomberman seems like the only one to boot for some reason.
I'm using an original R4 flashcard

**Comment by NightYoshi370** [comment]
Hey, would you mind separating the two issues? Instead of making this a general flashcard branch issue thingy, why not make one issue for games that don't boot and one for Bomberman and the soft reset issue?

**Comment by TheRamsWay** [comment]
Yes I can (I thought adding 2 issues at once would be a bit like spamming, sorry).
As it looks like every game except Bomberman can't boot, and that I tried to soft reset on a homebrew (I forgot to mention that), I think these are general issues.

**Comment by FlameKat53** [comment]
For me most of the Nintendogs games work on the latest commit of B4DS... 

All the other games don’t though, I can confirm

**Comment by TheRamsWay** [comment]
I only have Nintendogs Lab & Friends, it stays stuck on the loading screen.

**Comment by RocketRobz** [comment]
A decent number of games work now.
