### ISSUE TITLE
Ramdisk Creation (Linux)

### ISSUE THREAD

**Issue by Xeddius** [ahezard/nds-bootstrap#516]
Could you please post more about the ramdisk specifications/filesystem requirements for the .img?
Linux can create ramdisk images but without knowing the filesystem, block size, and other details, it is of no use for me.

**Comment by manujedi** [comment]
Max. 12MB for dsi, fat16 formatted.
I did it with:
dd if=/dev/zero of=SNES.img bs=1M count=11
losetup -P /dev/loop0 SNES.img
mkfs.fat -F16 /dev/loop0

**Comment by Verequies** [comment]
You can skip the loopback mounting as you can format the image directly. Also count 11 will make the image decimal based 12 MB, where as count 12 will make it binary based 12 MiB.

`dd if=/dev/zero of=SNES.img bs=1M count=12; mkfs.fat -F16 SNES.img`

**Comment by dubbz82** [comment]
Is there anything more needed for this, or can it be closed out?

**Comment by arraystock** [comment]
Perhaps instructions should be added somewhere to prevent this from happening again in the future?

**Comment by FlameKat53** [comment]
is this still relevant?

**Comment by clach04** [comment]
I'm tempted to re-open this as I was unclear on requirements for ramdisk too (I didn't want to have to install Windows software which the wiki mentions.

Is it appropriate to update https://github.com/DS-Homebrew/nds-bootstrap/wiki Homebrew/dldi compatibility? With a note to the effect that:

> RAMdisk images are FAT-16 format. With maximum size of 12MB if you're on DSi, or 28MB if you're on 3DS.
> On Linux a 12Mb image can be created via:
>     dd if=/dev/zero of=FILENAME.img bs=1M count=12; mkfs.fat -F16 FILENAME.img
>
> Where FILENAME should also match the .NDS filename
> For Windows see https://wiki.ds-homebrew.com/twilightmenu/creating-ram-disks


information pooled from:

* https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.16.0
* https://github.com/DS-Homebrew/nds-bootstrap/issues/516#issuecomment-459553449
* https://github.com/DS-Homebrew/TWiLightMenu/wiki/Creating-a-RAM-disk-for-homebrew
