### ISSUE TITLE
Still white screen issues...

### ISSUE THREAD

**Issue by BluntJoy** [ahezard/nds-bootstrap#52]
I have a N3DS running Luma with Al9h and I have had these three games: The legend of zelda: phantom hourglass, the legend of zelda: spirit tracks, and golden sun: dark dawn.
Each one of these games stays on white screen on startup even though I consistently update bootstrap.
Here are my settings:
Language                               System
Color                                      Fuchsia
Menu Color                            White
Show Filename                       Off
Game counter                        Off
Costom Bottom Image          Off
Auto update bootstrap          Off
Auto update latest twloader  Off
Flashcard(s) select                  Off
Rainbow LED                          133mhz (TWL)
ARM9 CPU Speed                   On
VRAM boost                           On
DS/DSi Boot Screen                On
Health and safety message    On
Reset Slot-1                            Off
Console Output                      Off
Lock ARM9 SCFG_EXT            Off

**Comment by Lykie** [comment]
They aren't supported.

**Comment by hectortillo** [comment]
Try with the ones knew to work. Try Super Mario 64. Or Pokemon Mistery Dungeon.  Or also WarioWare.:)

**Comment by Robz8** [comment]
*Mystery

**Comment by BluntJoy** [comment]
Is there a list of known supported games?

**Comment by Robz8** [comment]
https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=0
