### ISSUE TITLE
rom white and black screen release 0.4.0

### ISSUE THREAD

**Issue by killer983** [ahezard/nds-bootstrap#53]
White: New super Mario bros, gta: chinatown wars, ninjatown, tetris party deluxe and sonic colours
Black: fifa 11,

**Comment by Robz8** [comment]
There's a compatibility list:
https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=0

**Comment by killer983** [comment]
Ok

**Comment by Robz8** [comment]
Close this issue as well.
