### ISSUE TITLE
Pokémon White doesn't work.

### ISSUE THREAD

**Issue by Antonio231102** [ahezard/nds-bootstrap#532]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.17.0]_
- [x]  Nightly _[edc51e1]_

### If this issue only affects a certain game, which game is it?

Pokémon White

### Expected behaviour

Game should work normally.

### Actual behaviour

After resuming saved game the game freezes.

### Steps to reproduce

1. Run the game.
2. Select "Continue".
3. Game will be stuck in a white screen.

### Other notes
I've tried both AP patched and clean ROMs but it still doesn't work. Mystery Gift and other options work fine.

**Comment by Stack3r** [comment]
All four of the black and white series games work on the latest unofficial and release bootstrap

**Comment by Antonio231102** [comment]
Indeed! Pokémon White is working for me again, now can close this for good.
If you are readng this, thanks Robz for the new update! :)
