### ISSUE TITLE
Tomodachi Collection not booting

### ISSUE THREAD

**Issue by Unfriended** [ahezard/nds-bootstrap#533]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.17.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Tomodachi Collection

### Expected behaviour

It should show the Nintendo logo, and ask me to set the date and time.

### Actual behaviour

After the loading splash screen, it stays at white.

### Steps to reproduce

1. I have downloaded the rom.
2. I have applied the AP patch using XDELTA Patcher.

### Other notes

It said that it may not be AP-patched.

**Comment by MasterGamingYT** [comment]
Have you tried the English patch yet?

**Comment by dubbz82** [comment]
Regarding the "other notes", this will appear regardless of if a rom HAS actually been AP patched.  It's more of a generic check, rather than determining if an AP patch has in fact been applied.

**Comment by Unfriended** [comment]
Quick edit, I updated TWiLight Menu++ to the latest version, and now it works. Apologies for the interruption. I'm closing this issue right now.

**Comment by Unfriended** [comment]
But thank you for the note, dubbz82.
