### ISSUE TITLE
just wondering since im new

### ISSUE THREAD

**Issue by snes666** [ahezard/nds-bootstrap#535]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by piratesephiroth** [comment]
???

**Comment by snes666** [comment]
did you fix my problem just wondering since I'm new

**Comment by snes666** [comment]
@RocketRobz

**Comment by legoj15** [comment]
Uhh… what exactly is the problem?

**Comment by arraystock** [comment]
Are you referring to #520?

**Comment by snes666** [comment]
yes #520
