### ISSUE TITLE
hombrew installation 

### ISSUE THREAD

**Issue by kingofsteam** [ahezard/nds-bootstrap#536]
### Your console

Tell us which console do you have:

- [x]  Old 3DS/2DS (XL)

## CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS

### nds-bootstrap version

Tell us which versions you are using:

newest Release _[please specify version]_

i have been looking all over the internet for how to install homebrew apps on twilight menu++
but can not find an explanation so i came here. 

keep in mind i am very new to this site and have a Chromebook.
i modded my old 3ds xl in 2018 around august.

if you need more info please ask

**Comment by NightYoshi370** [comment]
a) This isn't related to nds-bootstrap, as its an "issue" you're having with TWiLightMenu++
b) Just put the .nds file and load it using twilight. No need for HBMenu
