### ISSUE TITLE
Metroid Prime Hunters Slow Loading

### ISSUE THREAD

**Issue by RinMaru** [ahezard/nds-bootstrap#538]
N3DSXL Latest FW
B9S Latest
Luma3DS Latest
TWiLightMenu v7.4.1

Metroid Prime Hunters is all the sudden loading very slowly it takes like 5sec for the game to get into the menus after tapping the start screen

**Comment by JeodC** [comment]
The menus have a low FPS and levels take around 30s to load into after selecting.

**Comment by RinMaru** [comment]
Fixed in latest nightly

**Comment by NightYoshi370** [comment]
Does this game use DMA read at all?

**Comment by RinMaru** [comment]
have no clue but the long loading in this and Spectrobes is gone

**Comment by NightYoshi370** [comment]
Wait, why was this reopened?

**Comment by RinMaru** [comment]
So the loading screen in Metroid is better but when I land the ship im faced with a Black screen or a very long load screen.
Still waiting for the game to load

**Comment by NightYoshi370** [comment]
On the latest release, it would work just fine, right?

**Comment by RinMaru** [comment]
ill check cause im using nightly atm and switching the clock speeds just to be sure

**Comment by JeodC** [comment]
Confirmed, I am using the nightly bootstrap build available via TWL++ Updater. The title menu loads slightly faster when navigating menus, but still noticeably low fps. Loading into a level is slower than the title menu navigation, however I am able to load in after about 10 seconds or so on a N3DSXL. Within the levels, doors still take a while to open if the areas aren't preloaded.

**Comment by RinMaru** [comment]
I stayed stuck on a black screen after exiting the ship for 15min before I just turned off the system

**Comment by Stack3r** [comment]
Hopefully this will be fixed with the upcoming sleep code patch

**Comment by ahezard** [comment]
When this started? does the last release have the same issue?

**Comment by RinMaru** [comment]
not sure when the slow loading or the black screen when exiting ship started so I cant say

**Comment by Stack3r** [comment]
Issue is still persistent on nightly

**Comment by RinMaru** [comment]
slow loading is fixed but still freezes to a black screen when I exit ship

**Comment by RinMaru** [comment]
Holding L on startup makes stages load when exiting ship but then makes loading very slow again

**Comment by MojoJojoDojo** [comment]
If i hold L my game will freeze itself near the intro.
without holding L i have missing graphics and non working gameplay.

**Comment by RinMaru** [comment]
> If i hold L my game will freeze itself near the intro.
> without holding L i have missing graphics and non working gameplay.

make sure to give it time. when I said slow earlier i meant slow slow lol unless somthing broke the game im not sure what to tell you

**Comment by ahezard** [comment]
2 things to try : 
1 - try to decrease the size of the cache / use much bigger slot size
2 - Restoring synchronous direct read without caching (when possible, arm7 directly reading to the destination address in a synchronous mode without copy somewhere)

**Comment by NightYoshi370** [comment]
Apparently, this is fixed on the latest nightly. I guess we could leave this open until release

**Comment by Stack3r** [comment]
Yeah it’s still having some small issues

**Comment by ahezard** [comment]
I would say it is mostly fixed with dd2f29dba182feadb434da00d22f1f8f7d5f926b , at least this is not anymore a regression compared to old bootstrap version and I do not consider this as a major bug anymore.
