### ISSUE TITLE
rom Error reading data release 0.4.0

### ISSUE THREAD

**Issue by killer983** [ahezard/nds-bootstrap#54]
Tetris ds

**Comment by killer983** [comment]
![1486661277484-1730672710](https://cloud.githubusercontent.com/assets/25202703/22795044/89cacaa0-eef5-11e6-81ac-641874488a05.jpg)

**Comment by Robz8** [comment]
Do you have a Slot-1 card inserted?

**Comment by killer983** [comment]
Yes slot-1

**Comment by Robz8** [comment]
Try taking it out.

**Comment by killer983** [comment]
I already know what the problem with the game is
Game is dagame

**Comment by Robz8** [comment]
?
Did you set a donor rom?

**Comment by killer983** [comment]
I have a cartridge and an internet

**Comment by Robz8** [comment]
If you don't want to set a donor rom, wait for a new bootstrap update, where a donor rom is not needed at all.

**Comment by killer983** [comment]
Ok
