### ISSUE TITLE
WALL-E: Freezes with black screen on intro video

### ISSUE THREAD

**Issue by JonArcherII** [ahezard/nds-bootstrap#540]
### Your console

Tell us which console do you have:

- [x]  Old 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.17.1]_
- [x]  Nightly _[08009e672ca03e55ac50175b14bea99136f3004e]_

### If this issue only affects a certain game, which game is it?

WALL-E (YWLE)

### Expected behaviour

Intro video begins to play after selecting new game

### Actual behaviour

Game freezes on black screen

### Steps to reproduce

1. Launch game (TWiLight Menu)
2. Tap the screen to continue to the menu
3. Press `A` on 'New Game'

### Other notes

I don't believe it's AP related, because it runs perfectly fine on a flashcart. ~~I can't test it with NO$GBA right now, but it might be related to dma.~~ Does not seem to be dma related.

**Comment by ahezard** [comment]
This game have a lot of different releases (9). Which one are you testing (I need the release number)?

**Comment by ahezard** [comment]
I repoduced the issue and as mentionned it is not dma related

**Comment by arraystock** [comment]
I’m away from home right now, in a few days I could let you know. How do I find the release number?

**Comment by dubbz82** [comment]
Since it's been replicated, I'd guess the release number probably doesn't matter as much, I'd presume it's probably the same issue, even if it's a different release of the same game.

**Comment by dubbz82** [comment]
dumb curiosity, can this be replicated after latest build since memcopy changes were made?

**Comment by arraystock** [comment]
@ahezard is this possibly related to #558?

**Comment by arraystock** [comment]
@dubbz82 Still happens on the latest nightly.

**Comment by ahezard** [comment]
the error of wall e seems different than ratatouille : 

Fatal Error: ARM9CPU stopped running because "Data access exception" occurred. ]]

   Symbol: STATIC:0x020211CC
   020211CC:  247692FA       ???

   CPSR:6000001F
     R0:01FFB274  R1:027E3FFC  R2:0215C4C0  R3:0214B680
     R4:00000020  R5:00000000  R6:00000000  R7:00000000
     R8:00000000  R9:00000000 R10:00000000 R11:00000000
    R12:07000400  SP:027E377C  LR:02000910  PC:020211CC

**Comment by dubbz82** [comment]
Still seems to happen on latest nightly.

**Comment by SleepyLark** [comment]
Has anyone tested this on v0.30.0 yet?  I would do it but can't at the moment

**Comment by JonArcherII** [comment]
I’ll give it a shot once I’m home

**Comment by JonArcherII** [comment]
Yep! It now runs as expected. I never realized how extensively this game uses soft-resetting :^)
