### ISSUE TITLE
Bootstrap Whitecreen for AP Patched Games

### ISSUE THREAD

**Issue by MysticPenguin3** [ahezard/nds-bootstrap#546]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.17.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

I've tested Pokemon HG, SS, B, W, B2, and W2

### Expected behaviour

The ap patching message will come up and then the game will play normally

### Actual behaviour

The ap patching message will come up but the game will freeze on a white screen on the top and bottom.

### Steps to reproduce

1. Load any ap patched pokemon game
2. press a or b on the ap patching notice
3. stare in wonder at your white screen of death

### Other notes
TWLMenu ++ Version 7.4.1

I've tried patching the games with multiple programs, multiple patches, and multiple roms, downloaded and dumped right from the card. The unpatched games are white screens and the patched games are also white screens. I have used all of the patches from the AP Patch Preservation thread, as well as DS Scene Rom Tool, xdelta, and OpenPatch. Games that don't require AP patches work fine, but the ones that do wont load with or without the patch. Not sure if it is like this for other games, but I don't own them myself. 
![img_0888](https://user-images.githubusercontent.com/47903355/53273589-65252800-36c2-11e9-8769-841950f2584a.jpg)
![img_0889](https://user-images.githubusercontent.com/47903355/53273590-65bdbe80-36c2-11e9-8e0f-c67a94be4e47.jpg)
![img_0890](https://user-images.githubusercontent.com/47903355/53273591-65bdbe80-36c2-11e9-9560-69086cc387a1.jpg)
![img_0891](https://user-images.githubusercontent.com/47903355/53273592-65bdbe80-36c2-11e9-8dcf-a3989e8f5cbf.jpg)

**Comment by RocketRobz** [comment]
Are you running the games in DS mode, and not DSi mode?

**Comment by MysticPenguin3** [comment]
They are being run in DSi mode. Should I change it to forced?

**Comment by RocketRobz** [comment]
No. Change it to DS mode.

**Comment by MysticPenguin3** [comment]
I changed it to DS mode and now the game is loading. I'll message again when I can be sure the AP patch is working properly. Thanks!
