### ISSUE TITLE
Dragon Ball Z - Supersonic Warriors 2 wont work

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [ahezard/nds-bootstrap#548]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.17.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Dragon Ball Z - Supersonic Warriors 2 (USA)

### Expected behaviour

Tell us what should happen

### Actual behaviour

the game says the gamecard removed.

### Steps to reproduce

1.
2.
3.

**Comment by Volti-p** [comment]
Fixed in latest Nightly.

**Comment by TheOneEyedGrimReaper** [comment]
> ly.

where to download the latest nightly?

**Comment by FlameKat53** [comment]
https://github.com/TWLBot/Builds/releases/download/v20190227-013443/nds-bootstrap.7z

**Comment by Volti-p** [comment]
download it with the TWL Menu++ Updater (From the 3DS). It works for me.

**Comment by TheOneEyedGrimReaper** [comment]
> https://github.com/TWLBot/Builds/releases/download/v20190227-013443/nds-bootstrap.7z

thanks bro.
it works with this.
