### ISSUE TITLE
Yoshi's Island DS Artifacting

### ISSUE THREAD

**Issue by LividJava** [ahezard/nds-bootstrap#551]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (Non-XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch+HiyaCFW _[Unlaunch 1.8 HyiaCFW 1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.17.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Yoshi's Island DS

### Expected behaviour

Game should run cleanly and with no artifacting.

### Actual behaviour

Gameplay is okay (tested until 1-2 before i noticed the main issue), Pause menu appears to be [artifacting](https://imgur.com/G7xhZa9) making some elements illegible 

### Steps to reproduce

1. Create a new game save
2. Load a Level
3. Open Pause Menu

**Comment by Stack3r** [comment]
This should be resolved as of the latest nightly, please test

**Comment by LividJava** [comment]
is this nightly build 279a9cc ?

**Comment by Stack3r** [comment]
It should be

**Comment by LividJava** [comment]
The issue persists.

**Comment by Volti-p** [comment]
https://github.com/TWLBot/Builds/blob/master/nds-bootstrap.7z  Download this build and test it.

**Comment by LividJava** [comment]
That build does solve the problem
