### ISSUE TITLE
Orcs & Elves - Black Screen

### ISSUE THREAD

**Issue by sweetpalma** [ahezard/nds-bootstrap#552]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]   (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only DSI v1.8
- [ ]   Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release v0.17.1.
- [ ]   Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Orcs & Elves (both USA and PAL versions).

### Expected behaviour

Game should start.

### Actual behaviour

Black screen instead.

### Steps to reproduce

1. Upload ROM to the SD card
2. Find it in the game list
3. Launch

### Other notes

Tried different modes - forcing both NDS/NDSi modes, different bootstrappers - nothing worked. Damn, that's my favourite NDS game so far, is there any way to fix this?

**Comment by ahezard** [comment]
This issue is not dma related

**Comment by ahezard** [comment]
the game is not bakc screening on master. Try the latest nightly.

**Comment by sweetpalma** [comment]
@ahezard Hmm, thanks. Just a small question - is there any place where I can download latest nightly without need to build repo myself?

**Comment by NightYoshi370** [comment]
@TWLBot's build repository has it

**Comment by sweetpalma** [comment]
Okay, I tried nds-bootstrap.7z from it, unpacked, copied `nds-bootstrap-nightly.nds`, `nds-bootstrap-hb-nightly.nds` and `nightly-bootstrap.ver` to their respective places on `_nds` folder. Set up `Nightly` in a `Bootstrap` option - still does not work, black screen. Am I missing something?

**Comment by ahezard** [comment]
(No CFW) Unlaunch only DSI v1.8 could be the issue. Please try to setup Unlaunch+HiyaCFW

**Comment by sweetpalma** [comment]
Tried - it really works now. Thanks!
