### ISSUE TITLE
Pokemon Mystery Dungeon 2: Explorers of Sky (E) save problem

### ISSUE THREAD

**Issue by muriloalpeixoto** [ahezard/nds-bootstrap#555]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[0.17.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokemon Mystery Dungeon 2: Explorers of Sky (E)

### Expected behaviour

The game should've mantained the save so I could have load it after.

### Actual behaviour

The game acted like there wasn't a save at all when I rebooted it.

### Steps to reproduce

1. Save the game.
2. Close it.
3. Open it again and the save will not be there.

### Other notes
The game created a 0 kbytes file on the saves folder and generated another save (with a normal file size) on the roms folder (which appears to be the initial one, because of the time windows says it was created). Also, when I tried to save again on the first opportunity the game gives and reboot it, it worked fine.

**Comment by TheRedMajora** [comment]
Same happens to me in both Explorers of Sky and in Zelda: Phantom Hourglass

**Comment by RocketRobz** [comment]
@TheRedMajora What theme are you using in TWLMenu++?

**Comment by TheRedMajora** [comment]
Mainly the Acekard (zelda).
I’ve had more luck getting the cheats to run on R4, but my main problem is
that I have to ‘randomly’ tweak settings every launch and it only seems to
work when specific cheats are on. (But sometimes it won’t work even with
all the cheats on (When it works with the specific ones tho, all the others
still work ingame, so they’re not bad codes.))

**Comment by ahezard** [comment]
If it is linked to a theme it cannot be nds-bootstrap related.
