### ISSUE TITLE
Problems with 0.17.1

### ISSUE THREAD

**Issue by khonshuknight** [ahezard/nds-bootstrap#556]
Having problems running mega Man zx Advent on my n2ds/n3ds running on luma. When choosing the male character, can't start the actual game as it freezes. The female works fine. 

Lunar knights also has problems. The images during dialogue sequences don't show but the dialogue does. 

Lastly, dragon quest IV has issues with the intro movie has screen tearing.

**Comment by ahezard** [comment]
Are these problems present with latest nightly?

**Comment by khonshuknight** [comment]
I'll try the nightly as soon as I get home and will let you know. Usually
only do standard releases

**Comment by ahezard** [comment]
we have included a lot of fixes lately. I am not able to reproduce the Lunar knights issue with nightly.

**Comment by khonshuknight** [comment]
I'm not seeing a link to nightly releases

**Comment by chyyran** [comment]
https://github.com/TWLBot/Builds/releases

**Comment by ahezard** [comment]
mega Man zx Advent also does not have issues on nigthly

**Comment by ahezard** [comment]
dragon quest IV intro movie have screen tearing indeed

**Comment by ahezard** [comment]
dragon quest IV issues is mot probably linked to #517

**Comment by khonshuknight** [comment]
Gameplay seems fine on DQ I'm not sure if there are cutscenes later in game
but those might be affected as well

**Comment by ahezard** [comment]
This DQ IV issue have always been there it seems according to the compatibility list : "Works. Has flickering at the title screen but other than that the game works"
Was it working better with an earlier version of nds-bootstrap?

**Comment by khonshuknight** [comment]
Honestly it's my first time testing it. Most of the other games are for a
friend who I've modded his 3ds for. Figured I'd join up to help notify
problems

**Comment by khonshuknight** [comment]
Last thing so I can check everything. Do I have to delete any files before
putting the nightly in the _nds folder?

**Comment by RocketRobz** [comment]
@khonshuknight No.

**Comment by khonshuknight** [comment]
I put the latest nightly (came out 20 odd days ago) in the _nds folder with
the nds-bootstrap-hb-release and nds-bootstrap-hb-release .NDS files and it
still frozen on mega Man zx Advent

**Comment by RocketRobz** [comment]
Use this build: https://github.com/TWLBot/Builds/releases/download/v20190305-214049/nds-bootstrap.7z
Switch Bootstrap to Nightly in TWLMenu++ settings.

**Comment by khonshuknight** [comment]
Sorry to be a pain in the ass I'm learning as I go. I'm in the twilight
menu settings and trying to locate a way to switch to nightly.

**Comment by RocketRobz** [comment]
Switch to Games/Apps page.

**Comment by khonshuknight** [comment]
So I set nightly on his n3ds and now mega Man seems to hang on a black
screen before the initial intro cinematic prior to the start menu. Aside
from changing to nightly in the menu, are there any other changes to
settings I should make?

**Comment by RocketRobz** [comment]
No.

**Comment by RocketRobz** [comment]
No.
Try launching it again. The black screen only happened once for me so far.

**Comment by khonshuknight** [comment]
Nope, consistent black screen on 2 different systems

**Comment by RocketRobz** [comment]
Hmm. After launching it with A button, hold L before the game boots.

**Comment by khonshuknight** [comment]
Same issue. Black screen after the inti creates logo

**Comment by RocketRobz** [comment]
I mean hold L immediately after pressing A.

**Comment by RocketRobz** [comment]
Oh wait, what theme are you using in TWLMenu++?

**Comment by khonshuknight** [comment]
One has 3ds and one has dsi

**Comment by RocketRobz** [comment]
Ok, so as of recent commits, I'm also getting the consistent black screen now.

**Comment by khonshuknight** [comment]
Okay. Just found out even the other characters story freezes, just a little
bit later.

**Comment by DMSalesman** [comment]
Just for the record, there are screen tearing issues with apfixed DQVI as well. Not sure about them depending on 0.17.1.

**Comment by khonshuknight** [comment]
Nightly 9277ccb seems to have fixed the issue with ZX Advent. Played both
characters and beat the first boss with no issues for a test run. This also
fixed an issue with lunar knights and Pokemon conquest that had some double
graphic issues I noticed recently.

**Comment by RocketRobz** [comment]
The double graphic issue comes from TWL_FIRM, not nds-bootstrap, and happens randomly.

**Comment by khonshuknight** [comment]
Got it. But so far the lastest nightly has all the former issues fixed.

**Comment by ahezard** [comment]
Is this issue still present?

**Comment by RocketRobz** [comment]
Aside from Dragon Quest IV, they don't occur now.
