### ISSUE TITLE
Find out what prevents ROM hacks from functioning correctly

### ISSUE THREAD

**Issue by shutterbug2000** [ahezard/nds-bootstrap#56]
Currently, it seems as though rom hacks of most games don't work.

**Comment by WubTheGame** [comment]
i'd greatly appreciate to know the answer to this too, because i want to be able to play MKDS and SM64 Romhacks

**Comment by Robz8** [comment]
They have different card read signatures, which nds-bootstrap currently don't support.

**Comment by WubTheGame** [comment]
dang. also, when will the next bootstrap update be?
