### ISSUE TITLE
pokemon white 2 black screen 

### ISSUE THREAD

**Issue by Vegeta780** [ahezard/nds-bootstrap#562]
hi am using N3ds Luma BS9 
i have R4isdhc Card from DS Lite 
my Pokemon W2 is Working fine with Card 3ds But When i 
Twliligh Menu++ >Start Game Card > Game > Pokemon W2 Play > after prof Intro show Black Screen...
is it problem with Twliligh Menu++ or nds-bootstrap i dont know ?? Thanks

**Comment by Volti-p** [comment]
Do you have an AP Patch on it? Are you on the latest NDS-Bootstrap Version?

**Comment by Vegeta780** [comment]
Yes and Yes

**Comment by coolmccoolsons** [comment]
set it to ds mode

**Comment by Vegeta780** [comment]
not working sir, lets go pkn world then black screen

**Comment by RocketRobz** [comment]
This isn't an issue with either app.
It's an issue with your flashcard firmware.
