### ISSUE TITLE
0.17.1 No Games Load

### ISSUE THREAD

**Issue by jewelforest** [ahezard/nds-bootstrap#563]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_ 0.17.1
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen
Clicking on a game should launch

### Actual behaviour

Tell us what happens instead
Stuck on white screen when clicked, no matter what game it is

### Steps to reproduce

1. Attempt to launch a game
2.
3.

### Other notes
Previous versions of nds-bootstrap work with my games (I downgraded to 0.13.0 since thats what I had before updating)

**Comment by RocketRobz** [comment]
Which games aren't working?

**Comment by jewelforest** [comment]
The ones I have are:
Jewelpet: Cute Magical Fantasy
Jewelpet: Magical DS Kirapi Kariin
Jewelpet: Let's Play Together in the Room of Magic!
Pokemon Black
Pokemon Black 2
Pokemon Heartgold
Pokemon Pearl
Dogz
Dogz 2
Bunnyz
Diary Girl
Hamsterz
Hamsterz Life
Pic Pic
Princess Debut
Bratz Ponyz
Littlest Pet Shop Beach Friends

None of those work on latest version, but do work on previous versions.

**Comment by RocketRobz** [comment]
Make sure DS mode is set in TWLMenu++ settings, instead of DSi mode (Regular or Forced).

**Comment by jewelforest** [comment]
I used DS Mode.

**Comment by jewelforest** [comment]
I have double checked to make sure it is DS mode, and it still gives the same result. There is no "loading" splash, it is just white until I press the home button to close Twilight Menu.

**Comment by RocketRobz** [comment]
Try deleting `nds-bootstrap.ini` at `sd:/_nds`.

**Comment by jewelforest** [comment]
Unfortunately, that does not help.. What else is there to try?

**Comment by JeodC** [comment]
No loading splash tells me you might have a corrupt bootstrap. Try redownloading it from TWL Updater.

**Comment by Stack3r** [comment]
Just to double check, I tested multiple games above on latest release and nightly and I had no issues, it’s definitely something on your end, try what JeodC said and redownload bootstrap, if that doesn’t work try to reinstall the whole thing. (Twlmenu++ and _nds folder)

**Comment by jewelforest** [comment]
Where do I get the rest of the twilight menu and _nds files? Sorry, I have not updated this in a long time, so I forgot things.

**Comment by RocketRobz** [comment]
Update using the updater.

**Comment by jewelforest** [comment]
https://github.com/RocketRobz/TWiLightMenu-Updater/releases
This is the correct one?

**Comment by MasterGamingYT** [comment]
yes

**Comment by jewelforest** [comment]
Updater app works. I have been updating manually, so I think that was the issue.
