### ISSUE TITLE
No games loading on DSI 0.17.1

### ISSUE THREAD

**Issue by semmeess** [ahezard/nds-bootstrap#564]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x ]  Unlaunch+HiyaCFW _[please specify versions of both]_
Unlaunch 1.8, The version of HiyaCFW delivered to me by launcher version 3.0.1 on the 13th of March 2019

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release 0.17.1
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Tetris
Elektroplankton
Pokemon white
Advance wars: Days of ruin
Puyo Pop Fever
All NDS roms

### Expected behaviour

The games should launch

### Actual behaviour

The save file is successfully created, the loading screen shows, then just white screen. Waited 10 minutes for each game, no result.
EUR DSI, set up with the steps on https://dsi.cfw.guide/installing-hiyacfw.html
I've tried enabling/disable DSI mode, playing with ,
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
Reformating my 4gb SDHC card to FAT32 32kb whatever,
Setting up a file structure with my twilightmenu boot.nds in the root folder, with the NDS roms in the roms/nds folder,
Enabling DEBUG mode for NDS bootstrap (No issues in the pre launch output),
Trying multiple regions, patched, unpatched.
None of these games work, I tried puyo-puyo fever as its listed as working with the DSI on the comparability list, however shouldnt at least one of the others work?
I understand to expect low compatability with the DSI, just wondering if there's anything else you think I should/could try to fix this?

### Other notes

Thanks very much for your help!

**Comment by RocketRobz** [comment]
I replied to you on GitHub,

**Comment by RocketRobz** [comment]
Issue solved over at Discord.

**Comment by semmeess** [comment]
FOR THOSE OF YOU WHO ALSO HAVE THIS PROBLEM - 
Make sure your unlaunch is auto booting hiyacfw, then hiya is autobooting twilight.
