### ISSUE TITLE
Blood of Bahamut does not save

### ISSUE THREAD

**Issue by piratesephiroth** [ahezard/nds-bootstrap#569]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[please specify version]_
- [ x]  Nightly _046018e_

### If this issue only affects a certain game, which game is it?

Blood of Bahamut

### Expected behaviour

Savedata should work,

### Actual behaviour

Savedata doesn't work.

### Steps to reproduce

1. Begin the game, complete the first basic mission and save.
2. The game says it saved fine, no error is displayed
3. Reset the game and see nothing has been saved.

**Comment by ahezard** [comment]
The save patch is not reporting any error : 
Arm7 (patch vAll)
Relocation src: 023801E8
Relocation dst: 037F8000

JumpTableFunc: 0238B5BC
Eeprom read:	0238B5C8
Eeprom page write:	0238B5DC
Eeprom page prog:	0238B5F0
Eeprom verify:	0238B604
Eeprom page erase:	0238B614
ERR_NONE

**Comment by piratesephiroth** [comment]
I though it could be AP but if it is then it's something that flashcards do not trigger.

**Comment by ahezard** [comment]
Please provide a valid save data for debug purpose.

**Comment by piratesephiroth** [comment]
Perhaps it's an issue with the translation patch then? It does save fine on emulators.
I'll test later, both the original and patched roms.

**Comment by piratesephiroth** [comment]
Oh, okay.
I tried with the original unpatched rom and it still doesn't save.

**Comment by Omnija** [comment]
you need to use the patch v1.05 for saving to work.

**Comment by piratesephiroth** [comment]
I just noticed it's not a problem with saving, it's actually a problem while loading the save data.

I copied the .sav file from the SD card to the PC and the game on DeSmuME was able to load it.
I also copied DeSmuME savedata to the SD card and nds-boostrap still loaded nothing.

**Comment by ahezard** [comment]
I suppose you are  using this patch https://gbatemp.net/threads/released-blood-of-bahamut-english-patch.283764/ ? Which version of the patch are you using?

**Comment by ahezard** [comment]
As mentionned the game does load the save if patched with that http://www.mediafire.com/download/3hgw71hu8u1qfu9/bahamut1.05.rar

So I assume this is AP. Closed.

**Comment by piratesephiroth** [comment]
I'll test this version of the patch however the original japanese game can't load the save data so there is a problem
