### ISSUE TITLE
Add nitrohax-based cheat capabilities

### ISSUE THREAD

**Issue by shutterbug2000** [ahezard/nds-bootstrap#57]
Eventually, integrate Nitrohax's cheat engine for retail games

Alternative until this is implemented : https://gbatemp.net/threads/ds-auto-trainer-maker-dsatm.80540/

**Comment by ahezard** [comment]
The cheat engine is written in asm and is here : 
https://github.com/ahezard/NitroHax3DS/blob/master/BootLoader/source/cheat_engine.s

**Comment by ahezard** [comment]
The nds-bootstrap card_engine was originally based on the Nitrohax cheat engine so it should be easy to integrate it
https://github.com/ahezard/nds-bootstrap/blob/master/cardengine_arm7/source/card_engine_header.s

**Comment by ahezard** [comment]
The irq hooking mechanism fron NitroHax is also used in nds-bootstrap, in an improved version but that should be compatible : https://github.com/ahezard/NitroHax3DS/blob/master/BootLoader/source/cheat.c

**Comment by ahezard** [comment]
The integration can be done like that : 
get the cheatData from the nds-boostrap ini file in the arm9 main binary
Pass the cheatData to the arm7 bootloader as it is done in NitroHax
Pass the cheatData from the arm7 bootloader to the arm7 card_engine as an additional argument
Integrate cheat_engine.s into arm7 card_engine_header.s

**Comment by ahezard** [comment]
This will work via an option in the INI file. 

Todo : check the maximum lenght of a string in the ini file

[NDS-BOOTSTRAP]
...
CHEAT_DATA = 94000130 FCFB0000 023FE074 012FFF11 E0000000 000000A8 E28F0001 E12FFF10 A21AB5F0 88234C24 80138811 D02A428B 25803490 F0002000 1C06F82A F0002004 2703F826 21404007 D003420B 420B2180 E018D00C 4231210C 2F03D006 1C79D013 F0002004 E00EF816 E0094331 438E210C 2F001C31 1E79D004 F0002004 E002F80A F0002000 BCF0F806 4718BC08 30800000 88222100 D1FC422A 80224A08 88208060 D1FC4228 80220C12 88228061 D1FC422A 21FF8860 47704008 04000130 80028802 023FE074 E3520003 D2000000 00000000

**Comment by ahezard** [comment]
Max length of a cheat is 256

**Comment by ahezard** [comment]
Now it works on the cheat branch

**Comment by piratesephiroth** [comment]
Are you sure this works?
The codes are getting added to nds-bootstrap.ini however I can never notice any effects on the games.

**Comment by ahezard** [comment]
Which game? SDK2-4 or SDK5?
I have tested with mario kart ds back then : it was working

It may have been broken in the latest release though or maybe sdk5 have issue.

**Comment by piratesephiroth** [comment]
Hmm... this is funny...
I tried with Castlevania Dawn of Sorrow (SDK 2) and Solatorobo Red the Hunter (SDK 5) and it didn't work.
I tried with Castlevania Order of Ecclesia (SDK4) and it works!

**Comment by ahezard** [comment]
thanks for reporting this nug. Are this kind of code working with nitrohax?

**Comment by ahezard** [comment]
can you post some code example? xml + cheat_data generated in the ini file

**Comment by piratesephiroth** [comment]
I never used nitrohax before and I don't have a DS flashcard at the moment.
The original readme for nitrohax claims that it supports all the standard Action Replay DS code types so the codes I tested  should work. Plus they're included in the cheatdatabase you have available in the NitroHax3DS release.

For example, the "'Moon Jump" code for Castlevania Dawn of Sorrow (U)
```
94000130 FFFD0000
020CA96C FFFFB1D5
D2000000 00000000
```
Apparently only the second line is interpreted and our character gets blasted upwards

And the "Move 4x faster" code, for the same game
```
521F6854 E0800006
021F6854 E0800106
D2000000 00000000
```
This one seems to be entirely ignored


Also DSIMenu++ is weird and can't read subfolders in the cheat database so we must make a simpler file just for using with it.

**Comment by piratesephiroth** [comment]
xml example

```
<?xml version="1.0" encoding="UTF-8"?>
<codelist>
	<game>
		<name>Castlevania - Dawn of Sorrow (U)</name>
		<gameid>ACVE 9a6b468a</gameid>
		<date>2018/06/20 15:01</date>
		<cheat>
			<name>Moon Jump</name>
			<note>Only works on Default button mapping</note>
			<codes>94000130 FFFD0000 020CA96C FFFFB1D5 D2000000 00000000 </codes>
		</cheat>
		<cheat>
			<name>Julius Mode 4x Speed</name>
			<codes>521F6854 E0800006 021F6854 E0800106 D2000000 00000000 </codes>
		</cheat>
	</game>
</codelist>
```

**Comment by ahezard** [comment]
I close in favor of #200

**Comment by barringtonluke98** [comment]
So I'm a little confused. Are the codes working on any games? Also where do i put the cheats.xml for it to be read?

**Comment by piratesephiroth** [comment]
- The file is called "cheats.xml" and should be placed in the `_nds` folder.
- It has no option for enabling or disabling cheats so it will just read all you put there for the game.
- The maximum length is 255 characters so it can accept up to 31 codes per game.
You can create the file with [ARDS Code Editor](http://projects.sappharad.com/tools/ards_editor_exe.zip) or [R4CCE](http://hp.vector.co.jp/authors/VA013928/bin/r4cce086.zip). It can't have subfolders so you must add the codes right after adding the game.

Now the problem is that only 'constant write' codes are working as expected (codes beginning wth 0, 1 or 2). Patch codes have no effect at all and conditional codes seem to malfunction as well.

**Comment by piratesephiroth** [comment]
Updatedd the cheats.xml example. Added a sample patch code for quick testing that should replace  "Start" with "CHEAT" on the data management screen.

![pic](https://i.imgur.com/Umy0E0M.png)

**Comment by kimstraza** [comment]
does this work if the games are booted from sd card? i don't have a physical cart and some content are locked behind online play

**Comment by MojoJojoDojo** [comment]
Add dsiware cheats support too.

**Comment by kimstraza** [comment]
The file is called "cheats.xml" and should be placed in the _nds folder.
It has no option for enabling or disabling cheats so it will just read all you put there for the game.
The maximum length is 255 characters so it can accept up to 15 code lines (8 bytes/16 characters each) per game.
You can create the file with ARDS Code Editor or R4CCE. It can't have subfolders so you must add the codes right after adding the game.

i met all of the above condition but i can't launch the game without a catridge in my sd card
