### ISSUE TITLE
Pokemon White won't launch

### ISSUE THREAD

**Issue by percy511** [ahezard/nds-bootstrap#572]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.17.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokemon White

### Expected behaviour

Game should launch up

### Actual behaviour

After loading is finished, 3DS is left at a white screen

### Steps to reproduce

1. Select Pokemon White Rom in TWiLight Menu
2. Wait for loading to finish
3. White Screen

### Other notes
This rom worked before, but after the most recent update of TWiLightMenu++ and nds-bootstrap I've been stuck at this white screen. I've tested my other roms (Pokemon Platinum and Pokemon SoulSilver) and they have been fine.

**Comment by percy511** [comment]
1. Forgot to add log. Here it is.
2. I did test it on the nightly build but the same thing happened.
[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/2985327/NDSBTSRP.LOG)

**Comment by FlameKat53** [comment]
hello, did you run this in DS Mode or DSi Mode? You set this in TWiLight Menu++

**Comment by percy511** [comment]
I ran it in DSi Mode

**Comment by edo9300** [comment]
Twl games have to be run in ds mode

**Comment by percy511** [comment]
Oh, I guess I must have missed that in some of the documentation. It worked though, so thanks!
