### ISSUE TITLE
Fire Emblem: Heroes of Light and Shadow loads to whitescreen

### ISSUE THREAD

**Issue by diedricm** [ahezard/nds-bootstrap#574]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _17.1_
- [X]  Nightly _17.1_

### If this issue only affects a certain game, which game is it?

Fire Emblem: Heroes of Light and Shadow
Tested:
 - - Clean jap 128MB rom
 - - Above version ap patched using Scene Rom Tool
 - - Rnglish patch 3.1 applied to both above

### Expected behaviour

Game starts

### Actual behaviour

After loading screen the system is stuck in whitescreen

### Steps to reproduce

1. Get basically any dump of the game you can find
2. Try to launch it
3. Profit

### Other notes

- Tested Release and Nightly
- Tested NTR and TWL frequencies
- Tested in DSi mode
- Using TWiLightMenu 7.4.1

**Comment by RocketRobz** [comment]
`Tested in DSi mode`
There's your issue. DSi-Enhanced games don't work in DSi mode yet.
