### ISSUE TITLE
Super Mario 64 DS Crash After Logo

### ISSUE THREAD

**Issue by YESPLZOK** [ahezard/nds-bootstrap#576]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[latest]_
- [x]  Nightly _[latest]_

### If this issue only affects a certain game, which game is it?

Super Mario 64 DS

### Expected behaviour

The game should run normally.

### Actual behaviour

The game gets to the Nintendo logo screen, but freezes on a black screen after it fades away.

### Steps to reproduce

1. Launch SM64DS (v1.0 I think)
2. Wait until the Nintendo logo disappears
3. The game will freeze on a black screen

### Other notes
- TWiLight Menu was used 
- Cheats were off
- The settings were the default ones, Old 3DS/2DS was selected initially upon TWiLight's setup

**Comment by YESPLZOK** [comment]
i dont want cfw

**Comment by RocketRobz** [comment]
CFW is the way to go. You won't brick by installing it on your DSi.
Without CFW, some games won't work properly.

**Comment by NightYoshi370** [comment]
Uh, he wasn't talking about the DSi. He was talking about the 3DS.
Why would he need CFW on the 3DS to use nds-bootstrap?

Although, @YESPLZOK, any specific reasons as to why you don't want CFW?

**Comment by YESPLZOK** [comment]
@NightYoshi370 I don't want CFW because I don't want to accept any of the potential risks of having/getting it. (I want to play things safe)

**Comment by Volti-p** [comment]
A CFW nowadays is safe, as Long you don't cheat online.

**Comment by YESPLZOK** [comment]
@RocketRobz Oh yeah, I forgot something. When TWiLight Menu was still named SRLoader, SM64DS ran perfectly fine with Sudokuhax on my 3DS

**Comment by RocketRobz** [comment]
Try this nightly build:
[nds-bootstrap-nightly.zip](https://github.com/ahezard/nds-bootstrap/files/3005878/nds-bootstrap-nightly.zip)
SM64DS works fine for me on Sudokuhax.

**Comment by YESPLZOK** [comment]
Huh, the game still gets stuck with the linked bootstrap. Which game versions do you know that work?

**Comment by RocketRobz** [comment]
Did you switch Bootstrap to Nightly in the TWLMenu++ settings?

**Comment by YESPLZOK** [comment]
I'm pretty sure I did, on the settings menu I saw the word Nightly in a corner and the version thing next to it

**Comment by RocketRobz** [comment]
Your save file might be corrupt then.

**Comment by YESPLZOK** [comment]
Should I just try to delete the save file from the SD Card?

**Comment by RocketRobz** [comment]
Probably.

**Comment by YESPLZOK** [comment]
For some odd reason, it still didn't work after I deleted the save.

**Comment by RocketRobz** [comment]
fyi, I use the ROM with release number 0056.

**Comment by YESPLZOK** [comment]
How do you find the release number?

**Comment by RocketRobz** [comment]
The ROM has to be a scene dump to contain it.
Search for `0056 - Super Mario 64 DS (v01) (U)(Trashman)`

**Comment by YESPLZOK** [comment]
I just tried that, but the game still won't run for whatever reason.

**Comment by legoj15** [comment]
Are you running the game under NDS mode? For me, TWL Mode (forced) has issues for me with SM64DS.

**Comment by YESPLZOK** [comment]
Yes, I'm running the game under NDS mode.

**Comment by YESPLZOK** [comment]
@RocketRobz I have another question, does my SD Card have to do with anything? Mine's a 2 GB Toshiba one found in old 3DSes.

**Comment by RocketRobz** [comment]
No, it doesn't.

**Comment by YESPLZOK** [comment]
Idk what to do now, so I guess I'll give up or test the game when the next bootstrap comes out

**Comment by YESPLZOK** [comment]
I'm going to wipe every TWiLight Menu related thing off my sd card then I'll try to reinstall it. I'll report back whatever happens

**Comment by YESPLZOK** [comment]
@RocketRobz I dumped a rom from my own cart but that the game still got stuck at the logo
