### ISSUE TITLE
Issues with Club Penguin - Elite Penguin Force

### ISSUE THREAD

**Issue by sonicfan2007** [ahezard/nds-bootstrap#577]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x] Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x] Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _0.17.1_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Club Penguin - Elite Penguin Force

### Expected behaviour
 
It should run normally
### Actual behaviour

Sprites from top screen appear on bottom screen and vice-versa with flickering

### Steps to reproduce

1. Just start the game

### Other notes
Rom was downloaded from here: *link removed*

**Comment by sonicfan2007** [comment]
The questions with the points are my answers.

**Comment by RocketRobz** [comment]
To fix the issue, set the clock speed to NTR.
Also, don't post links to retail/commercial ROMs next time.
