### ISSUE TITLE
M&L BiS cut scenes slowdowns

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#578]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release 0.17.1
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?
M&L BiS

### Expected behaviour

Cut scenes after leveling up / Fawful awakening dark star shouldn't be slowed down

### Actual behaviour

These cut scenes slow down

### Steps to reproduce

1. Level up
2. Notice slowdown in animation

1. Beat frozen/ice midbus
2. Watch cutscene
3. Notice how those dark thunders are slown down in comparison to native game

**Comment by RocketRobz** [comment]
Sounds like it's related to DMA.

**Comment by FlameKat53** [comment]
Hello, does this still occur on the latest version of nds-bootstrap? (v0.19.5)

**Comment by ahezard** [comment]
Could be linked to #517
