### ISSUE TITLE
MKDS USA - Random whitescreens

### ISSUE THREAD

**Issue by JeodC** [ahezard/nds-bootstrap#579]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [x]  Nightly _e715a0d0acd3ed8e1ac474564108b3562cbbeb74_

### If this issue only affects a certain game, which game is it?

Mario Kart DS USA

### Expected behaviour

Game launches as normal

### Actual behaviour
Game randomly whitescreen crashes at boot

### Steps to reproduce

1. Set manual TWL++ settings to: DS Mode, 67 MHz (NTR), VRAM Boost: Off
2. Launch game a few times
3. Whitescreen crash occurs randomly

### Other notes

This does not appear to happen when the above TWL++ settings are the Defaults and the game is using the Default settings.

Initially I thought VRAM Boost: On fixed the problem. This now appears unrelated as the game continued to crash randomly despite the change in setting.

**Comment by JeodC** [comment]
Whatever is causing this issue may also causing Metroid Prime Hunters to consistently display a whitescreen crash after selecting a level (after cutscene).

**Comment by RocketRobz** [comment]
Also happens on GTA: Chinatown Wars.
I got a white screen 4 times in a row.

**Comment by Stack3r** [comment]
Definitely not a coincidence if three games are having the issue now, it must be from the recent changes

**Comment by RocketRobz** [comment]
Starting with commit 1474fe6, GTA doesn't seem to white screen now.
Can any of you check if MKDS is fixed by that commit?

**Comment by JeodC** [comment]
MPH still has the whitescreen, MKDS has loaded successfully 4 times in a row now.

**Comment by RocketRobz** [comment]
Ok, so now that the issue with MKDS and GTA are fixed, and the MPH issue is unrelated, I'll close this.
