### ISSUE TITLE
Kirby Super Star (SNES) not loading

### ISSUE THREAD

**Issue by MasterGamingYT** [ahezard/nds-bootstrap#580]
So I load kirby super star, right? But instead of showing the intro, it just shows a white screen on the top, the bottom screen works fine

**Comment by MarkTheFreak** [comment]
SNES games aren't loaded via nds-bootstrap.

**Comment by RocketRobz** [comment]
SNES games are loaded via SNEmulDS.

**Comment by piratesephiroth** [comment]
why aren't you playing Kirby Super Star Ultra

**Comment by MasterGamingYT** [comment]
@piratesephiroth I actually do, however I only play the snes version because of that impressive intro
