### ISSUE TITLE
Music Issues in Ghost Trick

### ISSUE THREAD

**Issue by sourmilkcereal** [ahezard/nds-bootstrap#582]
### Your console

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:
Can't specify with options presented. Using default that comes with the most recent release of Twilight Menu++.
- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Ghost Trick
### Expected behaviour

Usually, the music should play properly. Not leave anything out, no other noises should play.
### Actual behaviour

Certain music tracks have a lot of sounds being made, like beeps or bzzts, and other tracks have entire parts of them missing. For example, a large part of "welcome to the salon" is missing.

### Other notes

I used an AP Patch.

**Comment by RocketRobz** [comment]
Use TWiLight Menu++ Updater to get the latest nds-bootstrap nightly, then go into TWLMenu++ settings, and set Bootstrap to Nightly.
The latest nds-bootstrap nightly fixes some issues.

**Comment by sourmilkcereal** [comment]
Ah, thanks. Hopefully this clears up the issue!

**Comment by dubbz82** [comment]
is this still a problem with more recent builds?

**Comment by hubert-skowronek** [comment]
@RocketRobz @dubbz82 @ahezard I'm currently playing/testing Ghost Trick with 0.24 nds-bootstrap and the mentioned issue is not happening.
