### ISSUE TITLE
softlock on save select (BIS)

### ISSUE THREAD

**Issue by MDHEXT** [ahezard/nds-bootstrap#583]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.17.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Mario & Luigi: Bowser's inside story

### Expected behaviour

game should run properly

### Actual behaviour

game controls lock at save selection screen

### Steps to reproduce

1.open game
2.press a to start
3.game softlocks on save selection

### Other notes
i can't find an ap patch

**Comment by FlameKat53** [comment]
This is an AP issue, please patch your rom with kinder_bueno’s patch to fix the issue

**Comment by MDHEXT** [comment]
can you leave a link?

**Comment by FlameKat53** [comment]
https://www.odrive.com/s/8443cc3a-862e-41d7-b064-09378f79f6b3-5965a89a
Click the folder “kinder_bueno’s patches”

**Comment by MDHEXT** [comment]
how do i apply the patch?

**Comment by FlameKat53** [comment]
use xdelta UI on windows
MultiPatch on MacOS
xDelta UI: https://www.romhacking.net/utilities/598/
MultiPatch: https://www.romhacking.net/utilities/746/

**Comment by MDHEXT** [comment]
I keep getting "XD3_INVALID_INPUT"

**Comment by FlameKat53** [comment]
What region is your rom?

**Comment by MDHEXT** [comment]
USA

**Comment by FlameKat53** [comment]
Huh, that’s weird...

**Comment by FlameKat53** [comment]
Did you dump it from your cartridge or download it from somewhere (do not specify download location)

**Comment by MDHEXT** [comment]
dump

**Comment by FlameKat53** [comment]
Try finding a scene rom dump and try that

**Comment by FlameKat53** [comment]
I can’t give you a link ofc, that’s quite illegal

**Comment by MDHEXT** [comment]
i get it

**Comment by Moises5555** [comment]
Trash

**Comment by FlameKat53** [comment]
@Moises5555 sorry but I don’t understand what you said “trash” for 😅

**Comment by MDHEXT** [comment]
i don't know what a scene rom dump is

**Comment by FlameKat53** [comment]
It’s basically one that is posted onto the internet

**Comment by MDHEXT** [comment]
there's no patches or scene rom dumps available

**Comment by FlameKat53** [comment]
the scene dumps are found on google or your prefered search engine
