### ISSUE TITLE
Kirby SS Ultra controller issue

### ISSUE THREAD

**Issue by sourmilkcereal** [ahezard/nds-bootstrap#584]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ x]  Release _[v0.17.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
Kirby Super Star Ultra
### Expected behaviour

Tell us what should happen
After completing game, should be able to go into menu and interact with game.
### Actual behaviour

Tell us what happens instead
Game still runs, but it's impossible to interact with. Can still exit ROM however.
### Steps to reproduce

1. Not sure, only started happening after playing for a while.
2.
3.

**Comment by Stack3r** [comment]
Please test on the latest nightly build

**Comment by sourmilkcereal** [comment]
I beat Milky Way Wishes, and the glitch happened again. Game still ran, like before, but couldn't input anything.

**Comment by legoj15** [comment]
This is an issue that needs to be patched through the rom https://github.com/ahezard/nds-bootstrap/issues/314#issuecomment-451814850
