### ISSUE TITLE
Professor Layton Curious Village no sound in cutscenes

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#585]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [x]  Nightly 1474fe6

### If this issue only affects a certain game, which game is it?

Layton Curious Village (EUR)

### Expected behaviour
There should be sound in cutscenes when there are no dialogs but progress in plot is presented (e.g. animation with drawbridge at the beginning of the game).

### Actual behaviour

There is no sound in those cutscenes and also sometimes the games doesn't load at all, it stays on white screens after "loading" screen.

### Steps to reproduce

1. Progress the plot
2. Watch a cutscene
3. Notice that there is no sound

### Other notes

The issue doesn't occur for release 0.17.1

**Comment by RocketRobz** [comment]
Can you check if the white screen issue is fixed in the latest commit, and if the no sound issue occurs in the USA version?

**Comment by hubert-skowronek** [comment]
The latest commit fixed the white screen issue.
Sound issue is present also in the USA version.

**Comment by RocketRobz** [comment]
It seems the issue only occurs when you skip over the sounds for the cutscenes.

**Comment by hubert-skowronek** [comment]
@RocketRobz I cannot agree. Please compare initial cutscene of riding Layton's car - for nightly it doesn't have SFX of working engine, there is silence, only music; for release bootstrap you can hear the engine and other SFX clearly. I think this should be reopened.

**Comment by RocketRobz** [comment]
You haven't updated the nightly bootstrap. Please update it, then try again.

**Comment by hubert-skowronek** [comment]
@RocketRobz Aah, ok :-) I overlooked this, forgive me :-)
