### ISSUE TITLE
Chrono Trigger save corruption and black screen

### ISSUE THREAD

**Issue by LaiKash** [ahezard/nds-bootstrap#588]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.17.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Chrono trigger, but may happens in others.

### Expected behaviour

Normality

### Actual behaviour

When I put the 3DS into sleep mode while in the game, the save files are corrupted until I reboot the 3DS. Also when changing from one scenario to another, the second one may be black (but the character can move and the minimap works). Sometimes the 3DS just semi-frozen (sounds works but nothing else and if HOME is pressed, the console powers off).

### Steps to reproduce

1. Put the 3DS into sleep (close it) while in the game ant let it some time (undetermined, may be hours)
2. Try to save the game.
3. Try to change from one scenario to another.

### Other notes
May be a problem of TWL Menu++. I tried with 2 different ROMs but it happens with both. The ROM is in Spanish (translated).

**Comment by RocketRobz** [comment]
I never had that happen for me. Sounds like an issue with your SD card.
Try checking it for errors.

**Comment by hubert-skowronek** [comment]
I've completed entire game before release 0.17.1 (unfortunately I don't remember the version, but it was release available during august 2018) and had never encountered such issues

**Comment by LaiKash** [comment]
Ok after some testing yes, it was muy SD. Thanx a lot forma the help!
