### ISSUE TITLE
Guru Meditation Error! glitch

### ISSUE THREAD

**Issue by crensyhanilas** [ahezard/nds-bootstrap#589]
### Your console

Tell us which console do you have:

- (  )  DS Phat/Lite
- (x)  DSi (XL)
- (  )  Old 3DS/2DS (XL)
- (  )  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- (  ) (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- (x) (No CFW) Unlaunch 1.8 only
- (  )  Unlaunch 1.4 + HiyaCFW
________________________________________
i got a problem to order this app.

**Comment by RocketRobz** [comment]
What happens, exactly?

**Comment by NightYoshi370** [comment]
You need to install HiyaCFW in order to use nds-bootstrap

**Comment by crensyhanilas** [comment]
When i Power on, it continues a RSOD.
