### ISSUE TITLE
Blood of Bahamut corrupted graphics

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#590]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [x]  Nightly b4cc75c

### If this issue only affects a certain game, which game is it?

Blood of Bahamut

### Expected behaviour

Title screen is rendered correctly

### Actual behaviour

The top screen of title screen is glitched

### Steps to reproduce

1. Run Blood of Bahamut with nightly b4cc75c

**Comment by RocketRobz** [comment]
Does the release nds-bootstrap have the same issue?

**Comment by piratesephiroth** [comment]
aren't you more concerned with the fact that the game doesn't save? lol

**Comment by hubert-skowronek** [comment]
@RocketRobz it is ok for release version
@piratesephiroth every bug deserves attention! But to be honest you got me here, I didn't know nor even checked this :-)

**Comment by ahezard** [comment]
Is this issue still present with latest release?

**Comment by piratesephiroth** [comment]
the graphical issue is gone but the game still doesn't save
