### ISSUE TITLE
Picross DS does not display top screen

### ISSUE THREAD

**Issue by cole36912** [ahezard/nds-bootstrap#591]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.17.1]_
- [x]  Nightly _[b4cc75cef94fc4af22f097d823538fca0ff79975]_

### If this issue only affects a certain game, which game is it?

Picross DS

### Expected behaviour

Top screen displays:
https://www.nintendo.com/consumer/gameslist/manuals/DS_Picross.pdf

### Actual behaviour

Top screen is black

### Steps to reproduce

1. Happens on all settings as far as I can tell
2.
3.

**Comment by RocketRobz** [comment]
It might need to be AP-patched.

**Comment by dubbz82** [comment]
Picross DS (not 3d...) is old enough that AP isn't likely.  Rom number for the latest release of this (Korean) is 1426, so AP seems unlikely.

**Comment by MasterGamingYT** [comment]
Weird Picross DS works fine for me

**Comment by cole36912** [comment]
> Weird Picross DS works fine for me

do you know what region you have and/or the hash of the rom?
So far I've tried:
1280 - Picross DS (U)(DOMiNENT).nds (md5 = a980adb92b4bbda7784cdf960ada8826) - No top screen
1062 - Picross DS (E)(Legacy).nds (md5 = 85be04d1c454938fecadeb0e3eb09d05) - No top screen
Picross DS.nds (Korean) (md5 = 8dc070acfafbaea072e0a288a32e6eb2) - Doesn't boot

**Comment by dubbz82** [comment]
Those MD5's do match up with the dumps in no-intro, so likely not a problem with the roms.  Perhaps there's some configuration issues?  What's your CPU speed set to in TWLoader?

**Comment by RocketRobz** [comment]
@dubbz82 Your post said TWLoader. I fixed it for you. :P

**Comment by LanceBoyle94** [comment]
I've had this issue too, and I found out that disabling the loading screen from the TWiLight Menu settings does display the top screen in the game.

![imagen](https://user-images.githubusercontent.com/25116320/56627651-20176680-661d-11e9-95de-44d2b723f3cf.png)

Geometry Wars Galaxies has that same issue too, and the same solution. I don't know if there's other games that have this kinda issue.
