### ISSUE TITLE
Kirby Power Paintbrush/Canvas Cruse Problem Save (EU)

### ISSUE THREAD

**Issue by Kikou3344** [ahezard/nds-bootstrap#592]
I have a problem with this game with Bootstrap version 0.17.1  and Twilight Menu++ 7.4.1, but after making a new save, leaving the game (going to the DSI main menu), and coming back... the save is deleted... I tried out saving in slot 1, 2, and 3, with the same results.

**Comment by FlameKat53** [comment]
This issue is fixed on the latest nightly

**Comment by Kikou3344** [comment]
In dsi and twilight menu ++ ? ? because when i choose "nightly " i have the same problem

**Comment by FlameKat53** [comment]
Did you download the latest nightly from here? https://github.com/TWLBot/Builds/releases/download/v20190402-175153/nds-bootstrap.7z

**Comment by Kikou3344** [comment]
I try this i give you a response aftehr this thanks

**Comment by FlameKat53** [comment]
Okay 👌

**Comment by Kikou3344** [comment]
It's Work thanks , i have just downloaded the nightly you have give me, 
the problem is i have download the release version so is ok Now , thanks a lot :)

**Comment by FlameKat53** [comment]
No problem! I am happy to help!
