### ISSUE TITLE
Pokemon SoulSilver randomly freezes

### ISSUE THREAD

**Issue by DavidhvYT** [ahezard/nds-bootstrap#593]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x ]  Unlaunch+HiyaCFW _[latest versions]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokemon Soulsilver

### Expected behaviour

Play the game without freezing

### Actual behaviour

It freezes in random moments

### Steps to reproduce

1.Play the game
2.It's random, so this can happen anytime
3.It freezes

### Other notes
I patched the game with DS Scene Rom Tool 1.0 build 1215, i'm using the spanish version and i didn't try Pokemon HeartGold yet

**Comment by MasterGamingYT** [comment]
Try using a different ap patch (Found in the AP Patch Preservation Thread on GBAtemp)
