### ISSUE TITLE
Final Fantasy 4 heroes of light black screen when game is launched

### ISSUE THREAD

**Issue by TheFlintASteel** [ahezard/nds-bootstrap#594]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [o ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ o]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [o ]  Release _[0.17.1]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Final Fantasy 4 heroes of light

### Other notes
The issue occurs either in the clean game and de AP Patched game

**Comment by MasterGamingYT** [comment]
It's most likely not compatible (I'm not sure)

**Comment by ahezard** [comment]
Tested with 0.20.0 : the game runs
