### ISSUE TITLE
White Screen Pokemon V gen

### ISSUE THREAD

**Issue by Sherlockowiec** [ahezard/nds-bootstrap#595]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release (0.17.1)
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokemon White/Black, Pokemon White2/Pokemon Black2

Descriptions:
I'm trying to play Pokemon White and Pokemon Black 2, I downloaded both AP patched, I select the rom, save file created successfully, loading screen and after that screen remains white.
I tried different roms, patched, clean, from different sources but nothing.
I played New super mario bros, pokemon Heartgold, Pokemon Platinum and it worked without issue.
I also set DS mode and turned VRAM boost off but it didn't work.

**Comment by RocketRobz** [comment]
Where did you set both of those settings? In TWLMenu++ settings, or the game's per-game settings?

**Comment by FlameKat53** [comment]
Can you try the pergame settings of TWiLight menu++ as:

`DS Mode
67MHz (NTR Clock Speed)
VRAM Boost off`

Just in case, it might work

**Comment by FlameKat53** [comment]
Yes I understand you tried DS Mode already :P

**Comment by FlameKat53** [comment]
Did this work?

**Comment by Sherlockowiec** [comment]
> 
> 
> Where did you set both of those settings? In TWLMenu++ settings, or the game's per-game settings?

In TWLMenu settings.

> 
> 
> Did this work?

It worked, thanks!!

**Comment by FlameKat53** [comment]
oh nice, now the issue may be closed.
