### ISSUE TITLE
Digimon World DS (U)

### ISSUE THREAD

**Issue by khonshuknight** [ahezard/nds-bootstrap#596]
noticed on the compatibility list that the game loads to white screen, so i tested it out on the latest release. same issue. also tested it out on nightly v20190305 and same issue. on n2dsXL

**Comment by RocketRobz** [comment]
Did you update the nightly using TWiLight Menu++ Updater?
It worked fine for me, last time I tested it.

**Comment by khonshuknight** [comment]
I knew I forgot to install something! I'll test it out and let you know

**Comment by khonshuknight** [comment]
You were totally right. Issue fixed on nightly
