### ISSUE TITLE
Soul Silver crashes even with AP Patch

### ISSUE THREAD

**Issue by sapfel93** [ahezard/nds-bootstrap#598]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ x ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

Pokemon Soul Silver

Tell us what happens instead
 
Game crashing

### Other notes

Occasionally the sprites glitch up and the game crashes. I know this is the result of AP, but I tried a dump of SS that I own and applied the AP patch through DS-Scene and the bug still isn't fixed. I have the latest release of nds bootstrap. What am I doing wrong?

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue, not something you did wrong.
Try updating the nds-bootstrap nightly using the TWiLight Menu++ Updater.
Then open the TWiLight Menu++ app, go into the settings, and set Bootstrap to Nightly.
The latest nds-bootstrap nightly fixes some issues.

**Comment by sapfel93** [comment]
I tried that and it still had that same glitch. Perhaps I should just use Desmume until the bug gets patched?

**Comment by DavidhvYT** [comment]
I only use D-Pad and stylus, not A/B/Y/X buttons and it reduced the frequency of crashes and if sprite glitches happens i save inmediatly and reset the game

**Comment by Stack3r** [comment]
I’ve had these texture issues also, apparently turning off vram boost fixed them for me

**Comment by ExperimentT** [comment]
I've tested this on a DSi with AP applied via Unlaunch 0.18 on it's own and the same version with HiyaCFW 1.3.2. with bootstrap 19.5 Graphical issues do not occur but the game will freeze in either NTR or TWL Mode with both the VRAM boost enabled or disabled. When this occurs is seemingly random: Sometimes it'll only take 10 minutes to freeze or it can go roughly 8 hours before doing so.

**Comment by GlitchMC** [comment]
I'm also experiencing this issue on bootstrap v0.22 (mostly the random hangs when it tries to load something, but occasionally the sprites too), though I haven't AP patched my ROM. I was also using TWL CPU speed and VRAM boost.

I'm going to patch my ROM and change those settings and see if that helps at all.

**Comment by RocketRobz** [comment]
Seems to be fixed.
