### ISSUE TITLE
Odd Alphabetical Chunk of DsiWare Games Don't Launch

### ISSUE THREAD

**Issue by thepieddragon** [ahezard/nds-bootstrap#600]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only 
- [x]  Unlaunch+HiyaCFW [Ulaunch v1.8, HiyaCFW Unsure Version. Presumably latest, but I'm 
           having issues checking]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release [v0.17.1]
- [ ]  Nightly 

### If this issue only affects a certain game, which game is it?

-Battle of the Giants: Dragons - Bronze Edition
-Bejeweled Twist
-Bird & Beans
-BlayzBloo - Super Melee Brawlers Battle Royale

### Expected behaviour

Games should create a save file and launch.

### Actual behaviour

White screen. DSi locks and requires a hard power off.

### Steps to reproduce

1. Attempt to launch game via menu
2. White screen

### Other notes

Games are in alphabetical order, one after the other according to somewhat older No-Intro dats when filtering to only US games, starting with Battle or the Giants and ending with BlayzBloo (Big Bass Arcade, and Biorhythm has not been tested). This does not happen to any other DSiWare game I've tested, including US roms immediately before and after this particular group of rom alphabetically. Chinese version of Bird and Beans also does not function. Name of file, location of file in directory structure, and number of files in directory do not affect behavior. The roms are known good, verified dumps as far as I can test. Only tested the .nds roms, and not the games as installed titles on the DSi.

**Comment by RocketRobz** [comment]
This is a TWiLight Menu++ issue, not an nds-bootstrap issue.
The issue will be fixed in the next version.

**Comment by thepieddragon** [comment]
> This is a TWiLight Menu++ issue, not an nds-bootstrap issue.
> The issue will be fixed in the next version.

Awesome! Sorry for putting the ticket in the wrong place. I thought because it was a game issue it belonged here.
