### ISSUE TITLE
Pokemon BW & B2W2 

### ISSUE THREAD

**Issue by arthurhg** [ahezard/nds-bootstrap#601]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_0.17.1
- [x]  Nightly _[insert here commit hash]_c03a77d

### If this issue only affects a certain game, which game is it?

Pokemon BW & B2W2 (AP-Patched)

### Expected behaviour

The game should start after the loading screen

### Actual behaviour

The screen goes blank after the loading screen and nothing happens

### Steps to reproduce

1.
2.
3.

### Other notes
THE GAMES ARE AP-PATCHED, THAT'S NOT THE ISSUE

**Comment by Volti-p** [comment]
You probably have DSi Mode on, which doesn't work. Put it to DS Mode.

**Comment by RocketRobz** [comment]
^
