### ISSUE TITLE
Prince of Persia Forgotten Sands: Black/White screen

### ISSUE THREAD

**Issue by JGPenaB** [ahezard/nds-bootstrap#602]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release 
- [x]  Nightly _c03a77d_

### Game

_Title_: Prince of Persia - The Forgotten Sands
_ID_: TWL-VPPE-USA
_CRC32_: 1BD94AE0

### Explanation

When the configuration is set to DS mode, after the game loads it shows a black screen. If switched to DSi mode, it shows a white screen instead. Using NTR or TWL mode does not make any difference. The game is AP patched.

[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/3077754/NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
Is the ROM AP-patched?

**Comment by JGPenaB** [comment]
> Is the ROM AP-patched?

Yes

**Comment by JGPenaB** [comment]
I decided to re-patch the game using xdelta patches, and now it works for some reason. My previous attempts didn't work even thought the game was functional after it and the rom and patch were the same.
