### ISSUE TITLE
Save Nand functions implementation

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#603]
Nand functions needs to be patch in order to fix #306 and #599 .

The nand code from wood can be used as a template (it cannot be reused directly but it gaves some hint about how to implement this) :
https://github.com/ahezard/woodrpg_forwarder/blob/e0280c91b21e28443c23f98a171012ef8a301b0c/akloader/arm9/source/patches_sd.cpp
Line 29-90

Patches that can be directly reused from wood :
u32 gNandInit(void)
u32 gNandResume(void)
u32 gNandError(void)

Functions to implement : 
u32 gNandWrite(void* memory,void* flash,u32 size,u32 dma_channel)
u32 gNandRead(void* memory,void* flash,u32 size,u32 dma_channel)

These functions needs to be patched at arm9 level while usual saves are patched at arm7 level so specifics arm9/arm7 commands have to be added in order to read/write from the sd card save file (only accessible by arm7 currently).

**Comment by ahezard** [comment]
Done but only works on warioware

**Comment by MasterGamingYT** [comment]
hmm.....ok

**Comment by RubberDuckShobe** [comment]
@ahezard Tested it on the newest release builds and the nightly builds of nds-bootstrap and TWiLightMenu++, WWDIY is still stuck at creating save file

**Comment by ahezard** [comment]
By creating save file you mean before the game boot? If so this a https://github.com/DS-Homebrew/TWiLightMenu issue.

**Comment by ahezard** [comment]
Is is similar to https://github.com/DS-Homebrew/TWiLightMenu/issues/581

**Comment by ahezard** [comment]
I suppose you can create a 32 MB save file by fsutil file createnew "game.sav" 33550592" 
Or just delete the file and try again, it will work eventually.
