### ISSUE TITLE
Trying to exit to twilight menu while in a slot 1 game crashes system

### ISSUE THREAD

**Issue by MasterGamingYT** [ahezard/nds-bootstrap#604]
Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
-  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

-  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

-  Release _[0.18.0]_
- [ ]  Nightly _[8efbcdd]_

### Expected behaviour

Should be able to exit to twilight menu

### Actual behaviour

Trying to exit to twilight menu with the L+R+Down+B causes the system to crash and with this message: "An error has occured, press and hold the power button for a few seconds to power off" (Something like that)

### Steps to reproduce

1.Launch a slot 1 game
2.Try to exit to twilight menu
3.System crash

### Other notes

I've only tested this with super mario 64 ds, anyone that wants to test it with the others is highly appreciated

**Comment by RocketRobz** [comment]
This is a TWiLight Menu++ issue, not an nds-bootstrap issue.
