### ISSUE TITLE
Tony Hawk - Downhill Jam error

### ISSUE THREAD

**Issue by JGPenaB** [ahezard/nds-bootstrap#607]
### Console

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW
- [ ]  Older CFW

### nds-bootstrap version

- [x]  Release _0.18.0_
- [ ]  Nightly

### Game Affected

Tony Hawk - Downhill Jam

### Expected behaviour

The game should load normally, with the nightly builds it was working fine.

### Actual behaviour

The game upon loading shows a "Could not read data" message. On previous nigthly builds it was working, but with the nightly build that comes with 0.18.0 still shows the same error.

### Steps to reproduce

1. Follow TWiLightMenu installation.
2. Run Tony Hawk - Downhill Jam.

**Comment by JGPenaB** [comment]
It seems to be a problem with TwilightMenu

**Comment by JGPenaB** [comment]
After testing more and more, it seems that TWiLightMenu is having problems reading the ROM and creating a .sav file, perhaps is my SD.

**Comment by RocketRobz** [comment]
Have you tried holding L after pressing the launch button?

**Comment by RocketRobz** [comment]
I tried it (without holding L), and it works fine for me.

**Comment by RocketRobz** [comment]
Save functions aren't patched for this game, but still booted. Tested with the USA ROM.
I think those times when it worked for you, you had an NTR game card inserted.
What region is your ROM?

**Comment by JGPenaB** [comment]
I tested USA and EUR versions. And holding L makes no difference.

**Comment by ahezard** [comment]
Fixed (including saving) in c31ab31
