### ISSUE TITLE
Explorers of Sky white screen

### ISSUE THREAD

**Issue by meoxx** [ahezard/nds-bootstrap#608]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release 8efbcdd
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokemon Mystery Dungeon: Explorers of Sky

### Expected behaviour

The game should load

### Actual behaviour

The game shows a white screen

### Steps to reproduce

1. Select game 
2. Wait for it to load
3. White screen

### Other notes
Earlier versions were able to boot the game

**Comment by RocketRobz** [comment]
Will be fixed next TWLMenu++ version, where you won't need to hold L to fix it.
