### ISSUE TITLE
[5213] Last Window - The Secret of Cape West won't boot.

### ISSUE THREAD

**Issue by mamimi0** [ahezard/nds-bootstrap#609]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

5213 Last Window - The Secret of Cape West.

### Expected behaviour

In previous version it boots normally, but it suffers from random freezings.

### Actual behaviour

It won't boot, blank screen.

### Steps to reproduce

1. Just try to boot it.
2. ^
3. ^^

### Other notes

On a related note, do you guys know what it's causing the game to freezes at random times? An AP measure?

**Comment by RocketRobz** [comment]
Try holding L after pressing the launch button.
If it fixes it, then tell me the game's TID, so I can add it into the next TWLMenu++ version, in order for it to boot normally.

**Comment by RocketRobz** [comment]
I tried it (L not held), and it booted fine for me.
Are you sure you're on the latest TWLMenu++ and nds-bootstrap versions?
If you are, make sure your ROM isn't corrupted.
