### ISSUE TITLE
Micro Machines V4 wont run

### ISSUE THREAD

**Issue by exilzz** [ahezard/nds-bootstrap#610]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

- [X]  Release v0.18.0
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

micromachines v4

### What's the issue

displays "could not read data turn off power and reinsert the ds card"

**Comment by RocketRobz** [comment]
Works fine for me.

**Comment by exilzz** [comment]
How can I fix it?

**Comment by RocketRobz** [comment]
What are your settings?

**Comment by exilzz** [comment]
I’m running in ds mode with arm9 at 133mhz vram boost is on 
Force sleep mode patch off
SCFG access is off 
Slot 1 launch is direct 
Mic is 32.73khz

**Comment by RocketRobz** [comment]
Try turning off VRAM boost.

**Comment by exilzz** [comment]
No luck with turning vram off what region is ur rom

**Comment by RocketRobz** [comment]
USA

**Comment by exilzz** [comment]
Let me try a US rom

**Comment by RocketRobz** [comment]
Tried with no Slot-1 card inserted, and I got the same issue.
It seems save functions are not patched for this game.
If an NTR cart is inserted into Slot-1 to use as a donor, then the game works.

**Comment by exilzz** [comment]
Excuse my lack of knowledge what do you mean by an NTR cart

**Comment by RocketRobz** [comment]
A DS game card with `NTR` at the bottom of the sticker.

**Comment by exilzz** [comment]
Yeah putting in a NTR cart worked for me

**Comment by ahezard** [comment]
The save patch on ARM7 is completely failing for this game, which explains the issue

**Comment by ahezard** [comment]
A save patch is available into wood code here :
https://github.com/ahezard/woodrpg_forwarder/blob/e0280c91b21e28443c23f98a171012ef8a301b0c/akloader/arm9/source/patches_sd.cpp

The proper condition that match is
if(COMPARE_VALUE(0x34372e32,0x023a9fc8)...) //2.74

**Comment by ahezard** [comment]
The save patch applied is similar to pokemon pearl/diamond

**Comment by ahezard** [comment]
The issue is fixed in latest nightly
