### ISSUE TITLE
Pokemon Ranger Guardian Signs White Screen

### ISSUE THREAD

**Issue by zeroultima6** [ahezard/nds-bootstrap#612]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [* ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [* ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [* ]  Release _[0.18.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen

Game should've worked as expected 

### Actual behaviour

Tell us what happens instead

White screens upon booting

### Steps to reproduce

1.
2.
3.

**Comment by SuperSaiyajinVoltZ** [comment]
This Game Needs to be AP Patched.

**Comment by zeroultima6** [comment]
I did that but the same issue still occur.

**Comment by RocketRobz** [comment]
Try holding L before the nds-bootstrap loading screen is shown.

**Comment by zeroultima6** [comment]
Holding L doesn't work either.

**Comment by RocketRobz** [comment]
Did you hold L immediately after pressing A/START?

**Comment by zeroultima6** [comment]
Yes i did

**Comment by RocketRobz** [comment]
In what TWLMenu++ theme?

**Comment by zeroultima6** [comment]
DSi Theme which i prefer using

**Comment by RocketRobz** [comment]
Weird. Anyone else have this issue?

**Comment by RocketRobz** [comment]
Ok, so I have the issue as well.

**Comment by RocketRobz** [comment]
White screen bug is fixed, but game now crashes after top screen symbol fades out, which is fixed by disabling heap shrink (hold L).
