### ISSUE TITLE
Gyakuten Kenji 2 (Translated; AP-Patched): Blackscreen when starting Case 3

### ISSUE THREAD

**Issue by warrenher** [ahezard/nds-bootstrap#613]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.18.0]_
- [X]  Nightly _[8efbcdd54c4cdf2207cdeb0962f170df7aa83415]_

### If this issue only affects a certain game, which game is it?

Gyakuten Kenji 2

### Expected behaviour

Case 3 should start normally

### Actual behaviour

Upon starting Case 3, both the upper and bottom screen just go black.

### Steps to reproduce

1. Obtain an AP-patched, translated ROM of Gyakuten Kenji 2
2. Start up the game and play until Case 3 or get a 100% save file
3. Start Case 3 by clicking "New Game" and then selecting "The Inherited Turnabout"
4. Case 3 never starts and instead a black screen appears. The game becomes unresponsive.

### Other notes

Gyakuten Kenji 2, apart from the black screens at certain points in the game, is generally playable.

**Comment by warrenher** [comment]
The problem has been resolved. My problem was that I used an old version of the AP-Patch. The one that I needed was https://gbatemp.net/threads/ace-attorney-investigation-2-prosecutors-path-final-release.367451/page-47#post-8282054

**Comment by Stack3r** [comment]
Can you verify your other issue has been resolved also? I’m closing this
