### ISSUE TITLE
Culcept DS and Windaria (and more) boots to black screen

### ISSUE THREAD

**Issue by zeroultima6** [ahezard/nds-bootstrap#614]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ *]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [* ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[0.18.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
Culcept DS
Dungeon of Windaria
Rabbids Go Home DS

### Expected behaviour

Tell us what should happen
 Should've worked as expected 
### Actual behaviour

Tell us what happens instead

Boots but after the logos it black screens

### Steps to reproduce

1.
2.
3.

### Other notes
Some of these games have worked in earlier versions before or not, now it no longer works in 
the latest version.

**Comment by RocketRobz** [comment]
Hold L immediately after pressing A/START to launch the game.

**Comment by zeroultima6** [comment]
Doesn't work, I've  already tried.

**Comment by RocketRobz** [comment]
Culdcept DS is working fine for me.

**Comment by RocketRobz** [comment]
Same for Dungeon of Windaria.

**Comment by RocketRobz** [comment]
and for Rabbids Go Home, is the ROM AP-patched?
If it white screens, make sure it's being ran in DS mode.

**Comment by zeroultima6** [comment]
Not on my end and Rabbids Go Home is not patched and there is AP patch for it anywhere

**Comment by RocketRobz** [comment]
Have you tried DS-Scene ROM Tool?

**Comment by zeroultima6** [comment]
I did and the AP patch didn't exist yet for that game

**Comment by zeroultima6** [comment]
Found the problem for the first two games, for some reason they got corrupted somehow so I ended up replacing those games and they're working again.

**Comment by pedrosonic213** [comment]
Help with rabbids pls

**Comment by pedrosonic213** [comment]
Im using twilight menu ++ the game show the ubi logo and stay with black screens

**Comment by zeroultima6** [comment]
See my solution above

**Comment by pedrosonic213** [comment]
But i dont have any cheats

**Comment by pedrosonic213** [comment]
No cheats found and i searched for rabbids go home cheats and i cant find any

Can you tell me the steps to get this game working? Pls

**Comment by pedrosonic213** [comment]
I even change the save directory and i get a blue screen on top and black on bottom

**Comment by zeroultima6** [comment]
Have you download the cheat database? if you haven't, go do that first and mind you the cheats themselves are a bit finicky .

**Comment by pedrosonic213** [comment]
Okay i ll try

**Comment by pedrosonic213** [comment]
White screen with the cheat... or well

**Comment by zeroultima6** [comment]
Yeah it happens, it worked on the previous versions as well but not the latest version for some reason

**Comment by pedrosonic213** [comment]
Well at least it works on drastic for android i ll wait for an update even if takes a while
