### ISSUE TITLE
Problems with dragon quest iv

### ISSUE THREAD

**Issue by khonshuknight** [ahezard/nds-bootstrap#615]
- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ x]  Release _[0.18.0]_
- [ x]  Nightly _[ver: 31f8916]_

### If this issue only affects a certain game, which game is it?

Dragon quest iv

### Expected behaviour

Should be able to talk to a shop keeper during the second characters chapter start.

### Actual behaviour

Freezes Everytime you talk to the shop keeper.

### Steps to reproduce

1. Get past prologue
2. Exit Castle after character change
3. Talk to shop keeper to the left of where you exit

**Comment by MasterGamingYT** [comment]
Sounds like AP

**Comment by khonshuknight** [comment]
Did some research and apparently this doesn't have AP. This is just a general error due to possibly the bootstrap. Idk if anyone else can test this

**Comment by khonshuknight** [comment]
I have a patched version. I'll repatch a fresh copy and retest.

**Comment by MasterGamingYT** [comment]
Test with the latest nightly and see if it has the same issue

**Comment by khonshuknight** [comment]
Issue persists

**Comment by MasterGamingYT** [comment]
You should wait for it to get patched if it continues

**Comment by khonshuknight** [comment]
So I booted it up on 0.17.1 and it works again. I did have to launch while
holding L or else it black screens.

**Comment by MasterGamingYT** [comment]
It may be a bug with the bootstrap itself

**Comment by MasterGamingYT** [comment]
Test with release 0.19.0

**Comment by Luka020** [comment]
I also tested this and i can confirm that i have the same issue. on 0.19.2 when i change the settings to force DSi mode in TWilight++ then it kinda works but instead of text i get ERROR

**Comment by khonshuknight** [comment]
I finished the game recently using 0.17.1 release. You have to hold L after
booting the game to have it run properly.

**Comment by Luka020** [comment]
@khonshuknight Yes, Thank you! That worked for me! 👍  i hope there wil be a fix soon in the latest release .

**Comment by NightYoshi370** [comment]
If you have to hold L, then it's no longer an issue with nds-bootstrap but rather with the frontend setting it to use the heap shrink
