### ISSUE TITLE
[Regression] Trauma Center 2 hard crashes when loading into an operation

### ISSUE THREAD

**Issue by robzombie91** [ahezard/nds-bootstrap#616]
Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.8, 3.0.2, February 28th]_

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[0.18.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Trauma Center 2

### Expected behaviour

Load into an operation after strings of text

### Actual behaviour

Game hardlocks before he says lets begin the operation

### Steps to reproduce

1. Load into Trauma center 2
2. Choose a mission
3. Scroll through text
4. Hard crash

### Other notes
Worked in previous bootstrap versions

**Comment by robzombie91** [comment]
[Video of issue](https://youtu.be/mvVeVH5Oi54)

**Comment by robzombie91** [comment]
`findModuleParamsOffset:
Module params offset found: 02000BC8
sdk_version: 04027531
This rom is compressed
findHeapPointerOffset:
Init Heap End found: 02030298
heapPointer: 02030284
old heap pointer: 02182480

new heap pointer: 02184480

Heap Shrink Sucessfull

relocate_ce9
firstCardLocation 02182480 : 02700000

armReadCardLocation 02182534 : 02700000

thumbReadCardLocation 02182550 : 02700000

armReadCardDmaLocation 02182588 : 02700000

thumbReadCardDmaLocation 021825C0 : 02700000

globalCardLocation 0218386C : 02700000

 ce9->patches 021824B0

patchCardNds

Found cardId

findMpuInitCacheOffset:
Mpu init cache found: 02000B38

patchMpuSize: 00000000

ERR_NONE


Arm7 (patch vAll)
Relocation src: 023801E8
Relocation dst: 037F8000

JumpTableFunc: 0238B5BC
Eeprom read:	0238B5C8
Eeprom page write:	0238B5DC
Eeprom page prog:	0238B5F0
Eeprom verify:	0238B604
Eeprom page erase:	0238B614
ERR_NONE

ERR_NONEhookNdsRetailArm7
hookLocation: 0238F584

ERR_NONE
chipID: 80003FC2`

not sure if this has anything to do with it but here is a log

**Comment by RocketRobz** [comment]
Try holding L before pressing A/START to launch the game.

**Comment by robzombie91** [comment]
Since it is an sdk4 game yeah that seemed to fix that issue

**Comment by NightYoshi370** [comment]
If holding L fixed the issue, then it's a TWiLightMenu++ issue.
