### ISSUE TITLE
Digimon World DS soft locks during certain actions

### ISSUE THREAD

**Issue by robzombie91** [ahezard/nds-bootstrap#617]
Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.8, 3.0.2, February 28th]_

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[0.18.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Digimon World DS

### Expected behavior

Game does not soft-lock when doing certain actions

### Actual behavior

Game softlocks after taking certain actions like digivolving, degenerating or using certain items

### Steps to reproduce

1. Load into Digimon World DS
2. Try certain actions like degenerating or digivolving or use certain items that affect digivolution
3. Randomly softlock or corrupt graphics

**Comment by RocketRobz** [comment]
Fixed in 5aab814
