### ISSUE TITLE
Advanced Wars Dual Strike (EU) Need to hold L

### ISSUE THREAD

**Issue by daog8** [ahezard/nds-bootstrap#622]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.8 and 3.0.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.19.1]_
- [x]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Advanced Wars Dual Strike (EU)

### Expected behaviour

Start game on selection.

### Actual behaviour

White screen.

### Steps to reproduce

1. Load game

### Other notes
Holding L makes it work. 
Holding L using a forwarder on the 3ds white screens.
USA version works without holding L.

**Comment by NightYoshi370** [comment]
This is a TWiLightMenu++ issue I believe

**Comment by daog8** [comment]
Do cia forwarders on the 3ds go through TWiLightMenu++? 
 
The issue is the need to hold L so cia forwarders don't work?
