### ISSUE TITLE
Pokémon Heartgold Randomly Blackscreens

### ISSUE THREAD

**Issue by nsuchy** [ahezard/nds-bootstrap#623]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [x]  Nightly _[I'm not sure how to find this out, it's whatever is included with the latest release of DSIMenu++]_

### If this issue only affects a certain game, which game is it?

Pokémon HeartGold

### Expected behaviour

The game plays mostly normally

### Actual behaviour

At random, generally after a battle or when opening and closing the menu the screen will go black and freeze the game requiring a restart start

### Steps to reproduce

1. Dump a cart of Pokémon HeartGold
2. Play the game
3. Wait for the bug to occur and take a tear break for the lost progress

### Other notes

When these bugs occured I was playing in forced DSI Mode at TWL Clockspeed with the VRAM Boost enabled. I switched back to DS Mode without TWL Clockspeed and disabled the VRAM Boost. I haven't seen the bug reoccur yet (although unsure if it will or not). Also of note, during parts of the game where a battle is loading or a new area / menu change, the touch screen will occasionally turn a solid white for upwards of 1 second. It's a minor issue and is likely related to loading speed (using a 128GB MicroSD Card). Also of note, I dumped my own cart as there's zero reason to download a ROM (technically piracy) when I own the game, likewise it is NOT AP Patched. I'm not sure if there's a need to AP Patch HeartGold but if someone wants to tell me how to AP Patch if there's a chance it'll fix the issue I'm willing to give it a try. That said I'm using a Mac so please provide instructions for macOS.

**Comment by nsuchy** [comment]
Went into DSIMenu++ Settings and got the following info.

It says TWLMenu++ in the settings screen (weird, maybe it's a bug, maybe intentional) but Version 7.4.0. The nds-bootstrap version release is 0.17.1 So for purposes of debugging this, I can run in release mode so we know the version.

**Comment by MasterGamingYT** [comment]
Is the game ap patched, also you can check what nightly build you're using if you switch bootstrap to nightly in the games and apps page in twilight menu settings

**Comment by nsuchy** [comment]
@MasterGamingYT It wasn't during the crashes, I switched to an AP Patched Dump as well as switched back to release. I haven't seen any crashes since. I want to keep this issue open or a few days so I can put further details as they become available. I will note that I still see the white touch screen from time to time as areas things are loading. My SD Card might be a bit slower as its 128GB with 64kb fat clusters.

**Comment by legoj15** [comment]
Theoretically, 64kb clusters should be _faster_, but is also technically not supported by the 3DS/DSi OS and could be causing issues

**Comment by nsuchy** [comment]
@legoj15 works for me though, maybe I just got lucky :|

**Comment by legoj15** [comment]
It doesn't help that the Pokémon games have never been perfectly stable like other games on nds-bootstrap :P it could honestly be anything causing this, bad dump, improper AP patch, SD Card formatting, random flukes, or even a nds-boostrap issue (although, I would guess that others would chime in if that was the case).

**Comment by MasterGamingYT** [comment]
Do black (2) and white (2) have perfect stability?

**Comment by Stack3r** [comment]
I have been playing all of the DS titles without any issues as long as they are AP patched, the only one I had a problem with was a rom hack of heart gold and then I figured out an AP patch was needed on top of it and I haven’t had any issues since, HG/SS and the Gen 5 series require these patches to fully work without issue

**Comment by MasterGamingYT** [comment]
Well that's good, because Gen 5 is my all time favourite generation (Come at me gen 5 haters)

**Comment by Stack3r** [comment]
Anyways I’m gonna close this, as long as you have a proper dump and AP patch these games work without issue

**Comment by MasterGamingYT** [comment]
Ok
