### ISSUE TITLE
Reading from saved FAT table .bin file doesn't work for some users

### ISSUE THREAD

**Issue by RocketRobz** [ahezard/nds-bootstrap#624]
When trying to boot a game the second time, after the .bin file was already created in `sd:/`_nds/nds-bootstrap/fatTable`, the game will white screen.

**Comment by hubert-skowronek** [comment]
I confirm, it was sometimes happening to me recently

**Comment by piratesephiroth** [comment]
yeah, it's somewhat random

**Comment by Stack3r** [comment]
I wonder what could be causing it, does it still happen with the removed loading screen update?

**Comment by zeroultima6** [comment]
Same for me

**Comment by RinMaru** [comment]
only happens to me when booting a second time from the quick menu on some games. speaking of the fat table is there a possibility to generate a fat table for all games through an option that way theres no need for a second boot?

**Comment by RocketRobz** [comment]
So that bug is occurring due to the devkitArm build that TWLBot uses to compile nds-bootstrap.
I compiled it on my side, and there's no white screen crashes.
A new nds-bootstrap version will be released shortly.

**Comment by RocketRobz** [comment]
Ok, it is out now.

Also, @RinMaru I believe it's not possible, as nds-bootstrap only generates the FAT table when booting a game the first time, if the game and/or save is moved around, or if the size of the game and/or save is changed.
