### ISSUE TITLE
Cheats in Guardian Signs do not work

### ISSUE THREAD

**Issue by TheRedMajora** [ahezard/nds-bootstrap#625]
- New 3DS XL
- Luma3DS
- TWiLight Menu++ v8.1.1
- nds-bootstrap v0.19.1

### If this issue only affects a certain game, which game is it?
Pokemon Ranger: Guardian Signs (EU) - B3RP-366AB533
EDIT: Seems to be happening in all games

### Behaviour

Cheat codes (both own usrcheat.dat and the one downloaded from the updater) shows up in the menu, but in the game no codes work. I have triple checked, the region matches, the codes are written as they should. The game is AP patched to prevent the screen blackout, but I've tried loading an unpatched version with the AP cheat code, but that left me with a screen blackout (possibly because the cheat didn't load?)
I've tried manually adding a cheats.xml to the _nds folder with my desired codes. They show up in the nds-boostrap.ini (I've tried both with and without debug mode) but they don't work in the game at all.

**Comment by RocketRobz** [comment]
Turn on debug in TWLMenu++ Settings for cheats to work.

**Comment by TheRedMajora** [comment]
I've tried that, but it still won't work :|

**Comment by arraystock** [comment]
Are cheats broken for you in other games?

**Comment by arraystock** [comment]
The latest release of nds-bootstrap uses a different build of devkitArm, could you try that and see if there’s any difference?

**Comment by TheRedMajora** [comment]
Still not working

**Comment by MasterGamingYT** [comment]
Test with latest nightly

**Comment by TheRedMajora** [comment]
Tested with latest nightly (from the TwilightMenu++ Updater) but no luck.
The debug log says “cheat_data_len: 14” so something should be loaded.

**Comment by TheRedMajora** [comment]
Don’t know what I did but 0.19.2 (which I tested before) suddenly works 🤨

**Comment by ahezard** [comment]
It could be due to this bug :  #619 Cheats only activated if debug is enabled
Please confirm

**Comment by TheRedMajora** [comment]
Update;
It stopped working now. Debug is still enabled, I'm using the same settings as before, but I changed my enabled cheats (I had enabled **everything** for testing purposes) and now it stopped functioning.
I am unable to get it working even after switching between different versions.

**Comment by ahezard** [comment]
Please test again with latest nightly : 5fe51b6

**Comment by RocketRobz** [comment]
Should be fixed now.
