### ISSUE TITLE
Pokemon Games White Screen! (Heart Gold & Pearl)

### ISSUE THREAD

**Issue by hannahlorrainee** [ahezard/nds-bootstrap#626]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[latest]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokemon Heart Gold (Patched Version) & Pokemon Pearl

### Expected behaviour

Game should boot 

### Actual behaviour

Pokemon Pearl goes to white screen and Pokemon HG goes to black screen

### Steps to reproduce

1. Open TWL
2. Select Game
3. Try to open it

### Other notes
I have it set to boot to DS Mode but that still doesn't help ): I tried Tamagotchi Connection Corner Shop and it worked just fine. Thank you so so much for your work on this. I am FOREVER grateful I don't have to spend $50 on a HeartGold cartridge. 
Should also mention I used updater to update bootstrap & TWL to latest!

**Comment by Stack3r** [comment]
It needs to be on DS mode and verify your ROMs are patched, these games work without issues otherwise, it’s not an issue on bootstraps side

**Comment by hannahlorrainee** [comment]
> It needs to be on DS mode and verify your ROMs are patched, these games work without issues otherwise, it’s not an issue on bootstraps side

Hey, I mentioned they're both set to boot in ds mode.

**Comment by SuperSaiyajinVoltZ** [comment]
Make sure, your ROM isn't corrupted or something.

**Comment by hannahlorrainee** [comment]
> Make sure, your ROM isn't corrupted or something.

I've redownloaded them about 5 times now

**Comment by SuperSaiyajinVoltZ** [comment]
Please don't say `redownloaded` or something, because this is Piracy and I won't help with Piracy.

**Comment by hannahlorrainee** [comment]
> Please don't say `redownloaded` or something, because this is Piracy and I won't help with Piracy.

okay well they aren't corrupted.

**Comment by hannahlorrainee** [comment]
@Stack3r why would you close this if it isn't solved!

**Comment by RocketRobz** [comment]
Just to verify, you're on TWLMenu++ v8.1.1, and you're on nds-bootstrap v0.19.2?

**Comment by MasterGamingYT** [comment]
Make sure you're using a proper AP patch and rom

**Comment by NightYoshi370** [comment]
@SuperSaiyajinVoltZ If he pirated the game, that's on him. He could have also dumped the game himself and it would have had the same effect.

@hannahlorrainee Are you sure you applied an Anti-Piracy patch on the ROM?
