### ISSUE TITLE
Pokemon Mystery Dungeon 2: Explorers of Time (E) don't want boot

### ISSUE THREAD

**Issue by Kikou3344** [ahezard/nds-bootstrap#627]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[please specify version]_ 0.19.2
- [X]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?
Pokemon Mystery Dungeon 2: Explorers of time (E)
Pokemon Mystery Dungeon 2: Explorers of shadow (E)
Game goes here if applicable

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1. boot latest Twl menu
2. launch roms
3.

### Other notes

when i launch this game with and without save the game don' want boot i see "loading" but after blank screen

**Comment by RocketRobz** [comment]
v0.19.2 do not have the loading screens, so you're not on the latest nds-bootstrap.
Also, make sure you're on TWLMenu++ v8.1.1.

**Comment by Kikou3344** [comment]
i have updated but same problem with 

Pokemon Mystery Dungeon 2: Explorers of Sky (E)

**Comment by RocketRobz** [comment]
Your ROMs might be corrupted then.

**Comment by RocketRobz** [comment]
Try holding L immediately after pressing A/START to launch the game.

**Comment by Kikou3344** [comment]
i have try this trick is work perfectly
how to set this permanently?

**Comment by RocketRobz** [comment]
Wait for the next version of TWLMenu++ to be released.
