### ISSUE TITLE
black "an error has occurred" when launching twilightmenu

### ISSUE THREAD

**Issue by 33snowballs** [ahezard/nds-bootstrap#629]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  latest as of 5/6/19
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

twilightmenu++

### Expected behaviour

should open dslite-looking menu

### Actual behaviour

black screen with "an error has occurred. please hold down the power button to turn the system off"

### Steps to reproduce

1. open twilightmenu++
2. press a
3. tap the touch screen when prompted
4. error

### Other notes

this is my first time using twilightmenu++

**Comment by RocketRobz** [comment]
Wrong repo.
Also, don't use the TWiLight Menu++ Launcher, install the TWiLight Menu++ Updater, and after that, launch TWiLight Menu++ directly from the 3DS HOME Menu.

**Comment by 33snowballs** [comment]
@RocketRobz i've tried to install the cias for twilight menu++ and twilight menu++ game launcher a couple of times but every time they just disappear. im extremely new to this all so forgive me if the answer is obvious

**Comment by RocketRobz** [comment]
Try rebooting the console.

**Comment by 33snowballs** [comment]
i guess sixth time was a charm, because after the sixth cia install it worked! thanks for your patience & advice :)
