### ISSUE TITLE
Kirby Super Star Ultra Can't find save file.

### ISSUE THREAD

**Issue by Redswastaken** [ahezard/nds-bootstrap#63]
When I try to launch super star ultra the game gives me a message saying that the save file could not be accessed, and to power off and remove the game cart. I'd tried booting up the game without a game cart inserted and the issue persisted

NOTE: I'm running the roms from my micro sd card

**Comment by Robz8** [comment]
You forgot to set a donor rom.

**Comment by Redswastaken** [comment]
huh? I dont think i know what that is.

**Comment by Robz8** [comment]
Set as donor ROM: Applies an ARM7 binary from the set donor, to the game you're running with non-working saves.

In TWLoader, press SELECT when the cursor is on MKDS, and select "Set as donor ROM".

**Comment by maorninja** [comment]
@ahezard Can this be closed, since it already has been resolved?

**Comment by Robz8** [comment]
Are you not able to close the issue yourself?

**Comment by maorninja** [comment]
Um, I can't. I don't have repo access...
