### ISSUE TITLE
This Edition of nds-bootstrap can only be used on the SD Card

### ISSUE THREAD

**Issue by ProgrammingHider** [ahezard/nds-bootstrap#630]
### Your console

- [ ]  DS Lite

### CFW and configuration

- [ ] Flashcard (R4i Gold)

### nds-bootstrap version

- [ ]  Release _[0.19.2]_

### Expected behaviour

1. TWiLightMenu++ Should boot up
2. The Selected Game/Homebrew should load via nds-bootstrap
3. The Game/Homebrews loading screen should appear

### Actual behaviour

1. TWiLightMenu++ Boots
2. The Selected Game/Homebrew tries to lauch
3. A heartwarming message appears, [Kinda Like This](https://imgur.com/a/Vas8d2U):
This edition of nds-bootstrap can only be used on the SD Card

### Steps to reproduce

1. Install TWiLightMenu++
2. Install nds-bootstrap 0.19.2
3. Be Disappointed

### Other notes

Some Homebrew Tiltles do load

**Games tested**:
Mario Kart DS
Super Mario 64 DS
DSLinux

**Comment by SuperSaiyajinVoltZ** [comment]
You Need B4DS for the Flashcard. NDS-Bootstrap is only for DSi and 3DS with TWiLightMenu++ installed on the console.

**Comment by androidian5980** [comment]
> You Need B4DS for the Flashcard. NDS-Bootstrap is only for DSi and 3DS with TWiLightMenu++ installed on the console.

Where can you find said "B4DS"?
