### ISSUE TITLE
Pokemon Diamond Ranomizer not working.

### ISSUE THREAD

**Issue by HawkEagel** [ahezard/nds-bootstrap#631]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X ]  Release _[0.19.2]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
Pokémon Diamond

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

Whitescreen on load up the randomizer .nds.

**Comment by RocketRobz** [comment]
Try holding L immediately after pressing A/START to launch the game (if you're not in the Acekard theme).

**Comment by HawkEagel** [comment]
Thanks is working!

**Comment by RocketRobz** [comment]
What region is the ROM?

**Comment by HawkEagel** [comment]
German

**Comment by RocketRobz** [comment]
Hmm. Does the clean german ROM work without holding L?

**Comment by NightYoshi370** [comment]
I think this could be closed now since OP said that it works for him (unless I'm missing something in which case, reopen this)
