### ISSUE TITLE
Metroid Prime Hunters white screen

### ISSUE THREAD

**Issue by chinook9** [ahezard/nds-bootstrap#632]
### Your console

Tell us which console do you have:
- [X]  DSi (XL)

Tell us which CFW do you have:
DSi:
- [X]  Unlaunch+HiyaCFW (unlaunch ver 8.1.1, HiyaCFW ver 1.8)

### nds-bootstrap version

Tell us which versions you are using:
- [X]  Release (0.19.4)

### If this issue only affects a certain game, which game is it?
Metroid Prime Hunters (USA)

### Expected behaviour
Loading into a planet when selected from the map screen

### Actual behaviour
Game hangs on a white screen when a planet is selected

### Steps to reproduce
1. Create a new game
2. After cutscenes play, select a planet on the map screen
3. Once the ship flying scene plays after "land ship" is selected, the game will hang.

Also tested with 0.19.2, and disabling heap shrink.

**Comment by Pik-a-boo** [comment]
Also you cant play online.
But then you would get a black screen lol.

**Comment by ahezard** [comment]
I cannot reproduce with heap shrink disabled. Remember that you have to wait a while on the white screen.

**Comment by Pik-a-boo** [comment]
Disable heap shrink for online play?

**Comment by chinook9** [comment]
Looks like it's fixed in 0.19.4 with heap shrink disabled. I only tested disabling heap shrink in 0.19.2.
