### ISSUE TITLE
Error 1 nds-bootstrap not found.

### ISSUE THREAD

**Issue by CloudyShintou** [ahezard/nds-bootstrap#633]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [v8.2.2 ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

The game SHOULD start up like a normal DS Game but they do not.

### Actual behaviour

My games won't open, saying "Start failed. Error 1 nds-bootstrap not found."

### Steps to reproduce

1. Open TWiLight
2. Select NDS file in roms and pick the game 
3. Launch game

### Other notes
After I launch the game, it gives me error 1.

**Comment by RocketRobz** [comment]
You have to download and install nds-bootstrap.
