### ISSUE TITLE
Pokémon Dash Freezes before Title Screen

### ISSUE THREAD

**Issue by Gumdradude** [ahezard/nds-bootstrap#634]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[19.5]
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokémon Dash

### Expected behaviour

Game loads up normally

### Actual behaviour

Game freezes and randomly flashes before getting to the Title Screen 
![20190515_225734](https://user-images.githubusercontent.com/27980228/57830316-9879cf00-7766-11e9-9bb1-60eaed8093ee.jpg)

### Steps to reproduce

1. Start up Pokémon Dash
2. Wait a few seconds
3.

**Comment by ahezard** [comment]
Same as #286 the current behavior is expected with the current state of the code. Closed for duplication.
