### ISSUE TITLE
MapleStory DS and Spider-Man 3 white screen, etc.

### ISSUE THREAD

**Issue by zeroultima6** [ahezard/nds-bootstrap#636]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [*]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [*]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [*]  Release _0.19.5_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
MapleStory DS
Spider-Man 3
### Expected behaviour

Tell us what should happen

Game works as normal

### Actual behaviour

Tell us what happens instead

MapleStory DS white screens on boot
Spider-Man 3 has a "Could not read data error".

### Steps to reproduce

1.
2.
3.

### Other notes
And yes, MapleStory DS is AP patched.

**Comment by ahezard** [comment]
spiderman 3 works for me please try  with latest nigthly, seems to be the issue fixed in c31ab31

**Comment by ahezard** [comment]
maplestory white screen indeed while it was working before (see #483)

**Comment by zeroultima6** [comment]
Spider-Man 3 does indeed work on the latest nightly, for now i'll wait on the maplestory ds fix
