### ISSUE TITLE
Black Sigil, Bleach: Dark Souls, etc. bug

### ISSUE THREAD

**Issue by zeroultima6** [ahezard/nds-bootstrap#637]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [*]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [*]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _0.19.5_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

Black Sigil: Blade of the Exiled
Bleach: Dark Souls
Sonic Chronicles: The Dark Brotherhood

### Expected behaviour

Tell us what should happen

Black Sigil: Blade of the Exiled: Game works as normal
Bleach: Dark Souls: Game works as normal
Sonic Chronicles: The Dark Brotherhood: Game works as normal

### Actual behaviour

Black Sigil: Blade of the Exiled: white screens on boot with BGM playing
Bleach: Dark Souls: save data corrupts upon booting
Sonic Chronicles: The Dark Brotherhood: upon saving the game it white screens

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Other notes
Black Sigil: Blade of the Exiled was working before on 0.19.2 Edit: remembered it wrong, its not 0.19.0

**Comment by RocketRobz** [comment]
Try holding L for Black Sigil

**Comment by zeroultima6** [comment]
Holding L doesn't work for Black Sigil

**Comment by RocketRobz** [comment]
What happens in v0.19.1?

**Comment by zeroultima6** [comment]
White screens on v0.19.1 for that game

**Comment by zeroultima6** [comment]
Wait, it was on 0.19.2 where it last working, sorry

**Comment by zeroultima6** [comment]
I can confirm Black Sigil works on the latest nightly, the other two games are minor annoyances at the moment

**Comment by RocketRobz** [comment]
Can you check Bleach on v0.26.1?

**Comment by zeroultima6** [comment]
> Can you check Bleach on v0.26.1?

Sorry for the late reply, Bleach Dark Souls still had the same problem on 0.26.1 and 0.27.0

**Comment by Monalisashusband** [comment]
Tested Bleach Dark Souls on 0.27.0 now loads on white screen then black screen after a second. Tried different rom combination settings as well: DS mode - NTR, DSi mode - TWL, etc.

**Comment by Monalisashusband** [comment]
Tested Bleach Dark Souls on 0.28.0 still same results, white then black screen, let me get a clean dump and get back to this

**Comment by RocketRobz** [comment]
What about with heap shrink off?

**Comment by Monalisashusband** [comment]
@RocketRobz false alarm had a bad dump will recheck all dumps before posting my apologies
