### ISSUE TITLE
Running DSiWare for the first time resets console

### ISSUE THREAD

**Issue by snoozysoft** [ahezard/nds-bootstrap#638]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch _v1.8_ + HiyaCFW _(no idea how to find version number, presume latest.)_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _0.19.5_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

After selecting a DSiWare title to play, the console/nds-bootstrap creates a public save file and boots straight into the game/title.

### Actual behaviour

After selecting a DSiWare title to play, nds-bootstrap will make a public save file and then reboot the console, taking me back to TWiLight Menu++.

### Steps to reproduce

1. Load a DSiWare title onto the SD card.
2. Open it up with TM++
3. Sit back and watch

### Other notes

I have no idea if this is actually intended behaviour or a bug, but it's certainly a confusing sight to behold. This only affects DSiWare titles on their first run, consequent runs (regardless of if the console has been turned off or not) will load immediately thereafter. If this is intended then it's certainly a confusing thing to have happen - is there a way to make it immediately boot into the users choice after that reboot happens, perhaps?

**Comment by FlameKat53** [comment]
This is an issue with Unlaunch, not nds-bootstrap

**Comment by ahezard** [comment]
Indeed, nds-bootstrap does nothing with dsiware.

**Comment by snoozysoft** [comment]
Ah, my apologies. It's incredibly unclear what part does what with all of this so I had no idea. There's so many working parts to DSi CFW...

**Comment by ahezard** [comment]
Ok no problem
