### ISSUE TITLE
Metroid Prime: Hunters hangs on black screen entering gameplay

### ISSUE THREAD

**Issue by the-conceptionist** [ahezard/nds-bootstrap#640]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.19.5]_
- [ ]  Nightly 

### If this issue only affects a certain game, which game is it?

Metroid Prime: Hunters (USA)

### Expected behaviour

After entering a game, the main gameplay should load and the player should be able to play the game.

### Actual behaviour

After transitioning off of a menu screen to go into gameplay, the game hangs on a black screen without audio. The L+R+DOWN+START combo for TWiLight Menu does not work on this screen.

### Steps to reproduce

1. Enter game.
2. Go through menu of choice to access gameplay.
3. Start a game.

### Other notes

67MHz CPU speed (issue isn't fixed on 133MHz)

**Comment by RinMaru** [comment]
use the latest nightly TWLMenu

**Comment by FlameKat53** [comment]
or hold the L button right after pressing A to launch the game
