### ISSUE TITLE
Pokemon rom nds bootstrap not found error 1

### ISSUE THREAD

**Issue by ap1kay** [ahezard/nds-bootstrap#641]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v.0.19.5]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

all pokemon roms
### Expected behaviour

Game would launch 
### Actual behaviour

nds_boostrap not found error 1, even though I have it installed as instructed

### Steps to reproduce

1. Select Pokemon roms in TWiLight Menu
2. Directly after opening the rom it freezes
3. "Start failed. Error 1/ nds-bootstrap not found."

### Other notes
I have got this error for many games, currently using a pokemon white rom. the pokemon white rom is created from a cartridge gm9 dump. My nds-boostrap is in my sd card under: "_nds" "nds-bootstrap" and inside are the files "nds-bootstrap-hb-release.nds" and "nds-bootstrap-release.nds". the file named "release-bootstrap.ver" is found under: "_nds" "TWiLightMenu".

**Comment by Epicpkmn11** [comment]
`nds-bootstrap-release.nds` needs to be in just `sd:/_nds/nds-bootstrap-release.nds` not `sd:/_nds/nds-bootstrap/nds-bootstrap-release.nds`

**Comment by RocketRobz** [comment]
The nds-bootstrap .nds files have to be outside the `nds-bootstrap` folder, and should be in the same folder as `nds-bootstrap.ini`.

**Comment by Bulbasaurio** [comment]
Something similar happens to me but I get the message "Not found (null) please recreate the forwarder with the correct rom path", the same only with pokemon roms.

**Comment by Epicpkmn11** [comment]
> Something similar happens to me but I get the message "Not found (null) please recreate the forwarder with the correct rom path", the same only with pokemon roms.

What exactly are you doing when that happens? I know that will happen if you try to load the `sdcard.nds` file from the forwarder template directly, if you're doing that you should be loading the forwarder ROM, not the `sdcard.nds` file. If you're trying to use TWiLight Menu++ then you should just be loading the game directly.

If you're trying to make a forwarder, see this guide: https://wiki.ds-homebrew.com/ds-index/forwarders

**Comment by koolman12333** [comment]
my dsi says start failed error 1 nds-bootstrap (Release) not found

**Comment by RocketRobz** [comment]
> my dsi says start failed error 1 nds-bootstrap (Release) not found idk how to fix it help pls

Are you using TWiLight Menu++ or forwarders?

**Comment by koolman12333** [comment]
Twilight Menu++ why?

**Comment by koolman12333** [comment]
TWilight Menu++ why?

**Comment by RocketRobz** [comment]
> TWilight Menu++ why?

Which guide did you follow to install it?

**Comment by koolman12333** [comment]
a video I saw that was 2 years ago

**Comment by RocketRobz** [comment]
> a video I saw that was 2 years ago

Please don't follow video guides. Follow this guide to repair your TWLMenu++ installation: https://wiki.ds-homebrew.com/twilightmenu/updating-dsi
