### ISSUE TITLE
white screen on load up of nds roms after messing with save files

### ISSUE THREAD

**Issue by ap1kay** [ahezard/nds-bootstrap#642]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v.0.19.5]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?
Pokemon white, pokemon blaze black

### Expected behaviour

The rom should load and run as usual

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1. Open the nds rom from TWiLightMenu++
2. After opening: (blaze black) a white screen after opening OR (white) "Now saving" and then after the screen, it gives a white screen
3. 

### Other notes
I was messing with the save files in the saves directory under >_nds >roms >nds >saves and i deleted save files for pokemon white after losing progress and wanting to restart. I deleted and when opening the rom again it stated that it created a new file, saved to the file, and then gave a white screen. the same thing happened on the first load up of my blaze black rom (create save file, saved, white screen). after deleting save files for pokemon white it says (along the lines of) "creating save file, file saved" the nds bootstrap logo loads into the screen, and afterwards it is a white screen

**Comment by RocketRobz** [comment]
The ROMs should be loaded in DS mode, and if you have cheats enabled, try disabling them.

**Comment by Ardakilic** [comment]
For anyone checking this, try disabling WiFi and NFC from 3DS/2DS settings and re-start the TWiLightMenu++ , that may fix your issue, at least it did for me.
