### ISSUE TITLE
Download play freezes on nintendo screen

### ISSUE THREAD

**Issue by Asif6474** [ahezard/nds-bootstrap#643]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.19.5]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Download play to another 3ds/ds system works fine, with no issues.

### Actual behaviour

The games freezes on the receiving 3ds at the nintendo screen.

### Steps to reproduce

1. Launch Game
2. Select Local Multiplayer
3. Receive game on another 3ds/ds system via download play

**Comment by RocketRobz** [comment]
This is a known issue. It's due to cloneboot not working for some games.

**Comment by Asif6474** [comment]
Is there a list of games where it wont work?

**Comment by RocketRobz** [comment]
afaik, there isn't.

**Comment by Asif6474** [comment]
Thanks for you fast response!

**Comment by NightYoshi370** [comment]
Please use the cloneboot issue to speak about this
