### ISSUE TITLE
nds-bootstrap not working on flashcard with all files in place

### ISSUE THREAD

**Issue by androidian5980** [ahezard/nds-bootstrap#644]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour
Runs the .nds rom

### Actual behaviour
Dosen't boot up rom

### Steps to reproduce

1.Have ROMs on flashcard
2.Start front-end
3.Start game
4. Error

### Other notes
I am running TWiLightmenu++ from a R4iSDHC flashcard

**Comment by FlameKat53** [comment]
Here’s B4DS, Most games do not boot, atm it’s only known that SDK2 games boot https://github.com/TWLBot/Builds/blob/master/extras/B4DS.7z
