### ISSUE TITLE
[Note] Titles working slowly in the newest release (Kind of solution, speccially NINoKuNi)

### ISSUE THREAD

**Issue by Pokefanmati** [ahezard/nds-bootstrap#645]
First, I'm not a native speaker. That's an important thing.
Second, are you ussing forwarded games? if it that, then you should read me
Third, I do not have any log of this issue, because there is nothing as a crash (or, I'm too stupid to find it out where this could be)
Fourth, I've seen there are some closed post about this, I believe I have new information that could give a new perspective
Fifth, probably I should have posted this on a forum, but i'm pretty sure the people with this isuue will come here any way

Console:
- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)
 
CFW:
- [x]  Luma3DS 9.1
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

nds-bootstrap version
- [X]  Release _[0.19.5]_
- [ ]  Nightly _[]_

### If this issue only affects a certain game, which game is it?

NiNokuni (A lot)
Pokemon MM Explorers of sky (kinda)

### Expected behaviour

Sound issues and kinda slow movement

### Actual behaviour

I think i'm not the first that notice NiNoKuni were going slow 
> https://github.com/ahezard/nds-bootstrap/issues/173

Short answer:
I found this issue is on the NDS forwarder, so it's not a nds-bootstrap issue. Using TWiLight menu should help. I thought you like to know it.

Long answer:
There are (or i thought there were), there are some audio issues and you could spect them.
The thing is... they weren't there before. I updated from 0.17.1 to 0.19.5 and before it worked perfectly.

So I decided to test the Pokemon MM game because of it's size, and even if the audio goes fine, the loading screens don't. They are slower now, noticiable considereing how many map transitions this game have. This does not seem to be a thing in the dungeons any way. So it's not the big deal.

Tested different games and found nothing to report

Then I found it, It is on the NDS forwarder, so it's not a nds-bootstrap issue. I thought you like to now it

### Steps to reproduce

1. Load the forewarded version of NiNoKuni
2. Go to any screen with sound

I took some video if you like to see it. That's it. Please keep doing your excellent work. Love!

**Comment by ahezard** [comment]
So it is a forwarder issue not passing the option to use heap shrink.
