### ISSUE TITLE
Problems with 2 Dragon Ball games

### ISSUE THREAD

**Issue by MarioSonicU** [ahezard/nds-bootstrap#646]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [* ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [* ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [* ]  Release _[0.19.5]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Dragon Ball Z: Harukanaru Densetsu [USA version]
Dragon Ball Origins 2 [USA version]

### Expected behaviour

Dragon Ball Z: Harukanaru Densetsu: Game works as normal
Dragon Ball Origins 2: Game works as normal

### Actual behaviour

Dragon Ball Z: Harukanaru Densetsu: Has a "Could not access save data" error
Dragon Ball Origins 2: Doesn't load even with AP patch

### Steps to reproduce

1.
2.
3.

**Comment by ahezard** [comment]
Can you please try with the latest nightly? The commit c31ab31 fix a lot of "Could not access save data" issues but is not included in 0.19.5 release (will be in the next release)

**Comment by MarioSonicU** [comment]
DBZ: Harukanaru Densetsu works with the nightly, but DB Origins 2 is not working, it just hangs on white screen after boot.

**Comment by RocketRobz** [comment]
Hold L immediately after pressing A/START to launch DB Origins 2.

**Comment by MarioSonicU** [comment]
It works now, but now I'm having another problem. When i reach the save select screen, i hit New Game, and it sends me back to Game select.

**Comment by NightYoshi370** [comment]
Most likely an issue with soft reset

**Comment by MarioSonicU** [comment]
What should I do then?
