### ISSUE TITLE
Certain modes in games go to a white screen upon selecting

### ISSUE THREAD

**Issue by zeroultima6** [ahezard/nds-bootstrap#647]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _0.19.5_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

Bomberman 2
Contact
Professor Layton and the Last Specter

### Expected behaviour

Tell us what should happen

Bomberman 2: Works as intended
Contact: Works as intended
Professor Layton and the Last Specter: Works as intended

### Actual behaviour

Tell us what happens instead

Bomberman 2: Battle mode go to white screen
Contact: Contact mode go to white screen
Professor Layton and the Last Specter: London Life mode go to white screen

### Steps to reproduce

1.
2.
3.

### Other notes

There are other games with a wifi setup option or Dgamer option that has the same issue.

**Comment by dubbz82** [comment]
Current status on this - Professor Layton still white screens on London Life Mode.  Bomberman 2 - Still white screens on battle mode.  Contact - I don't have a save for this game, so it won't allow me to go into contact mode.  I may sink some more time into the last one later, though I suspect that it may be soft resetting to go into these modes?

**Comment by RocketRobz** [comment]
Fixed in v0.30.0, which implements soft-reset.
