### ISSUE TITLE
Error 1 nds-bootstrap not found

### ISSUE THREAD

**Issue by Remco4444** [ahezard/nds-bootstrap#649]
### DS Lite

Tell us which console do you have:

-   DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

-   (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
-   Other CFW [I use a ds]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
-   Nightly _[The version included in the latest Twilight Menu++]_

### If this issue only affects a certain game, which game is it?

This happens in all games i have.

### Expected behaviour

The game should start

### Actual behaviour

I get the error: Error 1. nds-bootstrap not found

### Steps to reproduce

1. Start Twilight Menu++
2. Goto the menu
3. Start a game

**Comment by SuperSaiyajinVoltZ** [comment]
You missed `nds-bootstrap-nightly.nds` / `nds-bootstrap-release.nds`.

**Comment by Remco4444** [comment]
I have nds-bootstrap-nightly.nds.
But in the settings it displays no nds-bootstrap version found.
In the picture below you can see i have the .nds in the folder.
![twlightmenu1](https://user-images.githubusercontent.com/51338223/58829363-f2740300-8647-11e9-900b-840e91d51745.PNG)

**Comment by Remco4444** [comment]
I have run the nds-bootstrap-nightly.nds.
When i do that i get the error 'FAT init failed!'
This makes me question, do i have to format my micro sd card to FAT or does this mean something else.

**Comment by RocketRobz** [comment]
You have to launch a game.

**Comment by ahezard** [comment]
What do you mean by Other CFW [I use a ds] ? Are you running on a flashcard?

**Comment by Remco4444** [comment]
ahezard, I meant that I didnt use a dso but a ds/ds lite as you can see at the top.

RocketRobz:
Thats the problem if I run a game it fails to start.
Il link a video down below.
In the first part you see that the games do work.
In the second part you see that twilight doesnt detect a nds-bootstrap and it gives an error when starting a game.
In the third part you see that I get the error FAT init failed!
https://youtu.be/a2pI5Gy_Dzo

**Comment by SuperSaiyajinVoltZ** [comment]
You Need B4DS, and B4DS doesn't have a good Compatibility. I would reccomend use the Flashcard Firmware, to play your Games.

**Comment by Remco4444** [comment]
I have checked the compatibility list and my games work and some not fully.
So im ok with bad compatibility.
But I cant B4DS.

**Comment by Remco4444** [comment]
Does anyone know where to find B4DS?
I have searched but i cant find it.

**Comment by Raichu170** [comment]
Rip
