### ISSUE TITLE
Elite Beat Agents loads kinda.

### ISSUE THREAD

**Issue by skyboy8** [ahezard/nds-bootstrap#65]
I had a pokemon sun cartridge in the slot. loading EBA, it would say "Cannot access data. Turn off the power and reinsert the game card". I decided to take the cartridge out and load it again. Booted it up and i loaded the boot screen of EBA going to the start screen. The audio lagged and when i toughed the screen, i thought id be able to play the game but it froze on a black screen for like 2 minutes then went to the first boot tutorial. Very laggy and choppy audio.

**Comment by Margen67** [comment]
This should be added to the compatibility list. https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit?usp=sharing

**Comment by ahezard** [comment]
Similar issue as #66 , bootstrap does not like data streaming from sd card currently. Proper async prefetch implementation may help in the future. This is being worked on into the async branch.

**Comment by Robz8** [comment]
Fixed in 0.6.0 and 0.6.1.
