### ISSUE TITLE
Stuck on DScraft Title Screen

### ISSUE THREAD

**Issue by YESPLZOK** [ahezard/nds-bootstrap#650]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v19.5]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

The game should allow you to get past the title screen.

### Actual behaviour

You can't tap on any of the options on the title screen so you will be stuck. (Animations still take place)

### Steps to reproduce

1. Boot up the game.
2. Wait for the title screen.
3. You get stuck

### Other notes
- I used direct boot in TWiLight Menu with all of the default settings 
-Somebody said DScraft works fine on a DSi with the fat version of the game, but I tried on 3DS and still couldn't tap anything
-Aperture Science DS has the same problem.

**Comment by NightYoshi370** [comment]
Put the FAT version on both the root and the same directory as the game, then try again.
Also, direct boot will not work

**Comment by YESPLZOK** [comment]
@NightYoshi370 If I don't use direct boot the game keeps on crashing. Also dscraft comes with an .nds file and a folder

**Comment by arraystock** [comment]
Did you put the folder on the root of your SD?

**Comment by YESPLZOK** [comment]
@arraystock yes

**Comment by ahezard** [comment]
It seems that you need also to put the nds on the sd root
https://gbatemp.net/threads/dscraft-in-twilight-menu.540432/

**Comment by RocketRobz** [comment]
Touch not working is normal, as it's due to a bug related to touch input on 3DS, in the libnds version used at the time.
