### ISSUE TITLE
Mario 64 DS White Screen

### ISSUE THREAD

**Issue by NoMod-Programming** [ahezard/nds-bootstrap#651]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [X]  (No CFW) Unlaunch only _1.8_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _0.19.5_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Mario 64 DS (EU)

### Expected behaviour

Game should boot and play normally

### Actual behaviour

There is a white screen after loading the ROM, and if the built-in crash debugger is loaded (`L+R+Left+A`, then `Down+B` and `Start+Select`), the game goes to a black screen

### Steps to reproduce

1.
2.
3.

### Other notes

Not patched and is an original rom, however this game did work on an earlier version of nds-boostrap (unknown how long ago, I had to reinstall a while ago)

**Comment by RocketRobz** [comment]
Does the US ROM work?

**Comment by NoMod-Programming** [comment]
Just downloaded it and tested it, and yes, the US ROM does work

**Comment by RocketRobz** [comment]
Are cheats enabled for the EU ROM?

**Comment by NoMod-Programming** [comment]
Nope, I've tried enabling and disabling the VRAM boost option as well, and changing between DS mode and DSi mode with no difference

**Comment by ahezard** [comment]
I am not able to reprodiuce the issue. The game works.

**Comment by RocketRobz** [comment]
Try deleting the `settings.ini` file at `sd:/_nds/TWiLightMenu/`, and `nds-bootstrap.ini` at `sd:/_nds/`.
It fixed the issue for one user, if there's no issue with the ROM itself.

**Comment by tilse** [comment]
just wanted to comment here because i had the same issue but it turns out at some point my luma settings were reset so it couldn't apply the circle pad controls hack. what i did to fix it was:
- boot up the system while holding select
- enable game patching again

**Comment by soniola** [comment]
old 3ds same problem, white screen sm64ds original rom with dsi mode active, i don't have any patch active, and the rom refuses to boot

**Comment by RocketRobz** [comment]
> old 3ds same problem, white screen sm64ds original rom with dsi mode active, i don't have any patch active, and the rom refuses to boot

Does it work fine with DS mode? If so, then there is no point in using it with DSi mode, even though there should be no issues with it.

**Comment by soniola** [comment]
> > old 3ds same problem, white screen sm64ds original rom with dsi mode active, i don't have any patch active, and the rom refuses to boot
> 
> Does it work fine with DS mode? If so, then there is no point in using it with DSi mode, even though there should be no issues with it.

well, i want to play with the 60 fps patch, and a friend said that the dsi mode give better perfomance, first i tried the normal rom and does not work after that the custom rom with 60 fps patch does not work, and he have an old twlmenu version that runs on dsi mode sm64ds, idk why the most actual version can not run the game 

his twl menu version is: 17.0.0
mine: 27.5.1

**Comment by soniola** [comment]
and yes, ds mode can run the both version of the game on my old 3ds

**Comment by RocketRobz** [comment]
> and yes, ds mode can run the both version of the game on my old 3ds, but the 60fps patch has some terrible slowdowns on all maps, excluding outside and inside the castle and slides

Then just set ARM9 CPU Speed to TWL.
