### ISSUE TITLE
Pokemon Black/White white screen regardless of the AP patch

### ISSUE THREAD

**Issue by marysiamzawka** [ahezard/nds-bootstrap#653]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch1.9+HiyaCFW 3.2

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release 0.19.5
- [X]  Nightly 4cb2763

### If this issue only affects a certain game, which game is it?

Pokemon Black/White [UE]

### Expected behaviour

Game starts in any way or form

### Actual behaviour

White screen

### Steps to reproduce

1. Open the ROM through TWLMenu++
2. Watch the whiteness

### Other notes
Happens regardless of running release/nightly. Tried through Unlaunch for shits and giggles and got a black screen

**Comment by RocketRobz** [comment]
The game has to be launched in DS mode.
