### ISSUE TITLE
Goosebumps HorrorLand not working

### ISSUE THREAD

**Issue by Markieyer** [ahezard/nds-bootstrap#655]
### Your console

Tell us which console do you have:

- [X]  DS Phat/Lite
- [✓]  DSi (XL)
- [X ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [✓, latest versions]  Unlaunch+HiyaCFW _[please specify versions of both]_

### nds-bootstrap version

Tell us which versions you are using:

- [✓, latest]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Goosebumps HorrorLand

### Expected behaviour

Game should start normally and be playable

### Actual behaviour

The game boots up to a weird "Nintendo 3DS" screen and then goes white, and I have to restart the DSi

### Steps to reproduce

1.  Open the game on TwilightMenu++

**Comment by RocketRobz** [comment]
Sounds like you aren't on the latest nds-bootstrap. The latest does not show any loading screen before booting a game.
Please update it.

**Comment by Markieyer** [comment]
I went ahead and updated my nds-bootstrap, same thing, it shows a weird 3DS loading screen and then goes to a white screen, it's only with this game in particular, all other games work fine

**Comment by RocketRobz** [comment]
What exact nds-bootstrap version did you download?
Also, are you using Release or Nightly version of nds-bootstrap (check TWLMenu++ settings).
And also, you might need to hold L immediately after pressing A/START to launch the game.

**Comment by Markieyer** [comment]
I downloaded the the latest, v0.20.0, I downloaded the Release, not Nightly, and now I've approached a different issue after updating my bootstrap, adding ANY game now causes an error on boot that says something like "Guru Meditation Error! Data abort!"

**Comment by RocketRobz** [comment]
If you're on the Acekard theme, then please switch to another theme, as the Acekard theme isn't stable.

**Comment by Markieyer** [comment]
In actually on the 3DS theme

**Comment by Markieyer** [comment]
I've tested every theme and all of them either crash on start or crash when going to an emulator folder, same Guru meditation error, only theme that works is R4 and a big problem with it is that new games don't show up, this happened after updating my bootstrap, why?
