### ISSUE TITLE
Radiant Historia flicking screen

### ISSUE THREAD

**Issue by zeroultima6** [ahezard/nds-bootstrap#656]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.20.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

Radiant Historia
Age of Empires: Mythologies

### Expected behaviour

Tell us what should happen

Radiant Historia: Works as intended
Age of Empires: Mythologies: Works as intended

### Actual behaviour

Tell us what happens instead

Radiant Historia: flicking screens (top and bottom) on some of the menus and the intro
Age of Empires: Mythologies: flicking screens on the map during gameplay

### Steps to reproduce

1.
2.
3.

### Other notes

CPU settings are the same

**Comment by RocketRobz** [comment]
> CPU settings are the same

So NTR clock speed didn't fix this?
Might be another issue related to card read DMA.

**Comment by zeroultima6** [comment]
It consistently works up until this point in this version its somewhat broken.

**Comment by hubert-skowronek** [comment]
I confirm that on 19.5 there is no flickering

**Comment by dubbz82** [comment]
given that this has been confirmed working correctly on newer builds, should this issue be closed out?
