### ISSUE TITLE
Tales of Hearts white screen

### ISSUE THREAD

**Issue by zeroultima6** [ahezard/nds-bootstrap#657]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.20.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

Tales of Hearts-Anime Movie Edition

### Expected behaviour

Tell us what should happen

Tales of Hearts-Anime Movie Edition: Works as intended

### Actual behaviour

Tell us what happens instead

Tales of Hearts-Anime Movie Edition: white screens on boot (was working on 0.19.5 or earlier)

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
Try replacing your ROM, in case if it got corrupt.

**Comment by zeroultima6** [comment]
Its working again as it should, don't know why it corrupts itself though.

**Comment by RocketRobz** [comment]
Sounds more like an issue with your SD card.
Please check it for errors, if you haven't done so yet.
