### ISSUE TITLE
Cars crash when exiting a mini-game

### ISSUE THREAD

**Issue by ahezard** [ahezard/nds-bootstrap#658]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.20.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

0458 - Cars (USA)

### Expected behaviour

Game do not crash

### Actual behaviour

Game crash when exiting a mini game

### Steps to reproduce

1. Launch the game
2. when the first mini-game start enter the menu
3. exit

**Comment by ahezard** [comment]
[[ Fatal Error: ARM9CPU stopped running because "Data access exception" occurred. ]]

   Symbol: STATIC:0x02000A28
   02000A28:  00000000       ANDEQ      R0, R0, R0

   CPSR:8000001F
     R0:02000B48  R1:0217386C  R2:02173878  R3:0216D500
     R4:027E0001  R5:01000101  R6:080205D9  R7:00000000
     R8:00000000  R9:00000000 R10:00000000 R11:00000000
    R12:07000400  SP:027C3B7C  LR:0200088C  PC:02000A28
This is for cars
this is like a software reset by the way
0x02000A28 is like the start of the code
it is before that the start of the code actually
this is the issue
I see no issue for cars

**Comment by NightYoshi370** [comment]
Does this happen on the latest nds-bootstrap? Seems like it's related to soft-reset

**Comment by RocketRobz** [comment]
Nope, it doesn't.
