### ISSUE TITLE
Winx Club: Saving Alfea white screen

### ISSUE THREAD

**Issue by zeroultima6** [ahezard/nds-bootstrap#659]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.20.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen

Winx Club: Saving Alfea: works as intended to be

### Actual behaviour

Tell us what happens instead

Winx Club: Saving Alfea: white screens on boot

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
Is the ROM AP-patched?

**Comment by zeroultima6** [comment]
That patch in particular doesn't exist yet so no

**Comment by ahezard** [comment]
[[ Fatal Error: ARM9CPU stopped running because "Data access exception" occurred. ]]

   Symbol: STATIC:0x01FF9C4C
   01FF9C4C:  E790320E       LDR        R3, [R0, LR, LSL #4]

   CPSR:6000001F   
     R0:00000000  R1:027E3FFC  R2:021415C0  R3:0213C280
     R4:027E0EA0  R5:027E0000  R6:027E0EA0  R7:00000000
     R8:023F4868  R9:04000000 R10:00000000 R11:00000000
    R12:00000000  SP:027E3770  LR:00000000  PC:01FF9C4C

**Comment by RocketRobz** [comment]
Turns out the tested ROM is a bad dump.
Try searching the ROM elsewhere.
