### ISSUE TITLE
White screen issue with wifi/online features in games

### ISSUE THREAD

**Issue by westinhouse** [ahezard/nds-bootstrap#660]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.20.0]_
- [ ]  Nightly _[insert here commit hash]_

### If this issue only affects a certain game, which game is it?

Pokemon Diamond
Pokemon Platinum
Pokemon White 2
Tetris DS

### Expected behaviour
Enter the wifi configuration and back to home menu flawlessly.

### Actual behaviour
Game stucks in a white screen.

Hi, i'm not an english speaker (I speak spanish), but I can't find any solution to this issue so I'll sharing here.
Any time I try to enter the in-game options dedicated for online and wireless features (for both worldwide and local connections with other ds consoles), when I back to main menu, the game shows a white screen. I try dowloading another roms and ap patched them, but the problem persists. Also I tried to start the application in ds mode, dsi mode, vram on and off, both processors configurations and nothing works. 
Is there an actual solution to this problem? I notice that Pokemon games gave me this issue, but I try same options in a random different game like Tetris DS and result was the same. 
As a final comment, in all this games the app does not recognize the soft reset combination buttons.

### Steps to reproduce

1. Open any game and enter to wifi/online features.
2. Back to main menu of the game.

### Other notes
I want this working to play online features in Pokemon mostly. I want to connect with GTS using available tutorials on the web.

**Comment by RocketRobz** [comment]
When you exit the WiFi settings, the game soft-resets, which doesn't work yet.

**Comment by MojoJojoDojo** [comment]
If you use a 3DS just change the wifi settings from the 3DS settings menu.
I hope one day there would be a way to change wifi settings from Twilightmenu itself 
it would be more easy that way.

**Comment by ahezard** [comment]
This needs #259 to be implemented

**Comment by Stack3r** [comment]
Closing this, soft reset implementation has fixed this issue
