### ISSUE TITLE
Transformers: Autobots no longer launches

### ISSUE THREAD

**Issue by kingcailan** [ahezard/nds-bootstrap#661]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch v1.9, HiyaCFW v1.3.1]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### nds-bootstrap version

Tell us which versions you are using:

- I tested both the Stable and Nightly releases included with TwilightMenu++ v8.3.0
- [x]  Release _[0.20.0]_
- [x]  Nightly _[df9f55d]_

### If this issue only affects a certain game, which game is it?

Transformers: Autobots

### Expected behaviour

Game should launch, albeit without save capability (According to the Compatibility list)

### Actual behaviour

Game Whitescreens on launch.

### Steps to reproduce

1. Attempt to launch game.

**Comment by ahezard** [comment]
Was the game working before? With which release? Try to press L booting the game.

**Comment by RocketRobz** [comment]
^ Hold L immediately after pressing A/START to launch the game.

**Comment by Greenaxe64** [comment]
Transformers worked on dsimenu++ version 1.1.0 but when I updated to the latest twilightmenu and updated the bootstrap it now requires holding L to launch and when it does there are visual glitches not present in the older bootstrap

**Comment by dubbz82** [comment]
Current status - Game boots without needing L held.  I do see occasional black screen flickering, Not sure if that's what's being referred to as far as visual glitches or not?
