### ISSUE TITLE
Solatorobo (U) [Patched] 

### ISSUE THREAD

**Issue by Mauritus** [ahezard/nds-bootstrap#662]
Hello good devs! Amazing software you guys do, it is really impresive work. Thank you. ∑:3

### My System
-New 3DS
-Luma3DS
-Release v0.20.0
- the game is Solatorobo (U) [patched already]. SDK5, i think.

### Expected behaviour

used to load and playable on older versions of the nds-bootstrap (v.0.17.1)

### Actual behaviour

it just hangs in top Black screen, white on the bottom screen, right after the nds-bootstrap screen. 

### Steps to reproduce

just updated to latest to lastest TWLmenu++ (v8.3.0) and nds-bootstrap (v0.20.0) with TWLmenu++ updater to Release. [Not nightly]
started trying the games and got to this one that compatibility was broken.

**Comment by RocketRobz** [comment]
The game has to be run in DS mode, not DSi mode.

**Comment by Mauritus** [comment]
indeed it was. pressed Y to meke sure it is running in DS mode.

**Comment by RocketRobz** [comment]
Replace your ROM then. It might've got corrupted somehow.

**Comment by Mauritus** [comment]
already deleted the ROM last night from the Micro SD, and used ap patch on fresh ROM.

**Comment by RocketRobz** [comment]
I can run the game just fine.

Are any cheats enabled?

**Comment by Mauritus** [comment]
redumped my copy and used the new ROM file.
patched with multipatch and seems to work. 
will try to get to the save point later today to confirm it works appropiately.
