### ISSUE TITLE
Feel the Magic

### ISSUE THREAD

**Issue by piratesephiroth** [ahezard/nds-bootstrap#663]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.21.1]_
- [x]  Nightly _[8492898]_

### Your device

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Feel the Magic XX-XY

### Expected behaviour

Old SDK 2 game, so should probably work

### Actual behaviour

Stuck in a black screen after the SEGA/Sonic Team logo

### Steps to reproduce

1. Just run the game

**Comment by RocketRobz** [comment]
Try holding L immediately after pressing A/START to launch the game.

**Comment by piratesephiroth** [comment]
> Try holding L immediately after pressing A/START to launch the game.

oh, it worked
