### ISSUE TITLE
The Rub Rabbits!

### ISSUE THREAD

**Issue by piratesephiroth** [ahezard/nds-bootstrap#664]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.21.1]_
- [x]  Nightly _[8492898]_

### Your device

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

The Rub Rabbits!

### Expected behaviour

Old SDK 2 game, so should probably work

### Actual behaviour

Stuck in a white screen screen right away, even before displaying the SEGA/Sonic Team logo

### Steps to reproduce

1. Just run the game

**Comment by RocketRobz** [comment]
I'll just assume this is fixed by holding L. :P

**Comment by piratesephiroth** [comment]
yep, it worked on this one as well.

but shouldn't this alternative launch mode be added to the individual game settings?

**Comment by RocketRobz** [comment]
I didn't add it because it wouldn't fit as a per-game setting.
The launch mode also very slightly increases load speeds.

**Comment by piratesephiroth** [comment]
\>certain games only boot if we hold down the L button while launching them
\>I didn't add it because it wouldn't fit as a per-game setting.

wat

**Comment by RocketRobz** [comment]
Plus, there are TWLMenu++ updates that remove the requirement to hold L for games reported working by holding the button.
