### ISSUE TITLE
WarioWare D.I.Y. refuses to load, gets stuck at save file creation

### ISSUE THREAD

**Issue by sks316** [ahezard/nds-bootstrap#666]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release 0.20.0, 0.21.1
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

WarioWare D.I.Y.

### Expected behaviour

Save file should be created, game launches normally.

### Actual behaviour

TWLMenu++ gets stuck at `Creating save file...`, refuses to launch the game.

### Steps to reproduce

1. Ensure that TWLMenu++ is up to date.
2. Put a good dump of WarioWare D.I.Y. on your SD Card.
3. Attempt to launch WarioWare D.I.Y. via TWLMenu++.
4. Wait forever as the console fails to create a save file.

### Other notes

I have tried: Deleting any pre-existing save files, downgrading nds-bootstrap to the version that's supposed to fix WarioWare D.I.Y. (0.20.0), and updating nds-bootstrap and TWLMenu++ to their latest versions.
Any other game launches normally, so I know my nds-bootstrap and TWLMenu++ installations aren't corrupted.
My ROM is verified by comparing the hash with that of No-Intro, so I know it's a good dump.

**Comment by RocketRobz** [comment]
This is a TWLMenu++ issue, not an nds-bootstrap issue.
It is fixed by waking the console form sleep mode at that message.

**Comment by sks316** [comment]
Thanks for clearing that up Robz, you may want to note that somewhere on the compatibility list document, or at least in the release notes for TWLMenu++.

**Comment by teddblue** [comment]
how would i do that? i have the same problem with metroid prime on dsi sd card
