### ISSUE TITLE
Suikoden Tierkreis Stuck

### ISSUE THREAD

**Issue by Leyshirtt** [ahezard/nds-bootstrap#667]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Suikoden Tierkreis

### Expected behaviour

When talking to Moana take quest or take reward after quest is okay

### Actual behaviour

It's will stuck if Moana still talking in quest or reward scene and backsound still play or stuck too.

### Steps to reproduce

1. when take quest or reward at moana  i press a button quick to skip conversation.

### Other notes

i use cheat for item only.

Save file: [3593 - Suikoden - Tierkreis (US)(M3)(XenoPhobia).zip](https://github.com/ahezard/nds-bootstrap/files/3284525/3593.-.Suikoden.-.Tierkreis.US.M3.XenoPhobia.zip)

**Comment by ahezard** [comment]
Have you tried that?
Hold L immediately after pressing A/START to launch the game

**Comment by dubbz82** [comment]
Is this still an issue?

**Comment by RocketRobz** [comment]
It seems turning off heap shrink fixes this.
