### ISSUE TITLE
Final Fantasy: The 4 Heroes of Light softlock

### ISSUE THREAD

**Issue by poscompi** [ahezard/nds-bootstrap#668]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW (Unlaunch 1.9 + HiyaCFW 3.3)

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.20.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Game should carry on as normal upon returning to the starting village after receiving the sword from the king.

### Actual behaviour

After leaving the castle area to return to the village, the game will softlock with a black bottom screen. 
### Steps to reproduce

1. Go to King's Castle, receive sword 
2. Leave the castle area
3. Upon entering the loading zone for the village, the game will softlock.

### Other notes
This may also happen upon entering certain houses in the village and trying to exit them.

**Comment by RocketRobz** [comment]
Sounds like an AP-issue.
Did you try AP-patching the ROM?
