### ISSUE TITLE
Spirit tracks train problem

### ISSUE THREAD

**Issue by techmuse8** [ahezard/nds-bootstrap#669]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [x ]  Nightly _[

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable The Legend of Zelda Spirit Tracks

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.When I was leaving a station the menu and gearbox should appear
2.What happens is that I can’t see the gearbox and access the collection screen
3.

**Comment by arraystock** [comment]
Your game needs to be AP patched.

**Comment by techmuse8** [comment]
My game was ap patched

**Comment by techmuse8** [comment]
My game was fine before

**Comment by techmuse8** [comment]
With the same rom

**Comment by techmuse8** [comment]
https://drive.google.com/file/d/1AAbmlG5Z5IL8el2PI8RL1xQXs30pZ7o7/view
This is a picture of the rom

**Comment by Barawer** [comment]
try to AP patch it again, your problem is exactly the AP measure in Spirit Tracks.

**Comment by arraystock** [comment]
Have you tried the patch in DS-Scene ROM Tool?

**Comment by arraystock** [comment]
https://gbatemp.net/threads/ap-patch-preservation.477536/

**Comment by techmuse8** [comment]
I fixed it by updating bootstrap

**Comment by arraystock** [comment]
This can be closed.
