### ISSUE TITLE
[Request] Specify to use Python 2

### ISSUE THREAD

**Issue by Jolty95** [ahezard/nds-bootstrap#67]
Hello there!
Since this have been added ([link](https://github.com/ahezard/nds-bootstrap/blob/card/patch_ndsheader_dsiware.py#L115)) I'm unable to run [build_cia.sh](https://github.com/ahezard/nds-bootstrap/blob/card/build_cia.sh) because I've got Python 2.x and 3.x in the same computer and trying to run build_cia.sh is getting me an error.
My suggestion is to modify this two lines [L12](https://github.com/ahezard/nds-bootstrap/blob/card/build_cia.sh#L12) and [L13](https://github.com/ahezard/nds-bootstrap/blob/card/build_cia.sh#L13) modifying `python xxxxxx` to `py -2 xxxxxx` to make it works on Python 2.x

Thanks for all :)

**Comment by maorninja** [comment]
@Jolty95 Would this make it work on both 2.x and 3.x or would this just make it work only on 2.x?

**Comment by Jolty95** [comment]
@maorninja nope, just to make sure it will compile with python 2.x :P

**Comment by piratesephiroth** [comment]
it will make it work with python 2 when you have both installed
