### ISSUE TITLE
Warioware Touched DSi Version not run as DSiWare

### ISSUE THREAD

**Issue by LittleStinky123** [ahezard/nds-bootstrap#670]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:
I use unlaunch to boot TwilightMenu++
DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch+HiyaCFW _[1.9 and 1.3.2 but I don't use HiyaCFW as it doesn't boot emuNAND on my 32 GB microSD]_

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[0.21.1]_
- [X]  Nightly _[8492898]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Warioware Touched DSiWare version (Z2AP)

### Expected behaviour

Should be booted as DSiWare after creating the pub save file

### Actual behaviour

DS save is created in saves subdirectory and it is booted via nds-bootstrap and crashes after this

### Steps to reproduce

1. Install Warioware Touched via eShop after attaining 1000 platinum points and acquiring it
2. Extract .app file via GodMode9 and rename it to warioware.nds
3. Copy to /roms/dsiware on DSi and run it

**Comment by RocketRobz** [comment]
This is a TWiLight Menu++ issue, not an nds-bootstrap.
It has to do with how TWLMenu++ detects some games as DS games or DSiWare.
