### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by IchBinsTim** [ahezard/nds-bootstrap#671]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.21.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen
Launching
### Actual behaviour
Error1
Tell us what happens instead

### Steps to reproduce

1. Launch NDS game on home screen
2. Error 1
3.

### Other notes
im using a software calles Forwarder3ds to have the games accessable on my home screen, put the cia in the cia folder and the small nds in the nds folder, ran cia. popped up, launched, error

**Comment by RocketRobz** [comment]
Anything else shown besides `Error 1`?

**Comment by IchBinsTim** [comment]
SD Card template not found

**Comment by RocketRobz** [comment]
You need to download and extract the latest forwarder pack, as it has that.

**Comment by IchBinsTim** [comment]
already got ver. 2.9.6

**Comment by RocketRobz** [comment]
I said the forwarder pack, not Forwarder3-DS.

**Comment by IchBinsTim** [comment]
could you please tell me where i can find that?

**Comment by RocketRobz** [comment]
This is from the first post of the forwarder thread at GBATemp: https://www.dropbox.com/s/k5uaa4jzbtkgm0z/DS%20Game%20Forwarder%20pack%20%283DS%20SD%20Card%29.7z?dl=0

**Comment by IchBinsTim** [comment]
tyvm for your quick help
