### ISSUE TITLE
Stitch Jam won't load

### ISSUE THREAD

**Issue by RyanTheInkling** [ahezard/nds-bootstrap#672]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch V1.8 and HiyaCFW]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.19.5]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Disney Stitch Jam

### Expected behaviour

Game should start after selecting Story Mode, New Game and Stylus or Button Controls.

### Actual behaviour

Game crashes after selecting Story Mode, New Game and Stylus or Button controls.

### Steps to reproduce

1. Get the rom and put it on the sd card.
2. Start the game
3. Select Story Mode, New Game, then Stylus or Button Controls.

### Other notes
There is no AP-Patch for this game.

**Comment by RocketRobz** [comment]
You should update nds-bootstrap to v0.21.1, and see if it fixes the issue.

**Comment by RyanTheInkling** [comment]
i will try it

**Comment by RyanTheInkling** [comment]
> You should update nds-bootstrap to v0.21.1, and see if it fixes the issue.

Now it doesn't launch.

**Comment by RocketRobz** [comment]
Try holding L immediately after pressing A/START to launch the game.

**Comment by RyanTheInkling** [comment]
> Try holding L immediately after pressing A/START to launch the game.

Doesn't work

**Comment by ahezard** [comment]
For some reason a lot of disney games have issue with nds-bootstrap, I still hope that I will be able to fix the issues at some point.

**Comment by SleepyLark** [comment]
Tested it on 0.27.1, the game will boot if heap shrink is turn off, else it just gets stuck on a black screen.

**Comment by RyanTheInkling** [comment]
where do you find that option?

**Comment by SleepyLark** [comment]
Just before you launch the game press 'Y' and it will pull up the per-game settings.  Scroll down and turn heap shrink to off

**Comment by SleepyLark** [comment]
Is there a reason why this is still open?  The game works fine if heap shrink is off.
