### ISSUE TITLE
Kingdome Hearts 358/2 not loading after difficulty select or mission mode.

### ISSUE THREAD

**Issue by CheatCodeSam** [ahezard/nds-bootstrap#674]
### Console

Standard DSi

### CFW and configuration
 
Unlaunch v1.9 + HiyaCFW v3.3

### nds-bootstrap version

Both 
- Release v0.21.1
- Nightly 8492898

### Your device

Standard DSI
SD Card

### If this issue only affects a certain game, which game is it?

- 4223 - Kingdom Hearts - 358-2 Days (USA) (En,Fr)
- 4262 - Kingdom Hearts - 358-2 Days (Europe) (En,Fr,De,Es,It)
Both patched and unpatched

### Expected behavior

It should boot into the game. When booting into main story it should load into the opening FMV. When booting into the Twilight Town mission in mission mode it should boot directly into game.

### Actual behavior

Game stops functioning at black screen. 

### Steps to reproduce

1. Boot game
2. Select New Game then a difficulty

The same bug appears when trying to enter a mission in mission mode. However in this instance the background music continues to play while the game is frozen.
1. Boot Game
2. Mission Mode -> Solo -> Guest Play -> Select Character -> Holo-Missions -> Twilight Town -> Embark -> Start

Game does not work after selecting a premade save file either

### Other notes

It doesn't look like the game is trying to load anything during these black screens. It's like the game just gives up. I turned on ROM read LED and the light stopped flickering once I reached these black screens.

**Comment by shellster** [comment]
I have experienced this same issue, with the same DSi setup.

**Comment by RocketRobz** [comment]
Closing, as this is an AP-issue, and not an nds-bootstrap issue.
Can be worked around, by inserting a DS game cart into Slot-1.

**Comment by Angelixia** [comment]
Does this mean we have to get the actual game cart to play it or can it be fixed using a flash cart?

**Comment by edo9300** [comment]
Any cart will work

**Comment by Angelixia** [comment]
Oh. Thanks!
