### ISSUE TITLE
Modified WarioWare DIY save files get overwritten with no games

### ISSUE THREAD

**Issue by RyanTheInkling** [ahezard/nds-bootstrap#675]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch V1.8 and HiyaCFW]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.21.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

WarioWare DIY

### Expected behaviour

Microgames added to the save file should be visible.

### Actual behaviour

No microgames are present when at the DIY Shop.

### Steps to reproduce

1. Get the WarioWare DIY Editor
2. Extract save from SD Card and add microgames to the save.
3. Copy modified save to SD Card and play WarioWare DIY.

**Comment by RyanTheInkling** [comment]
@RocketRobz

**Comment by NightYoshi370** [comment]
Let's use issue #306 instead
