### ISSUE TITLE
Mario & Luigi partners in time softlock

### ISSUE THREAD

**Issue by MDHEXT** [ahezard/nds-bootstrap#676]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.21.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mario & Luigi partners in time

### Expected behaviour

After beating kamek, you walk right and enter a cutscene with baby Bowser. After two shroob UFO's pass by, the top DS screen transitions to a view of a mountain with a monster Yoshi climbing it. The cutscene should progress.

### Actual behaviour

On the first frame of the monster Yoshi animation, the game softlocks itself. All ambient animations continue to play, but the game is otherwise completely frozen.

### Steps to reproduce

1. Beat kamek (very hard)
2.walk right
3.start baby Bowser confrontation cutscene

### Other notes
I had this issue on twilight menu ver: 8.3.0 running the previous version of nds bootstrap.
I updated twilight menu to 8.4.0 and updated nds bootstrap to 0.21.1
I saved after I beat kamek
This issue happens when I open the save file after I beat kamek
I'm not sure if this issue can be avoided by deleting my save file and starting from the beginning
No cheats were active
All animations on the bottom screen still run but the game is softlocked
![20190618_230524](https://user-images.githubusercontent.com/42657178/59738189-956a7680-921d-11e9-9303-4900048f9de2.jpg)

**Comment by MDHEXT** [comment]
I should also add that I'm playing the American copy of this game

**Comment by MDHEXT** [comment]
The game runs fine if the ARM9 CPU speed is set to 133 MHz (TWL)

**Comment by RocketRobz** [comment]
@ahezard Here's the save file (provided by SvenDaHacker64), if you want to try to fix this.
[Mario__Luigi_-_Partners_in_Time.zip](https://github.com/ahezard/nds-bootstrap/files/3352714/Mario__Luigi_-_Partners_in_Time.zip)

**Comment by SvenDaHacker64** [comment]
Yep, I have same issue. Tried everything - set DS/TWL/forced mode, switch nds-bootstrap build, no luck. Works fine on R4i flashcart without any workarounds (it's a completely valid ROMs). I'm playing on a EUR version of this game btw.

**Comment by cecadenas** [comment]
Same softlock. Thanks for the advise, I played on emulator, past the baby browser scene, saved and returned to 3ds

**Comment by zenseii** [comment]
Good news! This problem is solved in both the latest stable 0.28.1 and latest nightly a33e2d8c . However, it only works when using DSi mode (twl clock and vram boost). DS mode still crashes at the same point.

Also, here's a save point a bit later so you only have to walk to the right to initiate the cutscene. The fight with Kammy is already done.
[Mario & Luigi - Partners in Time (Europe) (En,Fr,De,Es,It).zip](https://github.com/ahezard/nds-bootstrap/files/4125710/Mario.Luigi.-.Partners.in.Time.Europe.En.Fr.De.Es.It.zip)

**Comment by eku** [comment]
> Good news! This problem is solved in both the latest stable 0.28.1 and latest nightly [a33e2d8](https://github.com/ahezard/nds-bootstrap/commit/a33e2d8c6a5d7ac9495f92d629960dc7736f94e2) . However, it only works when using DSi mode (twl clock and vram boost). DS mode still crashes at the same point.

Well, doesn't work for me.

**Comment by zenseii** [comment]
> > Good news! This problem is solved in both the latest stable 0.28.1 and latest nightly [a33e2d8](https://github.com/ahezard/nds-bootstrap/commit/a33e2d8c6a5d7ac9495f92d629960dc7736f94e2) . However, it only works when using DSi mode (twl clock and vram boost). DS mode still crashes at the same point.
> 
> Well, doesn't work for me.

Care to elaborate? What system? Flashcard? Which rom version? No-intro rom?

**Comment by eku** [comment]
> Care to elaborate? What system? Flashcard? Which rom version? No-intro rom?

O3DS, No-intro ROM ARMP.

**Comment by zenseii** [comment]
> > Care to elaborate? What system? Flashcard? Which rom version? No-intro rom?
> 
> O3DS, No-intro ROM ARMP.

Okay good. Are you using twilightmenu++ to boot into it? Are you using the latest 3DS version of gbarunner2?

**Comment by zenseii** [comment]
> Why should I use gbarunner2 when M&L is a NDS game?
> BTW I always use the latest versions from the build bot.

Oh right I was getting mixed up with another issue. In other words you've tried using twl clock speeds and the extra vram. i could check if there is a problem with the latest nightly but it'll take some time before I have the opportunity.

**Comment by Kaisaan** [comment]
The game seems to no longer softlock in both DS and DSi mode on the latest nightly, [c53f924](https://github.com/ahezard/nds-bootstrap/commit/c53f9240521d598a6edb9db18fb6d18b5b6d6c46), tested this on my N2DS XL.

**Comment by zenseii** [comment]
I just checked both DS and DSi mode and I can confirm that it does work! Great job!

**Comment by AlpayTr58** [comment]
Hi, I have the same issue on my dsi. I wanted to try out the trick you mentioned where I have to load the save file on emulator, play the scene and then load it back onto the dsi. But how do I do that? How can I transfer the save file from my dsi to desmume on pc?
