### ISSUE TITLE
White screen on Shrek The Third

### ISSUE THREAD

**Issue by samvg2505** [ahezard/nds-bootstrap#677]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.21.1]_
- []  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
Shrek The Third
### Expected behaviour

Tell us what should happen
The game should boot in with no problem
### Actual behaviour

Tell us what happens instead
When I start the game, it just shows a white screen
### Steps to reproduce

1. Install Shrek The Third rom
2.Start the rom
3.

**Comment by RocketRobz** [comment]
Try holding L immediately after pressing A/START to launch the game.

**Comment by samvg2505** [comment]
IT WORKED!!!
thank you so much!
