### ISSUE TITLE
NDS BOOSTRAP ERROR 

### ISSUE THREAD

**Issue by tntrose13** [ahezard/nds-bootstrap#678]
Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ x]  Other/Older CFW [specify]
homebrew 

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[ the second to latest_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected Behaviour
Launch game 

### Actual behaviour
nds bootstrap not found error 

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
You need to install nds-bootstrap.
Download it from the releases page.
