### ISSUE TITLE
nds rom bug

### ISSUE THREAD

**Issue by fuckyouyu** [ahezard/nds-bootstrap#680]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[3.1.0]_
- [x]  Nightly _[3.1.0]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour
i boot the rom and the game should boot up
Tell us what should happen

### Actual behaviour

Tell us what happens instead
the game redirects me to the power off menu 
### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
What nds-bootstrap version are you using, and what games are you trying?

**Comment by fuckyouyu** [comment]
v.0.21.1 and the game i'm trying is wario ware diy

**Comment by RocketRobz** [comment]
What's the bug?

**Comment by fuckyouyu** [comment]
every time i boot the game from the file selector the game redirects me to the power off screen (3DS)

**Comment by RocketRobz** [comment]
Try deleting `settings.ini` at `sd:/_nds/TWiLightMenu`.

**Comment by RocketRobz** [comment]
Also, delete any .ini file in `sd:/_nds/TWiLightMenu/extras`, if they exist.

**Comment by fuckyouyu** [comment]
there are 2 settings files though one that says setting but the file has a gear next to it and the other says settings.srldr

which one should i remove

**Comment by RocketRobz** [comment]
The one with the gear is the `.ini` file.

**Comment by fuckyouyu** [comment]
ok all .ini files have been removed

**Comment by RocketRobz** [comment]
Ok, so try launching the game again.

**Comment by fuckyouyu** [comment]
ok the game works now thanks

**Comment by RocketRobz** [comment]
No problem.

**Comment by RocketRobz** [comment]
If you need further assistance, please come over to this Discord server: https://discord.gg/yqSut8c
