### ISSUE TITLE
Monster Jam - Urban Assault, Lock on Launch

### ISSUE THREAD

**Issue by Nicholas428** [ahezard/nds-bootstrap#681]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.21.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Monster Jam - Urban Assault
ID: CM5E
[GameTDB Page](https://www.gametdb.com/DS/CM5E)

### Expected behaviour
(Done using **Native** 3DS/DSi/DS Game Cart Launcher.)
Game goes black and is expected to boot. Shows developer/publisher logos and game start screen.

### Actual behaviour
(Done using TWiLightMenu++ Application, version details in issue.)
Software is stuck at a white screen while booting.

### Steps to reproduce

1. Insert Monster Jam: Urban Assault DS Cartridge into gameslot.
2. Copy .nds file from gameslot via Godmode9 into it's clipboard
3. Paste .nds file into (root)/roms/nds
4. Open TWiLightMenu++ and launch .nds file from it's targeted directory. (/roms/nds)

### Other notes

This may be a bad dump of the game. 
I'm planning to redump the .nds file from the physical cartridge release to see if it'll work.
If the game does boot normally, then I'll close the issue.

**Comment by RocketRobz** [comment]
Hold L immediately after pressing A/START to launch the game.

**Comment by Nicholas428** [comment]
That seemed to fix it. Thank you very much!
