### ISSUE TITLE
Compiling fails on latest devkitarm

### ISSUE THREAD

**Issue by Ntemis** [ahezard/nds-bootstrap#683]
### Your console

Tell us which console you are using:

- [X ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [X ]  (No CFW) Unlaunch only 1.8_[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [X ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

### Other notes

demetris@demetris-TA770E3:~/Desktop/ds/nds-bootstrap$ make
make[1]: Entering directory '/home/demetris/Desktop/ds/nds-bootstrap/retail'
Makefile:15: /opt/devkitpro/devkitARM/ds_rules: No such file or directory
make[1]: *** No rule to make target '/opt/devkitpro/devkitARM/ds_rules'.  Stop.
make[1]: Leaving directory '/home/demetris/Desktop/ds/nds-bootstrap/retail'
Makefile:32: recipe for target 'retail' failed
make: *** [retail] Error 2

**Comment by Epicpkmn11** [comment]
Did you do `sudo dkp-pacman -S nds-dev`? You seem to be missing devkitARM's ds_rules

**Comment by Ntemis** [comment]
It works thanks but please update this on Compiling section in read me, there is not such req/info
