### ISSUE TITLE
kirby mass attack and pokemon black v2 issue 

### ISSUE THREAD

**Issue by fuckyouyu** [ahezard/nds-bootstrap#686]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [x]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
If they aren't booting, make sure both ROMs are AP-patched, and that they are running in DS mode.

**Comment by fuckyouyu** [comment]
pokemon black 2 does boot but the picture doesn't show up except for the sound plus mass attack says that the rom doesn't need a ap patch but then when i boot up the game it says it needs a ap patch and the game will just leave at a blank screen when the game boots up

**Comment by fuckyouyu** [comment]
also how do i run a game in ds mode

**Comment by RocketRobz** [comment]
Check the `Run in` setting in TWLMenu++ settings.
If it shows `DSi mode` (regular or forced), change it to DS mode.

**Comment by fuckyouyu** [comment]
ok also what's the differences between ds mode and dsi mode

**Comment by RocketRobz** [comment]
DSi mode allows DSi features like the extended memory, camera, and WPA networks to be used in DSi-Enhanced games.

**Comment by fuckyouyu** [comment]
also it is running in ds mode

**Comment by fuckyouyu** [comment]
plus pokemon black 2 has been ap patched
