### ISSUE TITLE
Bolt - white screen

### ISSUE THREAD

**Issue by TwisX** [ahezard/nds-bootstrap#687]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.21.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Bolt / Bolt: BeAwesome Edition

### Expected behaviour

Game should load

### Actual behaviour

Doesn't load, freezes at white screen

### Steps to reproduce

1. Attempt to launch the game

### Other notes

Not on compatability list

**Comment by RocketRobz** [comment]
In TWiLight Menu++, hold L immediately after pressing A/START to launch the game.

**Comment by TwisX** [comment]
> In TWiLight Menu++, hold L immediately after pressing A/START to launch the game.

That worked. What does holding L do?

**Comment by RocketRobz** [comment]
It disables heap shrink for a launched game, in case if it breaks it.

**Comment by TwisX** [comment]
> It disables heap shrink for a launched game, in case if it breaks it.

Cool, thanks for the help. Is there a way to enable that by default for certain games?
