### ISSUE TITLE
The Legendary Starfy: Other console not finding the sender

### ISSUE THREAD

**Issue by RocketRobz** [ahezard/nds-bootstrap#690]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [X]  (No CFW) Unlaunch only _[1.8]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.21.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

The Legendary Starfy

### Expected behaviour

Tell us what should happen

In the other console running DLP, it should find the console requesting to do Multiplayer.

### Actual behaviour

DLP menu is unable to find the console.

### Steps to reproduce

1. Launch The Legendary Starfy.
2. Go into `Local Play`.

**Comment by SleepyLark** [comment]
So it turns out that multiplayer is only avaliable in certain areas (surprisingly there's actually a [wiki page](https://starfywiki.org/wiki/Team_Play) dedicated to this).  I played the game until I got to first Team Play spot and was able to connect from both DLP and Local Wireless
