### ISSUE TITLE
cheats Not Working

### ISSUE THREAD

**Issue by bloggingninja** [ahezard/nds-bootstrap#692]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.21.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon Black 2
Pokemon Black
Monster Rancher DS
Possibly others but this is all I tested with so far.

### Expected behaviour

You should select cheats for a game and have them work.

### Actual behaviour

Activating Cheats for a game either causes the game to not load or the game loads and the cheats do not work.

Cheats cause game to not load:
Pokemon Black
Pokemon Black 2

Game loads but cheats fail to work
Monster Rancher DS

### Steps to reproduce

1.start TWiLight Menu++
2.Go to game
3.Press Y
4.Press X (enter cheat menu)
5.Select any cheat
6.Press X (save cheats)
7.Start Game
8a. for Pokemon Games see white screen and game never loads
8b. for Monster Rancher DS any cheats requiring button presses do nothing when buttons are pressed.

### Other notes

I used the latest release of TWiLight Menu ++ (8.5.1) and used the TWiLight Menu updater to download the usrcheat.dat file. I also have "Enable Game Patching" checked in the Luma3ds options

**Comment by arraystock** [comment]
Does this still happen for you on the latest TWiLight + nds-bootstrap?

**Comment by ahezard** [comment]
Can you please re-test focusing on the cheat part?

**Comment by NightYoshi370** [comment]
Does not specify what cheats were activated and this was made before the huge revamp.
No comment in 20 days either, so I'm going to assume resolved until proven wrong.
