### ISSUE TITLE
WarioWare D. I. Y. save issue

### ISSUE THREAD

**Issue by YoshiBoiAdvance** [ahezard/nds-bootstrap#693]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release 0.21.2
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?
WarioWare D. I. Y.

### Expected behaviour
NDS-boostrap should create a save file and run the game

### Actual behaviour
It's stuck on the screen "**Creating save file...**"

### Steps to reproduce

1. Open TwilightMenu++
2. Select WarioWare D. I. Y.
3. Voila!

### Other notes
I know, that there's a bajilion of fixes, **BUT NONE OF THESE F%%KING WORK FOR ME!!!**

**Comment by 4424dev** [comment]
WarioWare D.I.Y uses a different save method on the Nintendo DS because of the large save file sizes. It will not work for emulation. You need to find a patcher/pre-patched ROM, but those are impossible to find now. Good luck, and please do report back anything you discover.

**Comment by ahezard** [comment]
This issue is not nds-boostrap related but https://github.com/DS-Homebrew/TWiLightMenu related since nds-bootstrap does not create the save file, it only use it once create.

This is issue is known : https://github.com/DS-Homebrew/TWiLightMenu/issues/581

You can create a 32 MB save file by typing fsutil file createnew "game.sav" 33550592" on a command window.

**Comment by ahezard** [comment]
Remark this other issue on WarioWare D. I. Y. is nds-boostrap related and still present : #675
So do not expect a fully working game yet

**Comment by YoshiBoiAdvance** [comment]
Oh, about 10 months later (aka right now, in April of 2020), I tested it out on melonDS and I **specifically** waiten until I see the saving screen. Shut off the firmware, reopened WWDIY, no savefile found. I know melonDS isn't the be-all and end-all emulator, but melonDS requires a BIOS and firmware to play games with best compatability, so I consider it one of the best emus of the DS, the best being, well, a 3DS.
