### ISSUE TITLE
AP Patched Games Make Twilight Menu Restart

### ISSUE THREAD

**Issue by Dchamp27** [ahezard/nds-bootstrap#694]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

**Comment by Dchamp27** [comment]
The AP Patched Games are:
HeartGold US
Dragon Quest IX 
Radiant Historia 
Im on the updated versions of twilight and Luma 
They show up under my roms, I click on the games but when i try to launch them Twilight Menu just restarts. (This happens to some Un AP patched games also) I have yet to get a single AP patched game to even load, while the Un AP patched roms either lags or freezes on certain games.

**Comment by RocketRobz** [comment]
Try re-installing TWLMenu++.

**Comment by Dchamp27** [comment]
I re-installed TWLMenu and now the AP patched games give me a Infinite White screen after it says it was loading the Bootstrap.

**Comment by RocketRobz** [comment]
Make sure you don't have cheats enabled, and that the DSi-enhanced games are running in DS mode.

**Comment by Dchamp27** [comment]
How do I that?

**Comment by RocketRobz** [comment]
Check TWLMenu++ settings for the `Run in` settings. If it's set `DSi mode`, whether it's forced or not, please change it to `DS mode`.

**Comment by Dchamp27** [comment]
I changed it to DS Mode and now It instantly restarts Twilight Menu again

**Comment by RocketRobz** [comment]
Please check your SD card for errors.

**Comment by Dchamp27** [comment]
What type of errors?

**Comment by RocketRobz** [comment]
Read/Write errors, ofc

**Comment by Dchamp27** [comment]
Could it be the way im AP patching them? Im using DS-Scene Rom Tool

**Comment by RocketRobz** [comment]
@Dchamp27 No.
Have you tried launching any ROMs that don't need AP-patching?

**Comment by Dchamp27** [comment]
Yes I have played Dragon Quest 4 and 5 with no problems

**Comment by RocketRobz** [comment]
No, but you can create forwarders to DS ROMs.
https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/

**Comment by Dchamp27** [comment]
When it says Download a pack, what/how do I download what is on the link given. It says it cannot be previewed

**Comment by RocketRobz** [comment]
There should be a `Download` button.

**Comment by Dchamp27** [comment]
So does God mode go on the root of the SD card? Sorry for so many questions

**Comment by RocketRobz** [comment]
The `.firm` file goes in `sd:/luma/payloads`.

**Comment by Dchamp27** [comment]
Im Sorry im confused right now, Im using God Mode and selected Game Cart but once I click there it shows priv bin, 3ds, split 0, split 1, trim 3ds. 
I have no idea what any of that means

**Comment by RocketRobz** [comment]
If you already have the ROMs, then just skip the dumping process.

**Comment by Dchamp27** [comment]
well how did you pull up the Forwarder on the 3ds

**Comment by RocketRobz** [comment]
If you mean how do you install it, open up FBI, then find and install the CIA.

**Comment by Dchamp27** [comment]
The Forwarder3-Ds link did not give me a cia file

**Comment by RocketRobz** [comment]
idk why that happens for some users.
Please check your SD card for errors, so that hopefully the reboot issue will be fixed.

**Comment by Dchamp27** [comment]
Im not tech savvy so i dont even know what a error would look like on my 3ds

**Comment by RocketRobz** [comment]
If you're using Windows, right-click on the SD card, click `Properties`, and then click `Tools`.
You will see an option for error-checking.

**Comment by Dchamp27** [comment]
And where can I get the CIA file

**Comment by RocketRobz** [comment]
> And where can I get the CIA file

Forwarder3-DS was supposed to give you one.

**Comment by Dchamp27** [comment]
I clicked on property and I dont have a tools option, but is that because im accessing my 3ds SD card through my network?

**Comment by Dchamp27** [comment]
So do you have any way for me to play Dragon Quest 9? Since I cant get the CIA file

**Comment by dubbz82** [comment]
From the looks of it, this may be better to be brought up in discord or so.

**Comment by RocketRobz** [comment]
@Dchamp27 Yeah, you need the SD card in the computer itself.
