### ISSUE TITLE
Last Window: The Secret of Cape West - Black Screen 

### ISSUE THREAD

**Issue by Spluaks** [ahezard/nds-bootstrap#695]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[please specify version]_  0.21.2
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Last Window - The Secret of Cape West

### Expected behaviour

Game non crashing on charge black screens 

### Actual behaviour

This is a gameplay video ( https://www.youtube.com/watch?v=vm5EokskP-8&list=PLAF5C5B1EFA317336 ) 

a charge black screen can be seen for exampel on mins 12:37 / 12:41 / 14:19, its a very common moment on the game when you do a transcition between interactive stuff or places, on the video from youtube it works well but on my console sometimes it gets crash (perma black screen) 

### Steps to reproduce

You can force the crash (since it has happent to me) at the beginning of the game, don't always happens on the same place, but it happent a lot of times to me in the few time I was playing

1. https://gyazo.com/9a3a246f523bb9e4b7dfcba15ab02340 
On the photo we can see the start of the game

2. Just walk left and use the lens to interact with a part of the room

3. Then you will see the black screen of the game charging that part, thats when SOMETIMES the game crashes and you get full black screen

### Other notes

I don't know what to answer on the DSi question or how to check it

**Comment by dubbz82** [comment]
I believe(?) This is an AP protected game.  I'm not at home at the moment to double check my lists and confirm, but I think I recall someone else bringing this up a while ago...

**Comment by Spluaks** [comment]
Hmmm no idea as I said I'm new on this, that would mean that is impossible to play this game without crashes?

**Comment by arraystock** [comment]
Unless a patch exists, then yes.

**Comment by RocketRobz** [comment]
You need to hold L after pressing A/START to launch the game, for it to work.
If holding L doesn't work, then wait for the next TWLMenu++ release.
