### ISSUE TITLE
Bowser's Inside Story graphical and sound delays and small screen glitches

### ISSUE THREAD

**Issue by frakta** [ahezard/nds-bootstrap#697]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release [latest as of writing]
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
Bowser's Inside Story (from XenoPhobia) with an ap xdelta applied, attached
[the patch i used.zip](https://github.com/ahezard/nds-bootstrap/files/3360732/the.patch.i.used.zip)

### Expected behaviour

Tell us what should happen
Normal gameplay and non delayed battle entrance voice clips

### Actual behaviour

Tell us what happens instead
When entering a battle with either mario or bowser, the star effect will glitch for half a second on the top screen along with a delayed voice clip that usually plays in realtime. Also other small "tearing" effects on top screen in either black blue or red.

### Steps to reproduce

1.Enter battle with said patch or
2.Play the game normally until you start noticing said tearing effect

### Other notes
The game froze on the save select due to ap measures so I applied the ap xdelta.

**Comment by leloyon** [comment]
Have the same issue on a DSi XL running HiyaCFW, Unlaunch and Twilightmenu++. 

Also I can't proceed any further without the game locking up. The game will lock up completely when you transition to a specific boss cutscene (Scutlet).
