### ISSUE TITLE
Giana Sisters DS (EUR) white screen

### ISSUE THREAD

**Issue by zeroultima6** [ahezard/nds-bootstrap#698]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.21.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

Giana Sisters DS

### Expected behaviour

Tell us what should happen

Giana Sisters DS: works as intented

### Actual behaviour

Tell us what happens instead

Giana Sisters DS: white screens on boot

### Steps to reproduce

1.
2.
3.

### Other notes
Works before on 0.19.5

**Comment by RocketRobz** [comment]
Does the bug persist in v0.26.1?

**Comment by zeroultima6** [comment]
The bug still persist in v0.26.1

**Comment by Agetian** [comment]
Still the case on v0.27.1

**Comment by SleepyLark** [comment]
Tried turning heap shrink to off and waiting a couple seconds?

**Comment by Agetian** [comment]
Yes, tried that right now, v0.27.1, heap shrink off, started the game and waited for about two minutes during the white screen issue, didn't go in game (still bottom screen white, top screen black). This is on a New 2DS XL system, if that matters.

**Comment by Agetian** [comment]
Interesting, after two retries it somehow magically worked. I'm not sure what it's dependent on :/ Basically, I restarted TwilightMenu and tried again, this time it got stuck on both screens white. Then I restarted it and tried one more time, and this time the game booted normally and very quickly. I tried one more time and the game booted again. Throughout all these tests, "heap shrink" was set to "off".

**Comment by Agetian** [comment]
Ok, I can no longer reproduce the white screen problem after multiple tests since it started working. Not sure if it's coincidental, random, or if the option didn't apply until I fully restarted TwilightMenu, but now the game works correctly with heap shrink turned off. Thanks for suggestion a solution, I believe this can be considered resolved then, with the "heap shrink off" as the recommended solution.

**Comment by zeroultima6** [comment]
On my end, I tried that recommended option Agetian did and that bug is indeed gone, for now at least, 
unless the issue shows again, it is resolved.

**Comment by ahezard** [comment]
I have white screen again

**Comment by RocketRobz** [comment]
Is heap shrink turned off?

**Comment by ahezard** [comment]
yes

**Comment by RocketRobz** [comment]
What region is the ROM?

**Comment by ahezard** [comment]
europe

**Comment by RocketRobz** [comment]
USA version (SDK5) boots.

**Comment by ahezard** [comment]
Interesting, I am quite sure the eur version also worked with previous release, I could have my dump corrupted

**Comment by RocketRobz** [comment]
Well, the same EUR version dump worked for me before.
