### ISSUE TITLE
Pokemon Platinum cheats issue

### ISSUE THREAD

**Issue by Gammazeth** [ahezard/nds-bootstrap#699]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ x]  Release _[v0.21.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon Platinum

### Expected behaviour

The game should load properly and/or the cheat should work causing no issues

### Actual behaviour

Most of the cheats make the game unable to load (white screen when "entering" the game) and if it loads, they're not working or are causing a black screen a few seconds after enabling them, here are some examples:
-Increase Game Speed v2 (Button version) : to enable the cheat, you have to press the L button, but when you press it, nothing happens
-All Item Codes : when you load the cheat, the items are succesfuly injected to your inventory but after a few seconds, the game freezes (black screen/white screen)
-Manaphy Egg : the game won't load at all (white screen) but unlike some other posts I've seen, the console isn't freezed (you can exit the game with the Home button without any issue/having to force the reboot of the console)

### Steps to reproduce

1.Take the game
2.Load a cheat
3.Launch the game and play a few minutes (trying to fight/enter some buildings/save) and check if the cheats work

### Other notes
I tried several times to reboot my console or to close and open the game again but without success... I haven't tried the nightly features and haven't tried other games since pokemon platinum is the only pokemon game I have atm but I've read some posts about a similar problem with pokemon black but it got closed because it wasn't in the right place and I haven't managed to retrieve it... 
I just mentioned some examples, but I tried different cheats that are from the "same category" [Trying to inject different "event pokemons" (such as Deoxys, Heatran, Pikachu), "event items" (Secret Key, Azure Flute), " basic items" (all pokeballs, all adventure items) and "game enhancements" (text speed, different versions of the game speed, bicycle speed, etc...)].
The only cheat that caused no issues at all is the cheat that enables the boots at the very beginning of the adventure but it ain't causing any trouble since I've deleted the save file (in-game) and created another one without any cheat and I just began to try to activate them again...
I also apologize for not including a log or a file allowing to concretely see what happens, but I don't know how to do that and so far, I haven't seen a log file/crash report on the SD Card.
If something isn't clear feel free to mention it, so I can try to explain it in a different way.

**Comment by Gammazeth** [comment]
Also, my game isn't ap patched but the issue isn't coming from there since the game is running perfectly as long as no cheat is loaded

**Comment by Gammazeth** [comment]
It's been a week, has anyone seen this thread ?

**Comment by ahezard** [comment]
As reported in other issues ( #737 , #704 ...) pokemon platinum freezes even without using cheats and there is no easy and short term fix available. I hope we will figure a solution a some point. Thanks for reporting though since it is indeed possible that activating cheats increase the game instability and so makes the freezes easier to reproduce.

**Comment by Gammazeth** [comment]
The point though is that the game runs flawlessly, I made the main adventure twice without any performance issue/lag/freeze. This only occurs when cheats are activated. I talked with DeadSkullJr. and he said that all the codes were working fine (for flashcarts) now, I'm not saying that the issue is coming from your development team or anything like that, but the thing is that the cheat codes are made for flashcarts and for some reasons, they're not that properly supported by nds-bootstrap. Also, I read here and there that only the five first cheat codes in the list were working, and that's partially true (it the case in games such as Mario Party DS, Pokemon B2W2, Pokemon Platinum but here the third or the fourth I don't remember were causing the game to have a white screen again, and I haven't tried other games at this point) so I hope this will give you a clue with the issue. You should collaborate with DeadSkullJr to try to find a viable solution for all games. Again thanks for taking the time to reply, thanks for your amazing software, and I hope that this can help the development.

**Comment by NightYoshi370** [comment]
All of the cheats that don't work are due to E-type codes. There should be an open issue for the few remaining code issues but most of it has been fixed.
Closed
