### ISSUE TITLE
DS DOOM v1.4

### ISSUE THREAD

**Issue by ShadowOne333** [ahezard/nds-bootstrap#7]
I had an issue when trying to use the DS DOOM homebrew with the latest version of nds-bootstrap.
I made the CIA forwarder and everything was okay.

When I boot the game, I get a white screen, and until I press some buttons, the screen changes to a black background with only a message saying:
"Welcome Shadow!"

I am guessing this might have something to do with the fact that the homebrew app is not detecting the WAD files for Doom at all, nor prboom.
Here's the thread for DS DOOM latest version v1.4 which add music support:
https://gbatemp.net/threads/dsdoom-svn.364770/

If there's any more information needed, I'd be glad to help out.
Thanks in advance:
Shadow

**Comment by ahezard** [comment]
This homebrew is quite recent it may not even need dldi patch at all (like gameyob for example). For this kind of hemebrew dldi patch break them. Was it working with hbmenu beta4 (https://github.com/ahezard/nds-hb-menu/releases/tag/V0.5.0-cia-ntr-beta.4) ?

**Comment by ShadowOne333** [comment]
Oh, I'm not really sure how to test it with hbmenu beta4.
I tried booting DS DOOM using the CIA forwarder for it with the latest package of the 3DS' SD card from Forwarder3-DS.

How would I go about testing it with hbmenu beta4?

**Comment by ahezard** [comment]
Just download the cia, install it then run it. You will have a menu showing the content of your sdcard. Then select dsdoom.nds

**Comment by ahezard** [comment]
I have looked at the code and it is based on libfat for disc access and compiles with latest devkitpro/libnds/libfat. So dldi should not be needed. If it is not working right away a simple recompilation should be enough.

**Comment by ShadowOne333** [comment]
Do you mean recompiling the 1.4 source with the latest libs to make it work with the 3DS' DS package?
I"m not at home, but I'll be in a few hours to test.

**Comment by ahezard** [comment]
Yes I mean compiling dsdoom with the latest official devkitpro package

**Comment by ShadowOne333** [comment]
Oh very well then, once I get home I'll try to set everything up to compile the latest DS Doom source with latest devkitpro, libnds and libfat then.
I'll let you know how it goes. Thanks!

**Comment by ahezard** [comment]
I can spare you the effort : I have tried, it is not working. I am looking at the code to understand what is going wrong.

**Comment by ShadowOne333** [comment]
Just to be sure, it's not a compilation problem, right?
The homebrew did compile correctly, it's just the fact that it doesn't work with the bootstrap, correct?
Thanks for sparing me of the compilation though :P
And also thank you trying to look into it.

**Comment by ahezard** [comment]
Well there is a problem with the official libnds and this version of dsdoom. Robz8 have compiled a version that works with hbmenu beta 4 : https://github.com/Robz8/dsdoom/releases
This is not the 1.4 version but it works quite well.

If you want to make it works with hbmenu beta 5 you need to desactivate the dldi bootstrap into the hbmenu.ini file by removing the last line BOOTSTRAP_INI = sd:/_nds/nds-bootstrap.ini

I suppose Robz8 have a similar option into his forwarder, you can ask him. I may add an option to not dldi patch such kind of recent homebrews into nds-bootstrap.ini but this is not my priority since this kind of homebrews does not needs this project to run.

**Comment by ShadowOne333** [comment]
Well the package from the forwarder has an nds-bootstrap.ini with the following lines:

`[NDS-BOOTSTRAP]
NDS_PATH = fat:/nds/cf_ds.nds
BOOTSTRAP_PATH = fat:/_nds/bootstrap-dldi.nds
NTR_MODE_SWITCH = 0
CONSOLE = 0
DEBUG = 0`

The only one close enough is the "BOOTSTRAP_PATH = fat:/_nds/bootstrap-dldi.nds" line, but I'm not sure if that's it.
However, a file called ntr_forwarder.ini in the same package does include that line:

`[NTR-FORWARDER]
; Set to 1 to use NTR clock speed
NTR_CLOCK = 0
; Disables DS/DSi boot animation
DISABLE_ANIMATION = 0
; Set to 0 to disable Health and Safety bottom screen message
HEALTH&SAFETY_MSG = 0
; Resets Slot 1
RESET_SLOT1 = 0
; LOCK_ARM7_SCFG_EXT
LOCK_ARM7_SCFG_EXT = 0
; ENABLE_ALL_TWLSCFG
ENABLE_ALL_TWLSCFG = 0
; Bootstrap path
BOOTSTRAP_INI = sd:/_nds/nds-bootstrap.ini`

So I'm guessing that one is the right one.

**Comment by ahezard** [comment]
Yes you can try remove the last line from the ntr_forwarder.ini

**Comment by ShadowOne333** [comment]
Just tried removing said line from ntr_forwarder.ini
No luck, DS Doom v1.4 boots directly to a white screen with those changes.

**Comment by ahezard** [comment]
This a problem in https://github.com/Robz8/NTR_Forwarder-Wfwd I would suggest that you open an issue there.

**Comment by ahezard** [comment]
DS Doom v1.4 cannot work, only 1.2.1 robz8 version works.

**Comment by ShadowOne333** [comment]
Thanks!

Although, I already went to that Github page but there doesn't seem to be any Issues tab.
If I manually enter:
https://github.com/Robz8/NTR_Forwarder-Wfwd/issues
I get redirected to the Pull Requests tab.

I'll let Robz8 know in the GBATemp thread though, just so that he is aware of it.
Thank you agaun!

**Comment by ahezard** [comment]
Thanks to you for the feedback! Please test other ds homebrews.

So for this kind of recent homebrews I will add an option to not dldi patch / irq patch to the .ini file. As soon it is done I will close this issue.

**Comment by ahezard** [comment]
Please update to the latest version of nds-nb-menu/nds-bootstrap and try again. The version 1.4 may works now (but I have not tested yet)

**Comment by ShadowOne333** [comment]
Hey sorry for not getting back sooner.
Somehow the message got lost in my inbox.

Indeed, v1.4 still doesn't work.
I am able to boot into it but I still get the "Welcome Shadow!" message and it just stays there.

Thank for trying to get this working.

**Comment by Stack3r** [comment]
Does this still need to be open?

**Comment by ahezard** [comment]
DS doom 1.4 is now dsi/3ds compatible natively. This issue can be closed.
https://gbatemp.net/threads/homebrew-on-dsi-menu-white-boxes.518131/#post-8288598
https://gbatemp.net/threads/dsdoom-svn.364770/

**Comment by ahezard** [comment]
[dsipack.zip](https://github.com/ahezard/nds-bootstrap/files/3237278/dsipack.zip)
