### ISSUE TITLE
Anything Happening?

### ISSUE THREAD

**Issue by FerrazaDazzle** [ahezard/nds-bootstrap#70]
Hey guys
Ive noticed that work has stopped on TWLoader and ndsbootstrap here. is there anything bad happening? or are you just taking couple months break?

**Comment by Robz8** [comment]
Just a couple months break, but it's likely that I'll continue work on TWLoader.

**Comment by FerrazaDazzle** [comment]
ok sweet, what about ahezard?

**Comment by Robz8** [comment]
We haven't heard from him.

**Comment by Zetchzie** [comment]
I hope he's ok Idk who would continue this if he's gone.

**Comment by Margen67** [comment]
He's occasionally online on Discord.

**Comment by FerrazaDazzle** [comment]
thats good to hear. i hope he will still work on this project.

**Comment by ahezard** [comment]
I still work on the project do not worry.
