### ISSUE TITLE
Animal Crossing: Wild Word Problems

### ISSUE THREAD

**Issue by Darkmech** [ahezard/nds-bootstrap#700]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.21.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
Animal Crossing Wild Word DS

### Expected behaviour

Tell us what should happen
The bell of the town hall should ring every hour.
Stable weather depending on the season.

### Actual behaviour

Tell us what happens instead
The bell of the town hall rings every hour and more than 3 times between hours.
The weather is unstable, for example, snow in summer. (It is usually solved by entering a building, but it can happen again.)

### Steps to reproduce

1. Play the game for a few minutes.
2.
3.

### Other notes
I use a DeSmuME save file that I converted to be able to use it.

**Comment by MichaelG621** [comment]
Yep, having the same issue with the chime on my dsi, it goes off every 5-7 minutes for me.

**Comment by Toblerone1** [comment]
For me I don't get issues like that, rather that occasionally it'll randomly flick to night for a few frames, or something to that effect. It's strange.

**Comment by leloyon** [comment]
I can't say that I've had any spastic weather changes, but I didn't play it for too long. The screen does flicker briefly to night however, which causes the town bell to chime every few minutes.

Also there's a tiny bit of stuttering and lag when booting up the game. It seems to get better as you continue playing but I'm not positive on that.

**Comment by Darkmech** [comment]
> I can't say that I've had any spastic weather changes, but I didn't play it for too long. The screen does flicker briefly to night however, which causes the town bell to chime every few minutes.
> 
> Also there's a tiny bit of stuttering and lag when booting up the game. It seems to get better as you continue playing but I'm not positive on that. Running on a DSi XL if that matters.

The same thing happens to me, talking about the blinking at night, ringing the bell every time it happens.

**Comment by Hitonoriol** [comment]
v0.27.0, same bug on DSi: time of a day changes to night for a few milliseconds triggering the bell ring and occasional weather changes.

**Comment by NightYoshi370** [comment]
This would be much more suitable with the more general #827 
Closing
