### ISSUE TITLE
IG Soft-Reset Changes Save Number loaded

### ISSUE THREAD

**Issue by nwg5817** [ahezard/nds-bootstrap#703]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[Latest]_
- [X]  Nightly _[Latest]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon Soul Silver

### Expected behaviour

Using save #4 on Pokemon Soul silver and Soft resetting ingame should return to title screen with same save loaded.

### Actual behaviour

Save #1 is loaded on reset.

### Steps to reproduce

1. Change save slot to 4
2. Soft reset ingame 
3. Title loads save slot 1 instead of selected slot

### Other notes

Soul Silver locks up on the game's forced soft reset after receiving wonder card in mystery gift. Attempting to soft reset after receiving gift prior to forced reset is a workaround, but if using other save slots, you'll load save #1 on reset.

Current workaround alternative is to reset to twilight (L+R+Down+B) and reload the game from TWLM,
or use save slot 1 only if game requires soft resetting.

**Comment by RocketRobz** [comment]
That's a TWLMenu++ issue, and will be fixed in the next version.
