### ISSUE TITLE
Mugen no Frontier EXCEED does not save

### ISSUE THREAD

**Issue by weirdingway** [ahezard/nds-bootstrap#705]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X ]  Release 0.21.2
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mugen no Frontier EXCEED 

### Expected behaviour

The game saves after hitting save and I can exit the save menu and keep playing instead of the game hanging.

### Actual behaviour

Using 8.5.1 TWLM++ and nds-bootstrap v0.21.2.

In Mugen no Frontier EXCEED whenever I hit save at a save point the game responds with the audio cue for selecting the option but then hangs. The default save file exists at sdroot\romfolder\saves (512KB) but clearly isn't being written to or loading (restarting the game there is no continue option, only new game) so it must not see the save file.

This is a translation patched ROM using xDeltaUI. ROM saves fine on drastic.

It is a .sav and it has the same name as the ROM.

### Steps to reproduce

1. Start the ROM in TWLM++
2. Get to the first save point
3. Attempt to save

### Other notes

I was sent here by RocketRobz to post my bug here instead of TWLM++

**Comment by weirdingway** [comment]
Second troubleshooting attempt:

1) Load the ROM on Desmume 0.9.11
2) Start New Game
3) Get to first save point and save
4) Export .dsv to .sav and copy .sav to SD card in roms\saves\ folder
5) Make sure .sav name matches ROM on SD card
6) Load ROM on TWLM++
7) Load Game shows on ROM main menu, .sav is recognized
8) Attempt to Load save
9) Hangs again

**Comment by dubbz82** [comment]
Have you AP patched the rom?  It does look like it is AP protected according to latest NDS Scene tool.

**Comment by weirdingway** [comment]
Isn't AP patching for games that won't load? It loads perfectly, and plays fine everywhere except the one critical thing: saving (via the in-game way).

**Comment by dubbz82** [comment]
Not specifically.  Actually the majority of the AP protected games DO in fact boot, but exhibit in-game issues (some lock up at random points, some refuse to save, some affect gameplay in adverse means, etc.)

**Comment by weirdingway** [comment]
I ran 1.0 build 1215 of DS Scene Rom tool. I applied the AP patch it detected was available for the game, exported the ROM and loaded it into TWLM++. The game is recognized as being there, title and icon, but if I launch it now it just gives me a white screen and boots back into TWLM++. Basically it won't even launch with the patch installed.

**Comment by RocketRobz** [comment]
What theme are you using in TWLMenu++?

**Comment by weirdingway** [comment]
3DS

**Comment by RocketRobz** [comment]
Is the AP-patched ROM using the same filename as the non-AP-patched ROM?

**Comment by weirdingway** [comment]
It was but I shortened it because the filename was getting really long. After exporting the ROM I just renamed it to 4737 Mugen no Frontier EXCEED (JP)_apfix.nds from 4737 Super Robot Taisen OG Saga - Mugen no Frontier EXCEED (JP)_apfix.nds. I also deleted the save that was generated (the 512KB one) to let the bootstrap remake the .sav for the newly AP patched ROM.

**Comment by RocketRobz** [comment]
Try the latest TWLMenu++ nightly.

**Comment by weirdingway** [comment]
I'd love to but the updater crashes on me

ARM11 (core 0)
data abort
TWLM++ U (0004000004395500)

I can get you the dump if you need but I'd rather not go through the hassle of compiling the nightly manually.

**Comment by weirdingway** [comment]
Okay so I have no idea why this fixed it but I went from 3DS theme to DSi and it's saving just fine now.
