### ISSUE TITLE
pokemon black 2, M&L partners in time problems 

### ISSUE THREAD

**Issue by fuckyouyu** [ahezard/nds-bootstrap#706]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [x]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour
(pokemon black 2) i boot up the game and i start my adventure
(M&L partners in time) i swing my hammer at the enemy during the tutorial and it does damage 
Tell us what should happen

### Actual behaviour
(pokemon black 2) i get a small purple pixel and when i press a 2 times nothing happens 
(M&L partners in time) i swing my hammer and it soft locks the game 
Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by fuckyouyu** [comment]
can someone help me with my situation

**Comment by SuperSaiyajinVoltZ** [comment]
First : Fill out the whole Issue. What happened? What should we do to reproduce it?

**Comment by RocketRobz** [comment]
Sounds like the ROMs got corrupted somehow.
Before replacing the ROMs, check the SD card for errors. If errors are found, then replace the ROMs.

**Comment by fuckyouyu** [comment]
how do i check for errors exactly

**Comment by RocketRobz** [comment]
If you're using Windows, right-click on the SD card, click `Properties`, and `Tools`.
You will see the error-checking feature.

**Comment by fuckyouyu** [comment]
no errors were found

**Comment by RocketRobz** [comment]
Hmm, try replacing the ROMs anyway.

**Comment by fuckyouyu** [comment]
will any save data be lost if i replace the M&L rom

**Comment by RocketRobz** [comment]
No. The save data is in it's own file.

**Comment by fuckyouyu** [comment]
ok so i replaced the pokemon black 2 rom and i booted it up but it's on a white screen rn

**Comment by fuckyouyu** [comment]
should i reboot my system or not

**Comment by RocketRobz** [comment]
Are you using `Release` nds-bootstrap?
Check by going into TWLMenu++ settings.

Also, yes.

**Comment by fuckyouyu** [comment]
it says that i have to version available

**Comment by fuckyouyu** [comment]
no*

**Comment by fuckyouyu** [comment]
what should i do

**Comment by RocketRobz** [comment]
Download the latest version: https://github.com/ahezard/nds-bootstrap/releases

**Comment by fuckyouyu** [comment]
ok i did what was instructed now whats next

**Comment by RocketRobz** [comment]
Try loading the ROM again.
If it's still not working, make sure it's being loaded in DS mode.

**Comment by fuckyouyu** [comment]
the rom is still not working plus it is in ds mode

**Comment by RocketRobz** [comment]
Is it still AP-patched?

**Comment by fuckyouyu** [comment]
yes

**Comment by SuperSaiyajinVoltZ** [comment]
Try deleting the patchOffsetCache and the fatTable for the Games in `SD:/_nds/nds-bootstrap/`. Maybe this fixes it? I'm not 100% sure though.

**Comment by fuckyouyu** [comment]
it still shows a white screen

plus the rom says ndsi enhanced

**Comment by RocketRobz** [comment]
Try the ROM on a DS emulator for PC.
Also, is the issue with M&L fixed?

**Comment by fuckyouyu** [comment]
same thing happens in the emulator

**Comment by fuckyouyu** [comment]
idk why this is happening
