### ISSUE TITLE
New Super Mario Bros. freezes after beating the World 8-Tower and after using any Wrap Cannon on the map 

### ISSUE THREAD

**Issue by iGom** [ahezard/nds-bootstrap#707]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.21.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

New Super Mario Bros. (USA) 

### Expected behaviour

[1] The game should continue to work after beating the World 8-Tower level (First Tower Level with Bowser Jr.) 

[2] (any) Wrap Cannon will move the player to another world 

### Actual behaviour

[1] Game freezes on the world map after finishing World 8-Tower level 

[2] Black screen after shot from the (any) Wrap Cannon

### Steps to reproduce

1. Go to World 8 and beat the first tower level with Bowser Jr. 
2. Go to any Wrap Cannon on the world map and try to shot

**Comment by RocketRobz** [comment]
Try holding L immediately after pressing A/START to launch the game, and see if that fixes it.

**Comment by iGom** [comment]
Yep, holding L fixed it, thanks a lot.
What does holding L change?

**Comment by RocketRobz** [comment]
Holding L reverts the heap size back to normal, while moving nds-bootstrap's code to uncached memory.
