### ISSUE TITLE
pokemon white 2 guru meditation error

### ISSUE THREAD

**Issue by Augusto2236** [ahezard/nds-bootstrap#709]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[v 8.5.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

The game should start-up when launched.

### Actual behaviour

When the game is launched, the now saving icon appears on the bottom but a "Guru Medittion Error! Data abort!" error occurs, thus freezing Twilightmenu.

### Steps to reproduce

1. Open Twilightmenu.
2. Locate Pokemon White 2.
3. Attempt to boot up the game.

### Other notes
The only cheats enabled are AP patches, game enabler, and the fix for No$GBA. The game was AP patched manually with DS Scene Rom Tool.

**Comment by RocketRobz** [comment]
There's a bug with the code that updates the recently played list.
That can be disabled in the next version.

**Comment by Augusto2236** [comment]
Are you referring to a new update to the Twilightmenu?

**Comment by RocketRobz** [comment]
Yes.

**Comment by Augusto2236** [comment]
Oh ok, thanks for your help!
