### ISSUE TITLE
Houkago Shounen freeze while saving.

### ISSUE THREAD

**Issue by Atomwho** [ahezard/nds-bootstrap#711]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [-]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [-]  Unlaunch+HiyaCFW _[v1.9 and v1.3.2]_

### nds-bootstrap version

Tell us which versions you are using:

- [-]  Release _[v0.21.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [-]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

houkago shounen

### Expected behaviour

Continue after saving.

### Actual behaviour

Freeze while saving.

### Steps to reproduce

1. Play the game until you can control the character.
2. Hit the start button to save.

### Other notes

I think the game saved properly, but the screen(or something else) froze, so can't continue to play the game, have to reboot the console then load the save to continue.

**Comment by RocketRobz** [comment]
The ROM may need to be AP-patched, by using xDelta patcher, and an AP patch from my GBATemp thread.

**Comment by Atomwho** [comment]
The method works.
