### ISSUE TITLE
White screen for Layton Kyouju to Akuma no Hako - Friendly Ban(J)

### ISSUE THREAD

**Issue by Atomwho** [ahezard/nds-bootstrap#712]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [-]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [-]  Unlaunch+HiyaCFW _[v1.9 and v1.3.2]_

### nds-bootstrap version

Tell us which versions you are using:

- [-]  Release _[v0.21.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [-]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

White screen for Layton Kyouju to Akuma no Hako - Friendly Ban(J)

### Expected behaviour

Continue to play.

### Actual behaviour

White screen after launching the game.

### Steps to reproduce

AP pathed from:
Just launch the game, the white screen will show immediately.

None patched ROM:
1. launch the game, you will see a selection screen which you can choose the play the mean game, additional mode or see the commercial. 
2. Select any of them, the white screen would be shown.

**Comment by RocketRobz** [comment]
Try holding L immediately after pressing A/START to launch the AP-patched ROM.

**Comment by Atomwho** [comment]
> 
> 
> Try holding L immediately after pressing A/START to launch the AP-patched ROM.

Unfortunately, still shows the white screen.

**Comment by RocketRobz** [comment]
The game reportedly works on the latest version, if the AP-patch is deleted.
