### ISSUE TITLE
Pokemon HG/SS unable to read some save files from SD card

### ISSUE THREAD

**Issue by RocketRobz** [ahezard/nds-bootstrap#715]
Tell us which versions you are using:

- [X]  Release _[v0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [X]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon HeartGold and SoulSilver

### Expected behaviour

Save loads successfully from both SD card and flashcard.

### Actual behaviour

Save only loads successfully from flashcard. Black screens from SD card.

### Steps to reproduce

1. Download [this](https://web.archive.org/web/20190311122801/https://filetrip.net/nds-downloads/game-saves/download-pokemon-hgss-perfect-save-1-31-f10256.html) save file, and extract the .sav file to `saves` folder.
2. Have set device be SD card in TWiLight Menu++.
3. Launch Pokemon HG/SS.
4. Select the save, and it'll crash on a black screen.

### Other notes
Thanks to @xRoyalPainx for finding this issue!

**Comment by AlexHalley** [comment]
You could see the possibility of full pokemon compatibility from DS (HeartGold SoulSilver) to Wii (Pokemon Battle Revolution).

The screen goes white and frozen when I try to connect with the Wii

**Comment by RocketRobz** [comment]
@AlexHalley There's already an issue open for that, I believe.

**Comment by AlexHalley** [comment]
You could create one more topic in TWiLight Menu ++ updates in the "What's new?" or in the "Bug fix" section.
Suggestion:
"Full compatibility of HeartGold / SoulSilver / Platinum / Pearl / Diamond pokemon games with the Pokemon Battle Revolution (Wii) game:" there you answer: "Yes / No"
Simple suggestion, please don't get me wrong!

**Comment by RocketRobz** [comment]
@AlexHalley If it we're fully working, we would've just added it to `What's new?` or `Bug fixes`, no answer needed.

**Comment by AlexHalley** [comment]
Alright, you're already doing an amazing job and we (myself) poor mortals always want something more like this PBR compatibility which you (rightly so) should have little interest in. These are my own reasons and it would be nice if you would give this support if it's not too much trouble. Thank you!

**Comment by AlexHalley** [comment]
Not this Wii AP-Patch yet? or is it already about compatibility?

**Comment by RocketRobz** [comment]
Apparently, you didn't get the joke. :P
`Wii` = `We`
`U` = `you`

**Comment by AlexHalley** [comment]
Sorry ... I'm Brazilian ... internal slang and jokes is hard for me to understand ... in a frank conversation is complicated for me!

**Comment by AlexHalley** [comment]
What does that mean?? forgive my ignorance!
"The Gen 4 Pokemon games as retail carts should hopefully work now."

**Comment by RocketRobz** [comment]
Fixed by this commit: https://github.com/ahezard/nds-bootstrap/commit/74709c1dc54a32a7e37382714c31d312e7cad013
