### ISSUE TITLE
Mario and Luigi: Bowser's Inside Story Crash before Scutlet Boss

### ISSUE THREAD

**Issue by Cacx101** [ahezard/nds-bootstrap#717]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch 1.9/HiyaCFW 1.3.2]

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mario and Luigi: Bowser's Inside Story (with applicable ap patch applied)

### Expected behaviour

You should enter the room and enter a cutscene. After the cutscene, you fight the boss and [INSERT SPOILER HERE].

### Actual behaviour

As soon as you enter the room, the game crashes whatever note the music was playing before the crash, that continues playing if you don't turn off the system.

### Steps to reproduce

1.Get to a point before the Scutlet boss.
2. Try to enter the room.
3. Voila! Crash.

### Other notes
Tried holding L, didn't work. (Although the input might have not gone in) A few other minor, graphical glitches (Small lines on the top screen warping color, starting a batle takes longer and the screen before is kind of bugged), but nothing that might ruin the gameplay, not by a long shot.

EDIT: Interestingly, when loading the game in DSI Mode (Forced), the game doesn't crash, the music still plays and the animations for the top screen still plays, but the game still softlocks.

**Comment by RocketRobz** [comment]
The game already has L "held", so it boots.

**Comment by Cacx101** [comment]
Ok then, just put that in there to make sure.

**Comment by Cacx101** [comment]
Just to make sure, it wasn't the L holding that caused the problem, it just didn't work.

**Comment by Cacx101** [comment]
Edit added: "Interestingly, when loading the game in DSI Mode (Forced), the game doesn't crash, the music still plays and the animations for the top screen still plays, but the game still softlocks."

**Comment by ahezard** [comment]
Do you know if this is a regression? Was it working in previous releases?

**Comment by leloyon** [comment]
Have the same problem, but I can't confirm it was working in previous releases.

**Comment by leloyon** [comment]
Just an update. With the release of Bootstrap 0.24.0, this lockup appears to be fixed. At least, it's fixed for me.
