### ISSUE TITLE
New Super Mario Bros. USA not working

### ISSUE THREAD

**Issue by SplatMan333** [ahezard/nds-bootstrap#72]
Whenever I try to run New Super Mario Bros. USA, I get a white screen after the ds boot logo. Plz help. I lost my cart for this game and want to play it in TWLoader!

**Comment by Necklaces** [comment]
Hey @SplatMan333, this game cannot currently be booted with TWLoader+nds-bootstrap, sorry. As you can see [here, a spreadsheet of games that work and not](https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/)  it is unable to boot with or without a donor card. We already have an issue on this here: #32

**Comment by maorninja** [comment]
@shutterbug2000 ...This is just a ripoff of #32. Please close...
