### ISSUE TITLE
Pokemon conquest

### ISSUE THREAD

**Issue by fennectech** [ahezard/nds-bootstrap#720]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ X]  Release _[0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon conquest

### Expected behaviour

The game should start normaly

### Actual behaviour

After opening the game and the ndsbootstrap dissapears the game just freezes on a white screen

### Steps to reproduce

1.open game and wait.
2.
3.

### Other notes

This rom is ap patched

**Comment by RocketRobz** [comment]
You should also run the game in DS mode.

**Comment by fennectech** [comment]
how?

**Comment by RocketRobz** [comment]
Press Y on the game in TWLMenu++, then set `Run in` to `DS mode`.
