### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by apple-strudel** [ahezard/nds-bootstrap#721]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ X ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ X ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ X ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon Black/HearGold

### Expected behaviour

Load into game menu

### Actual behaviour

Sustained white screen

### Steps to reproduce

1. Open DSimenu++ and enable AP patch for game
2. Open game (no other cheats enabled)

Game runs as expected without patch, no exp on Black and random Crashes on HG. Using latest version from the Updater (not nightly).

**Comment by Jerdo32** [comment]
It has the white screen if it's AP Patched? That's interesting.

**Comment by RocketRobz** [comment]
DSiMenu++?
Do you mean TWiLight Menu++? DSiMenu++ was the previous name.

**Comment by RocketRobz** [comment]
Also, you need to AP-patch the ROM itself. An AP-cheat won't work.

**Comment by apple-strudel** [comment]
Yes Twilight++, that makes more sense, the AP cheat was the issue. Have a patched version now and it works flawlessly, cheers for all your work.
