### ISSUE TITLE
Error 1 (possible OSX issue?)

### ISSUE THREAD

**Issue by Nathan-ccma** [ahezard/nds-bootstrap#722]
Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### Actual behaviour

Error 1 nds-bootstrap not found

### Steps to reproduce

1. Install Twilightmenu via FBI
2. Copy nds-bootstrap.zip contents to SD:/_nds using OSX
3. Attempt to open a DS rom

Is there a known issue with OSX? I have every file in the proper place on the SD card, the only thing I can think of that might be causing the issue is something in the way OSX handles external storage. Has this been tested on mac hardware? The card is formatted fat32 and I haven't had any issues with other 3ds homebrew

**Comment by RocketRobz** [comment]
Is `nds-bootstrap-release.nds` and `nds-bootstrap-hb-release.nds` in `sd:/_nds`?

**Comment by Nathan-ccma** [comment]
Yes, nds-bootstrap-release.nds, nds-bootstrap-hb-release.nds are in sd:/_nds and nds-bootstrap.ini was created successfully

**Comment by RocketRobz** [comment]
Use GodMode9 to see if there's a weirdly named `_nds` folder on the SD root.

**Comment by Nathan-ccma** [comment]
There were OSX metadata files and folders (._nds/, ._nds-bootstrap-release.nds), I have deleted them and let twilightmenu create a new ini file

**Comment by RocketRobz** [comment]
Check if the metadata files are recreated.

**Comment by Nathan-ccma** [comment]
I double-checked using filezilla on the max before ejecting the card and then again on the 3ds using godmode9, it's just the files that are supposed to be there.

**Comment by RocketRobz** [comment]
Try switching nds-bootstrap to `Nightly` in TWLMenu++ settings.

**Comment by Nathan-ccma** [comment]
I did that, but unfortunately it didn't help. 

Just to be safe after I make any change I power off the system entirely, reload twilightmenu++, double-check to make sure the setting saved and load a new game that has no previous save file

I'm going to try and get ahold of a windows PC and reinstall everything from scratch to see if it works that way. At least then we'll know for sure if this is a mac issue or not

**Comment by Jerdo32** [comment]
I suppose release-bootsrtap.ver is on the TwilightMenu++ folder and not nds folder.
