### ISSUE TITLE
Mario Kart DS - Ghosts Unable to be Saved

### ISSUE THREAD

**Issue by Cornholio309** [ahezard/nds-bootstrap#723]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release (v0.22.0)
- [ ]  Nightly 

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mario Kart DS

### Expected behaviour

Upon finishing a course in Time Trial mode, the game should save the player's best time as a ghost that they can toggle on and off from re-selecting the course in Time Trial Mode if they wish. No message appears and the save is automatic.

### Actual behaviour

Near the end of a race (on the final lap, close to the finish line), a message pops indicating that the ghost data is unable to be saved. When the player finishes the race, their time will be saved, but the ghosts aren't.

### Steps to reproduce

1. Choose 8-Figure Circuit in Time Trial Mode (Single Player > Time Trial)
2. Complete a full race on the track.
3. Near the end of the track, the message should pop up indicating the player's ghost was unable to be saved.

### Other notes

Outside of this one save flaw, the game appears to work fine otherwise through this loading method? If nds-bootstrap is exited and returned to by re-loading the ROM, the game still remembers all other player save data (including times). The player just won't be able to race against their ghost or save their best time as a ghost.

**Comment by RocketRobz** [comment]
What region is the ROM?

**Comment by Cornholio309** [comment]
So sorry! I completely forgot to include that in my original post.

The ROM is the USA revision.

**Comment by RocketRobz** [comment]
Does the bug persist in v0.26.1?

**Comment by FlameKat53** [comment]
hello, i would like to know what character you used. i don't think it would change anything but eh

**Comment by NightYoshi370** [comment]
2 discord users just said that it didn't happen to them. I'm gonna close this
