### ISSUE TITLE
Unable to pass 'Touch to start' on Super Mario 64 DS

### ISSUE THREAD

**Issue by robertfwallis** [ahezard/nds-bootstrap#725]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Super Mario 64 DS

### Expected behaviour

The game says "TOUCH TO START" with the star floating above it. Touching the screen should then make the game continue on so I can actually play it.

### Actual behaviour

Touchscreen seems to be unusable. I touch the screen but nothing happens. I use the widescreen hack on both Mario Kart DS and Super Mario 64 DS, yet the latter is the only one of the two that doesn't function correctly.

### Steps to reproduce

1. Follow the steps [here](https://gbatemp.net/threads/ds-i-3ds-twilight-menu-gui-for-ds-i-games-and-ds-i-menu-replacement.472200/) to install the widescreen hack
2. Set all games to boot at a 16:10 ratio (widescreen) in TWiLight Menu's settings
3. Load up Super Mario 64 DS (EUR)

### Other notes

I'm not entirely sure why this issue is occurring since it barely seem to be mentioned anywhere else. Perhaps I did something wrong?

**Comment by robertfwallis** [comment]
I'm closing this. Turns out I clearly didn't research enough. Touchscreen doesn't work at all on Mario Kart DS either... Seems to be a wide spread issue for me.

**Comment by RocketRobz** [comment]
Fixed in #726
