### ISSUE TITLE
Touchscreen input seems to be completely broken

### ISSUE THREAD

**Issue by robertfwallis** [ahezard/nds-bootstrap#726]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mario Kart DS, and Super Mario 64 DS (from what I've tried so far)
NOTE: I am also using the widescreen hack provided on the official TWiLight Menu thread.

### Expected behaviour

I should be able to touch the screen and have it act like normal.

### Actual behaviour

It does not register any input. I believe it may be registering a random input of some kind? Since I saw the highlight on Mario Kart DS's menu move on its own.

### Steps to reproduce

1. Install the widescreen hack from the official thread
2. Set the game ratio to Widescreen (16:10)
3. Launch the game

### Other notes

I'm not sure if I'm doing anything wrong, but I followed the steps on the official thread exactly as they said. Widescreen DOES seem to work, but the touchscreen breaks.

**Comment by NightYoshi370** [comment]
Have you tried a non wide screen game?

**Comment by robertfwallis** [comment]
> Have you tried a non wide screen game?

As in playing without widescreen enabled? No, not yet. Should I disable widescreen and load the same games?

**Comment by RocketRobz** [comment]
How did you update TWiLight Menu++?

**Comment by robertfwallis** [comment]
> How did you update TWiLight Menu++?

I used the manual method.

**Comment by robertfwallis** [comment]
I'm confident this is an NDS Bootstrap bug of some kind. The touchscreen works as intended everywhere except when running a DS game via NDS Bootstrap in TWiLight Menu++.

**Comment by RocketRobz** [comment]
So you're still on an outdated nds-bootstrap version.
The latest nds-bootstrap fixes the touch issue.

**Comment by robertfwallis** [comment]
> So you're still on an outdated nds-bootstrap version.
> The latest nds-bootstrap fixes the touch issue.

I dragged all the files over from the latest release of TWiLight Menu++ (v9.0.4). Do I need to download NDS Bootstrap from this GitHub repo and copy those over?

**Comment by RocketRobz** [comment]
Yes. It's possible you didn't copy over the nds-bootstrap files included.

**Comment by robertfwallis** [comment]
> Yes. It's possible you didn't copy over the nds-bootstrap files included.

Seems to have fixed it! My bad. Wasn't aware I needed both folders. Thanks!
