### ISSUE TITLE
nds-bootstrap not found

### ISSUE THREAD

**Issue by zerotheumbreon** [ahezard/nds-bootstrap#727]
-->
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ √]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ √]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ √]  Release _[0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ √]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?
It affects Pokémon Black 2.

### Expected behaviour

The game should open with no issues.

### Actual behaviour

Error 1, nds-bootstrap not found.

### Steps to reproduce

1. Load up Pokémon Black 2 via Twilight Menu.
2. Wait.
3. Error 1.

### Other notes
The releases are indeed with the .ini, but the issue stays the same.

**Comment by RocketRobz** [comment]
Does it happen with any other game on the SD card?

**Comment by zerotheumbreon** [comment]
It occurs with my other games such as Platinum and Chrono Trigger.

**Comment by InstantWindow** [comment]
I have the same issue but then with pokemon diamond

**Comment by ahezard** [comment]
It cannot be a nds-bootstrap issue, this bug is on twilight-menu side.
