### ISSUE TITLE
Picross 3D not loading on DSi

### ISSUE THREAD

**Issue by SleepyLark** [ahezard/nds-bootstrap#728]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.9  + v1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Picross 3D

### Expected behaviour

The game should boot into the main menu

### Actual behaviour

The game "loads" but there's only a black screen on the top and a white screen on the bottom with no sound or touch input

### Steps to reproduce

1. load Picross 3D on a DSi
2. Game boots but not to the actual screen

### Other notes

It was working on an earlier version (I believe version 0.21.2) and it also works on my 3DS (latest version 0.22.0).

**Comment by RocketRobz** [comment]
Try holding L immediately after pressing A/START to launch the game.

**Comment by SleepyLark** [comment]
It didn't work

**Comment by SleepyLark** [comment]
I tried the latest version (0.24.0) and made a new save file and it actually worked!

**Comment by SleepyLark** [comment]
Must have been related to #739
