### ISSUE TITLE
Pokémon Diamond freezing

### ISSUE THREAD

**Issue by CaptainLibrary** [ahezard/nds-bootstrap#729]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch 1.9, HiyaCFW not sure how to check, but should be latest]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.22.0]_
- [x]  Nightly _[the one distributed with Twilight Menu ++ v9.0.4]_
Tested both

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokémon Diamond USA
(Haven't tested Pokémon Pearl or Pokémon Platinum, but another user reports the same for Platinum so you may consider this to be a duplicate)

### Expected behaviour

Game plays normally

### Actual behaviour

Game randomly freezes. Music continues to play. Stuck on a single frame. Button inputs have no effect.

### Steps to reproduce

1. Launch Pokémon Diamond from Twilight Menu ++
2. Play normally
3. Wait for a freeze to occur

### Other notes
Much, much more frequent in the Underground where freezes occur within a couple of minutes without fail, but unexpected freezes also happened in Eterna Forest and Eterna City

Holding L on boot does not prevent freezes.

**Comment by CaptainLibrary** [comment]
Still getting this on latest bootstrap

**Comment by IsaacWP121** [comment]
I can confirm that pearl and platinum freeze as well

**Comment by IsaacWP121** [comment]
I have fixed all gen 4 games with a simple ap patch

**Comment by CaptainLibrary** [comment]
Still occurring as above on v0.28.1

**Comment by NightYoshi370** [comment]
Let's use #737 instead
Closing...

**Comment by DiamondPK** [comment]
My diamond on Ds lite keeps freezing when I try to trade using the wireless union thing. Is there a way to fix it ?
