### ISSUE TITLE
Club Penguin: Herbert's Revenge - Game does not boot when AP cheat is on

### ISSUE THREAD

**Issue by noddy360** [ahezard/nds-bootstrap#730]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Club Penguin: Elite Penguin Force: Herbert's Revenge (USA)

### Expected behaviour

After selecting the AP cheat, the game should boot. You should be able to progress through the game with the cheat on.

### Actual behaviour

After selecting the AP cheat, the game either displays a white screen, or a black screen at the top screen and a white screen at the bottom screen. Game does not boot.

### Steps to reproduce

1. Press Y to go to the game settings, then go to the cheat selection by pressing X.
2. Select the AP cheat code and go back.
3. Launch the game.

### Other notes
Used the default settings. The game boots with no cheats on. You obtain a Puffle Whistle when you start the first mission in the cave, but you're unable to click it in the lower right corner on the screen, making the game impossible to beat. I believe this is an anti-piracy thing.

**Comment by RocketRobz** [comment]
You need to AP-patch the ROM, not use an AP-fix cheat.
