### ISSUE TITLE
Visual elements get randomly drawn on the wrong screen

### ISSUE THREAD

**Issue by LHK1337** [ahezard/nds-bootstrap#731]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Experienced in Star Wars - The complete saga (EU)

### Expected behaviour

Screen content not getting merged without flickering.
Upper screen stays upper screen and
bottom screen stays bottom screen. 

### Actual behaviour

the visual elements from the upper screen appear on the lower screen and vice versa.
These elements also alternate between the two screens rapidly. Often they even overlap and both screens displaying rapidly overlapping garbage. 
But the alignment and the look of these visual elements is as it should be.

So I think it could just be something like a broken pointer during the drawing step. 

### Steps to reproduce

1. run Star Wars - The complete saga (EU)
2. experience this big in the main screen
--- additionally---
3. start a new or load save game
4. enter episode 1 stage 3 - the pot race
5. realize this stage is unplayable

### Other notes

tried with different game specific settings -> not fixed

![15661675088197810550799541518571](https://user-images.githubusercontent.com/25325997/63231234-1099da00-c219-11e9-9508-bbe1db6f3dff.jpg)

**Comment by RocketRobz** [comment]
I'm guessing DS mode with NTR clock speed doesn't work?
Those settings fix the issue for me.

**Comment by LHK1337** [comment]
@RocketRobz oh hell yeah!!
Forced DSI mode and higher clock or ds mode with lower clock speed fix the issue

btw I love your work, it reveals soooooo many childhood memories ^^
