### ISSUE TITLE
error 1

### ISSUE THREAD

**Issue by megaxan10** [ahezard/nds-bootstrap#732]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[0.22.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

game should load

### Actual behaviour

error 1 appears even though i have the nds bootstrap file in the correct place

### Steps to reproduce

1. launch a game
2. thats it
3.

**Comment by NightYoshi370** [comment]
What did you use to copy the files over?

**Comment by RocketRobz** [comment]
Fixed in TWiLight Menu++ v9.1.2.
