### ISSUE TITLE
Pokémon Conquest Not Playing

### ISSUE THREAD

**Issue by garmedon97** [ahezard/nds-bootstrap#735]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[0.23.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokémon Conquest

### Expected behaviour

The game should launch

### Actual behaviour

Game gets stuck on a white screen when launched

### Steps to reproduce

1.launch the game
2.
3.

### Other notes
I have already tried running it in ds mode and I could not find an ap patch for it

**Comment by RocketRobz** [comment]
What TWLMenu++ version are you using?

**Comment by garmedon97** [comment]
I’m using 9.0.2

**Comment by RocketRobz** [comment]
The latest is v9.1.0.
Please update to that version, as it includes the AP patch needed for the game to work.

**Comment by garmedon97** [comment]
I updated and it work now thank you
