### ISSUE TITLE
Soft Reset kicks the system to Home Menu instead of [frontend] randomly

### ISSUE THREAD

**Issue by Dartz150** [ahezard/nds-bootstrap#738]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.23.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

All games

### Expected behaviour

Games should reboot to [frontend] when pressing L+R+B+DOWN combo for two seconds.

### Actual behaviour

System reboots into Home Menu, but it happens only a fraction of times, around 3 of 10, meaning that the other 7 boots into [frontend] as expected.

### Steps to reproduce

1. Open any game through [frontend]
2. Press L+R+B+DOWN key combination for two seconds.
3. If it reboots into [frontend], try again with the same or another game until you step into a Home Menu reboot.

### Other notes

This has happened since the first time I have tried bootsrap, I thought that it had some flaws but after hearing feedback from another users, this should only happen on the first batch of o3DS.

**Comment by ErdbeerbaerLP** [comment]
For me all attempts always boot into home menu :(

**Comment by tomudo** [comment]
DSi 1.2J has some random start to DSi system menu too. I guess glitch chance is about 10%. Sometimes I got red screen of death

**Comment by Stack3r** [comment]
Duplicate issue
