### ISSUE TITLE
Picross 3D is created incorrect sram file size.

### ISSUE THREAD

**Issue by tomudo** [ahezard/nds-bootstrap#739]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW - Unlaunch 2.0 + Hiya 1.3.2

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ x ]  Release 23.0
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?
Picross 3D (U)

### Expected behaviour
SRAM file size incorrect. Game cannot pass logo after in-game save file created. Nds-bootstrap create 512k file but correct file size is 1MB

### Actual behaviour
Create correct 1MB file size.

### Steps to reproduce

1. Start game from SD-card
2. Game start and create in game save file
3. Game freeze after logo

### Other notes
It may problem of other games if sram file size create incorrectly.

**Comment by RocketRobz** [comment]
So a 1MB file will fix the issue?

**Comment by tomudo** [comment]
> 
> 
> So a 1MB file will fix the issue?

Yes, it is. I create file by flashcart and tranfer file to /roms/nds/save folder. The game is run normally.

**Comment by RocketRobz** [comment]
Ok, nice! Closing this, since the save is created by TWLMenu++.

**Comment by tomudo** [comment]
I tested it. It works, correct 1M save file size.
