### ISSUE TITLE
Please make the Pokemon games work

### ISSUE THREAD

**Issue by RUNETHERABBITYT** [ahezard/nds-bootstrap#74]
Yeah make Pokemon
Diamond, Peral, Platinum, Black & white, Black & White 2 
Please i so badly want to play them

**Comment by Robz8** [comment]
You'll have to wait a while for them to work.
The games you mentioned, including HeartGold and SoulSilver, are the mainstream Pokemon games.
The spinoff games such as Pokemon Trozei/Link and the Pokemon Mystery Dungeon games are the only Pokemon games that work for now.

**Comment by RUNETHERABBITYT** [comment]
Then ill wait

**Comment by maorninja** [comment]
@shutterbug2000 Please close this...

**Comment by ApacheThunder** [comment]
Most of the main series pokemon games are also DSi enhanced games. It's gonna be awhile before we get to those.
