### ISSUE TITLE
"make[2]: lzss: Command not found" - 

### ISSUE THREAD

**Issue by tomudo** [ahezard/nds-bootstrap#740]
I compile in Ubuntu 18. Here is error while compiling.

built ... cardengine_arm7.bin
rm /home/nott/nds/nds-bootstrap/retail/cardengine/arm7/../../nitrofiles_dec/cardengine_arm7.elf
make[3]: Leaving directory '/home/nott/nds/nds-bootstrap/retail/cardengine/arm7/build'
make[2]: lzss: Command not found
Makefile:108: recipe for target 'build' failed
make[2]: *** [build] Error 127

I think it is missing lzss package. Which package should I install. I search google for lzss in debain/ubuntu but it not found yet.

**Comment by RocketRobz** [comment]
The link will be in azure pipeline .yml file.

**Comment by NightYoshi370** [comment]
https://cdn.discordapp.com/attachments/283769550611152897/615767904926826498/lzss

Download this, chmod +x it and then dump it in the bin folder of devkitpro

**Comment by Epicpkmn11** [comment]
https://cdn.discordapp.com/attachments/283769550611152897/615767365266833408/lzss.c
(Also, here's the modified source file that works on linux for future reference)

**Comment by stripes-8** [comment]
I hate to do this, (especially after screwing up the Wood UI with my scroll-half-way-through-the-page idea,) but the links are down, and I also can't find the file anywhere else. Does anyone know where to find that now?

**Comment by RocketRobz** [comment]
> I hate to do this, (especially after screwing up the Wood UI with my scroll-half-way-through-the-page idea,) but the links are down, and I also can't find the file anywhere else. Does anyone know where to find that now?

You can download it here: https://www.romhacking.net/utilities/826/

**Comment by Epicpkmn11** [comment]
Also, source is in the repo [lzss.c](https://github.com/DS-Homebrew/nds-bootstrap/blob/master/lzss.c)

```bash
gcc lzss.c -o lzss
```

**Comment by stripes-8** [comment]
Rad, thanks guys.
