### ISSUE TITLE
Load Blowfish key from boot ROMs instead of hard-coding it

### ISSUE THREAD

**Issue by GerbilSoft** [ahezard/nds-bootstrap#742]
The NDS Blowfish key for Secure Area decryption is currently hard-coded in: https://github.com/ahezard/nds-bootstrap/blob/15a0659a77e4550745dcdfe23edf63629d58213c/retail/bootloader/source/arm7/decompress.c#L23
This takes up 1,048 bytes of space in nds-bootstrap, and it isn't needed.

According to [GBAtek](https://problemkaputt.de/gbatek.htm#dsencryptionbygamecodeidcodekey1), the Blowfish keys are available in the following locations:

```
NDS.ARM7 ROM: 00000030h..00001077h (values 99 D5 20 5F ..) Blowfish/NDS-mode
DSi.ARM9 ROM: FFFF99A0h..FFFFA9E7h (values 99 D5 20 5F ..) ""
DSi.TCM Copy: 01FFC894h..01FFD8DBh (values 99 D5 20 5F ..) ""
DSi.ARM7 ROM: 0000C6D0h..0000D717h (values 59 AA 56 8E ..) Blowfish/DSi-mode
DSi.RAM Copy: 03FFC654h..03FFD69Bh (values 59 AA 56 8E ..) ""
DSi.Debug:    (stored in launcher) (values 69 63 52 05 ..) Blowfish/DSi-debug
```

The NDS key is the important one in most cases. I believe the DSi keys are only needed when reading the DSi secure area from an actual cartridge, and in addition to the Blowfish key, there's also modcrypt (AES).

Some fiddling may be needed in order to ensure these keys are correct on all systems. I'll test this on 3DS tonight.

**Comment by RocketRobz** [comment]
The boot ROMs cannot be accessed, after console boot, so this will not work.
