### ISSUE TITLE
Soft Reset makes console crash (An exception occurred)

### ISSUE THREAD

**Issue by Jerdo32** [ahezard/nds-bootstrap#744]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.24.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### Expected behaviour

1. Press L, R, B and down on the D Pad for 3 seconds during gameplay and should go back to menu.

### Actual behaviour

Do what's told before and console crashes with "An exception occurred". Specifying it's prefetch abort (svcBreak).

### Steps to reproduce

1.Hold L, R, B and down for a few seconds.

### Other notes
1. This may be due to widescreen. Before, it would go directly to HOME Menu.
![15678136347083583820254867719465](https://user-images.githubusercontent.com/53071715/64466298-3828e780-d0df-11e9-8514-a00e582416be.jpg)

**Comment by RocketRobz** [comment]
What version of Luma are you using?

**Comment by Jerdo32** [comment]
Luma3DS v9.1

**Comment by RocketRobz** [comment]
You're using an out-of-date version.
Please updater to v10.0.1.

**Comment by Jerdo32** [comment]
I remember updating it to v10.0.1. I even checked the version. I'm do not have access to my PC for the moment. I'll update and recheck when I can (aproximately 20 min).

**Comment by Jerdo32** [comment]
Update: I know what happened. I did update a 2DS, but it wasn't mine. Now that I updated it, it does not crash and even better. It goes to the loader rather than to the HOME Menu.

**Comment by qamichelemassa5859** [comment]
Alright wasn't be presented on Luma3DS latest version??
