### ISSUE TITLE
Accelerated animation for Pokémon Platinum (DSi)

### ISSUE THREAD

**Issue by AozakiWr** [ahezard/nds-bootstrap#745]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokémon Platinum Version

### Expected behaviour

Should be playable at normal speed.

### Actual behaviour

Sound continues at normal speed when applied, but animations are accelerated.

### Steps to reproduce

1. loads the game normally.
2. music and effect sounds punctually begin their appearance normally.
3. Animation and visual effects accelerate as they are applied.

### Other notes

I have not tested previous versions like Pearl and Diamond.

**Comment by RocketRobz** [comment]
This was done to fix some slowdowns.
To remove the speedup, delete the .ips file in "sd:/_nds/TWiLightMenu/apfix/", featuring the game's TID shown in the per-game settings.
