### ISSUE TITLE
Widescreen acting odd?

### ISSUE THREAD

**Issue by Jerdo32** [ahezard/nds-bootstrap#747]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

I'm not quite sure if this is supposed to happen. But Twilight Menu and all games used Widescreen.

### Actual behaviour

Now the loader does not use widescreen and only a few select games I have use Widescreem

### Steps to reproduce

1. Not sure.

**Comment by RocketRobz** [comment]
Delete `TwlBg.cxi` at `sd:/luma/sysmodules/`.

**Comment by arraystock** [comment]
This is actually correct, not all games can run in widescreen mode. Also, the launcher is not designed to be widescreen either. Basically, anything that doesn’t use 3D in the top screen won’t work in widescreen mode AFAIK.

**Comment by Jerdo32** [comment]
There is no TwlBg.cxi there.

**Comment by Jerdo32** [comment]
Hold on, adding ^^TwlBg.cxi^^ fixed my issue.

**Comment by RocketRobz** [comment]
It shouldn't be there though. You only need `Widescreen.cxi` at `sd:/_nds/TWiLightMenu/TwlBg/`, and yes, not all games work with widescreen mode.

**Comment by ahezard** [comment]
This is a twilight menu issue
