### ISSUE TITLE
Kirby Super Star Ultra no longer works

### ISSUE THREAD

**Issue by remivamp** [ahezard/nds-bootstrap#75]
Even with Mario Kart DS set as my donor rom, Kirby Super Star Ultra fails to find a save file. How can I fix this?

**Comment by Robz8** [comment]
What region is your MKDS ROM?

**Comment by FateForWindows** [comment]
Same issue here, USA ROM. Other games that require a donor ROM such as Namcomuseum have no issues.

**Comment by Robz8** [comment]
In the TWLoader settings screen, update Release bootstrap, then set Bootstrap to Release.
If there's a cartridge inserted, try taking it out.

**Comment by FateForWindows** [comment]
Tried the release with no card, still white screen. I also tried messing with a few settings and it still didn't work.

**Comment by Robz8** [comment]
Do other games work?

**Comment by Robz8** [comment]
Try waiting for 10 minutes on the white screen.

**Comment by FateForWindows** [comment]
O_o Damn that's a long time. I'll try it.

**Comment by FateForWindows** [comment]
Tried it once again after playing a DSiWare game and loaded in 2 minutes. Don't know how but it worked.

**Comment by ahezard** [comment]
I am a litlle bit lost, is this game working or not with the latest release? Is it a save issue only?

**Comment by Robz8** [comment]
Yes, it's a save issue. A donor ROM is currently needed for the game to work.

**Comment by Robz8** [comment]
I think this can be closed now.
