### ISSUE TITLE
Pokemon 5 Gen they do not work (W/B & W2/B2)

### ISSUE THREAD

**Issue by DuraAdri** [ahezard/nds-bootstrap#750]
###

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?
- Pokémon Black and White & White 2 and Black 2

Game goes here if applicable

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by edo9300** [comment]
You have to boot any twl game (DSO enhanced/exclusive) in ds mode

**Comment by DuraAdri** [comment]
Probably yes, I use the latest update available. 
My configuration is as follows: 
Boot Mode: DS mode
CPU Speed: 67 MHz 
VRAM acceleration disabled
 Bootstrap launch 
I don't have much idea of ​​the subject, I'm sorry.

**Comment by edo9300** [comment]
So they don't boot even if you're launching them in ds mode? Are you using any cheat?

**Comment by DuraAdri** [comment]
I don't know, but I haven't used tricks. The screen goes blank, I can't do anything.

**Comment by RocketRobz** [comment]
If `usrcheat.dat` exists at `sd:/_nds/TWiLightMenu/extras/`, delete it.

**Comment by DuraAdri** [comment]
Thank u, its work 😍
