### ISSUE TITLE
Infinity Space

### ISSUE THREAD

**Issue by jasiu512** [ahezard/nds-bootstrap#751]
### Your console

Tell us which console you are using:

- [ *]  DSi (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [* ]  Unlaunch+HiyaCFW _[please specify versions of both]_
Twilight Menu v9.4.0

### nds-bootstrap version

Tell us which versions you are using:

- [* ]  Release _[ 0.24.0]_

### Your device

Tell us which card you are using:

- [ *]  SD Card

### If this issue only affects a certain game, which game is it?

Infinity Space

### Expected behaviour

Tell us what should happen

### Actual behaviour
The intro is playing 
The game run but only on bottom screen. The top screen is white. 
![IMG_20190917_074814](https://user-images.githubusercontent.com/40211001/65014885-3e5d6600-d920-11e9-8417-cc82b99032f1.jpg)

**Comment by RocketRobz** [comment]
I thought that was fixed.
Are you sure you're on v0.24.0?

**Comment by jasiu512** [comment]
Yes. I'm sure. Just updated.
![IMG_20190917_075655](https://user-images.githubusercontent.com/40211001/65015127-f25ef100-d920-11e9-92c7-9ba2a0d2cc08.jpg)

**Comment by RocketRobz** [comment]
Did the nds-bootstrap logo show when launching the game for the first time?

**Comment by jasiu512** [comment]
Yes

**Comment by tomudo** [comment]
Undub version works for me.

**Comment by jasiu512** [comment]
I have checked this version now and unfortunately it still doesn't work.

**Comment by piratesephiroth** [comment]
Is this a DSi-only issue? The game works fine on the 3DS.

**Comment by jasiu512** [comment]
I have only DSi XL

**Comment by RocketRobz** [comment]
This issue doesn't seem to occur now.
