### ISSUE TITLE
Ghost Trick (EUR) - flickering screen/animations

### ISSUE THREAD

**Issue by hubert-skowronek** [ahezard/nds-bootstrap#752]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release 0.24
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Ghost Trick (EUR)

### Expected behaviour

All animations should be flawless

### Actual behaviour
Cut scenes of moving clocks/traveling between phones flicker sometimes. In Chapter 7 the scene when Lynne is going to die flickers violently.

### Steps to reproduce

1. Download my save file https://drive.google.com/file/d/1i8AcsJ1zgZv9PAcpWuLgAclxtVhBH3Cz/view?usp=sharing
2. Run the game
3. Choose chapter 7
4. Notice how the bottom screen tears/flickers during cut scene of Lynne's death

**Comment by RocketRobz** [comment]
Are you using NTR clock speed or TWL clock speed?

**Comment by hubert-skowronek** [comment]
NTR clock speed

**Comment by RocketRobz** [comment]
Sounds like a card read DMA issue.

**Comment by hubert-skowronek** [comment]
Just tested it with TWL speed - it is the same.

**Comment by Kaisaan** [comment]
Just tested this with the savefile that you have provided and I don't see any flickering in the cutscenes, so this seems to be fixed. Test on my DSi XL on nds-bootstrap version 0.32.1.

**Comment by hubert-skowronek** [comment]
@Kaisaan what settings do you have? With bootstrap 0.32.1 I still have flickering just before Lynne dies

**Comment by hubert-skowronek** [comment]
Also the animation in chapter 16 of emerging submarine still flickers - @RocketRobz I think this issue should be reopened

**Comment by Kaisaan** [comment]
@hubert-skowronek I have it set to Run in DSi mode, with TWL speed and VRAM boost On.

**Comment by hubert-skowronek** [comment]
I still get flickering during the cutscene in chapter 16 even with above mentioned settings

**Comment by RocketRobz** [comment]
The issue could be related to the SD card then.

**Comment by hubert-skowronek** [comment]
@RocketRobz how can I verify it to be 100% sure that's SD card related issue? I never had SD related problems when using nds-bootstrap since the very first version released

**Comment by hubert-skowronek** [comment]
@RocketRobz Tried the same configuration with another new 3DS XL unit. Flickering still appears. Using 32 caching block size helps with submarine cutscene but not with dying Lynne in Chapter 7. For both 3DSes I use 32 GB sd cards formatted with 32 kb sector size, of class 10, these are of different brands (one is Kingstone, another is GoodRAM). Doesn't seem like SD card issue to me.

**Comment by piratesephiroth** [comment]
Try formatting the SD with the official SD Formatter software first, just so the partition gets aligned properly.
