### ISSUE TITLE
GBC game freezes from twilightmenu when lauched from 'recently played game'

### ISSUE THREAD

**Issue by elephantdino** [ahezard/nds-bootstrap#754]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ X]  Release _[v10.0.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Legend of Zelda, The - Oracle of Ages (U) [C][!]

### Expected behaviour

GBC game should launch 

### Actual behaviour

White square screen. Game does not launch

### Steps to reproduce

1. Load Legend of Zelda - Oracle of Ages (GBC) USA
2. Launch the game by finding it in roms folder
3. Quit to 3ds homescreen
4. Now launch the game from 'recently played' menu on twilightmenu v9.5.0
5. white square screen / game not launching

### Other notes

The white screen appears only when launching from the 'recently played' menu on twilightmenu v9.5.0. But if launched the game by finding it in roms folder, it runs perfectly regardless of using savestate or not. 
not sure if its front end or backend problem

**Comment by RocketRobz** [comment]
This is a TWiLight Menu++ issue, not an nds-bootstrap issue.
