### ISSUE TITLE
Tony Hawk's American Sk8land Freezed

### ISSUE THREAD

**Issue by MikeCruzer** [ahezard/nds-bootstrap#755]
### Your console

Tell us which console you are using:

-   Old 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

-  Luma3DS

### nds-bootstrap version

Tell us which versions you are using:

-   Release _[0.24.1]_

### Your device

Tell us which card you are using:

- SD Card

### If this issue only affects a certain game, which game is it?

Tony Hawk's American Sk8land (USA)

### Expected behaviour

Created new save

### Actual behaviour

Game freezed 

### Steps to reproduce

1. launch game
2. Tap "New Save"
3. Enter save name

### Other notes

When i creating new save - game freezed.

**Comment by vulpes-vulpeos** [comment]
Tried to lunch this game myself - same issue.

**Comment by RocketRobz** [comment]
After the title screen, the crashes seem random, but it's seemingly always before entering a game.

**Comment by RocketRobz** [comment]
Ok, I was able to enter a name, and select one of the two options, but the game froze after doing so.
