### ISSUE TITLE
Some games not working without ceCached setting

### ISSUE THREAD

**Issue by RocketRobz** [ahezard/nds-bootstrap#759]
* Castlevania: Order of Ecclesia
* Ultimate Mortal Kombat
* The World Ends With You

Issue reported by Auri and Dartz

**Comment by piratesephiroth** [comment]
yeah we need to hold down L

**Comment by RocketRobz** [comment]
Not anymore, with TWLMenu++ v9.5.1.

**Comment by ahezard** [comment]
So can we close that?
