### ISSUE TITLE
Pokemon Platinum randomly speeding up

### ISSUE THREAD

**Issue by Gogobr8** [ahezard/nds-bootstrap#761]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release v0.24.1
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokémon Platinum (U)

### Expected behaviour

Game should run at normal speed

### Actual behaviour

Game consistently speeds up

### Steps to reproduce

1.
2.
3.

### Other notes

[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/3664802/NDSBTSRP.LOG)

The game ran normally until I updated the bootstrap via the Twilight Updater one day. Now it just speeds up randomly. Or rather, it seems to speed up outside of towns, where I'd guess it's processing more stuff? It's always sped up when using the menus and in battles. It's more evident in the "Pokemon" menu, where the little sprite animations move way too fast.
 
The Twilight menu settings are all the default ones. This only seems to happen with this game, I also play Fire Emblem and Advance Wars, and they run normally.

**Comment by RocketRobz** [comment]
Delete the `apfix` folder in `sd:/_nds/TWiLightMenu/`, then install (or re-install) the latest version of TWiLight Menu++.

**Comment by Gogobr8** [comment]
Perfect. Thank you very much!
