### ISSUE TITLE
Resident Evil: Deady Silence freezing on death, buzzing when music plays

### ISSUE THREAD

**Issue by ajs91** [ahezard/nds-bootstrap#762]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[0.24.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Resident Evil: Deadly Silence 

### Expected behaviour

No freezing, no buzzing 

### Actual behaviour

The game will completely freeze after displaying the "You Died" screen. Waiting or pressing a button to return to the menu both produce the same result. Additionally, there is a strange loud buzzing noise that can be heard during sections of the game with music 

### Steps to reproduce

1. The buzzing can be heard right at the beginning of the game on the first floor of the mansion
2. The freezing on death can be reproduced anywhere in the game.
3.

**Comment by dubbz82** [comment]
This is likely because the system is soft resetting after each death.  This issue is directly related to issue #259

**Comment by RinMaru** [comment]
no idea why the music still buzzes though it happens to me too

**Comment by dubbz82** [comment]
Indeed..this seems like two separate, unrelated issues really.  I know some time back a lot of other games had problems with audio, but most have long since been cleared up.  This game in particular must do something with the sound that's different from others...

**Comment by RinMaru** [comment]
> Indeed..this seems like two separate, unrelated issues really. I know some time back a lot of other games had problems with audio, but most have long since been cleared up. This game in particular must do something with the sound that's different from others...

yea its been around. even reported it on the PR while in testing phase i believe

**Comment by Stack3r** [comment]
Closing this, the you are dead issue has been fixed due to proper soft resetting, also the buzzing issue has not been encountered

**Comment by HazNut** [comment]
Hi @Stack3r, just been playing Deadly Silence and noticed the buzzing audio still seems to be an issue, although this isn't heard everywhere in the game. Wanted to give some indication of where it's happening.

I've just started a fresh save again (Rebirth mode as Jill), and noticed the first time you can hear it is in the room where you fight zombies with the knife for the first time (when you go to the east wing after looking for Wesker). There's a period of a few seconds of buzzing audio that takes a while to reappear (this isn't the sound of the zombie eating nearby). Also happens a bit while you're actually fighting the zombies with the knife.

It also happens in the tiny corridor before you go outside and find Forest's body (very obvious here), and in the west wing save room, where it plays the save room music.

I'm on version 2.9.1 if that helps.

If testing you can skip doors and cutscenes so wouldn't take too long to get to that first spot.

I've tried running the game in DS mode, and increasing audio quality in TwilightMenu, and it made no difference.
