### ISSUE TITLE
Kirby Squeak Squad and Black Sigil - Longer loading times/white screens inbetween 

### ISSUE THREAD

**Issue by PurpleHazeFeedback** [ahezard/nds-bootstrap#763]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[latest versions for both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.24.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Kirby Squeak Squad

Black Sigil: Blade of the Exiled

### Expected behaviour

Kirby Squeak Squad should load new areas fast and have zero hiccup when Kirby swallows an enemy and gains a copy ability, same goes for when pressing enter to get to the menu/power-up info screen and getting hit. There shouldn't be any hiccups/hanging normally.

Black Sigil should also load enemy battles fairly quickly, about one or two seconds of white screen on normal hardware.

### Actual behaviour

Kirby Squeak Squad hangs/has long periods of white screen (about 7 or 8 seconds) when going into new areas or parts of the level (after a door), and has mini-pauses/hiccups when gaining power-ups or getting hit and loosing said power-ups, about a solid 2 or 3 second pause before going back into normal gameplay (sound still goes on in the background)

Black Sigil also features the same problem when going into a random encounter. On normal hardware there might be a small pause (again, one or two seconds), but here it hangs for 5 seconds and sometimes longer when going into battle (white screen transition, and again, sound carries on in the background)

### Steps to reproduce

1. Play Kirby SS or Black Sigil
2. In Kirby, simply progress into new areas and get powerups/get hit while having said powerups and also open up the menu. In Black Sigil, progress until you get to your first random encounter in the overworld map (the first scripted fight doesn't count)
3. Compare to gameplay videos or actual hardware if possible and a noticeable difference in loading speed can be seen (assuming it's not a problem specific to my setup)

### Other notes

I have tried many different ROMs, but all of them seem to share the same problem.

**Comment by PurpleHazeFeedback** [comment]
UPDATE: Still the same problems even with the new bootstrap release.

**Comment by RocketRobz** [comment]
Can you check v0.26.1?

**Comment by PurpleHazeFeedback** [comment]
Yes of course, but it will take me a while since I usually do these tests on multiple DSi's. Will update shortly after I've played through both for a bit.

**Comment by PurpleHazeFeedback** [comment]
Ok, so I'm happy to report that it seems like the issue has been fixed with both games. Both Kirby and Black Sigil are a lot more snappy and quick with the loading, and when comparing them to gameplay recordings on Youtube and actual gameplay from a DS cartridge it doesn't seem like there's a difference in frame-by-frame speed/loading time. I'll close the thread now, thank you!
