### ISSUE TITLE
Solatorobo: Red the Hunter - AP-checks are still intact and blocking saves without manual patch [EUR and USA]

### ISSUE THREAD

**Issue by minishLAN** [ahezard/nds-bootstrap#765]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
**- [x]  New 3DS/2DS (XL)**

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

**- [x]  Luma3DS**
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

**- [x]  Release _[0.24.1]_**
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

**- [x]  SD Card**
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

**Solatorobo: Red the Hunter [EUR]
Solatorobo: Red the Hunter [USA]**

### Expected behaviour

The game should be saving at save points

### Actual behaviour

It's not saving

### Steps to reproduce

I'm not sure how applicable this is here. The game just isn't saving when the prompts ask for it, both at save points and throughout the game. I have reproduced this on different ROMs from two regions (EUR and USA). You'll spot this immediately after saving at the first save point on the Hindenberg, then resetting - you'll spot it just the same saving at any other save point too

### Other notes

I am using TWiLightMenu release v9.5.1, if that's at all relevant. Other games are saving, and the .sav files for Solatorobo are showing up in the /saves/ directory on the SD card - they just either aren't saving the actual data or aren't loading in the game.
Neither ROM was patched with any AP-patches.

**Comment by minishLAN** [comment]
**UPDATE: After testing a ROM with a manually applied AP-patch, the EUR version of the game can now save as normal with no issues. It appears the reason for this bug was that the AP-patch which was supposedly be applied automatically by nds-bootstrap / TWiLightMenu wasn't being applied at all. I'll keep the issue open, but rename it so it's clear it's specifically an AP patch issue.**

**Comment by RocketRobz** [comment]
Does this still happen on latest version?

**Comment by MikeModder** [comment]
Using nds-bootstrap v0.28.1 and TWiLightMenu v11.2.0 I can confirm that the US version of the game has no issues saving. I'm in the process of trying the European version, and I'll edit this comment when I get to the save point
