### ISSUE TITLE
Kirby Canvas Curse graphical glitching

### ISSUE THREAD

**Issue by chachachah** [ahezard/nds-bootstrap#769]
### Console

Old 3ds/2ds (XL)

### CFW and configuration

- [X ]  Luma3DS

### nds-bootstrap version

Tell us which versions you are using:

- [2.1.1 ] 
### Your device

- [ X]  SD Card

### If this issue only affects a certain game, which game is it?

Kirby Canvas Curse

### Expected behaviour

Floor graphics to load in or load in properly.

### Actual behaviour

Floor/solid surfaces are invisible, and there are green glitched vertical lines everywhere. The map at the top is fine. Somehow this doesn't affect the tutorial. Level 1 is all messed up, until you die , then the graphics load in. It's a little inconvenient to have to die every new screen just to be able to play the level. 

### Steps to reproduce

1. Start the game
2. Play the first level

### Other notes

The option to update TWIloader++ or ndsbootstrap is grayed out and says "This feature cannot be used yet." on my 3DS. I don't know if 2.1.1 is the latest version of TWLMenu++ and ndsbootstrap but that's the version I got. Is anyone else experiencing this? If not, then can someone hook me up with a working ROM or an AP patch for this issue? I used the AP patch finding tool, but it has no AP patch available for kirby canvas curse.

**Comment by RocketRobz** [comment]
The version shown is the launcher (now an updater) version, not the TWLMenu++ or nds-bootstrap version.
Please follow [this](https://github.com/DS-Homebrew/TWiLightMenu/wiki/How-to-update-TWiLight-Menu) guide to update.
