### ISSUE TITLE
Dragon Quest V Regression in 0.24.1

### ISSUE THREAD

**Issue by alex34567** [ahezard/nds-bootstrap#771]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release 0.24.1
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Dragon Quest V (Usa) 

### Expected behaviour
Game boots.

### Actual behaviour
White screen.

### Steps to reproduce

1. Open twilight menu++
2. Run the rom for Dragon Quest V.

### Other notes
Works if you downgrade nds-bootstrap to 0.24.0
The sd card is 128 Gb.

**Comment by RocketRobz** [comment]
Works for me on the latest version.
Make sure TWiLight Menu++ is up to date, and update nds-bootstrap as well.

**Comment by gixnode** [comment]
Having same issue on latest release: Twilight Menu 10.1.0 and nds-bootstrap 0.25.3

White screen right after launch and 'Now saving'.

**Comment by RocketRobz** [comment]
Make sure it's a clean ROM, and not AP-patched.
