### ISSUE TITLE
Touch Screen Not Working

### ISSUE THREAD

**Issue by pokams15** [ahezard/nds-bootstrap#772]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[it says No Version Available]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

all games, it seems

### Expected behaviour

the touch screen should work

### Actual behaviour

it doesnt

### Steps to reproduce

1.open twilight
2.open a game
3.try to touch the touch screen

**Comment by RocketRobz** [comment]
Install the latest nds-bootstrap version,

**Comment by pokams15** [comment]
> Install the latest nds-bootstrap version.

i can use the updater to do this, right?

**Comment by pokams15** [comment]
oh nvm i had everything updated before, but i accidentally deleted something, and redownloaded it, and when it opened, i thought everything was fixed, i didnt even think to check the updater, thank you :)
