### ISSUE TITLE
Games not opening?

### ISSUE THREAD

**Issue by pokams15** [ahezard/nds-bootstrap#773]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v9.5.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?
 
i think it affects only pokemon games, but one of the platinum roms i have works

### Expected behaviour

the game should open

### Actual behaviour

it doesnt open, it briefly says now saving, then it goes back to the dsi screen that shows up when you first open the app

### Steps to reproduce

1.open twilight
2.open a game
3.go back to the opening screen

### Other notes
i tried updating everything and it said the download failed

i opened these games before, but they dont open now

**Comment by RocketRobz** [comment]
Turn off `Update recently played list`.

**Comment by pokams15** [comment]
question, what dos that option do that causes the problem?

**Comment by RocketRobz** [comment]
There's a bug when updating the recently played list.
idk what's wrong, exactly.
