### ISSUE TITLE
Submenus takes a second to load

### ISSUE THREAD

**Issue by J0las** [ahezard/nds-bootstrap#774]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.25.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Anno: Create A New World EU

### Expected behaviour

Every menu after loading a safegame should open instanly.

### Actual behaviour

It takes at least one second to open up the menus.

### Steps to reproduce

1. Create or load a safestate (it doesn´t matter if its a story or a custom game) 
2. Try to open a submenu like the buildmenu or the map (not the zoom button)

### Other notes

As far as I can tell it does not matter which configuration  the game is launched with (cpu speed vram boost etc.).

There was no issue with at least v0.21.2 and before.

**Comment by RocketRobz** [comment]
Seems to be an issue with card read DMA.

**Comment by J0las** [comment]
I have started the game with the logfunction enabled on v0.25.3 maybe it can help.
[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/3708714/NDSBTSRP.LOG)

**Comment by FlameKat53** [comment]
@J0las, Hello, may you try this on the latest release of nds-bootstrap and TWiLight Menu++?

**Comment by NightYoshi370** [comment]
Also, make sure to disable debug and log when you do test again

**Comment by J0las** [comment]
Hello, using the latest non-nigthly builds of nds-bootstrap v0.28.1 and TWiLight Menu++ v11.2.0, without any debugging or logging enabled, the issue seemes to be resolved, all loading times returned to their normal behavior.

Thanks for the fix,
I really appreciate the help.
