### ISSUE TITLE
Dragon Quest 5 White screen from version 0.24 on 

### ISSUE THREAD

**Issue by Luka020** [ahezard/nds-bootstrap#776]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[from version 0.24 till the latest version 0.25.3]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
Dragon Quest 5 
### Expected behaviour

Tell us what should happen
The game should play as normal
### Actual behaviour
Tell us what happens instead
When starting up the game, i get a white screen and it stays that way

### Steps to reproduce

1.Start up the game with nds-bootstrap 0.24 and higher 
2. You will get a White screen, and remain stuck 
3.

### Other notes
The game still works on nds-bootstrap version 0.23 and lower.
I tried starting up the game as normal and as a quick start after i exited out of the TwilightMenu++

The game is manually AP patched

**Comment by RocketRobz** [comment]
Try a clean ROM instead.

**Comment by Luka020** [comment]
and it worked :) THANK YOU 💯
