### ISSUE TITLE
Blackscreen after boot in Big Bang Mini

### ISSUE THREAD

**Issue by SleepyLark** [ahezard/nds-bootstrap#777]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.9 + v1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.25.2]_
- [ ]  Nightly _[N/A]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Big Bang Mini

### Expected behaviour

Game boots into starting menu

### Actual behaviour

The developers logo appears followed by a short sound clip and then proceeds to create a new save file.  After that it's just a black screen.

### Steps to reproduce

1. Launch game
2. Wait
3. Blackscreen

### Other notes
I have already tried changing the clock speed to NTR and switch to DS Mode.

**Comment by RocketRobz** [comment]
Try holding L after pressing A/START to launch the game.

**Comment by SleepyLark** [comment]
It works now, I keep forgetting that holding L was a thing :P 
Thx
