### ISSUE TITLE
Ace Attorney Investigation 1 (Gyakuten Kenji 1) doesn't start.

### ISSUE THREAD

**Issue by AmiAlcock** [ahezard/nds-bootstrap#778]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch+HiyaCFW (Unlaunch v2.0 & HiyaCFW v1.3.2)

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release (0.25.3)

- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?
Ace Attorney Investigation 1 (Gyakuten Kenji 1) 

### Expected behaviour

Pop up CAPCOM logo.

### Actual behaviour

Both screens become white and nothing else is going on.
### Steps to reproduce

1. Launch rom

### Other notes

DSi LL  1.4.1J.
2DS XL with the same version of Twlight and bootstrap (10.1.0 & 0.25.3) starts this rom fine.

**Comment by SleepyLark** [comment]
I can also verify that it's not working.  Both my DSi and DSi XL whitescreens while my n3DS takes about 30 secs before booting.  Holding L or changing the clock speed does nothing

**Comment by trlkly** [comment]
I have the same 30 sec delay opening on 3DS--when I hold B in TwilightMenu++, which I believe loads nds-bootstrap directly. 

However, if I actually load it through TM++, there is no such delay. In fact, it is faster to let TM++ load entirely, and then load AAI. So it somehow bypasses the problem, despite using the same version of nds-bootstrap.

**Comment by AmiAlcock** [comment]
It started with bootstrap v0.22.0.

**Comment by SleepyLark** [comment]
If you wanted a quick and dirty solution and you don't normally use nightly builds, what you can do is find a previous version that worked  (0.22.0 for example), rename it to "nds-bootstrap-nightly" and put it in the "_nds" folder.  Then open up the per-game settings and change the bootstrap to "Nightly".  Doesn't really solve the problem, but will at least let you still play it until a solution has been found.

**Comment by AmiAlcock** [comment]
I already did it lol, thx.

**Comment by RocketRobz** [comment]
Can you check if the bug persists in v0.26.1?

**Comment by SleepyLark** [comment]
I already did, still doesn't boot.  I messed with the heap sizes, but that didn't change anything.  On the brightside, when running it on the 3DS it takes 10 secs to boot compared to the it previously taking 30 secs

**Comment by RocketRobz** [comment]
What SDK version is the ROM?

**Comment by AmiAlcock** [comment]
SDK 4

**Comment by SleepyLark** [comment]
Still broken in 0.27.0 :/

**Comment by SleepyLark** [comment]
So I tried it on both 0.27.0 and 0.27.1 and it does boot if you turn heap shrink to off.  However, it takes 30 seconds before the game actually starts, meaning during that time it's just a white screen.  Any ideas why?  Because I've never heard of a game taking that long to load

**Comment by RocketRobz** [comment]
Nintendo DS Browser also takes long, but it's a few minutes longer.

**Comment by edo9300** [comment]
I remember this game worked flawlessly in the previous versions, in fact I played it on my console with no issues, I checked now with the latest version of both twilight and the bootstrap, and here too it's stuck on white screen

**Comment by RocketRobz** [comment]
Closing, since it at least boots.
