### ISSUE TITLE
Freeze at save point - Super Robot Wars OG Saga: Endless Frontier EXCEED (Artema Translations) 

### ISSUE THREAD

**Issue by tomudo** [ahezard/nds-bootstrap#779]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch 2.0]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.25.3]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?
Super Robot Wars OG Saga: Endless Frontier EXCEED (Artema Translations) 

project link: https://gbatemp.net/threads/release-super-robot-wars-og-saga-endless-frontier-exceed-artema-translations.550014/

### Expected behaviour

Not freeze when saving at save point

### Actual behaviour

Game freeze at first save point

### Steps to reproduce

1. Run game from twilight menu
2. Play game until reach 1st save point in game
3. Game freeze when saving

### Other notes

The game run fine in acekard 2i and I see gbatemp post mention that R4 card work fine too.

**Comment by RocketRobz** [comment]
Try holding L after pressing A/START to launch the game.

**Comment by tomudo** [comment]
> 
> 
> Try holding L after pressing A/START to launch the game.

I just tried but it does not work.

**Comment by RocketRobz** [comment]
So it seems to be an AP issue.
A patch will be included in the next TWLMenu++ version.

**Comment by tomudo** [comment]
Add a note: I tested the original game without english patch work fine.

**Comment by RocketRobz** [comment]
Yeah, a patch was only included for the clean ROM.
TWiLight Menu++ v10.2.0 now included the patch for the english ROM.
