### ISSUE TITLE
Bookworm (retail version) not booting 

### ISSUE THREAD

**Issue by SleepyLark** [ahezard/nds-bootstrap#781]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.9+1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.25.3]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x] SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Bookworm 

### Expected behaviour

Game should load

### Actual behaviour

Black screen 

### Steps to reproduce

1. Load game
2. Wait
3. Nothing shows up

### Other notes
Holding L or changing the clock speed does nothing

**Comment by RocketRobz** [comment]
I guess this is one of those odd games that only work on 3DS.
