### ISSUE TITLE
I cant play pokemon games on my dsi

### ISSUE THREAD

**Issue by koolaidmanonds** [ahezard/nds-bootstrap#782]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ This]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [HiyaCFW ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ This]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon games

### Expected behaviour

The game should just load up like normal

### Actual behaviour

It shows nds bootstrap at the top, and says an error occured under that

**Comment by RocketRobz** [comment]
Please run the games in DS mode.

**Comment by koolaidmanonds** [comment]
how do i run it in ds mode

**Comment by RocketRobz** [comment]
Go into TWLMenu++ settings, switch to `Games/Apps` page, and set `Run in` to `DS Mode`.

**Comment by koolaidmanonds** [comment]
Thanks for the help
