### ISSUE TITLE
Metroid prime pinball (U) - Performance issue - Minor stuttering.

### ISSUE THREAD

**Issue by tomudo** [ahezard/nds-bootstrap#783]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch 2.0]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.25.3]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Metroid prime pinball (U) 

### Expected behaviour

No stuttering during game play.

### Actual behaviour

The game lags. Some noise sound during stuttering.

### Steps to reproduce

1. Launch game by twilight menu
2. Start game
3. Noise sound because of lagging. Game play lags.

### Other notes
There are similar issues.
https://github.com/ahezard/nds-bootstrap/issues/222
https://github.com/ahezard/nds-bootstrap/issues/377

Hold L after launch game does temporary fix this issue.

edit: Could you explain what is hold L doing?

**Comment by RocketRobz** [comment]
Holding L moves cardEngine arm9 binary into a cached area, by shrinking the heap, and putting the binary into a prior heap area.
Originally, it moved it out of the cached area, with the default being that it's in the cached area, but broke some games.
