### ISSUE TITLE
Pokemon Platinum running at high fps

### ISSUE THREAD

**Issue by Rainer726** [ahezard/nds-bootstrap#784]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.26.0]_
- [ ]  Nightly _[bb7a4e72]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon Platinum (mine is Europe, i don't know if in different regions of the game happens)

### Expected behaviour

That the game go at normal speed

### Actual behaviour

Instead the game runs with a high FPS

### Steps to reproduce

1. Only booting up the game

### Other notes
Changing the settings doesn't seem to fix the framerate problem, so i don't know what cause it,
also the same issue happens with both release and nightly

**Comment by RocketRobz** [comment]
Delete `apfix` folder at `sd:/_nds/TWiLightMenu/apfix/`, and re-add it from latest TWLMenu 7z file.

**Comment by Rainer726** [comment]
> Delete `apfix` folder at `sd:/_nds/TWiLightMenu/apfix/`, and re-add it from latest TWLMenu 7z file.

I only needed to delete the apfix folder and now runs perfectly, thanks for the help

**Comment by RocketRobz** [comment]
Please re-add it.
Some other games won't work without it.
