### ISSUE TITLE
NDS-Bootstrap v26 Pokemon Black boot error

### ISSUE THREAD

**Issue by DavoThePhat** [ahezard/nds-bootstrap#785]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x ]  Unlaunch+HiyaCFW _(Unlaunch 2.0 & HiyaCFW 3.5.1)_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _(v.0.25.3)_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon Black

### Expected behaviour

Game should boot up

### Actual behaviour

I get an error message from NDS-Bootstrap

### Steps to reproduce

1. Launch game

### Other notes

Other games work just fine, it's just Pokemon Black 1 & 2. I had them working just fine once, but never before nor since. I have tried updating and reinstalling everything from the rom to the launchers and nothing seems to work.

**Comment by RocketRobz** [comment]
You need to run the games in DS mode.

**Comment by DavoThePhat** [comment]
Ohhhh I see. Thanks man, forgot I changed that.
