### ISSUE TITLE
Pokémon Conquest Stuck on White Screen

### ISSUE THREAD

**Issue by kaiiboraka** [ahezard/nds-bootstrap#788]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.26.0]_ 
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokémon Conquest

### Expected behaviour

The game should open.

### Actual behaviour

Launching the game from TwilightMenu++ results only in a frozen white screen that requires hitting the Home or Power buttons to return to 3DS home menu to get out of.

### Steps to reproduce

1. Use AP Patched game
2. Launch from TwilightMenu++
3. ?????
4. Profit (jk)

### Other notes

I've tried what feels like every possible combination of a bunch of different testing methods and nothing seems to yield positive results:

- AP Patched or not
- Using the AP "cheat" from the menu
- Running in either DS mode or DSi Mode
- Nightly bootstrap vs Release bootstrap

Like I said, I've mixed and matched across those as much as I could, and I've done extensive googling. Lots of people say they just do one or two little things (like any of the above) and it just magically starts working for them. I've yet to even see the game launch at all. 

I'm at the end of my rope here, and the only thing I can narrow down as "not behaving properly" is the bootstrapper itself, since the game just isn't even opening after selecting it.

Please let me know what other details you would like me to provide, or steps to follow, and I'll do my best.
Please and thank you in advance for your help.

**Comment by RocketRobz** [comment]
Try with no cheat.

**Comment by kaiiboraka** [comment]
Okay, so while I was waiting for a response I went and re-patched my clean copy of the game, and did some of the same testing.

I've just now gone and tried to run the AP patched version in default DSi mode on release bootstrap with no cheat AP fix, and I'm still getting the frozen white screen.

**Comment by kaiiboraka** [comment]
Tried it again in reverse -- non-patched game but using the cheat, same thing.
(man, how come everyone else got theirs to work with just one little fix? :( </3 )

**Comment by SleepyLark** [comment]
Run it in DS mode, DSi mode still isn't implemented yet and will crash the game on launch

**Comment by kaiiboraka** [comment]
I'll be sure to keep trying it in that mode and not DSi, I was just led to believe by the official compatibility chart that it might work in DSi mode now.
https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit#gid=0
