### ISSUE TITLE
Shin Megami Tensei: Strange Journey -- AP-patch not applied

### ISSUE THREAD

**Issue by ralsei** [ahezard/nds-bootstrap#789]
### Your console

Nintendo New 3DS XL

### CFW and configuration

Luma3DS 10.0.1, fastboot3DS

### nds-bootstrap version

Release 0.25.3 bundled with TWiLightMenu++ 10.1.0

### Your device

SD Card -- Samsung 64GB Class-10

### If this issue only affects a certain game, which game is it?

Shin Megami Tensei: Strange Journey

### Expected behaviour

Game should run and act appropriately

### Actual behaviour

Anti-piracy is detected, with the following symptoms:
* Random crashes
* No random encounters while exploring
* Save-game gets inexplicably "corrupted"

### Steps to reproduce

1. Load a SMT:SJ rom in TWiLightMenu++
2. Get through the first bit of the game
3. Observe aforementioned anti-piracy symptoms

### Other notes

I'm not sure if this counts as TWiLightMenu++'s fault or nds-bootstrap. Not sure what's in charge of applying the patches.

**Comment by RocketRobz** [comment]
Apparently, the issue is with the patch itself.

**Comment by ralsei** [comment]
really? that's surprising to me, especially when considering the patch worked for a time, but eventually failed...

**Comment by RocketRobz** [comment]
Does this still happen?
If so, I'll let RetroGameFan know about this.
