### ISSUE TITLE
Castlevania order of ecclesia still crasg with The bat screen, how works speedbumpinclude?

### ISSUE THREAD

**Issue by plusdjmaster** [ahezard/nds-bootstrap#791]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
What versions of TWLMenu++ and nds-bootstrap are you using?

**Comment by plusdjmaster** [comment]
10.2.0 y nds-bootstrap v0.26.0. But i was use 9.51 and stills crash in the same way. I dont know how to use speedbumpinclude.

**Comment by RocketRobz** [comment]
SpeedBumpInclude is a list, not an actual feature.
You can hold L, after pressing A/START to launch the game, to run it as if it's not in the SpeedBumpInclude list.
If that doesn't work, update both TWLMenu++ and nds-bootstrap nightlies.
then in TWLMenu++ settings, set Bootstrap to Nightly.

**Comment by plusdjmaster** [comment]
I try that before but i will try again.

**Comment by plusdjmaster** [comment]
Sometimes crash on a black screen and sometimes still miss in The same way

**Comment by plusdjmaster** [comment]
did you suggest something more?
