### ISSUE TITLE
Taiko no Tatsujin DS: Touch de Dokodon! Top/Bottom screen swapping flicker

### ISSUE THREAD

**Issue by wilsonwsun** [ahezard/nds-bootstrap#793]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ x]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Taiko no Tatsujin DS: Touch de Dokodon!

### Expected behaviour

Play normally.

### Actual behaviour

Top/Bottom screen swapping

### Steps to reproduce

1. open game.
2.
3.

### Other notes
Happened to both NTR and TWL speed.

**Comment by RocketRobz** [comment]
Try the latest release, which is v0.26.1.

**Comment by wilsonwsun** [comment]
I turned on debug in Twilight menu, and notice it said both cpu and vram are boosted although the setting is in NTR and VRAM boost disabled (double checked in the setting.ini.) I also tried to disable them in game setting, but it would still turn clock speed and vram boost on. I renamed setting.ini to setting.old to reset the setting. Then, the problem went away.  It looks like somehow the bootstrap setting is not being loaded correctly with the setting.ini I had. Attached the setting with problem below. Weird.

```
[SRLOADER]
PAGE_NUMBER = 0
CURSOR_POSITION = 24
STARTMENU_CURSOR_POSITION = 0
CONSOLE_MODEL = 2
AUTORUNGAME = 0
LANGUAGE = -1
USE_GBARUNNER2 = 1
SHOWLOGO = 0
SECONDARY_ACCESS = 0
SHOW_MAIN_MENU = 1
THEME = 3
SUB_THEME = 0
SHOW_DIRECTORIES = 1
SHOW_BOX_ART = 1
ANIMATE_DSI_ICONS = 1
SLOT1_LAUNCHMETHOD = 1
BOOTSTRAP_FILE = 1
USE_BOOTSTRAP = 1
AK_VIEWMODE = 2
AK_SCROLLSPEED = 16
AK_THEME = DS Menu
AK_ZOOM_ICONS = 1
SHOW_12H_CLOCK = 1
ROM_FOLDER = sd:/roms/nds/
SECONDARY_ROM_FOLDER = fat:/
SECONDARY_PAGE_NUMBER = 0
SECONDARY_CURSOR_POSITION = 0
PREVIOUS_USED_DEVICE = 0
LAUNCH_TYPE = 1
HOMEBREW_BOOTSTRAP = 0
SORT_METHOD = 1
COLOR_MODE = 0
BLUE_LIGHT_FILTER_LEVEL = 0
GBAR2_WRAMICACHE = 1
SD_REMOVE_DETECT = 1
DSI_SPLASH = 0
HS_MSG = 0
DSI_MUSIC = 1
SHOW_NDS = 1
SHOW_RVID = 0
SHOW_NES = 0
SHOW_GB = 0
SHOW_SMSGG = 0
SHOW_MDGEN = 0
SHOW_SNES = 0
UPDATE_RECENTLY_PLAYED_LIST = 0
SHOW_HIDDEN = 0
FLASHCARD = 0
FC_SAVE_ON_SD = 1
SLOT1_SCFG_UNLOCK = 0
R4_THEME = Nintendo 3DS
DSI_THEME = dark
3DS_THEME = light
SNES_EMULATOR = 1
WIDESCREEN = 0
ROM_PATH = sd:/roms/nds/1235 - Taiko no Tatsujin DS - Touch de Dokodon! (Japan).nds
GBAR2_DLDI_ACCESS = 1

[NDS-BOOTSTRAP]
LANGUAGE = -1
BOOST_CPU = 0
BOOST_VRAM = 0
DSI_MODE = 1
FORCE_SLEEP_PATCH = 0
SOUND_FREQ = 0
```
