### ISSUE TITLE
Castlevania order of ecclesia still missing, i try everything, installa 10.3.0, i hold L, and now no put de black screen, but steel freezing in the bat screen?

### ISSUE THREAD

**Issue by plusdjmaster** [ahezard/nds-bootstrap#795]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
What region is the ROM?

**Comment by plusdjmaster** [comment]
I try with Europe, and Usa región?

**Comment by RocketRobz** [comment]
Is the ROM modified in any way?

**Comment by plusdjmaster** [comment]
How to know that?

**Comment by RocketRobz** [comment]
If the ROM is smaller than 64MB.

**Comment by plusdjmaster** [comment]
No.

**Comment by RocketRobz** [comment]
Do the other Castlevania games work?

**Comment by plusdjmaster** [comment]
Portrait of Ruin perfecto.
Dawn of sorrow and OOE, failed.

**Comment by RocketRobz** [comment]
Dawn of Sorrow works for me.
My guess is that your DOS and OOE ROMs are corrupt somehow.

**Comment by plusdjmaster** [comment]
Well i try with some versions of order of ecclesia you can suggest me where i can find a good versión, i will guess for your idea

**Comment by plusdjmaster** [comment]
Please.

**Comment by RocketRobz** [comment]
Sorry, can't say the name of ROM sites here.

**Comment by plusdjmaster** [comment]
Ok, no problem. I will still try with other roms.
 A last questio, for you OOE crash with The bat and The WiFi screen.

**Comment by RocketRobz** [comment]
Never tried it.

**Comment by plusdjmaster** [comment]
I try with The game in emulators and works fine. 
The only is my pc is slow and my phone too, almost every game works but this game is The only who still crash.

**Comment by plusdjmaster** [comment]
Thanks, and sorry for The annoyance.

I will let open the issue if someone more wants to say something about the or if i know how to solve.

**Comment by plusdjmaster** [comment]
Dawn of Sorrow works now, i downloaded other versions of OOE and stills without work

**Comment by plusdjmaster** [comment]
I play in the twilight all the versions of Castlevania DOS and POR and works perfectly, but any version of OOE Works.

**Comment by RocketRobz** [comment]
*Doesn't* work, you mean?

**Comment by plusdjmaster** [comment]
Doesn't work, right, i downloaded in every región with every realese in diferent parts and still crash.

**Comment by plusdjmaster** [comment]
But  DOS and POR founds perfect.

**Comment by plusdjmaster** [comment]
There will be another version of Twilight Menu?

**Comment by RocketRobz** [comment]
Yes, but it most likely won't fix your issue.

**Comment by RocketRobz** [comment]
What console are you using?

**Comment by plusdjmaster** [comment]
DSi XL

**Comment by RocketRobz** [comment]
and is Unlaunch installed?

**Comment by plusdjmaster** [comment]
No

**Comment by RocketRobz** [comment]
That's why Order of Ecclesia isn't working then.
Follow this guide: http://dsi.cfw.guide/
The HiyaCFW part is optional, btw

**Comment by plusdjmaster** [comment]
I have to format The consolé, if gives me The mismatch error.

**Comment by plusdjmaster** [comment]
I need to formar thw consolé if gives me The mismatch fat error?

**Comment by RocketRobz** [comment]
No.

**Comment by plusdjmaster** [comment]
So what i can do with that failed?

**Comment by RocketRobz** [comment]
Buy another DSi console.

**Comment by piratesephiroth** [comment]
> 
> 
> I need to formar thw consolé if gives me The mismatch fat error?

https://dsi.cfw.guide/faq

**Comment by plusdjmaster** [comment]
Erase DSIWARe What means?

**Comment by piratesephiroth** [comment]
Games or applications that you installed using twllnf

**Comment by plusdjmaster** [comment]
Doesn't. Work

**Comment by RocketRobz** [comment]
So you copied them to the SD card, deleted them on System Memory, then you copied them back from the SD to System Memory.

**Comment by plusdjmaster** [comment]
Flipnote studio too?

**Comment by RocketRobz** [comment]
Yes.

**Comment by plusdjmaster** [comment]
I will try again

**Comment by plusdjmaster** [comment]
I need sudohax in The console?

**Comment by RocketRobz** [comment]
No.

**Comment by plusdjmaster** [comment]
I give up, i do it everything but still gives me mismatch in fat copies.
Do you know how to use memory pit with twiligth menu?

**Comment by RocketRobz** [comment]
Yes, but I don't recommend it.
Please just buy another DSi console, or wait for an nds-bootstrap version that somehow fixes the OOE issue, if you want to use TWiLight Menu++ without any WiFi-related issues.

**Comment by plusdjmaster** [comment]
Sory for take this issue again but, i get install unlaunch with a sofware knows like temp Nand and castlevania works, again.

**Comment by plusdjmaster** [comment]
Thanks for suggest me the unlaunch, now i can finally play the game, and install hiya cfw.
