### ISSUE TITLE
WarioWare: Touched! - touchscreen is jittery/unresponsive

### ISSUE THREAD

**Issue by PurpleHazeFeedback** [ahezard/nds-bootstrap#798]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[latest versions for both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.27.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

WarioWare: Touched!

### Expected behaviour

Game's touchscreen controls should work fine.

### Actual behaviour

Touchscreen is unresponsive. When trying to move a character in the menu/game room, they jitter around instead of moving smoothly. Microgames are also heavily affected, some are almost impossible to complete..

### Steps to reproduce

1. Play any ROM of WarioWare Touched
2. Try to move any character in a straight line or try playing a microgame that requires precise movement.
3. That's about it I guess.

### Other notes

Game used to work fine on older nds-bootstrap versions. It's not an issue with my touchscreen since in Flipnote I can draw straight lines perfectly and there aren't any other noticeable issues. I don't know if WarioWare is the only affected game or if there are any others, but I tried Kirby Canvas Curse and that worked fine.

**Comment by RocketRobz** [comment]
Sorry, can't reproduce this. :(
Touch always worked fine for me.

**Comment by PurpleHazeFeedback** [comment]
Any idea what might have caused this for me? It's the only touchscreen game that acts like this for me (that I know of/have tried)

**Comment by RocketRobz** [comment]
Do you have a flashcard?

**Comment by PurpleHazeFeedback** [comment]
No.

**Comment by RocketRobz** [comment]
Try directly booting TWLMenu++ using Unlaunch.

**Comment by PurpleHazeFeedback** [comment]
Done, what now? Do I just try the game again?

**Comment by RocketRobz** [comment]
Yes.

**Comment by PurpleHazeFeedback** [comment]
That didn't work, but I found something interesting. I randomly decided to try and remove my save file from the SD card and see if the game behaves differently. Sure enough it works fine when starting anew. This could mean either one of two things:

- my save file was corrupted for some reason and it affected the touchscreen (don't know how possible or even logical this is)

- the game only works fine up to a certain point (my save file was up to when you unlock Dr. Crygor)

**Comment by DabkunTV** [comment]
Same problem is happening to me with this game, all other games working fine, also a DSi, tried replacing the save file and the rom, didnt work for me. Also no flashcard and tried booting with unlaunch but no luck
