### ISSUE TITLE
"Chuukana Janshi Tenho Painyan Remix" and "Idol Janshi Suchi-Pai III Remix" black screen freeze

### ISSUE THREAD

**Issue by tomudo** [ahezard/nds-bootstrap#799]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.26.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

"Chuukana Janshi Tenho Painyan Remix" and "Idol Janshi Suchi-Pai III Remix"

### Expected behaviour

Not freeze when start game.

### Actual behaviour

Black screen Freeze immediately after start game.

### Steps to reproduce

1. start game
2. black screen freeze

### Other notes

Hold L before game could bypass black screen freeze

**Comment by RocketRobz** [comment]
Turn off heap shrink in the per-game settings.

**Comment by tomudo** [comment]
> 
> 
> Turn off heap shrink in the per-game settings.

Wow, that is a amazing feature. It works. Thank you for add it.
