### ISSUE TITLE
Nine Hours, Nine Persons, Nine Doors produces white screen upon launch

### ISSUE THREAD

**Issue by Ilyas-Erdogan** [ahezard/nds-bootstrap#800]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release v0.27.0
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable
Nine Hours, Nine Persons, Nine Doors

### Expected behaviour

Tell us what should happen
The .nds file should launch, like all the others.

### Actual behaviour

Tell us what happens instead
Rather than the game launching, there is just a white screen

### Steps to reproduce

1. Open Twilight Menu++
2. Launch game, creates save file
3.NDS-Bootstrap screen appears, then flashes into white screen

### Other notes
I have tried AP patching the file as well, however the same thing happens
Edit: Forgot to mention I have switched it to DS Mode and that didnt work either

**Comment by RocketRobz** [comment]
Try turning off heap shrink in the per-game settings.

**Comment by Ilyas-Erdogan** [comment]
> Try turning off heap shrink in the per-game settings.

Sorry to bother you, but how do I do that?

**Comment by RocketRobz** [comment]
In the TWiLight Menu++ ROM menu, press Y, then scroll down.

**Comment by Ilyas-Erdogan** [comment]
> In the TWiLight Menu++ ROM menu, press Y, then scroll down.

I do not see an option to turn off heap shrink in the settings, am I missing something?

**Comment by RocketRobz** [comment]
Did you scroll past the last option shown?

**Comment by Ilyas-Erdogan** [comment]
Yes, the only option on Games and Apps settings is Logging and on the other pages the last options are: TWLMenu++ Splash Screen, Zooming Icons, SNES/SFC ROMs and BIOS intro

**Comment by RocketRobz** [comment]
I said to press Y, not to go to TWLMenu++ settings.

**Comment by Ilyas-Erdogan** [comment]
> I said to press Y, not to go to TWLMenu++ settings.

Sorry for the misunderstanding, I had assumed that pressing Y would take me to the TWLMenu++ settings. It is now working after pressing Y and disabling Heap shrink. Thank you so much for your time. Good luck on your future releases!
