### ISSUE TITLE
Prof. Layton and the Curious Village error

### ISSUE THREAD

**Issue by Drakyem** [ahezard/nds-bootstrap#801]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ X ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ X ]  Release _[v0.25.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ X ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Professor Layton and the Curious Village

### Expected behaviour

When starting a new game and entering your name, and after Luke speaks, a cutscene should appear.

### Actual behaviour

The cutscene seems to be played, but the screen goes black instead. You can hear it though, but then it finishes and nothing else happens.

### Steps to reproduce

1. Entering New Game
2. Typing your name

**Comment by RocketRobz** [comment]
Please update nds-bootstrap (and TWLMenu++, while you're at it).

**Comment by Drakyem** [comment]
Well, it worked like a charm, thank you
