### ISSUE TITLE
VFOD  Der Fluch der Osterinsel - white screen while starting in DSi mode

### ISSUE THREAD

**Issue by eku** [ahezard/nds-bootstrap#803]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [x]  Nightly _[always latest]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

VFOD  Der Fluch der Osterinsel

### Expected behaviour

Boots and runs fine.

### Actual behaviour

Stuck in boot with both upper and lower screen white.

### Steps to reproduce

1. Just boot.
2.
3.

### Other notes

When I force DS over DSi mode the game boots.

**Comment by RocketRobz** [comment]
Try turning off heap shrink in per-game settings.

**Comment by eku** [comment]
@RocketRobz the question is _Why does this game not run in DSi mode?_

**Comment by SleepyLark** [comment]
It's because the game is DSi Enhanced which isn't supported yet.

**Comment by RocketRobz** [comment]
DSi mode isn't implemented yet.
