### ISSUE TITLE
DSLinux White Screen

### ISSUE THREAD

**Issue by ProgrammingHider** [ahezard/nds-bootstrap#804]
### Your console

Tell us which console you are using:

- [ ]  DS Lite

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Nightly _[7a76aaf]_

### Your device

Tell us which card you are using:

- [ ]  Slot-1 Flashcard (R4i-Gold)

### If this issue only affects a certain game, which game is it?

DSLinux

### Expected behaviour

1. TWiLightMenu starts
2. DSLinux should load via nds-bootstrap
3. DSLinux Boot screen should appear

### Actual behaviour

1. TWiLightMenu Boots
2. DSLinux tries to lauch
3. A Wild White Screen has Appeared
### Steps to reproduce

1. Install TWiLightMenu
2. Install nds-bootstrap-nightly included with TWiLightMenu
3. Run DSLinux

### Other notes
This Only Affects DSLinux, other games run fine

**Comment by RocketRobz** [comment]
None of the homebrew on flashcards are loaded via nds-bootstrap.
This sounds more like an issue with the homebrew itself.
Make sure Direct boot is turned on in the per-game settings.
