### ISSUE TITLE
Ivy the Kiwi? (retail version) whitescreens on boot

### ISSUE THREAD

**Issue by SleepyLark** [ahezard/nds-bootstrap#806]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.9 + 1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.27.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Ivy the Kiwi? (retail version)

### Expected behaviour

Game should load

### Actual behaviour

Whitescreens immediately after boot

### Steps to reproduce

1. load game
2. wait
3. whitescreen

### Other notes
It's SDK 5 so heap shrink isn't an option.  I've tried changing to DS mode which didn't do anything.  I saw on the compatibility sheet that it may need to be AP patched, so I tried using DS-Scene to AP patch it but it still wouldn't boot.  Could have worked in an older version, but I haven't tested it yet

**Comment by RocketRobz** [comment]
See if commit 7b4df20 fixes it.

**Comment by SleepyLark** [comment]
Yep it did, thanks :)
