### ISSUE TITLE
Nine Hours, Nine Persons, Nine Doors: permanent white screen

### ISSUE THREAD

**Issue by vyatu** [ahezard/nds-bootstrap#807]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.27.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Nine Hours, Nine Persons, Nine Doors

### Expected behaviour

After starting the game from the TWiLightMenu the following happens:
- a game save is created
- nds-bootstrap logo shows up
- the screen turns black, then back to white, then nothing else happens, ever

### Actual behaviour

The game should boot up normally

### Steps to reproduce

1. Start the game from TWiLightMenu
2. Wait for the nds-bootstrap logo to vanish
3. White screen for the rest of eternity

### Other notes

I checked an earlier version of nds-bootstrap and it works **perfectly** on _[v0.26.1]_

**Comment by RocketRobz** [comment]
Try turning off heap shrink.

**Comment by vyatu** [comment]
Tried that already. I also tried switching to DSi mode, I checked if the ramdump was 32MB, tried deleting fatTable and patchOffsetCache and basically made sure to fiddle with all the settings before I posted. The ROM is fine, it works on v0.26.1 and in OpenEmu, it's definitely a v0.27.0 issue.

**Comment by RocketRobz** [comment]
Hmm, it seems this broke it.
```
* **DSi/3DS SD card:** Load speeds have slightly improved!
-The IPC-Sync IRQ now only handles the reads.
-Games that render 3D on both screens will now have minimal to no swap flickers.
-Certain game crashes have been fixed, such as loading certain save files in Pokemon HGSS.
```
So the issue seems to be related to card read DMA.

**Comment by RocketRobz** [comment]
What SDK version is the game?

**Comment by SleepyLark** [comment]
It's SDK 4.  It's working fine on my DSi though you need to turn heap shrink off or else it whitescreens.  I'll test it on my 3DS when I get the chance

**Comment by RocketRobz** [comment]
That's good, because I'm sure nothing in v0.27.0 would've broke it.

**Comment by RocketRobz** [comment]
Plus, TWLMenu++ v11.0.0 should automatically turn off heap shrink, with `Auto` set.

**Comment by SleepyLark** [comment]
It's working fine on my 3DS.  Also setting heap shrink to `Auto` isn't working, it only boots if heap shrink is explicitly turned `Off`

**Comment by RocketRobz** [comment]
What TID is the ROM?

**Comment by vyatu** [comment]
I disabled heap shrinking by holding L, as per some forum post, didn't think of changing the settings themselves. Still a bug if it doesn't work without explicitly setting it to Off though. Also, the TID is 5356.

**Comment by SleepyLark** [comment]
The TID is BSKE

**Comment by vyatu** [comment]
Oh, I thought the TID meant title ID, sorry about the confusion, kinda new to the 3DS homebrew

**Comment by SleepyLark** [comment]
@vyatu also holding L doesn't work anymore (afaik) instead you Y on the game to open up the in-game settings and turn heap shrink to off
