### ISSUE TITLE
Pokemon HeartGold/SoulSilver White Screen after claiming Mystery Gift

### ISSUE THREAD

**Issue by DarthVitrial** [ahezard/nds-bootstrap#809]
Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X ]  New 3DS/2DS (XL) (Firmware 11.12.0-44)

### CFW and configuration

3DS/2DS:

- [X]  Luma3DS (Nightly build dfd50d9)

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ X]  Nightly _63e49ed

### Your device

Tell us which card you are using:

-  [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?
Pokemon HeartGold (Pokemon Sacred Gold romhack)

### Expected behaviour

I should be returned to the Mystery Gift menu (or the title screen?) after downloading a mystery gift over Nintendo WFC (set your dns to 164.132.44.106 to download the gifts)
### Actual behaviour

White screen that requires the game to be force-quit.

### Steps to reproduce

1. Use the games wifi settings to connect to a network, then change the primary dns to 164.132.44.106
2. Play through the game until you get a pokedex
3. return to the title screen, go to the mystery gift menu, download a gift over nintendo WFC.

### Other notes
I'm using the latest version of the Sacred Gold romhack, but IIRC that mod doesn't change anything involving mystery gifts.

**Comment by RocketRobz** [comment]
It's due to soft-reset not being implemented.

**Comment by DarthVitrial** [comment]
Oh, ok.

**Comment by NightYoshi370** [comment]
Lets keep everything soft-reset related in one issue; #259 
Closing
