### ISSUE TITLE
Pokémon Platinum runs too fast

### ISSUE THREAD

**Issue by Someguy1519** [ahezard/nds-bootstrap#810]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.27.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokémon Platinum

### Expected behaviour

Game and audio run at normal speed

### Actual behaviour

Audio is at normal speed but the game itself runs too fast

### Steps to reproduce

1.Launch Pokémon Platinum
2. Let the Intro play
3. Move around in the game

### Other notes
I tried it on my O3DS XL (Same TwilightMenu++ and nds-bootstrap version) and both the game itself and the audio run normally. Seems to be an N3DS specific issue

**Comment by RocketRobz** [comment]
Delete the .ips files with the game's TID, at `sd:/_nds/TWiLightMenu/apfix/`.
They are no longer included in the latest TWLMenu++ version.
