### ISSUE TITLE
Anpanman to Touch de Waku Waku Training Not Loading

### ISSUE THREAD

**Issue by dzeroxdzerox** [ahezard/nds-bootstrap#811]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ x]  Unlaunch+HiyaCFW _[HiyaCFW 3.5]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[v0.26.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Anpanman to Touch de Waku Waku Training (Japan) [b]

### Expected behaviour

Game should load normally.

### Actual behaviour

Game does not load. A white screen appears and doesn't progress. 

### Steps to reproduce

1. Select game in menu. (after this it saves and loads the boot strap screen...after that it's a blank white screen)
2. 
3.

**Comment by SleepyLark** [comment]
Try turning heap shrink off

**Comment by dzeroxdzerox** [comment]
I tried SleepyLark but it did not work. Pressing and holding the L button right after I select the game, correct?

**Comment by SleepyLark** [comment]
Yeah that would be what you would do, have you tried setting the clock speed to NTR?
Also I noticed that you're using version 0.26.0, you may want to update that.  The latest version is 0.27.1 with TWiLight Menu v11.1.0.  The latest version of TWiLight Menu has an option to manually turn heap shrink off in the per-game settings instead of having to hold 'L'.

**Comment by dzeroxdzerox** [comment]
I tried the clock speed now and unfortunately didn't work. Okay! I'll update it and give it a go. Thank you for helping me with this. My son loves Anpanman...

**Comment by dzeroxdzerox** [comment]
I updated to v0.27.1 and still no luck. It flickers to a black screen for a split second and turns all white.

**Comment by RocketRobz** [comment]
Fixed by 437de6a2
