### ISSUE TITLE
GBC games will not run 

### ISSUE THREAD

**Issue by Schrodingersbird** [ahezard/nds-bootstrap#812]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [X]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [X]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

GBC games

### Expected behaviour

Game should run

### Actual behaviour

Displays "Start failed. Error 1"

### Steps to reproduce

1. Attempt to run GBC game
2. Get error

### Other notes

I turned off update recently played & I didn't have this problem before.
Couldn't find an issue with a solution which applied to me, if you think there is one just link it.

**Comment by RocketRobz** [comment]
Re-install the latest TWLMenu++ version.
Also, this is not an nds-bootstrap issue.
