### ISSUE TITLE
power pro kun pocket 13 and 14 dont load

### ISSUE THREAD

**Issue by Rafab89** [ahezard/nds-bootstrap#813]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ x]  Release _[0.27.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

power pro kun pocket 13 and 14

### Expected behaviour

game should load normaly

### Actual behaviour

there is a white screen that says nds-bootstrap in black and a message thet says "an error has ocurred" in red below

### Steps to reproduce

1. select the game
2. load the game
3. said screen appears

### Other notes

english is not my main language, sorry if I made a mistake

**Comment by RocketRobz** [comment]
Is it a DSiWare game?

**Comment by Rafab89** [comment]
no, they aren't
http://www.ds-scene.net/?s=viewtopic&nid=10215
http://www.ds-scene.net/?s=viewtopic&nid=11451
