### ISSUE TITLE
CYFP Secret Files 2 - Puritas Cordis - freezes

### ISSUE THREAD

**Issue by eku** [ahezard/nds-bootstrap#814]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [x]  Nightly _[always latest]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

CYFP Secret Files 2 - Puritas Cordis 

### Expected behaviour

The game can be played till the end.

### Actual behaviour

The Game does not react on any input. Background music plays fine.

### Steps to reproduce

1. Get the game and load the provided savegame [savegame.zip](https://github.com/ahezard/nds-bootstrap/files/3887285/savegame.zip)
2. Throw the soup on shelter
3. At the control panel press the purple button and deactivate the alarm system. 

After that none of the other two buttons can be pressed and also START and SELECT do not react any longer. The touchpad is also dead.

### Other notes

Game settings: NDS mode, NTR speed, VRAM boost off,  Heap shrink off

Any other setting produces graphic issues, i.e. flipped playmate.

**Comment by RocketRobz** [comment]
I did the steps, but the controls still work for me.

**Comment by eku** [comment]
@RocketRobz did you start the game a second time?
