### ISSUE TITLE
Download play don't work

### ISSUE THREAD

**Issue by MisterGooigi2** [ahezard/nds-bootstrap#815]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.) (Memory pit)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[78f32385]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

All Games

### Expected behaviour

The Nintendo logo is block on download play app 

### Actual behaviour

Cannot play to Mario Party DS

### Steps to reproduce

1. Download play app
2. Download success
3. Nintendo logo is locked

### Other notes
N3DS OS : Sys11.12-44E
DSi OS : 1.4.5E

**Comment by MisterGooigi2** [comment]
> ### Your console
> Tell us which console you are using:
> 
> * [ ]   DS Phat/Lite
> * [x]   DSi (XL)
> * [ ]   Old 3DS/2DS (XL)
> * [x]   New 3DS/2DS (XL)
> 
> ### CFW and configuration
> Tell us which CFW do you have:
> 
> DSi:
> 
> * [x]   (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.) (Memory pit)
> * [ ]   (No CFW) Unlaunch only _[please specify version]_
> * [ ]   Unlaunch+HiyaCFW _[please specify versions of both]_
> 
> 3DS/2DS:
> 
> * [x]   Luma3DS
> * [ ]   Rei-Six
> * [ ]   Other/Older CFW [specify]
> 
> ### nds-bootstrap version
> Tell us which versions you are using:
> 
> * [x]   Release _[please specify version]_
> * [ ]   Nightly _[insert here commit hash]_
> 
> ### Your device
> Tell us which card you are using:
> 
> * [x]   SD Card
> * [ ]   (Slot-1) Flashcard
> 
> ### If this issue only affects a certain game, which game is it?
> All Games
> 
> ### Expected behaviour
> The Nintendo logo is block on download play app
> 
> ### Actual behaviour
> Cannot play to Mario Party DS
> 
> ### Steps to reproduce
> 1. Download play app
> 2. Download success
> 3. Nintendo logo is locked
> 
> ### Other notes
> N3DS OS : Sys11.12-44E
> DSi OS : 1.4.5E

**Comment by SleepyLark** [comment]
Already a known issue, refer to #553 and #515
