### ISSUE TITLE
GBARunner2 "NDS-Bootstrap (Release) not found" error after updating

### ISSUE THREAD

**Issue by MarioMover** [ahezard/nds-bootstrap#816]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _[1.9]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.27.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

GBARunner2

### Expected behaviour

GBARunner2 should boot

### Actual behaviour

White screen / NDS-Bootstrap (Release) not found

### Steps to reproduce

1. Open TwilightMenu++
2. Tap the GBARunner 2 icon
3. "Error 1: NDS-Bootstrap (Release) not found."

OR

1. Turn on the system, and on the quick menu, tap the option for GBARunner2
2. White screen error

### Other notes

This happens on both Release and Nightly. Nintendo DS games work just fine, so the Bootstrap is there and it works, but it definitely doesn't work on GBARunner2 for some reason.

**Comment by RocketRobz** [comment]
The hb nds-bootstrap build is missing.
Please update to the latest version.

**Comment by MarioMover** [comment]
Yep, that fixed it...how I missed that, I have no idea. Thanks!
