### ISSUE TITLE
Latest release broke Pokemon Silver Yellow support

### ISSUE THREAD

**Issue by Multimegamander** [ahezard/nds-bootstrap#817]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X ]  Unlaunch+HiyaCFW _[Latest of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X ]  Release _[Latest Release]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon Silver Yellow

### Expected behavior

Should boot up

### Actual behavior

Black screen when save is loaded

### Steps to reproduce

1. i dont think this needs steps for how to start pokemon
2.
3.

### Other notes
Worked in the last release

**Comment by RocketRobz** [comment]
Try launching with heap shrink turned off.
