### ISSUE TITLE
Bowser's Inside Story Softlock

### ISSUE THREAD

**Issue by jimbo4273** [ahezard/nds-bootstrap#818]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ X]  Release _[0.28.0]
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mario & Luigi: Bowser's Inside Story (or any game with mic usage)

### Expected behaviour

The Giga Bowser fight works perfectly fine, with mic support working.

### Actual behaviour

During the first Giga Bowser fight (against Bowser Castle), the Castle sends out groups of Spinys, impeding Bowser's ability to punch. To do further damage in the fight, the mic is needed to blast fire. Upon choosing the 'Fire Breath' option, the game softlocks due to the inability to get out of the fight without rebooting.

### Steps to reproduce

1. Advance through the story until the first Giga Bowser fight.
2. Attempt to breathe fire.
3. Fail miserably...

### Other notes

There is a Mic Test option on the Title Screen. Should make testing things a bit easier.

**Comment by eku** [comment]
See #259

**Comment by FlameKat53** [comment]
Does this still occur? my mic test works and i can't progress to the final boss (i'm stuck at that worm boss in bowser's stomach)...

**Comment by jimbo4273** [comment]
Yeah, it still does...

**Comment by Kaisaan** [comment]
The Microphone seems to be detected properly with the ingame Mic Test option, as tested on my N2DS XL on the latest version of nds-bootstrap (version 0.32.0). If this issue only occurs during the Giant Bowser fights, can you upload your savefile to make testing easier?

**Comment by jimbo4273** [comment]
It works now, just hadn't updated in awhile, sorry if I wasted time...
