### ISSUE TITLE
Gyakuten Kenji 2 softlock at the end of Case 2

### ISSUE THREAD

**Issue by redhotskull** [ahezard/nds-bootstrap#819]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.28.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Gyakuten Kenji 2

### Expected behaviour

This video https://youtu.be/TkNfX7qCt_Q?t=1760

### Actual behaviour

When Simon hands you the Berry Big Circus poster, the upper screen goes black and nothing is responsive, including the Organizer which can be checked at any time

### Steps to reproduce

1. Apply the final translation patch, plus the AP 1-5 beta patch 
2. Load it and play up until the end of case 2, when you are prompted to present the Chessboard to Simon
3. Wait for Simon to hand you the Berry Big Circus poster, but the game freezes instead

### Other notes

This issue is what happened with [https://github.com/ahezard/nds-bootstrap/issues/611](url) this person too, but I haven't found any sort of link to the AP patch that will fix this problem. So if a link for it could be provided, I would very much appreciate that.

**Comment by RocketRobz** [comment]
You should try with just the translation patch.
TWiLight Menu++ includes an AP patch that's automatically applied by nds-bootstrap.

**Comment by redhotskull** [comment]
> You should try with just the translation patch.
> TWiLight Menu++ includes an AP patch that's automatically applied by nds-bootstrap.

I tried this, and it works great! Thank you so much for your help. This issue can be closed now.
