### ISSUE TITLE
Not load the game

### ISSUE THREAD

**Issue by NoirBlaze** [ahezard/nds-bootstrap#821]
Console:
Old 3DS/2DS (XL)

CFW:
Luma3DS

Version:
Release v0.28.0

SD Card

Game:
Assasins creed II discovery

what should happen:
When selecting the Assassins Creed game, the game normally passes the loading screen where it says NDS-BOOTSTRAP

what happens instead:
when selecting the game in the Acekard menu, when loading the game in the upper screen it tells me below NDS-BOOTSTRAP: An error has occurred.

Steps:
-Iniciar TwiligthMenu++
-Seleccionar el juego Assasins creed II discovery

**Comment by RocketRobz** [comment]
You're missing one step before launching the game: Set DSi mode.
Also, it seems you selected the wrong console when launching TWLMenu++ for the first time.
Delete `settings.ini` at `sd:/_nds/TWiLightMenu/`, launch TWLMenu++, then select the O3DS.

**Comment by NoirBlaze** [comment]
still nothing ... still going the same
I also tried the mode (forced)

**Comment by NoirBlaze** [comment]
wait I realized that I have is actually the version of nds-bootstrap in v0.27.1

I will notify you later if it is fixed after updating it

**Comment by RocketRobz** [comment]
Okay.

Also, when I said to set DSi mode, I mean that step is needed reproduce that issue.

**Comment by NoirBlaze** [comment]
I already updated it, but the problem remains unresolved

**Comment by NoirBlaze** [comment]
I even deleted the settings.ini file several times to see if selecting another console the game would work, but not.
You are currently selected in Old 3ds

**Comment by SleepyLark** [comment]
Have you tried running the game in "DS Mode" with the clock speed set to NTR?

**Comment by NoirBlaze** [comment]
I've already tried

**Comment by RocketRobz** [comment]
If you can run other games, then the ROM might be a bad dump.

**Comment by NoirBlaze** [comment]
Ok, I'll see if I download the rom on another page ...
I will download both USA and EUR.

**Comment by NoirBlaze** [comment]
Ready! You were right, it was the ROM.
Thanks! (>w<)b
