### ISSUE TITLE
Advance Wars Dual Strike doesn't load

### ISSUE THREAD

**Issue by Gogobr8** [ahezard/nds-bootstrap#824]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release v0.28.0
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Advance Wars: Dual Strike

### Expected behaviour

Should load

### Actual behaviour

Gets stuck in a white screen

### Steps to reproduce

1. Tap advance wars dual strike in the menu
2.
3.

### Other notes

The first time I tried opening it it said something about RAM, showed the nds bootstrap logo, then got stuck on this white screen. Now it just goes straight to the white screen. Sometimes something about "now saving" shows before the white screen, but very briefly. Worked fine on previous versions.

[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/3941323/NDSBTSRP.LOG)

**Comment by SleepyLark** [comment]
before launching the game, press 'Y' to open up the per-game settings.  Scroll down and turn "Heap Shrink" to "Off" and then try launching it again

**Comment by Gogobr8** [comment]
> before launching the game, press 'Y' to open up the per-game settings. Scroll down and turn "Heap Shrink" to "Off" and then try launching it again

That worked. Thank you very much!
