### ISSUE TITLE
Megaman Star Force 3 Undub doesn't boot

### ISSUE THREAD

**Issue by mentholnos** [ahezard/nds-bootstrap#825]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _v2.0_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _v0.27.1_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Megaman Star Force 3 Red Joker - Undub Patch

### Expected behaviour

The game boots up.

### Actual behaviour

The game doesn't boot, black screen instead

### Steps to reproduce

1. Open an undubbed Megaman Star Force 3 Red Joker rom
2.
3.

**Comment by RocketRobz** [comment]
Try turning off heap shrink.

**Comment by mentholnos** [comment]
Turning off heap shrink doesn't work either.

**Comment by Stack3r** [comment]
I have both of my versions undubbed and they boot and play without any issues, closing
