### ISSUE TITLE
Animal Crossing - Wild World

### ISSUE THREAD

**Issue by ProgrammingHider** [ahezard/nds-bootstrap#828]
Tell us which console you are using:

- [x]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[0.27.0]_
- [x]  Nightly _[8309929f]_

### Your device

Tell us which card you are using:

- [ ]  SD Card
- [x]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Welcome to Animal Crossing - Wild World

### Expected behaviour

Launch Animal Crossing
See Debug text
Play the game

### Actual behaviour

Launch Animal Crossing
See Debug text
First White Screen that black screen
Then it's frozen

### Steps to reproduce

1. Use an R4i Gold 2019 with TWiLightMenu++
2. Start Animal Crossing Rom
3. Be Black Screened

### Other notes

This Only affects Animal Crossing. Games like New Super Mario Bros and Mario Kart DS work no problem

**Comment by RocketRobz** [comment]
Some games aren't compatible with B4DS. This game is one of them.
