### ISSUE TITLE
"An Error has accurred." with any DSiWare .nds rom.

### ISSUE THREAD

**Issue by danylopez123** [ahezard/nds-bootstrap#829]
Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.28.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Any DSiWare game

### Expected behaviour

Game should launch like a normal DSiWare game

### Actual behaviour

When the NDS-BOOTSTRAP logo apears, freezes with "An error has occurred."

### Steps to reproduce

1. Have any DSiWare game in the TwilightMenu++.
2. Launch it.
3. "An error has ocured."

### Other notes

I tested this with like 3 DSiWare games and they are doing the same thing.

**Comment by RocketRobz** [comment]
DSiWare doesn't work yet.

**Comment by danylopez123** [comment]
Oh, dam... then i guess i will have to wait

**Comment by Barawer** [comment]
You can just install .cia dsiware for now.
