### ISSUE TITLE
Neighbours from Hell doesnt run 3ds CFW Luma

### ISSUE THREAD

**Issue by lnxi4455** [ahezard/nds-bootstrap#830]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ x]  Release _[v0.28.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Neighbours from Hell

### Expected behaviour

Launch Neighbours from Hell
See Debug text
Play the game

### Actual behaviour

Launch Neighbours from Hell
See Debug text
After choosing any stage the black screen appeared instead of loading the stage.

### Steps to reproduce

1.   Use an CFW Luma 3DS with TWiLightMenu++
2.   Start Neighbours from Hell Rom
3.   Choose the mission stage and be stuck on the black screen instead of loading the level what are you choosing to.

### Other notes
Also i tried with Nightly version, and problem still the same.
Game was trying to running with dsi mode and ds mode, vram ON and OFF.

**Comment by RocketRobz** [comment]
You should also mention heap shrink.

**Comment by lnxi4455** [comment]
So, what should i need to do ? 
I don't get it :D

**Comment by RocketRobz** [comment]
Turn off heap shrink?
If you already did that, then wait for a fix.

**Comment by lnxi4455** [comment]
Yep, i tried ON and OFF heap shrink, and problem still the same.
Alright, thanks.

**Comment by FlameKat53** [comment]
Neighbours from hell doesn't work for me either. n3ds, Luma3DS v10.0.1-d(somethingsomething), latest nightly of nds-bootstrap and twilight menu++ (Game is no-intro #3954 SDK4, C58P)
same as you, select a stage and black screen

**Comment by nniikkttoo** [comment]
Same issue on my DSi with the last version of TWLMenu++

**Comment by tomudo** [comment]
same issue -> https://github.com/ahezard/nds-bootstrap/issues/786

**Comment by songokuemumania** [comment]
game working on latest  nds-bootstrap v0.53.0 !! Thanks for the update the game is now playable !!!
