### ISSUE TITLE
Sonic Classic Collection doesnt run

### ISSUE THREAD

**Issue by lnxi4455** [ahezard/nds-bootstrap#832]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[please specify version]_
- [x]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Sonic Classic Collection

### Expected behaviour

Launch Sonic Classic Collection
See Debug text
Play the game

### Actual behaviour

Launch Sonic Classic Collection
See Debug text
See freezing black screen or white screen.

### Steps to reproduce

1. Use an CFW Luma 3DS with TWiLightMenu++
2. Start Sonic Classic Collection
3. See freezing black screen or white screen.

### Other notes
Also i tried with Nightly version, and problem still the same.
Game was trying to running with dsi mode and ds mode, vram ON and OFF too.
Freezing black screen always(sometimes white screen).

**Comment by RocketRobz** [comment]
The game works for me.
I use DS mode with TWL clock speed and VRAM boost off, for that game.

Are you using cheats?
If not, check your SD card for errors.

**Comment by lnxi4455** [comment]
Work now. Thanks.
