### ISSUE TITLE
Error 1: nds-bootstrap (Release) not found

### ISSUE THREAD

**Issue by MephilesSA** [ahezard/nds-bootstrap#833]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _[v2.0]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

It should run the darn roms

### Actual behaviour

Not only does it not run SNES and GBA Games, but it also doesn't even show GEN Games

### Steps to reproduce

1. Open TwilightMenu
2. Try to open an SNES or GBA Game
3. Try not to throw the DSi out of frustration

### Other notes
GBARunner just doesn't open. One of the SNES Emulators shuts down the system and all other emulators don't show the ROMs

**Comment by Jerdo32** [comment]
This error only happens with GBARunner?

**Comment by MephilesSA** [comment]
the one where it doesn't even show the menu, yes. but the rest of the mentioned emulators (SNES and GEN) also don't work

**Comment by NightYoshi370** [comment]
This isn't a nds-bootstrap issue. This is related to TWiLight, but this is more of a support question. Please go to the discord server found in the ReadME and ask your question in #support of that server. We can help you better there.
Closing
