### ISSUE TITLE
Pokémon DPPt - colour palettes in rooms seem off unless making some interactions inside

### ISSUE THREAD

**Issue by ducrids** [ahezard/nds-bootstrap#836]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.28.1]_
- [x]  Nightly _[460c8aa6]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokémon DP - probably, Pokémon Pt - definitely (tested).

### Expected behaviour

Throughout the entire gameplay colour palettes should be preserved, unless game's internal code changes them. 

### Actual behaviour

Colour palettes in rooms seem slightly off (somewhat dull, subdued). When talking to an NPC or interacting with i.e. PC etc., a colour palette in any kind of room seems appropriate, restored to its supposed state. When any of above mentioned interactions ends/is terminated, the colour palette comes back to its original, dull state.

### Steps to reproduce

1. Boot the game with default settings.
2. Go to i.e. Pokémon Centre (I've noticed this issue in Hearthome City - I'd recommend going there).
3. Interact with NPCs.

**Comment by RocketRobz** [comment]
Does this still happen in v0.30.0?

**Comment by Kalanyr** [comment]
This does not seem to happen for me using e2ffcadd and a CPUE cart dump. The palette seems consistent when transferring indoors and talking to NPCs does not seem to cause it to brighten.
