### ISSUE TITLE
crashes when opening rom selection

### ISSUE THREAD

**Issue by TMO-JBAR** [ahezard/nds-bootstrap#837]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ *]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [* ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ *]  Release _[v0.28.1]_
- [x]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [* ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

shows my roms

### Actual behaviour

video https://youtu.be/CuzsWK77Lno

### Steps to reproduce

1. turn on twilight menu
2. click to open roms
3.

**Comment by RocketRobz** [comment]
Even though this isn't an nds-bootstrap issue, your ROMs seem to be corrupted.
Try replacing them.

**Comment by TMO-JBAR** [comment]
moved my roms to my pc deleted the ones on the 3ds and put the PC ones back and it worked

**Comment by TMO-JBAR** [comment]
thx
