### ISSUE TITLE
NDS Bootstrap an error has occured Pokemon Black

### ISSUE THREAD

**Issue by helpme1234679** [ahezard/nds-bootstrap#839]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [×]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [×]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [×]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [×]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon Black

### Expected behaviour

Run the game

### Actual behaviour

When launched it says nds bootstrap an error has occured

### Steps to reproduce

1.Launch the gane

### Other notes
It works on other games like Mario Kart but not in Pokemon Black. I am already using DS mode

**Comment by RocketRobz** [comment]
While DS mode may be set, check if the game runs in DS mode, in the per-game settings.

**Comment by anderBRA84** [comment]
@RocketRobz you are the one

**Comment by RocketRobz** [comment]
> @RocketRobz you are the one

If there's a specific issue you're having, please open a new one in this repo, or join our Discord server here: https://discord.gg/yD3spjv
