### ISSUE TITLE
Unable to run DSi-exclusive titles

### ISSUE THREAD

**Issue by EnekoT2001** [ahezard/nds-bootstrap#840]
Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X ]  Unlaunch+HiyaCFW _[please specify versions of both]_2.0 and 1.3.2

Tell us which versions you are using:

- [ X]  Release _[please specify version]_0.28.1
- [ ]  Nightly _[insert here commit hash]_

Tell us which card you are using:

- [X ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

All DSi exclusive games

### Expected behaviour

Open the game and play it

### Actual behaviour

Black screens after "init FAT filesystem" message (the 1st time)
black top screen and white bottom screen (after trying for the 1st time)

### Steps to reproduce

1. Put a DSi exclusive (no a dsi-enhanced) game onto the sd card
2. Open it (in my case with twilightmenu++)
3. Wait infinitely

### Other notes

I tried to change the settings to DS/DSi mode, DSi mode (forced) and stuff but I'm not able to start any dsi exclusive games, I know there are a very few but I couldn't find anything about the compatibility of dsi-exclusives with nds-bootstrap online so here I am

**Comment by FlameKat53** [comment]
this is a clone of #300 and #639, also DSi Mode (Forced) is broken (always results in "An Error has Occured.").
