### ISSUE TITLE
Tetris DS (Korea) shows red "An Error has Occurred" message on launch

### ISSUE THREAD

**Issue by Epicpkmn11** [ahezard/nds-bootstrap#841]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _v2.0_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _v0.28.1_
- [x]  Nightly _66a9bbd8_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

[Tetris DS](http://nintendo.co.kr/DS/soft/TetrisDS/TetrisDS_main.php)

### Expected behaviour

The game launches

### Actual behaviour

nds-bootstrap shows the "An Error has Occurred" in ted text message

### Steps to reproduce

1. Open Tetris DS (Korea) from TWiLight Menu++
2. It dies

### Other notes

I've tried on a Korean, American, and Japanese DSi, and the USA, EUR, and JPN versions of the game run fine, all were clean dumps, without cheats on, and with all the TWiLight AP patches downloaded. I've tried with heap shrink on and off.

**Comment by RocketRobz** [comment]
Delete the patchOffsetCache file for the ROM, turn on logging, and when the error shows up again, please upload the log file from the SD root.

**Comment by Epicpkmn11** [comment]
Here's the log: [NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4049043/NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
```
findCardReadEndOffsetType1:
ARM9 Card read end alt (type 1) found: 0200F900

findCardReadStartOffsetThumb:
ARM9 Card read start thumb not found
ARM9 Card read start thumb alt not found

findCardReadStartOffsetType1:
ARM9 Card read start alt (type 1) not found
```
Card read not found.
Welp, another ROM to add support. :P
