### ISSUE TITLE
Widescreen not working with cheats for some games

### ISSUE THREAD

**Issue by CatsLover2006** [ahezard/nds-bootstrap#842]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.28.1]_
- [x]  Nightly _[80366bd7]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Mario Kart DS Demo loads in widescreen with beta tracks

### Actual behaviour

Widescreen doesn’t happen; beta tracks do. 

### Steps to reproduce

1. Enable widescreen in TWLMenu++
2. Enable a cheat
3. Profit

### Other notes

I made this issue on TWLMenu++ and they said it was a nds-bootstrap issue. Don’t say it is an issue with TWLMenu++

**Comment by CatsLover2006** [comment]
**Note:** Attempted with both Release and Nightly

**Comment by JonArcherII** [comment]
Does it work without cheats? Is _Mario Kart DS **Demo**_ a supported widescreen game?

**Comment by RocketRobz** [comment]
@JonArcherII If you're referring to the DLP Demo, then no.

**Comment by CatsLover2006** [comment]
It happens with all games. MKDS (with rom hacks, but that’s unimportant. It happens with 2) also has this issue. Maybe there could be some more RAM allocated for cheats on DSis?

**Comment by RocketRobz** [comment]
There's already RAM allocated for cheats.
The widescreen cheat is placed there as well.

**Comment by CatsLover2006** [comment]
But **how** much is it? Could it be expanded-at all?

**Comment by RocketRobz** [comment]
32kb is allocated, which means lots of cheats can be used.

**Comment by RocketRobz** [comment]
Issue seems to be fixed.
