### ISSUE TITLE
White screen in games

### ISSUE THREAD

**Issue by Lement22** [ahezard/nds-bootstrap#844]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.28.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokémon Black Edition 2

### Expected behaviour

When changing the keys in the rooms or entering any option in the main menu.

### Actual behaviour

When you return to the main menu, the game freezes.

### Steps to reproduce

1. Enter any option in the main menu.
2. Return to the main menu.

**Comment by RocketRobz** [comment]
1. What TWLMenu++ version are you using?
2. Is this a ROM hack?

**Comment by Lement22** [comment]
Twin light menu version 11.2.0.

The game is the original version.

**Comment by RocketRobz** [comment]
Even so, is the ROM modified in any way, like repacking?

**Comment by Lement22** [comment]
I am not sure if the rom has been modified, I will try to get a clean rom and try to play.

**Comment by Lement22** [comment]
Rocket Robz i got the clean version without the Exp Fix and when changing the room keys in the teselia nexus, it went blank when I returned to the main menu.

**Comment by RocketRobz** [comment]
Is there an `apfix` folder in `sd:/_nds/TWiLightMenu/`?
If so, after battling Pokemon, does your Pokemon gain EXP?

**Comment by Lement22** [comment]
There is an ApFix folder with several ips files in the path you mention.

I played a couple of battles with wild Pokémon and my pokemon gained experience, but the white screen problem remains in the main menu.

**Comment by RocketRobz** [comment]
Maybe your save data is bugged?

**Comment by Lement22** [comment]
I started a new game, removing my sav file and the problem remains. My saved game is not bad.

**Comment by RocketRobz** [comment]
Try checking your SD card for errors.

**Comment by Lement22** [comment]
I will try to analyze my SD card to see if there are errors.

**Comment by Lement22** [comment]
Scan the sd card if you had errors with Windows 10, there are no errors.

**Comment by RocketRobz** [comment]
Try another SD card then.
