### ISSUE TITLE
Mario & Luigi RPG3 white screen

### ISSUE THREAD

**Issue by pakodx** [ahezard/nds-bootstrap#845]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ x]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mario and Luigi,
Bowser inside story (JP)

### Expected behaviour

Work

### Actual behaviour

White screen after alpha dreams/Nintendo logo, at boot ndsbootstrap does not appear or apply AP

### Steps to reproduce

1. Add rom
2. Try to boot it
3. White screen

### Other notes

Please add to the nds bootstrap the Pokemon black and white 1 and 2 fan translations too.

**Comment by RocketRobz** [comment]
Make sure you're using latest TWiLight Menu++.

The AP issue is when you can't select save data in the menu.
Sounds more like the ROM is corrupt.

**Comment by pakodx** [comment]
I am using the latest twlmenu and nds bootstrap. I'll try to download the rom from another place and post the results

**Comment by pakodx** [comment]
was using a redump and just tried the xenophobia release, the ndsbootstrap was loaded before the game but it still has the same issue. i think its the AP preventing the game from getting to the title screen.

**Comment by eku** [comment]
@pakodx I had to disable ```VRAM boost``` and ```Heap shrink```.

**Comment by pakodx** [comment]
I'm going to give it a shot later, but it's weird because the US version works normally

**Comment by eku** [comment]
Since a recent update of both ```nds-bootstrap``` and ```TW++M``` from the nightly builds  I have the same problem with the PAL version of the game.
