### ISSUE TITLE
Pokemon Black 2 has duplicated lines

### ISSUE THREAD

**Issue by arromdee** [ahezard/nds-bootstrap#846]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ X]  Release _[0.28.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon Black 2

### Expected behaviour

No duplicated lines

### Actual behaviour

Duplicated lines

### Steps to reproduce

1. Run Pokemon Black 2
2. Look at the bottom of the screen.  This happens on both the top and bottom screen.
3. Several lines at the bottom of the screen are repeated.  This is visible on all the screens that don't just have a solid black there.

### Other notes

I tried a different game and this did not happen; also, I don't believe the problem existed in earlier versions of nds-bootstrap.

**Comment by RocketRobz** [comment]
This bug happens randomly, in any game, and any nds-bootstrap version.
It's a TWL_FIRM bug.
