### ISSUE TITLE
Infinite Space : top screen not used and game wont run past intro video

### ISSUE THREAD

**Issue by blasev** [ahezard/nds-bootstrap#848]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ x]  Unlaunch+HiyaCFW _[2.0+latest Hiya]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ x]  Release _[please specify version]_
- [ x]  Nightly _[insert here commit hash]_

I have tried both

### Your device

Tell us which card you are using:

- [ x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Infinite Space USA and EUR version

### Expected behaviour

The game would run as usual , using top screen for the intro and gameplay, bottom screen for action menu

### Actual behaviour

The game only run on bottom screen, the top screen showing only blank white. the bottom action screen is missing and also the game cant be started after game intro

### Steps to reproduce

1. Play using infinite space (usa / eur)
2. The white screen on top will show directly
3. After the intro on the bottom screen you cant play the game

**Comment by RocketRobz** [comment]
Try turning off heap shrink.

**Comment by blasev** [comment]
thanks or the amazingly quick response. I have tried holding L after starting the game, the result is still the same.

**Comment by RocketRobz** [comment]
I didn't say to hold L.
I said to turn off heap shrink. It's a per-game setting.

**Comment by blasev** [comment]
ok I am at lost here, been searching google with no result. how can I turn off heap shrink per game setting?

**Comment by RocketRobz** [comment]
In TWLMenu++'s ROM menu, press Y, then find `Heap shrink`.

**Comment by blasev** [comment]
ah thanks again, but the game still wont run. the intro video jumping from top to bottom to top and lastly bottom screen again. the good news is that it can past intro but will be met with white screen on both screen after that.

**Comment by RocketRobz** [comment]
What version of nds-bootstrap are you using, exactly?

**Comment by blasev** [comment]
I use twilight 11.20, with nds-bootstrap 0.28.1 and also tried nightly ver 80366bd7

**Comment by RocketRobz** [comment]
Please update the nightly. I'm not getting this issue on my end.

**Comment by blasev** [comment]
i am noob, please sow me the step to do that, or maybe a site with the steps

**Comment by RocketRobz** [comment]
Ah, you're on a DSi.
Download [this](https://github.com/TWLBot/Builds/commit/a713c795e95b55060bc5c3af392317e7b835aead), and put the .nds files in `sd:/_nds/`.

**Comment by blasev** [comment]
yes I am using dsi, I tried the nightly 99c41aa2 and also I tried c3a09a3f.
both still making the same result as before , the game wont run

**Comment by RocketRobz** [comment]
What are your settings?

**Comment by blasev** [comment]
your question makes me tried alot, and it really help
run in : dsi mode - 133mhz (not working) ds mode - 67mhz (working!)
vram boost : on or off (working on both!) 
heap shrink : on or of (working on both!)
bootstrap : nightly 99c41aa2

thanks again , you are very helpfful

**Comment by Squall-Leonhart** [comment]
this game is weirdly sensitive to the clockrate of the cpu, even in an emulator that supports overclocking this issue can occur.

@RocketRobz is there not a blacklist for TWL clocks?.

**Comment by RocketRobz** [comment]
> @RocketRobz is there not a blacklist for TWL clocks?.

I think it's been requested from time to time, so I'll consider it.
