### ISSUE TITLE
Updater crashes 3DS 

### ISSUE THREAD

**Issue by Gimzie** [ahezard/nds-bootstrap#85]
Attempting to update anything crashes the 3DS.

(N3DS 11.4 USA Luma CFW 8.0)

**Comment by Margen67** [comment]
Are you sure you posted this in the right repo?

**Comment by Robz8** [comment]
The update issue is from TWLoader.

**Comment by Gimzie** [comment]
Oh, I'm really sorry about that! > . > (I must have been half asleep or something)

Yeah, this is a TWLoader bug, not an nds-bootstrap bug.

**Comment by weirdal3333** [comment]
@Gimzie please don't forget to close this issue!

**Comment by Gimzie** [comment]
Oops, I will!
