### ISSUE TITLE
Can't boot games when using a forwarder

### ISSUE THREAD

**Issue by Stealphie** [ahezard/nds-bootstrap#850]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.28.1]_ v0.28.1
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen
Game boots normally
### Actual behaviour
Gets stuck in a Black screen or bottom screens becomes white and gets stuck
Tell us what happens instead
Can't even boot the game
### Steps to reproduce

1. Not using TwiightMenu++
2. Triying to make a forwarder with Forwarder-3DS
3. Installing it
4. Running it
5. Done.

### Other notes
Games boot just fine when using TwilightMenu++.

**Comment by RocketRobz** [comment]
Not an nds-bootstrap issue.
