### ISSUE TITLE
Pokemon Soulsilver problem

### ISSUE THREAD

**Issue by irod14** [ahezard/nds-bootstrap#852]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _[11.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon SoulSilver

### Expected behaviour

If i reset the console when i saved, the game should start normally.

### Actual behaviour
the game starts but i can't load the saved game because of a "Communication error".

### Steps to reproduce

1.Save my game
2.reset console
3. start the game and skip intro

### Other notes
When I open the game there is l  a dialog box saying:

"A communication error has ocurred.
You will be returned to the title screen.
Please press the A button" Also my 3ds wifi card is broken
but I believe I dont need such thing to open my save file.

**Comment by irod14** [comment]
The problem magically disappeared,I just did'nt use twilight menu for a month and it got fixed.Shame on the supporters my issue was a hundred percent ignored,and got fixed because I was lucky that it worked without needing support.

**Comment by RocketRobz** [comment]
I haven't noticed this being open. We can't keep track of every open issue.
Also, the game checks for working WiFi, when loading existing save data.

**Comment by MrJPGames** [comment]
> The problem magically disappeared,I just did'nt use twilight menu for a month and it got fixed.Shame on the supporters my issue was a hundred percent ignored,and got fixed because I was lucky that it worked without needing support.

Why are you so rude? The "supporters" also known as maintaners of this project do this for the love of it. This isn't their job. They've created an amazing tool for every DS/DSi and 3DS owner. Be thankful for what you have, and be patient, they care and will get to it when they get to it, and that is fast enough!
