### ISSUE TITLE
Love Plus screen rotated

### ISSUE THREAD

**Issue by psmis2** [ahezard/nds-bootstrap#857]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.28.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Love Plus, with ENG Patch 1.0

### Expected behaviour

The game uses each screen separately.

### Actual behaviour

Game boots in some sort of landscape mode.
![p1](https://user-images.githubusercontent.com/32421734/73629031-d3e86080-4649-11ea-9736-c493250ded47.JPG)
![p2](https://user-images.githubusercontent.com/32421734/73629041-db0f6e80-4649-11ea-9a5d-13a2e65f5b72.JPG)

### Steps to reproduce

1. Open game

**Comment by RocketRobz** [comment]
That's normal?
Landscape DS games are a thing. :P

**Comment by psmis2** [comment]
Is it possible to override it? No matter how I rotate it, it just stays in that orientation (unless the gyroscope is broken)

**Comment by RocketRobz** [comment]
The gyroscope is not used in DS/DSi mode.
To override the screen mode, the game itself would have to be hacked.

**Comment by psmis2** [comment]
LOL, now that I googled game "screenshots", indeed it is meant to be played in that mode.
I never imagined landscape games existed. Thanks for clarifying.
