### ISSUE TITLE
Mario & Luigi: Bowser's Inside Story crashes when I try to load a save

### ISSUE THREAD

**Issue by TheFreindlyPlagueDoctor** [ahezard/nds-bootstrap#859]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _[v2.0]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.28.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mario & Luigi: Bowser's Inside Story (USA)

### Expected behaviour

Save should load and I should be able to play the game

### Actual behaviour

Game freezes

### Steps to reproduce

1. Launch game
2. Select save and load save
3. game freezes

### Other notes
-I was able to load from my save before just fine
-My save point was right before the Durmite boss fight about 3 hours in the game
-creating a new save in the second save slot results in the game freezing during the opening cutscene right when toad enters the house
-When game freezes there is a soft constant buzzing sound

**Comment by RocketRobz** [comment]
Try [this](https://github.com/TWLBot/Builds/raw/master/nds-bootstrap.7z) nds-bootstrap nightly build.
Extract the .nds file to `sd:/_nds/`, then switch to `Nightly` in TWLMenu++ Settings.

**Comment by TheFreindlyPlagueDoctor** [comment]
Tried switching it to Nightly with the version you sent. I got the same problem

**Comment by TheFreindlyPlagueDoctor** [comment]
I tried deleting the .sav file(I copied it to somewhere else) from the sd card and was able to play till right after i defeat Bowser (The first fight in the game) but it crashes when Peach is throwing Bowser out of the castle.

**Comment by TheFreindlyPlagueDoctor** [comment]
I deleted everything in the '_nds' file and reinstalled twillight menu and for some reason my original save works now

**Comment by TheFreindlyPlagueDoctor** [comment]
Same thing happened again. I think selecting 'save and quit' breaks it.

**Comment by RocketRobz** [comment]
That's related to soft-reset not working.
