### ISSUE TITLE
Games listed as compatible hang at white screen

### ISSUE THREAD

**Issue by Dysproh** [ahezard/nds-bootstrap#86]
The two games I have tested, Pokemon Black version and Pokemon White version, have both hung at a white screen every time. I have turned on console output. Any idea what might be causing this? If it helps, I am using TWLoader with this.

**Comment by Jolty95** [comment]
@Dysproh Pokemon B&W are not listed as compatible

**Comment by Robz8** [comment]
@Dysproh Yes, if you scroll to the right, you'll see there's more details.

**Comment by Dysproh** [comment]
@Robz8 What do you mean?

**Comment by Robz8** [comment]
In the list, there's a bar on the bottom of the screen, and you can drag it to the left or right.

**Comment by Dysproh** [comment]
@Jolty95 The spreadsheet that is widely referenced as a compatability list for nds-bootstrap says it is.

**Comment by Dysproh** [comment]
@Robz8 Yeah, I am not sure where these details are. I scrolled all the way to the right and just saw... Nothing.

**Comment by Robz8** [comment]
Do you see like green or red colors?

**Comment by Jolty95** [comment]
@Dysproh No, it is not. Spreedsheet say that those games show a white screen (and also are marked in red) (THUMB not implemented.)

**Comment by Margen67** [comment]
The name itself on the Pokemon titles are green for some reason but compatibility is clearly red.

**Comment by Robz8** [comment]
Here's a screenshot of the list.
![compatibility list](https://user-images.githubusercontent.com/16110127/27204138-907b7026-51e6-11e7-8ebf-372cf2fd2515.png)

**Comment by Robz8** [comment]
This can be closed now.

**Comment by Dysproh** [comment]
I seem to be too colorblind to correctly read a list.

**Comment by Dysproh** [comment]
@Robz8 Just 1 thing, if you wouldn't mind explaining, what exactly is THUMBS?

**Comment by Robz8** [comment]
THUMB is a type of opcode, where it's smaller than ARM.

**Comment by Dysproh** [comment]
So you essentually need to intercept THUMB instructions and convert them to ARM instructions? Or is there some THUMB processing thing already in there that you just need to access?

**Comment by Dysproh** [comment]
Or am I just illiterate as to how cpu architecture and stuff works?

**Comment by Gericom** [comment]
Thumb is just a reduced version of the arm instruction set that takes 16 instead of 32 bit per instruction. In return it's less powerful of course. You sometimes need more instructions to reach the same result, but because the instructions are smaller, more of them fit in the cache too. There are 2 versions of the sdk, one using arm and one using thumb and developers can choose whatever fits their needs. Most use the arm version though, since there is not really a reason to use the thumb version.
