### ISSUE TITLE
Mario & Luigi Inside Bowser "An error has occurred"

### ISSUE THREAD

**Issue by Jalkhov** [ahezard/nds-bootstrap#860]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _[1.4]_ (I am not sure what is CFW but the firmware of my console is 1.4)
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.28.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mario & Luigi Inside Bowser

### Expected behaviour

Game should launch

### Actual behaviour

Nds-bootstrap starts only to end up displaying "An error has occurred"

### Steps to reproduce

1. Launch ROM.
2. Show a black screen who says:
Creating RAM dump file.
Please wait...
3. Show white screen with nds-bootstrap logo, say please wait.
4. "An error has occurred" message appear.

**Comment by NightYoshi370** [comment]
Seems like this was a regression which was fixed in 0.28.2
Closing....
