### ISSUE TITLE
Corrupted Save Error on Pokemon Black & White 2

### ISSUE THREAD

**Issue by analyeet** [ahezard/nds-bootstrap#861]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax [ ]  (No CFW) Unlaunch only 
- [x]  Unlaunch+HiyaCFW+TWiLight Menu (Latest releases on all)

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW 

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release (v0.29.0)
- [ ]  Nightly 

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon Black 2 (U), Pokemon White 2 (U)

### Expected behaviour

Should show save file on main menu

### Actual behaviour

Returns error "The save file will be erased due to corruption or damage" after saving and attempting to load the save after a system/soft reset. Save file is not actually corrupted/missing.

### Steps to reproduce

1. Load new game or pre-existing save file
2. Save the game
3. Reset
4. Press A on title screen

### Other notes

- I've tried multiple ROMs 
- Game is running in DS mode, all nds-bootstrap options are default
- Deleting the game's .bin files from root/_nds/nds-bootstrap/fatTable and .../nds-bootstrap/patchOffsetCache fixes the issue temporarily, allowing me to load the save file. Saving and resetting breaks it again
- Replacing the ROM also fixes the issue temporarily

**Comment by Summerslyb** [comment]
Same issue here.
As long as it can trigger fatTable and patchOffsetCache update, it can start normally.
Not only for pokemon BW2, but also for large rom(>=128M in my test).

Version 0.28.1 don't have such problems.
