### ISSUE TITLE
White screen after save file creation on DSi with flashcard.

### ISSUE THREAD

**Issue by pivotiiii** [ahezard/nds-bootstrap#863]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[v0.29.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ ]  SD Card
- [X]  (Slot-1) Flashcard R4i-SDHC 1.4 from r4i-sdhc.com

### Expected behaviour

Selecting a .nds rom file in TWLM++.
Game launches.

### Actual behaviour

After selecting the rom, the bottom screen says that a savefile was created.
After that, the system white screens and can only be turned off.
I have let the white screen on for up to 40mins and tested different roms as well.

### Steps to reproduce

1. Use a R4i-SDHC from r4i-sdhc.com with TWLM++ v12.0 installed.
2. Select any .nds rom to launch.

**Comment by RocketRobz** [comment]
Not all games work with B4DS.

**Comment by pivotiiii** [comment]
I thought I've read somewhere that Mario Kart DS does work. It didn't for me.

**Comment by RocketRobz** [comment]
Games that work on one flashcard, may not work on the other.
The R4 Ultra and R4i Gold RTS are apparently the most stable flashcards to use with B4DS.

**Comment by pivotiiii** [comment]
Oh alright. I haven't found any kind of compability table, is there anything out there?

**Comment by RocketRobz** [comment]
https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit#gid=860616020
