### ISSUE TITLE
Mario & Luigi : Bowser's Inside Story - game freeze

### ISSUE THREAD

**Issue by AndiiBintang** [ahezard/nds-bootstrap#864]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch 1.9 +HiyaCFW 1.3.2

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release nds-bootstrap v0.29.2
- [ ]  Nightly _[insert here commit hash]_

### Your device
[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4238515/NDSBTSRP.LOG)

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Mario & Luigi: Bowser's Inside Story (USA)

### Expected behaviour

Allowed to progress the game after save & load.

### Actual behaviour

After loading save, transitioning map or any interaction with object freeze the game.

### Steps to reproduce

1.Launch game
2.Load recent save file
3.move to next area or interact with any object
4.freeze occur

### Other notes
-creating a new save in the second save slot results in the game freezing during the opening cutscene right after toad enters the house.
-similiar problem that i found https://github.com/ahezard/nds-bootstrap/issues/859.

**Comment by marcocro** [comment]
I have the same problem, dsi xl

**Comment by Kaisaan** [comment]
The game seems to work fine on the latest version of nds-bootstrap (0.32.0) as tested on my DSi XL. If this issue still occurs, can you upload your savefile?

**Comment by marcocro** [comment]
The problem remains on the latest build, maybe it depends on the ROM I'm using? I've tried multiple releases with AP-patches but no luck.
Anyway here is my save file, I had tried deleting it and starting a new game but with different save files the issue remained. 
Thank you for your help!
https://we.tl/t-MePTPLoxDB

**Comment by Kaisaan** [comment]
@marcocro Twilightmenu now automatically does AP-patching with ROMs. Try using a clean, unpatched ROM and see if the issue still occurs.

**Comment by TheFreindlyPlagueDoctor** [comment]
I'm using the latest version of bootstrap with a clean rom and I still get this issue.

**Comment by Kaisaan** [comment]
What system are you on, and what version of CFW are you on?

**Comment by TheFreindlyPlagueDoctor** [comment]
I'm on a dsi xl using unlaunch v2.0 only

**Comment by Kaisaan** [comment]
Try redumping your ROM. Just to make sure, which version of twilightmenu and nds-bootstrap are you on? Also, is there any carts inserted in your DSi XL?

**Comment by TheFreindlyPlagueDoctor** [comment]
I'm using v13.1.0 of twilight menu++ and v0.32.1 of nds-bootstrap. How do I redump my rom? If you mean deleting the fat table and patchOffsetCache I tried that and the problem still occurs.

**Comment by TheFreindlyPlagueDoctor** [comment]
and no. there is no carts in my dsi xl
