### ISSUE TITLE
Luminous Arc - game freeze

### ISSUE THREAD

**Issue by heliogfonseca** [ahezard/nds-bootstrap#865]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[0.29.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Luminous Arc (1)

### Expected behaviour

Game is listed as working on the compatibility chart.

### Actual behaviour

Game freezes (probably when trying to play voiced dialogue) during the game's 2nd introductory cutscene.

### Steps to reproduce

Freeze happens during intro. Game crashes shortly after Chapter 1 starts, about 2min after starting a new game if you're mashing A.

### Other notes

Tried testing different ROMs, including undub version; game freezes at the same spot in all versions.

**Comment by Kalanyr** [comment]
Confirmed that this happens in DS Mode with 133 MHz, VRAM boost, Widescreen, Improved Sound, Heap Shrink Auto.  

Testing in compatibility settings (full DS Mode settings) now

**Comment by RocketRobz** [comment]
Next TWiLight Menu++ will automatically disable heap shrink for Luminous Arc.
https://github.com/DS-Homebrew/TWiLightMenu/commit/2b368fa7a9cbd79b27bbb1e78a10ec2db97e683c
