### ISSUE TITLE
HGSS freeze even with AP patch

### ISSUE THREAD

**Issue by AdeptusCustodes** [ahezard/nds-bootstrap#866]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[HiyaCFW v.1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v0.28.1]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

HGSS.

### Expected behaviour

Game should work fine with AP patch.

### Actual behaviour

Sometimes games freezing, or in start of combat screens became blacks, but music still playing.

### Steps to reproduce

1. Use DS Scene Rom Tool, patching the rom.
2. Play the game long enough.

**Comment by mikruzer** [comment]
my game freeze to today sort after win battle but my game is not AP patch yet using latest nds-bootstrap

**Comment by Kaisaan** [comment]
TWiLightMenu++ automatically AP patches ROMs now, does this still happen with a clean ROM?
