### ISSUE TITLE
Dragon Ball Z Ultimate Butouden (J) and English version (Patched) don't work...

### ISSUE THREAD

**Issue by iL30N4RD0** [ahezard/nds-bootstrap#868]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [X]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[Latest v0.29.2]_
- [X]  Nightly _[Latest 54576a1e]_

### Your device

Tell us which card you are using:

- [X]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

Dragon Ball Z Ultimate Butouden (J) and English version (Patched)
 
### Expected behaviour

Tell us what should happen

Dragon Ball Z Ultimate Butouden (J) and English version (Patched): He tries to charge but in the attempt he doesn't succeed...

### Actual behaviour

Tell us what happens instead

Dragon Ball Z Ultimate Butouden (J) and English version (Patched): When I open it, the game launches the typical Bootstrap screen and then disappears, leaving the DSi with the screen at the top in black and the bottom in white. I tried to change the version of the launcher but it still doesn't open

### Steps to reproduce

1- I get into the camera and start the TwiLight Menu++ from there.
2- I go and open the DBZ UB game. 
3-While loading it, it seems to achieve it but it keeps the error of the black screen   

### Other notes

-I already tried to change the pitcher from Released to Nightly
-I changed the ARM9 and ARM7 CPU Speed, Run in...
-I pressed L just as I loaded the game with the A/Start
-I extended the AP patch to try to run (the one in the translated version didn't allow me to do so since there was none. Anyway, with or without the patch it won't run)
-I've trimmed the game and it's not working either.

**Comment by RocketRobz** [comment]
Try with Unlaunch, instead of DSiWarehax.
Also, heap shrink isn't an option for SDK5 games.

**Comment by iL30N4RD0** [comment]
Excuse me, isn't there another way to solve this so we don't have to use unlaunch? I don't want to damage the console.

**Comment by RocketRobz** [comment]
Nope, there is no other way.
Installing Unlaunch will not damage the console.

**Comment by iL30N4RD0** [comment]
Okay, thank you! I'll try.
