### ISSUE TITLE
Enable Rosalina debugging

### ISSUE THREAD

**Issue by weirdal3333** [ahezard/nds-bootstrap#87]
Please consider letting the Rosalina menu run while we play the DS game!

Screenshots and debugging features would be really helpful for further development!

**Comment by ApacheThunder** [comment]
No. this can't happen because Rosalina runs on arm11. Arm11 is largely inaccessible while in legacy mode. This is a feature we can't implement. Besides if this was possible, the issue belongs on Luma's github anyways. It's not our responsibly what features Luma3DS gets.
