### ISSUE TITLE
Pokemon White Edition does not start in flash card R4iSDHC

### ISSUE THREAD

**Issue by Lement22** [ahezard/nds-bootstrap#870]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [X]  Release _[0.29.2]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [ ]  SD Card
- [X]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Pokemon White Edition 

### Expected behaviour

Start the white edition pokemon game from the R4SDHC, with Twin Light Menu ++ on the console SD.

### Actual behaviour

The game does not start, it is necessary to exit the Twin Light Menu ++.

### Steps to reproduce

1. Start Twin Light Menu ++ from the console SD.
2. Start the games on an R4iSDHC card.
3. Start the white edition pokemon game.
4. Does not load and the blank screens remain.

### Other notes
Previously I played the game without problems loading it from the console SD, now I try to do it from an R4iSDHC card. I followed all the steps for the installation, format the SD several times in Fat 32 format and the rom is the same as I played previously.

**Comment by RocketRobz** [comment]
To run it from a flash card, use the flashcard on a DS or DS lite, along with a Memory Expasion Pak inserted.

**Comment by RocketRobz** [comment]
Alternatively, enable SCFG access for Slot-1 in TWLMenu++ Settings on the SD card.
