### ISSUE TITLE
Infinity Space

### ISSUE THREAD

**Issue by SlifeRed** [ahezard/nds-bootstrap#872]
### Your console

Tell us which console you are using:

- [x ]  New 3DS/2DS (XL)

### CFW and configuration

3DS/2DS:

- [x ]  Luma3DS

### nds-bootstrap version

Tell us which versions you are using:

- [x ]  Release _0.29.3_

### Your device

Tell us which card you are using:

- [x ]  SD Card

### If this issue only affects a certain game, which game is it?

Infinity Space

### Actual behaviour
The game shows SEGA logo and freeze on white screen.

**Comment by RocketRobz** [comment]
Try turning off heap shrink.

**Comment by SlifeRed** [comment]
I've turned it off on both variants of the game (different regions), but still nothing. I've even tried this game on n2dsXL with the same effect.
