### ISSUE TITLE
Soft Resetting goes to Unlaunch

### ISSUE THREAD

**Issue by Hawkeye1005** [ahezard/nds-bootstrap#875]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [- ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [- ]  Unlaunch v2.0+HiyaCFW v1.3.2_[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [- ]  Release v0.30.0_[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [- ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

The game should soft reset without going to any other menus

### Actual behaviour

Unlaunch opens and I have to restart my DSi to boot the game again. It does appear to be soft resetted there though, as NSMB minigames does open afterwards.

### Steps to reproduce

1. Open minigames on NSMB

**Comment by RocketRobz** [comment]
You need to update TWiLight Menu++ as well.
