### ISSUE TITLE
Final Fantasy Crystal Chronicles Echoes Of Time (EU) - Refuses to save

### ISSUE THREAD

**Issue by IrisHeartCPU** [ahezard/nds-bootstrap#877]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [x]  Release _[v.0.30.0]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Final Fantasy Crystal Chronicles Echoes Of Time (EU ver.)

### Expected behaviour

Game is listed as working on the compatibility chart, and the folder with the AP patches has it's AP Patch

### Actual behaviour

Refuses to save and let me play saying it isn't AP patched, but i said the patch in the folder, and in earlier versions of the nds-bootstrap is listed that it has the AP patch on-the-fly.

### Steps to reproduce

1.Load the game.
2.Try to save or try to change the settings of the game in the options, then press B to return.
3.Profit.

### Other notes
I can only play it and save if i activate the cheat to simulate the AP patch, but i don't see that as a solution, and the cheat sometimes works, and sometimes not, and most of the times makes the game crash.
I've taken photos of the issue and the steps, there are in spanish, but they
 make easy to see the issue.
![20200303_180850](https://user-images.githubusercontent.com/61751545/75801196-06859600-5d7b-11ea-8dce-7eed50ca1403.jpg)
![20200303_180912](https://user-images.githubusercontent.com/61751545/75801210-0b4a4a00-5d7b-11ea-8ed8-387033bdcfdb.jpg)
![20200303_181329](https://user-images.githubusercontent.com/61751545/75801218-0daca400-5d7b-11ea-82cd-216eb6ad7fd1.jpg)
![20200303_180925](https://user-images.githubusercontent.com/61751545/75801227-10a79480-5d7b-11ea-9e1f-b9f71d7e29db.jpg)

**Comment by SleepyLark** [comment]
I don't quite see the problem if it works if you have the cheat code activated.

**Comment by IrisHeartCPU** [comment]
Yes, but the cheat sometimes works, and sometimes not, and most of the times makes the games crash.

**Comment by Kalanyr** [comment]
Having a built in AP patch which happens automatically is preferably to having to actively use cheats too (since it requires you to know that such exists and is required).  Though I'm not sure if that's possible in this case, none of the patching tools have a permanent patch for this game.

**Comment by RocketRobz** [comment]
Is the original ROM modified in any way?

**Comment by IrisHeartCPU** [comment]
> Is the original ROM modified in any way?

No, it isn't

**Comment by IrisHeartCPU** [comment]
This is also happening on the version 0.30.1

**Comment by SleepyLark** [comment]
So I patched the US version using DS-Scene Tool and the game appears to be saving fine.  I think the problem is that the AP patch included with TWL menu isn't working.  I remembered before I manually patched it it would crash when saving and only work with the AP cheat activated

**Comment by Kalanyr** [comment]
As of nightly  Australian version now recognizes the presence of an AP patch but the saving still fails.

**Comment by Kalanyr** [comment]
Save works as of   e2ffcadd (bootstrap) /  ff0c0021 (Twilight)

**Comment by IrisHeartCPU** [comment]
Save working on nds-bootstrap 0.30.1 after AP patching the US ver. using DS-scene Tool that SleepyLark mentioned before~

**Comment by Shikafax** [comment]
I have the same problem, but I have a modified version to translate the game into Italian! Is there a way to solve it?

Thanks in advance!
