### ISSUE TITLE
Peppa Pig - The Game (EUR) white screen regression

### ISSUE THREAD

**Issue by jagurxe** [ahezard/nds-bootstrap#880]
### Your console

Tell us which console you are using:

- [ ]  DS Phat/Lite
- [ x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other/Older CFW [specify]

### nds-bootstrap version

Tell us which versions you are using:

- [ x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Your device

Tell us which card you are using:

- [x ]  SD Card
- [ ]  (Slot-1) Flashcard

### If this issue only affects a certain game, which game is it?

Game goes here if applicable

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
Try turning off heap shrink.

**Comment by RocketRobz** [comment]
Fixed by https://github.com/DS-Homebrew/TWiLightMenu/commit/665b950a42ea60f8cfd34b1590d819723c3d2145
