### ISSUE TITLE
James Cameron's Avatar: The Game white screen on load

### ISSUE THREAD

**Issue by o4ugDF54PlqU** [ahezard/nds-bootstrap#883]
**Your console:** DSi XL
**Launch Method:** Unlaunch 1.9 + HiyaCFW 1.3.2
**Version used:** release 0.30.1
**Game tested/used/applicable:** 4529 James Cameron's Avatar: The Game 
TWL-VAVE-USA

**Expected Behavior:** The game should load
**Actual Behavior:** White screen on both screens after the nds-bootstrap please wait message, top screen goes black for a fraction of a second before going completely white

### Steps to reproduce
Run the game
[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
ROMREAD_LED = 1
LOADING_SCREEN = 1
CONSOLE_MODEL = 0
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
LOADING_DARK_THEME = 0
LOADING_SWAP_LCDS = 0
LOADING_SCREEN_FOLDER = /_nds/TWiLightMenu/3dsmenu/loading/
LOADING_FRAMES = 0
LOADING_FPS = 0
LOADING_BAR = 1
LOADING_BAR_Y = 0
NDS_PATH = sd:/roms/nds/notworking/James Cameron's Avatar - The Game (USA) (En,Fr,Es) (NDSi Enhanced).nds
SAV_PATH = sd:/roms/nds/notworking/saves/James Cameron's Avatar - The Game (USA) (En,Fr,Es) (NDSi Enhanced).sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
DONOR_SDK_VER = 5
GAME_SOFT_RESET = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
SOUND_FREQ = 1
AP_FIX_PATH =
CACHE_FAT_TABLE = 0
DMA_ROMREAD_LED = -1

### Logs
findModuleParamsOffset:
Module params offset restored: 02004FCC
sdk_version: 05017537
This rom is not compressed

Switched to NTR mode BIOS
patchCardNds

[SDK 5]

Found cardId

ERR_NONE

Arm7 (patch v5)
Relocation src: 02380644
JumpTableFunc: 02390258
card read:	02390240
Eeprom read:	02390264
Eeprom page write:	0239027C
Eeprom page prog:	02390294
Eeprom verify:	023902AC
Eeprom page erase:	023902C0
ERR_NONE

ERR_NONEhookNdsRetailArm7
hookLocation arm7: 023921D8

ERR_NONE
hookLocation arm9: 027C0020

chipID: C0003FC2

**Comment by RocketRobz** [comment]
I derped somewhere.
Please downgrade to v0.30.0

**Comment by o4ugDF54PlqU** [comment]
Downgraded to v0.30.0, works again

**Comment by RocketRobz** [comment]
Please re-download v0.30.1.
A bug has been fixed to hopefully make this run again.

**Comment by o4ugDF54PlqU** [comment]
Tried it on 0.30.1 again, the game now boots normally.
