### ISSUE TITLE
Soft-resetting causes widescreened games to go 4:3

### ISSUE THREAD

**Issue by IrisHeartCPU** [ahezard/nds-bootstrap#884]
**Your console:**  New Nintendo 2DS (XL)
**Launch Method:**  Luma3DS
**Version used:**  Release (0.30.1)
**Game tested/used/applicable:**  Final Fantasy Crystal Chronicles Echoes Of Time (EU ver.), Pokémon Black (1 and 2) Pokémon White(1 and 2), Pokémon Soul Silver, Pokémon Heart Gold and Pokémon Platinum.

**Expected Behavior:**  The games in widescreen have to maintain the 16:10 resolution after the soft-reset.
**Actual Behavior:**  When i do a natural or forced soft-reset on a widescreened game, the game resets in 4:3, and i have to press button home to load the game another time on widescreen, or restart my 3DS for doing the same.

### Steps to reproduce

 1.Load the game.
2.Soft-reset normally or do a forced soft-reset on a widescreened game..
3.Profit~

### Other notes

(I didn't tested this bug in other games because i don't know what more games i have with widescreen, but if i find another game in my sd with widescreen and happens the same with it, i will edit this issue and add it here) All my games are in their Eur and Spa respective versions.

**Comment by RocketRobz** [comment]
There's already a such issue open here: https://github.com/DS-Homebrew/TWiLightMenu/issues/847

**Comment by IrisHeartCPU** [comment]
Sorry, i didn't know that, i only wanted to help.
