### ISSUE TITLE
3ds ds forwarder bottom screen lines doubling

### ISSUE THREAD

**Issue by recsterio** [ahezard/nds-bootstrap#886]
**Your console:** old 3ds
**Launch Method:** luma, nds bootstrap 3ds nds forwarder
**Version used:** latest release
**Flashcart used:** SD card
**Game tested/used/applicable:** pokemon diamond, and the legend of zelda phantom hourglass

**Expected Behavior:** perfect screen
**Actual Behavior:** wierd doubling in the bottom lines as if it were cut off and the line above was copied

### Steps to reproduce

not sure how to reproduce, but it happens randomly with every boot of the game

### Logs

not sure how to debug this

**Comment by RocketRobz** [comment]
This is a TWL_FIRM issue, not an nds-bootstrap issue.

**Comment by recsterio** [comment]
> This is a TWL_FIRM issue, not an nds-bootstrap issue.
> To fix it, just press HOME and then B.

i tried pressing home and then b in the game and it just asks if i want to close the software but the doubling is still there. when do i press those

**Comment by RocketRobz** [comment]
Press HOME to bring up the message, then press B to go back into the game.

**Comment by recsterio** [comment]
pressing home and b to resume the game doesn't seem to fix it

**Comment by recsterio** [comment]
i can send a video and pictures if that helps

**Comment by RocketRobz** [comment]
Try rebooting the game with no cartridge inserted.

**Comment by recsterio** [comment]
it still happens with no cartridge

**Comment by RocketRobz** [comment]
Try closing the lid and opening it again.

**Comment by recsterio** [comment]
opening and closing worked thank you

**Comment by fniutta** [comment]
> Try closing the lid and opening it again.

Can u provide me more info to why this "fix" works?

**Comment by RocketRobz** [comment]
> > Try closing the lid and opening it again.
> 
> Can u provide me more info to why this "fix" works?

TWL_FIRM has some weird race condition which sometimes causes the screen to initialize with doubled lines. Closing the console's lid and opening it back up re-initializes the screens to workaround this bug.

**Comment by fniutta** [comment]
> > > Try closing the lid and opening it again.
> 
> > 
> 
> > Can u provide me more info to why this "fix" works?
> 
> 
> 
> TWL_FIRM has some weird race condition which sometimes causes the screen to initialize with doubled lines. Closing the console's lid and opening it back up re-initializes the screens to workaround this bug.

Oh I see. Thank u very much for this reply.
