### ISSUE TITLE
Several Games that are working on the compatibility list do not load. (Stuck on white screen)

### ISSUE THREAD

**Issue by NinjaCheetah** [ahezard/nds-bootstrap#888]
**Your console: DSi** 
**Launch Method: Twilight Menu ++ and HiyaCFW** 
**Version used: release** 

**Game tested/used/applicable: Various including: Mario and Luigi: Bowser's Inside Story, Personal Trainer: Cooking (not on list but doesn't work), and Bejewled 3** 

**Expected Behavior: Game loads as normal** 
**Actual Behavior: Both screens turn white, and locks up, requiring a reboot

** 

### Steps to reproduce

Unsure, nobody else has ever had this problem so far. I just start the game and nothing happens

**Comment by RocketRobz** [comment]
Try turning off heap shrink for those games.

**Comment by NinjaCheetah** [comment]
> 
> 
> Try turning off heap shrink for those games.


Ok I will

**Comment by NinjaCheetah** [comment]
How do I do that?

**Comment by RocketRobz** [comment]
Press Y in the ROM menu, then scroll down.

**Comment by NinjaCheetah** [comment]
So, while trying to do that I discovered that Twilight Menu locks up when I scroll through the sd/Roms/nds folder. As soon as I hover over the first game in the list, it freezes

**Comment by NightYoshi370** [comment]
This is more of a support sort of thing rather than an issue. As a result, we'd much rather you use the discord server for support. Besides, we don't want to spam users emails.
Closed

**Comment by NinjaCheetah** [comment]
Where can I find the link to that?

**Comment by NightYoshi370** [comment]
Readme
