### ISSUE TITLE
NDS Games doesn't work on Multiplayer

### ISSUE THREAD

**Issue by Godbout2** [ahezard/nds-bootstrap#890]
**Your console:** DSi XL
**Launch Method:** Memory Pit (to launch TWLmenu++)
**Version used:** Release v0.29.2
**Game tested/used/applicable:** Mario Kart DS

**Expected Behavior:** Go to the Multiplayer Screen
**Actual Behavior:** Game Freezes and Crashes

### Steps to reproduce

Click Multiplayer on the Mario Kart DS screen

### Other notes

I heard Unlaunch could work, but i don't have a 2GB card and i wouldn't like to have Unlaunch on my DSi, so if you could make Memory Pit work on Multiplayer, it would be highly appreciated.

**Comment by NightYoshi370** [comment]
You don't need to have a 2GB SD card for Unlaunch. Only hiyaCFW
Memory Pit + nds-bootstrap is unsupported. Please install Unlaunch
