### ISSUE TITLE
Kingdom Hearts 352/8 Days Merchant Crash

### ISSUE THREAD

**Issue by Gregory2Bif** [ahezard/nds-bootstrap#892]
**Your console:** <New Nintendo 3ds XL>
**Launch Method:** <Luma 3ds (pretty sure 10.0.1), Latest version of Twimenu>
**Version used:** <Release v0.31.0>
**Game tested/used/applicable:** <Kingdom Hearts 352/8 Days (it was a us copy)>

**Expected Behavior:** <Interacting with the Moogle allows you to synthesize various items. You can leave to return to gameplay.>
**Actual Behavior:** <The game freezes and becomes unusable after exiting the synthesize menu. There isn't anyway to escape, aside from going back to homemenu.>

Bootstrap used
[nds-bootstrap.zip](https://github.com/ahezard/nds-bootstrap/files/4346373/nds-bootstrap.zip)

### Other notes
The rest of the game is fairly functional, and the rest of the shop is fine, just the synthesize menu.

**Comment by RocketRobz** [comment]
Try turning off heap shrink by pressing Y in the ROM menu, then scroll down to the option and set to `Off`.

**Comment by Gregory2Bif** [comment]
Nope, it seems to still be non-functional with the same freeze after the hemp shrink is turned off.

**Comment by NightYoshi370** [comment]
> NDS_PATH = sd:/roms/4223 - Kingdom Hearts - 358-2 Days (USA) (En,Fr)_apfix.nds
> AP_FIX_PATH = sd:/_nds/TWiLightMenu/apfix/YKGE-8904.ips

You're double patching the Anti-Piracy, causing this error. Either un-AP patch your ROM or delete the apfix file.
Closing
