### ISSUE TITLE
NSMB Single-Card Multiplayer Issues

### ISSUE THREAD

**Issue by TylerFurrison** [ahezard/nds-bootstrap#893]
**Your console: Old 3DS**
**Launch Method: Luma v10.0.1 + TWiLightMenu++ v12.2.1 (both client and host)**
**Version used: nds-bootstrap v0.31.0 (both client and host)**
**Game tested/used/applicable: New Super Mario Bros. (USA), A2DE; DS Download Play (USA)** 

**Expected Behavior: Tested both Mario and Luigi mode and Minigames mode, both were expected to send the data to the other DS when using Download Play and allow for single card multiplayer.** 
**Actual Behavior: After sending the data to the other 3DS, the game crashes on the system that used Download Play, causing a communication error, indicating single card multiplayer may be broken.** 

### Steps to reproduce
1. Launch NSMB (USA) on host 3DS via TWiLightMenu++.
2. Launch Download Play on client 3DS and select DS Download Play.
3. Once both have loaded their selected software, select either Minigames or Mario & Luigi on the main menu on the host system.
4. Go through the selections, making sure to select the options pertaining to Single-Card mode.
5. Once the option to join has appeared on the client 3DS, tap the game and join.
6. End the search on the host 3DS and start sending data.
7. Wait for the client to finish receiving data and for it to start loading the game properly
8. Once the Nintendo logo starts to appear on the client, it will crash and cause a communication error on the host.

Host 3DS ini:
[nds-bootstrap.zip](https://github.com/ahezard/nds-bootstrap/files/4349236/nds-bootstrap.zip)

Client 3DS ini:
[nds-bootstrap.zip](https://github.com/ahezard/nds-bootstrap/files/4349248/nds-bootstrap.zip)

### Logs
Log from the host 3DS, could not obtain log from client 3DS:
[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4349304/NDSBTSRP.LOG)

### Other notes
Did try and load DS Download Play via NAND and TWiLightMenu++, both versions are identical in nature and both crash when loading the multiplayer mode.

Possibility of being related to issue #890 at this time

**Comment by NightYoshi370** [comment]
Related to #553. Please use that issue instead.
Closing...
