### ISSUE TITLE
Game won't load from flashcart

### ISSUE THREAD

**Issue by EnchantedDiamondSword** [ahezard/nds-bootstrap#895]
**Your console:** DS Lite (USG-001) (also reproduced on n3DS XL (RED-001)) 
**Launch Method:** Flashcart (R4i-SDHC RTS-3DS, R4 firmware 1.85b) (the 3DS is on 11.10U) 
**Version used:** `9533d83e` as well as `Release v0.31.0` 
**Flashcart used:** See "Launch Method," I guess? 
**Game tested/used/applicable:** TETRIS DS by Nintendo (TID: ATRE, hashes at bottom, dumped from original cart) 

**Expected Behavior:** The game loads. 
**Actual Behavior:** The game didn't load. 

### Steps to reproduce

1. Place the game at fat:/roms/TETRISDS.NDS
2. Load the game through TWiLightMenu++ `754bebf5`
nds-bootstrap.ini:
`[NDS-BOOTSTRAP]`
`DEBUG = 1`
`LOGGING = 1`
`LOADING_SCREEN = 1`
`CONSOLE_MODEL = -1`
`CACHE_FAT_TABLE = 0`
`COLOR_MODE = 0`
`SOUND_FREQ = 1`
`NDS_PATH = fat:/roms/TETRISDS.NDS`
`SAV_PATH = fat:/roms/saves/TETRISDS.NDS`
`RAM_DRIVE_PATH = sd:/null.img`
`LANGUAGE = -1`
`DONOR_SDK_VER = 0`
`PATCH_MPU_REGION = 0`
`PATCH_MPU_SIZE = 0`
`CARDENGINE_CACHED = 1`
`FORCE_SLEEP_PATCH = 1`

### Logs
`debug: true`
`ndsPath: "fat:/roms/TETRISDS.NDS`
`"`
`savPath: "fat:/roms/saves/TETRIS`
`DS.NDS"`
`Press start...`
`saveSize: 2000`
`language: FF`
`donorSdkVer: 0`
`patchMpuRegion: 0`
`patchMpuSize: 0`
`boostCpu: false`
`forceSleepPatch: true`
`logging: true`
`initDisc: true`
`dldiPatchNds: true`
`backlightMode: 0`
`Press start...`
[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4357363/NDSBTSRP.LOG)

### Other notes
Checksum info from 7-Zip (*):
`Name: TETRISDS.NDS`
`Size: 13859784 bytes (13 MiB)`
`CRC32: E5C78586`
`CRC64: E15E95990F7C01FC`
`SHA256: 6768F24A2EFD72BAB4AC78FA94BA4896103B9014997A3BF560712E0160B432FB`
`SHA1: F0C91573C6ADF67359904144283ACC1CBE2B7FBD`
`BLAKE2sp: 7EE6158750BA95E3CD3FDB2DA0E1D47AB057AE246930BFADE361B2F5D06029DD`

**Comment by RocketRobz** [comment]
Not all games work with B4DS.
I suppose you could try with a DS Memory Expansion Pak, if you have one.

**Comment by EnchantedDiamondSword** [comment]
Thank you for your reply.
Apparently, TWiLightMenu++ was making the save files WAY too small. Also, on a completely unrelated note, it's not using the `.sav` extension; instead, it's just using the name of the ROM (`fat:/roms/TETRISDS.NDS` will be saved at `fat:/roms/saves/TETRISDS.NDS`).

**Comment by mOSU-eof** [comment]
Hi. This is EnchantedDiamondSword's primary account.
Turns out, this was just a compatibility issue. Pokémon Diamond (Nintendo) works just fine. However, it did say `forceSleepPatch: false`, and I also noticed that the force sleep patch option on my 3DS says "Remember to turn this off if you have a retail game card inserted." I'll see if I can't get that not to turn on.
