### ISSUE TITLE
Failed to Launch a game

### ISSUE THREAD

**Issue by Hyaku-san** [ahezard/nds-bootstrap#897]
**Your console:** Old 3DS
**Launch Method:** Luma3DS  11.13.0-45E
**Version used:** Release                  
**Game tested/used/applicable:** Pokemon White/Black 2

**Expected Behavior:** Launch the game quickly 
**Actual Behavior:** White screen after NDSBootstrap screen

### Steps to reproduce

1. Launch the game in TWLMenu++ in DSi Mode.
2. NDSBootstrap screen 
3.White screen.

### Other notes
I use a 32GB SD, the menu has been installed with Universal-Updater.

**Comment by SuperSaiyajinStackZ** [comment]
Easy solution for now: Launch the game in DS Mode. DSi Mode hasn't been fully implemented yet.

**Comment by Hyaku-san** [comment]
In DS mode, same. Appears the white screen

**Comment by NightYoshi370** [comment]
We'd be able to help you in the discord server, as this game is confirmed working. Please join; the link is in the ReadME.
