### ISSUE TITLE
Multiplayer does not connect correctly

### ISSUE THREAD

**Issue by Godbout2** [ahezard/nds-bootstrap#898]
**Your console:** DSi XL and DSi
**Launch Method:** Unlaunch
**Version used:** Release v0.29.2
**Game tested/used/applicable:** Mario Kart DS

**Expected Behavior:** When clicking "Cut Off" on the multiplayer screen, it shows the Select Game screen and stuff like that
**Actual Behavior:** Plays the "Select Game" music for 1 second then gives a Communication Error screen

### Steps to reproduce

Start a Multiplayer game in Mario Kart DS

### Other notes

Both DSi's have Unlaunch Enabled

**Comment by SleepyLark** [comment]
Already a know issue (#794 )
