### ISSUE TITLE
Pokemon Black 2 cannot use the input keyboard

### ISSUE THREAD

**Issue by LotRosh** [ahezard/nds-bootstrap#899]
**Your console:** O3DS
**Launch Method:** LumaCFW
**Version used:** Nightly e3a1a5df
**Game tested/used/applicable:** Pokemon Black 2 (Chinese Translation Version)

**Expected Behavior:** When setting the trainer's name or Pokémon's name, the keyboard should be displayed for input.
**Actual Behavior:** When setting the name, the input keyboard does not appear, the game freezes and the screen keeps blanking.

### Steps to reproduce

1.Launch game
2.Select "New Game"
3.Continue until you are asked to set a name
4.freeze occur

### Logs
[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4373972/NDSBTSRP.LOG)

### Other notes
The input keyboard works fine in the Release version. May be a problem with the Nightly version.
I haven't tested whether other regional versions of the game have the same problem.

**Comment by RocketRobz** [comment]
Try updating the nightly again.

**Comment by LotRosh** [comment]
> Try updating the nightly again.


All right, it works.
