### ISSUE TITLE
Bug: Sprites Not Loading

### ISSUE THREAD

**Issue by FlareRXW** [ahezard/nds-bootstrap#900]
Console configuration:
New 3ds XL (11.13.0-45U) with Luma3ds (10.0.1)
nds-bootstrap Release (v0.30.1)

Launching Method:
microSD card

Games effected:
Mario VS Donkey Kong Mini-Land Mayhem!

What is going on?
When I load a copy of "Mario VS Donkey Kong Mini-Land Mayhem!". The Game loads up fine. however, when i begin to play the game, Most of the character sprites don't load. in-game and the cutscenes.

How to replicate:
Launch "Mario VS Donkey Kong: Mini-Land Mayhem!"
Load up a level or start a new game.
Tada! Missing Sprites!

In-Game: Mini-Toys sprites are missing. but you can still interact with them.
Cutscenes: (Beginning cutscene) Donkey Kong, Mario, Mini-Toy's , and Palatania are missing.

**Comment by SleepyLark** [comment]
Already a known issue (#467)
If I recall it's an AP issue, but even when I tried patching it it would still happen.

**Comment by FlareRXW** [comment]
Ok. I guess I can close this then if it is a known bug.

**Comment by RocketRobz** [comment]
It's due to a function not being patched.
It is not related to AP.
