### ISSUE TITLE
Games not saving 

### ISSUE THREAD

**Issue by alliharin** [ahezard/nds-bootstrap#901]
**Your console:** 
**Launch Method:** 
**Version used:** 
**Flashcart used:** 
**Game tested/used/applicable:** 

**Expected Behavior:** 
**Actual Behavior:**

**Comment by NightYoshi370** [comment]
You're not giving any information when you say GodMode9 v1.9.1, nor when you say Games not saving. Fill in the template

**Comment by alliharin** [comment]
I was editing it accidentally posted before I finished

**Comment by RocketRobz** [comment]
Please upload `nds-bootstrap.ini` from `sd:/_nds/`.

**Comment by alliharin** [comment]
I found the file in the _nds folder but how do I upload it?
