### ISSUE TITLE
Games not saving 

### ISSUE THREAD

**Issue by alliharin** [ahezard/nds-bootstrap#902]
<NDS3 XL
Godmode9 v1.9.1
Luma3DS v10.0.1
Sys 11.13.0-45U
Twilightmenu++ 

Games are not saving 

using nds files 
Games load and play but when you exit and reenter Twilightmenu the save files for the game are blank

**Comment by Kaisaan** [comment]
Which version of TWiLightMenu++ are you on? Which games have you tried this with?

**Comment by alliharin** [comment]
The latest version just downloaded and installed it on Thursday 
I only have super Mario on there now I was testing how it worked before adding others

**Comment by Kaisaan** [comment]
Which DS Mario game specifically have you tried?

**Comment by alliharin** [comment]
New super Mario bros. 
Is the title

**Comment by alliharin** [comment]
In a closed request rocket rob said 
Please upload nds-bootstrap.ini from sd:/_nds/.

I found this file but do not know what he means by upload it.
My apologies I’m new to this

**Comment by RocketRobz** [comment]
Post what's inside it.

**Comment by alliharin** [comment]
I'm confused now. When the SDcard was in the NDS3 XL I saw the .ini file using FBI
When I took the SDcard out and put it in the laptop to get a screen shot I no longer see a file with the .ini extension 


![Capture](https://user-images.githubusercontent.com/62574054/78067138-34eb9680-7364-11ea-9b84-accd5544d897.PNG)

**Comment by RocketRobz** [comment]
That's because Windows hides the known file extensions.
`nds-bootstrap.ini` is the configuration file shown.

**Comment by alliharin** [comment]
So what do I need to do next?

**Comment by RocketRobz** [comment]
Open the file.

**Comment by alliharin** [comment]
![image](https://user-images.githubusercontent.com/62574054/78067621-07ebb380-7365-11ea-8775-1a0e438b146a.png)

**Comment by RocketRobz** [comment]
How big is the .sav file?

**Comment by alliharin** [comment]
That was the issue it’s not creating a save file

**Comment by RocketRobz** [comment]
What theme are you using in TWiLight Menu++?

**Comment by alliharin** [comment]
Never mind the save file is in the other NDS folder with the game 
It’s 8 kB 
But the game doesn’t see it

**Comment by alliharin** [comment]
I’m just using whatever theme is the default

**Comment by RocketRobz** [comment]
So how are you trying to save the game?

**Comment by alliharin** [comment]
![image](https://user-images.githubusercontent.com/62574054/78068295-243c2000-7366-11ea-9ad4-65845a46024b.png)

**Comment by alliharin** [comment]
![image](https://user-images.githubusercontent.com/62574054/78068342-3c13a400-7366-11ea-9b02-5606a3b194fe.png)

**Comment by RocketRobz** [comment]
I mean how do you save in the game itself?

**Comment by alliharin** [comment]
It's a check point save. You get so far and it auto saves

**Comment by RocketRobz** [comment]
So you select `Yes` to save the game?

**Comment by alliharin** [comment]
Should that saves file be someplace else?

**Comment by RocketRobz** [comment]
No. It only reads the save in `saves`.

Try re-installing nds-bootstrap.

**Comment by alliharin** [comment]
no you do not choose to save it automatically saves when you've gotten to a certain point in the game

**Comment by alliharin** [comment]
Yes did that yesterday before coming here. Someone suggested it on Discord

**Comment by RocketRobz** [comment]
Try a nightly build of nds-bootstrap then.
Be sure to update it first.

**Comment by alliharin** [comment]
That did not work. I went in and got to 2 different save points. Left Twilightmenu and reentered.
The game still has all save files as new and not the game I was playing

**Comment by RocketRobz** [comment]
Try changing the save number in the per-game settings.

**Comment by alliharin** [comment]
Same result. Doesn't matter which save file I try

**Comment by RocketRobz** [comment]
Then the issue could be the ROM (which wouldn't make sense, considering you dumped it yesterday) the created FAT table (if `Save FAT table cache` is turned on), or the SD card.

**Comment by alliharin** [comment]
SDcard is new

**Comment by alliharin** [comment]
Where do you turn on the save FAT table cache?

**Comment by RocketRobz** [comment]
in the Games/Apps page, in TWLMenu++ settings.

**Comment by RocketRobz** [comment]
Did you also switch Bootstrap to Nightly in TWLMenu++ Settings?

**Comment by alliharin** [comment]
I don't have a settings folder in Twilightmenu++

When I open Twilightmenu++ it looks like this 

![image](https://user-images.githubusercontent.com/62574054/78070954-a2022a80-736a-11ea-8139-5bb9041e78ed.png)

**Comment by RocketRobz** [comment]
To access TWLMenu++ Settings, press SELECT, and touch the DS icon on the bottom.

**Comment by alliharin** [comment]
If I scroll far enough down the NDS folder appears, I click on that then scroll to the game and I click on it to enter 

![image](https://user-images.githubusercontent.com/62574054/78071150-fc9b8680-736a-11ea-9091-b4214faa93c2.png)

**Comment by alliharin** [comment]
Found it! The save fat table cache said No

**Comment by RocketRobz** [comment]
Ok, so set these:
* `Save FAT Table cache`: `No`
* `Bootstrap`: `Nightly`

**Comment by alliharin** [comment]
Settings changed but that didn't fix it.
In the first picture it shows the flag which was the auto save point 
The second picture shows the save files still coming up as new 

![image](https://user-images.githubusercontent.com/62574054/78072453-2b1a6100-736d-11ea-9ce9-ffb68db91fee.png)

![image](https://user-images.githubusercontent.com/62574054/78072488-379eb980-736d-11ea-8a2a-6d82dac0ccad.png)

**Comment by RocketRobz** [comment]
Wait, what? That is *not* how you save the game.
What you shown was a checkpoint for when you lose a life, not a save point.

You save the game when it asks you to save.
If you completed the game, you can save in the map screen after pausing.

**Comment by alliharin** [comment]
When I was playing off the cartridge it always brought me back 
Ok let me check that out and I apologize for wasting your time
