### ISSUE TITLE
Touchscreen not working on Twilight++ Super Mario 64 DS

### ISSUE THREAD

**Issue by kullywon54** [ahezard/nds-bootstrap#903]
**Your console:** Old 2DS

**Launch Method:** Nintendo FW Version 11.13.0-45U; Luma3DS from BannerBomb 3 (I followed the guide from https://3ds.hacks.guide/)

**Version used:** Release (v0.32.0) (Upgraded from the bootstrap from 3ds.hacks.guide)

**Game tested/used/applicable:** I don't know what a MD5 hash is but the name of the file of Super Mario 64 DS I ran is "0037 - Super Mario 64 DS (U)(Trashman).nds" (along with the cover, icon, and ingame pngs). I ran Mario Kart DS and it worked beautifully (0168 - Mario Kart DS (U)(SCZ).nds).

**Expected Behavior:** Super Mario 64 DS boots up and I can tap the touchscreen to get past the "Touch to Start" prompt with the yellow star in the center.

**Actual Behavior:** Super Mario 64 DS boots up and the touchscreen is unresponsive.

### Steps to reproduce
The files in my "_nds" file are as follows:

- nds-bootstrap
- TWiLightMenu
- GBARunner2_arm7dldi_3ds.nds
- GBARunner2_arm7dldi_dsi.nds
- nds-bootstrap.ini
- nds-bootstrap-hb-nightly.nds
- nds-bootstrap-hb-release.nds
- nds-bootstrap-nightly.nds
- nds-bootstrap-release.nds

### Other notes
I tried following a solution from the comments of a github issue post named "Touchscreen input seems to be completely broken #726", but it did not change the problem with Super Mario 64 DS, as far as I am aware. I did not use any widescreen hack.

**Comment by RocketRobz** [comment]
Try a later revision of Super Mario 64 DS, with the release number of 0056.

**Comment by kullywon54** [comment]
Thank you RocketRobz! I replaced the old Super Mario 64 DS files with the 0056 version and it works like a charm! I didn't even know those first 4 digits refered to the version of the rom...
I usually don't ask for help in forums but you replied in TWO MINUTES! Now that's dedication.
Have a good one.
