### ISSUE TITLE
I cant play Pokemon w&b and w&b 2

### ISSUE THREAD

**Issue by AlejqueGB** [ahezard/nds-bootstrap#906]
when I open them the top screen turns off and the bottom screen goes blank, then I can do nothing but go to the menu with the power button. 
this is in a dsi xl

**Comment by RocketRobz** [comment]
Do other games work?

**Comment by AlejqueGB** [comment]
yes, it happens with some pokemon and some more, in the fourth generation it lets me play but when I save and restart the game it tells me that it cannot find the save but it is there

**Comment by RocketRobz** [comment]
How big is the .sav file?

**Comment by AlejqueGB** [comment]
512KB

**Comment by RocketRobz** [comment]
Please post what's in `sd:/_nds/nds-bootstrap.ini`

**Comment by AlejqueGB** [comment]
![Captura](https://user-images.githubusercontent.com/63411478/79034980-3dd93500-7bba-11ea-9413-5f9dacb668ee.PNG)

**Comment by RocketRobz** [comment]
I said `nds-bootstrap.ini`, not the folder called `nds-bootstrap`.

**Comment by AlejqueGB** [comment]
sorry, this is what's inside
![Captura](https://user-images.githubusercontent.com/63411478/79035042-e2f40d80-7bba-11ea-85c2-f94853999aa0.PNG)

**Comment by RocketRobz** [comment]
Try switching to the clean ROMs from the AP-patched versions.

**Comment by AlejqueGB** [comment]
how can I do it?

**Comment by RocketRobz** [comment]
You just add the ROMs from before you AP-patched them.
Those are without `_apfix` at the end.

**Comment by AlejqueGB** [comment]
the same happens, I did that to see if it was fixed

**Comment by RocketRobz** [comment]
Make sure you're running the games in DS mode.
Check TWLMenu++ Settings for the `Run in` setting, in the Games/Apps page.

**Comment by AlejqueGB** [comment]
it's already running in that mode

**Comment by RocketRobz** [comment]
Try changing the `i` in the ROM's folder, to a regular `i`.

**Comment by AlejqueGB** [comment]
sorry, but what i?

**Comment by RocketRobz** [comment]
`5th Generac**i**on`

**Comment by AlejqueGB** [comment]
the same error remains

**Comment by RocketRobz** [comment]
Is Unlaunch installed?

**Comment by AlejqueGB** [comment]
i searched the sd and it says nothing about Unlaunch

**Comment by RocketRobz** [comment]
What guide did you follow to install TWiLight Menu++ and nds-bootstrap?

**Comment by AlejqueGB** [comment]
I use the method of running the games from the sd image gallery

**Comment by RocketRobz** [comment]
I'm asking what guide you followed to install TWiLight Menu++ and nds-bootstrap, not how you run the games.

**Comment by AlejqueGB** [comment]
I have followed this youtube tutorial
https://www.youtube.com/watch?v=ft1TGF9G2fE

**Comment by RocketRobz** [comment]
Please do not follow video guides. They get outdated quickly.
Start here: http://dsi.cfw.guide/

**Comment by AlejqueGB** [comment]
is there no way not to have to install unlaunch on the ds and just use the sd to run the games?

**Comment by RocketRobz** [comment]
You could try re-installing TWiLight Menu++, by deleting the `_nds` folder, and following this guide: https://github.com/DS-Homebrew/TWiLightMenu/wiki/How-to-install-TWiLight-Menu

**Comment by AlejqueGB** [comment]
ok i'm going to try it

**Comment by AlejqueGB** [comment]
exactly what happened soo now I've had to force the ds aagado to get off the white screen

**Comment by RocketRobz** [comment]
Did the nds-bootstrap logo appear?

**Comment by AlejqueGB** [comment]
no, just crash

**Comment by RocketRobz** [comment]
See if the Gen 4 games still have the save issue.

**Comment by AlejqueGB** [comment]
yes, it keeps happening, what it says on the screen is:

There has been a connection error

You will return to the title screen

Please press the A button

I press it and it says that an error has occurred and that it forces the console to turn off, before I thought that it was an error in the rom but I have tried many and it still has the same error

**Comment by RocketRobz** [comment]
You need to Unlaunch to work around this error.

**Comment by AlejqueGB** [comment]
I'm going to install it, but is there a way that it won't run when the ds is turned on and it only works to start the games?

**Comment by RocketRobz** [comment]
You can have Unlaunch automatically start TWLMenu++ on startup.
The guide should tell you how to do that.

**Comment by AlejqueGB** [comment]
and I can not make it not automatic? that is, make it have to go through the normal menu of the dsi xl and run it from the camera as before

**Comment by RocketRobz** [comment]
Running it from the camera will cause the same error screen to appear.

**Comment by AlejqueGB** [comment]
is that I do not want to have to lose the menu of the xl

**Comment by AlejqueGB** [comment]
even so I do not understand why it happens only with the pokemon and not with other games that the game is saved correctly and there is no fault, is it possible that it is because it uses more resources?

**Comment by RocketRobz** [comment]
Wireless is broken in the DSi Camera app.

**Comment by AlejqueGB** [comment]
I have installed it and both bugs have been corrected!!!

**Comment by RocketRobz** [comment]
Great!

**Comment by AlejqueGB** [comment]
is there any way to get back to the normal ds menu without uninstalling Unlaunch?

**Comment by RocketRobz** [comment]
Yes. Hold A+B, then select `LAUNCHER`.
As a side effect of installing Unlaunch, sound won't be played there.
