### ISSUE TITLE
Is it possible to create save states of NDS games?

### ISSUE THREAD

**Issue by jcklpe** [ahezard/nds-bootstrap#907]
**Your console:** Original 3DS
**Launch Method:** Twilight Menu ++ (luma updater says that it has 2.3 and checking the TwilightMenu ++ updater it says that it's 3.1.2)
**Version used:** release
**Game tested/used/applicable:** Advance Wars Days of Ruin for DS

**Expected Behavior:**I'm trying to use save states. Is that possible? How do I do it?
**Actual Behavior:**To be able to use save states

### Steps to reproduce

N/A

### Logs

N/A

**Comment by NightYoshi370** [comment]
Save States are not a thing
Also, please ask general questions on the Discord server instead
