### ISSUE TITLE
Mario 64 DS Star on top ISSUE

### ISSUE THREAD

**Issue by blackhearth6** [ahezard/nds-bootstrap#908]
This problem continues when yoshi catch the star on top after defeat big bomb challenger frozen image and stop game, please fix them!

**Comment by Kaisaan** [comment]
I just collected the first star of Bob-omb Battlefield, "Big Bob-Omb on the Summit" as Yoshi and I did not have any freezing. Tested on my N2DS XL on nds-bootstrap version 0.32.1 and twilightmenu version 13.1.0. @blackhearth6 are you on the latest version of nds-bootstrap/twilightmenu? Also, which console are you using, and are you on the latest version of CFW for it?

**Comment by NightYoshi370** [comment]
@blackhearth6 There is no info on reproduction and as stated by Kaisaan, it works. It's probably a wrong set up on your end. Please join the discord server; we can give you much better support there
