### ISSUE TITLE
Doubt about compatibility

### ISSUE THREAD

**Issue by ThomasWils** [ahezard/nds-bootstrap#909]
Hello, I am interested in the Twilight menu (since my r4 is dying), but I have a doubt, checking the compatibility list there are several games that in the console that is used says 3ds, the question is whether they only work in 3ds or if can you use it on a Dsi Xl ?, sorry if it sounds obvious, but I'm new to this.

**Comment by Kaisaan** [comment]
That just tells what console the game has been tested on. Some games work fine on DSi but might not work on 3DS and vice versa. If you see a game that hasn't been tested on DSi, I'd suggest testing it yourself and then update the compatibility list (just request for access and ping Robz on the discord). If you notice any bugs or have any problems then you can make an issue page.

**Comment by NightYoshi370** [comment]
Also, please ask general questions on the Discord Server.
Closing
