### ISSUE TITLE
An error has occurred

### ISSUE THREAD

**Issue by Rodelas** [ahezard/nds-bootstrap#910]
When i start a ds game like new super Mario Bros or Mario kart ds, it doesnt load and appears a red signal saying "An error has occurred."

**Comment by RocketRobz** [comment]
You need to run the game in DS mode, instead of DSi mode.

**Comment by Rodelas** [comment]
I Run in ds mode and still nothing

**Comment by RocketRobz** [comment]
What happens now?

**Comment by Rodelas** [comment]
Its the same error

**Comment by RocketRobz** [comment]
Where did you set DS mode?

**Comment by Rodelas** [comment]
Twlmenu settings

**Comment by RocketRobz** [comment]
Try re-installing then: https://github.com/DS-Homebrew/TWiLightMenu/wiki/How-to-install-or-reinstall-TWiLight-Menu#re-installing
