### ISSUE TITLE
Elebits - The Adventures of Kai and Zero not working after intro

### ISSUE THREAD

**Issue by kamil9489** [ahezard/nds-bootstrap#912]
**Your console:** Nintendo DSI
**Launch Method:** Twilight Menu v14.0
**Version used:** nds-bootstrap v0.33.0
**Game tested/used/applicable:** 3250 - Elebits - The Adventures of Kai and Zero (U)(XenoPhobia)

**Expected Behavior:** After starting the game, creating save file and selecting story mode the game should play two intros and start the gameplay
**Actual Behavior:** After first intro, the game freezes on white screen and nothing more is happening (no matter what button you click).

### Steps to reproduce

1. run game
2. select/create save file
3. click start
4. click story
5. after first intro game will freeze

### Logs

No logs at all.

### Other notes
- on emulator DeSmuMe on pc game runs just fine without problems (the same rom file).

**Comment by RocketRobz** [comment]
Try turning off heap shrink.

**Comment by kamil9489** [comment]
Ok, works fine with turned off heap shrink. Thanks
