### ISSUE TITLE
Forwarder3-ds and black/white screen issue

### ISSUE THREAD

**Issue by orcutt989** [ahezard/nds-bootstrap#913]
Sorry if this is an inapropriate place for this question, but I can't seem to find where you're hosting Forwarder3-ds.

Have there been any updates to Forwarder3-ds? On the gbatemp thread it looks like a lot of people are having the same issues with the black screen/white screen crash. Where are you hosting the repository for it? I can't seem to find it anywhere.

My forwarders were working fine until I wanted to add some new forwarders. So I downloaded Forwarder3-ds from the gbatemp thread, and then noticed they were all launching a different rom (Contra 4) all the same rom for some reason. I saw in the `ini` file that Contra 4 was the loaded NDS file and it didnt seem to be changing no matter what. I deleted both ini files and regenerated new forwarders and tried reinstalling, but no avail.

 I updated nds-bootstrap manually and then with Universial Updater just to make sure I wasn't doing something wrong. I downloaded both release and nightly. I also updated Twilightmenu and games load fine from there, but my forwarders are broken. I've since uninstalled the working games while testing. I regenerated forwarders again and reinstalled them and it stil is crashing with black and white screens.

I see you mentioned disabling heap sizing in a per-game settings file. Where is this documented? I don't know the specific syntax for this setting or where to set it. I can't seem to find that information anywhere. I also saw you mentioned holding L on boot will disable heap sizing, but that didn't seem to work.

Thanks! Great stuff by the way.

**Comment by RocketRobz** [comment]
Forwarder3-DS is hosted here: https://github.com/Olmectron/Forwarder3-DS
Also, the issue is that the SD side of the forwarder template isn't writing to `nds-bootstrap.ini` for some reason.
Try deleting said file, then try the forwarder again.

**Comment by orcutt989** [comment]
Ah yes I saw that repo, but its a differnet username and there aren't any releases?

I did delete `nds-bootstrap.ini` and `ntr-bootstrap.ini` while troubleshooting and that didn't seem to do the trick. It generated a new `nds-bootstrap.ini` I'm not sure if when I launched a game with Twilightmenu perhaps. It has not populated `NDS_GAME` or what that entry is I cannot remember. Here is the `nds-bootstrap`.ini file that was generated recently.

```
[NDS-BOOTSTRAP]
SAV_PATH = /saves/
DONOR_SDK_VER = 0
GAME_SOFT_RESET = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
CONSOLE_MODEL = 2
DEBUG = 0
LOGGING = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
LOADING_SCREEN = 1
NDS_PATH =
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 0
BOOST_CPU = 0
BOOST_VRAM = 0
FORCE_SLEEP_PATCH = 0
```

Thanks for the quick reply.

**Comment by RocketRobz** [comment]
Try extracting this [sdcard.zip](https://github.com/ahezard/nds-bootstrap/files/4496209/sdcard.zip) file to `sd:/_nds/ntr-forwarder/`, replacing the existing file.
It'll print out the ROM path before attempting to boot it.

**Comment by orcutt989** [comment]
Wow! It worked! Now is there a file that will work without having to press start? Thanks!

**Comment by RocketRobz** [comment]
Here: [sdcard.zip](https://github.com/ahezard/nds-bootstrap/files/4497496/sdcard.zip)
Also, delete `nds-bootstrap.ini` first, so that I'll know if it created the file correctly.

**Comment by orcutt989** [comment]
That worked! I opened a couple games to make sure and they all played great.

**Comment by Fabri842** [comment]
i have the same problem and when i press start it give me an error
