### ISSUE TITLE
language problems in this game Hotel Dusk - Room 215

### ISSUE THREAD

**Issue by luismeza18** [ahezard/nds-bootstrap#914]
Su consola: dsi
Método de lanzamiento: sd
Versión utilizada: v14.0.0
Flashcart utilizado: sd

Comportamiento esperado: bueno 

el juego presenta un problema al momento de detectar los idiomas solo detecta el ingles, aunque cambie el idioma en configuración  de lanzamiento del juego al español o a otro idoma sigue ejecutándose en ingles probé el juego en un emulador en pc y si lo lanza en español y en otro idioma que prodria ser la consola?
 
**traducido por google :c sorry** 
Your console: dsi
Launch method: sd
Version used: v14.0.0
Flashcart used: sd

Expected behavior: good

The game has a problem when detecting languages, it only detects English, although it changes the language in the game's launch configuration to Spanish or another language continues to run in English, I tried the game on an emulator on PC and if it launches in Spanish and in another language that could be the console?

**Comment by kaosjr** [comment]
This should be merged into [Issue #654 ](https://github.com/ahezard/nds-bootstrap/issues/654) as it is referring to the same issue,

**Comment by NightYoshi370** [comment]
Thank you for letting us know @kaosjr.
OP, please report that you have the same issue on #654 

Closing
