### ISSUE TITLE
Game Won’t Boot

### ISSUE THREAD

**Issue by Manjiknights** [ahezard/nds-bootstrap#916]
**Your console:** New 3DS 
**Launch Method:** Luma3DS v10.0.x
**Version used:** TWiLight Menu Release v14.0.0
**Flashcart used:** SD Card 32GB
**Game tested/used/applicable:** Chou Gekijouban Keroro Gunso: Gekishin Dragon Warriors de Arimasu! (TID:C66J) (SDK ver: 4)

**Expected Behavior:** Game boots normally.
**Actual Behavior:** After launching game and getting past the nds-bootstrap loading screen, game hangs on top black screen and bottom white screen.

### Steps to reproduce

Boot game from TWiLight Menu.
nds-bootstrap.ini file contents:

[NDS-BOOTSTRAP]
NDS_PATH = sd:/3401 - Chou Gekijouban Keroro Gunsou - Gekishin Dragon Warriors de Arimasu! (JP)(Caravan).nds
SAV_PATH = sd:/saves/3401 - Chou Gekijouban Keroro Gunsou - Gekishin Dragon Warriors de Arimasu! (JP)(Caravan).sav1
DONOR_SDK_VER = 0
BOOTSTRAP_PATH = sd:/_nds/nds-bootstrap.nds
ROMREAD_LED = 0
BOOST_CPU = 0
DEBUG = 1
LOCK_ARM9_SCFG_EXT = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
LOGGING = 0
LOADING_SCREEN = 1
CONSOLE_MODEL = 2
LANGUAGE = -1
DSI_MODE = 0
BOOST_VRAM = 0
GAME_SOFT_RESET = 0
FORCE_SLEEP_PATCH = 1
LOADING_DARK_THEME = 1
LOADING_SWAP_LCDS = 0
LOADING_SCREEN_FOLDER = /_nds/TWiLightMenu/dsimenu/loading/
LOADING_FRAMES = 0
LOADING_FPS = 0
LOADING_BAR_Y = 0
RAM_DRIVE_PATH = sd:/null.img
CARDENGINE_CACHED = 0
PRECISE_VOLUME_CONTROL = 0
COLOR_MODE = 0
LOADING_BAR = 1
DMA_ROMREAD_LED = -1
CACHE_FAT_TABLE = 0
SOUND_FREQ = 0
AP_FIX_PATH =
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0

### Logs

SCFG_ROM ARM9 1
SCFG_CLK ARM9 85
SCFG_CLK ARM7
SCFG_EXT ARM7
ARM7 data 187
ARM7 data FB06
debug: true
ndsPath: sd:/3401 - Chou Gekijouban Keroro Gunsou - Gekishin Dragon Warriors de Arimasu! (JP) (Caravan).nds
savPath: sd:/saves/3401 - Chou Gekijouban Keroro Gunsou - Gekishin Dragon Warriors de Arimasu! (JP) (Caravan).nds.sav1
donorPath: “”
gbaPath: “”
saveSize: 80000
language: FF
dsiMode: 0
donorSdkVer: 0
patchMpuRegion: 0
patchMpuSize: 0
ceCached: false
CacheBlockSize: 4000
extendedMemory: false
consoleMode1: 2
colormode: 0
romRead_LED: 0
dmaRomRead_LES: FFFFFFFF
boostCpu: false
boosrVram: false
soundFreq: false
forceSleepPatch: true
logging: false
initDisc: false
gameOnFlashcard: false 
saveOnFlashcard: false
backlightMode: 0

### Other notes

-Heap Shrink turned off
-Running in DS Mode
-Could be a bad rom dump?

**Comment by Manjiknights** [comment]
Update: tried replacing the rom and the game is back to white screening on boot rather than the black/white issue. Cheats don't load either. A few of my other roms got corrupted somehow and some saves got deleted. No idea what to do about any of this sadly and it's probably too much for a single issue thread.

**Comment by Kaisaan** [comment]
Which twilightmenu theme are you on?

**Comment by Manjiknights** [comment]
@Kaisaan Using DSi theme

**Comment by RocketRobz** [comment]
If this issue still occurs, it's possible the ROM might just be incompatible.
