### ISSUE TITLE
DS Download play don't working

### ISSUE THREAD

**Issue by flitzekexHD** [ahezard/nds-bootstrap#917]
**Your console:** DSi XL
**Launch Method:** Unlaunch&Twilightmenu++
**Version used:** nds-bootstrap release: 0.33.0/Twilightmenu++: 14.1.0
**Flashcart used:** No
**Game tested/used/:**
Mariokart DS/Marioparty DS/New super mario bros.

**Expected Behavior:** When I host a game the others can play with me via Download play  without having a real copy of it (or modify their systems)
**Actual Behavior:** My friend can see me in the Download play app but if they connect to me his DS went into an white screen crash(or sometimes the "Nintendo®" shows   ##up)

**Comment by RocketRobz** [comment]
This is because those games use Cloneboot for DLP.
Please wait for Cloneboot support to be fixed.
