### ISSUE TITLE
Issues with nds-bootstrap on R4 gold card Animal Crossing/Zelda

### ISSUE THREAD

**Issue by adamj-codethink** [ahezard/nds-bootstrap#919]
**Your console:** 
Nintendo DS Lite

**Launch Method:** 

I'm using V14.10 of Twilight Menu via the R4 gold flash card

**Version used:** 

nds-bootstrap Ver: 7905342b (nightly)

**Flashcart used:** 

R4i-SDHC,R4iGold(non-RTS),r4isdhc.com cards (this id the r4.dat file i used from the Twilight install)

**Game tested/used/applicable:** 

I've Tried Animal Crossing Wild World (boots to white screen)
Legend of zelda phantom hour glass (shows nds-logo, then health warning screen, then crashes)
Legend of zelda spirit tracks (shows nds-logo, then health warning screen, then crashes)

**Expected Behavior:** 

Games should have launched/played? 

**Actual Behavior:** 

I've Tried Animal Crossing Wild World (boots to white screen)
9d0dda4ca7227c31bb31002342b8530e  0389-Animal_Crossing-Wild_World-E-Legacy-.nds

Legend of zelda phantom hour glass (shows nds-logo, then health warning screen, then crashes)
745e372bde611c2ceb3ec5db2bbeb77a  Zelda-Phantom_Hourglass.nds

Legend of zelda spirit tracks (shows nds-logo, then health warning screen, then crashes)
1fc910c48f67f01688b56c69c8cbd3e4  Zelda-Spirit_Tracks.nds

### Logs

ndsPath: "fat:/dsi/Zelda_combo-pack_DS/Zelda-Phantom_Hourglass.nds"
savPath "at:/dsi/Zelda_combo-pack_DS/Zelda-Phantom_Hourglass.sav"
donorPath ""

^ All three games look the same

### Other notes

Some games do play.

I would appreciate any help, i could have miscongfigured something, Animal Crossing did work when using the wood kernel, but i prefer nds-bootstrap and Twighlight.

Thanks

**Comment by RocketRobz** [comment]
These games aren't compatible with B4DS on your flashcards.
The Zelda games boot using either an R4 Ultra or an R4i Gold RTS.

**Comment by adamj-codethink** [comment]
Thanks @RocketRobz, any idea where i can get one of those cards, ebay has a lot of confusing names?

**Comment by RocketRobz** [comment]
Go to www.nds-card.com to buy an R4i Gold card with the `r4ids.cn` address.

**Comment by RocketRobz** [comment]
Re-install the flashcard kernel, and boot TWLMenu++ with that.

**Comment by adamj-codethink** [comment]
Where is the kernel located sorry? I tried a frsh install from the latest release but it just boots to a black screen

**Comment by RocketRobz** [comment]
Unfortunately, I don't know where the correct kernel for that flashcard is.

**Comment by adamj-codethink** [comment]
@RocketRobz Is the kernel not included under Autoload > flashcards?

**Comment by RocketRobz** [comment]
Something tells me it's the wrong one, if it black screens.
Try [this](http://old.r4wood.com/Kernel/e/R4i%20Gold%20V1.50%20+%20Wood%20R4i%20V1.19%20En.rar) one.

**Comment by adamj-codethink** [comment]
@RocketRobz I extracted this to the root of the SD card and now i get a quick white flash, then a black screen, am i putting it in the correct place? sorry for all the questions

**Comment by RocketRobz** [comment]
Yes, the root is the correct place.
Try deleting the `_rpg` folder on the SD card, then re-extract.

**Comment by RocketRobz** [comment]
If you're still having trouble, let's bring this over to Discord: https://discord.gg/yD3spjv
