### ISSUE TITLE
WarioWare D.I.Y. would not save creations

### ISSUE THREAD

**Issue by Pointless2034** [ahezard/nds-bootstrap#921]
**Your console:**  New Nintendo 3DS XL
**Launch Method:** Luma3DS
**Version used:** Release _Latest_
**Flashcart used:** SD Card
**Game tested/used/applicable:**  WarioWare: D.I.Y.

**Expected Behavior:**  The created microgames should be seen on the D.I.Y. shelves.
**Actual Behavior:**  none of the creations are there.

**Comment by NightYoshi370** [comment]
#306 already exists. use that instead
Closing
