### ISSUE TITLE
Kirby Superstar Ultra DS

### ISSUE THREAD

**Issue by BlueBlur26** [ahezard/nds-bootstrap#924]
When I finish the first story in Kirby SuperStar Ultra DS (Spring Breeze) the game will take me back to the other options but the controls are frozen, but the music will remain playing. Is there anything I can do to resolve this issue?

**Comment by RocketRobz** [comment]
Nope, you can't.
I've heard this is due to a bad ROM. Not sure if this was ever fixed though.

Just relaunch the game.

**Comment by NightYoshi370** [comment]
I can reproduce as well
There is a patch on that PC software uses before TWiLight added a bunch of .IPS files. See if that fixes it

**Comment by BlueBlur26** [comment]
Is it okay if you help me go through the steps? Unless there is a YouTube link that can help me?

**Comment by NightYoshi370** [comment]
Well, first off, I forgot what the PC software was called. Second, it's straight forward. Third, as Robz mentioned, just relaunch the ROM

**Comment by BlueBlur26** [comment]
Okay, I'll try that, and see if that does anything. By the way, if I experience the same issue, can I add "donor roms?" If so, how do I do that?

**Comment by RocketRobz** [comment]
You cannot use Donor ROMs for the games that already save properly.

**Comment by BlueBlur26** [comment]
Nvm I think I found a solution on the NDS bootstrap compability. I have to use the menu softlock fix cheat to fix this. Do you know what site I have to use to enable cheats and where I have to put them in my SD Card?

**Comment by BlueBlur26** [comment]
Actually, I think I'm good. Thank you for your help guys.

**Comment by RocketRobz** [comment]
No problem.
