### ISSUE TITLE
Clubhouse Games Flickers when in DSi Mode

### ISSUE THREAD

**Issue by N0v1C3-M0dd3R** [ahezard/nds-bootstrap#926]
N3DS XL
Luma10.1.3 via b9s, launched thru home menu on 3ds gui. Firmware 11.13.0-45U, TWLMenu++ version 14.2.0, nds-bootstrap: Release 0.34.0
Release 0.34.0

Clubhouse Games (Title ID Unknown)
 The game should have played normally without flickers of a different screen
 The game's upper and lower screen would flicker with the top on the bottom and vice versa. The game is still playable, just with an annoying flicker

### Steps to reproduce
1. Launch TWLMenu++ from the home menu on the N3DS
2. Tap on Clubhouse Games from TWLMenu
3. Presto, flickering screens

### Logs
N/A

### Other notes
N/A

**Comment by RocketRobz** [comment]
You need to run in DS mode with NTR clock speed.

**Comment by SleepyLark** [comment]
Can we close this issue?
