### ISSUE TITLE
The World Ends With You is not working.

### ISSUE THREAD

**Issue by TheGaboefects** [ahezard/nds-bootstrap#927]
**Your console:**  Nintendo 3DS XL

**Actual Behavior:** The game crashes during the cutscene after escaping from the frogs for the first time.

### Steps to reproduce

Play the game until you reach the cutscene.

**Comment by SleepyLark** [comment]
Weird, the cutscene works fine on DSi, maybe this is a 3DS only problem?

**Comment by Jerdo32** [comment]
That's odd, I played the game and my backup didn't freeze there, I'm actually in the third week. Maybe it's the dump itself or the region or the bootstrao version?

**Comment by SleepyLark** [comment]
> That's odd, I played the game and my backup didn't freeze there, I'm actually in the third week. Maybe it's the dump itself or the region or the bootstrap version?

Most likely the bootstrap version, this issue was also reported a few versions back but I thought it was fixed.  Like I said it's working fine on my DSi, don't know about 3DS though

**Comment by Niklink** [comment]
Setting cache block size to 32kb avoids the crash.

**Comment by PrgmrAtHrt** [comment]
Currently having this issue on nds-bootstrap 0.64.1 on ds lite.

**Comment by PrgmrAtHrt** [comment]
The cutscene issue.

**Comment by RocketRobz** [comment]
> The cutscene issue.

Sounds like it's either relying on card read DMA, or there's timing issues.
If it's a DMA issue, then it would be difficult to fix, as DLDI drivers (used to read data from the flashcard's SD slot) do not support DMA reads.
