### ISSUE TITLE
Pokemon Storm Silver Glitch

### ISSUE THREAD

**Issue by joraws** [ahezard/nds-bootstrap#929]
**Your console:**  Old 3ds
**Launch Method:**  Luma 3ds
**Version used:**  Nightly
**Game tested/used/applicable:**  Pokemon Storm Silver(hack)

**Expected Behavior:**  go through different areas without black screen
**Actual Behavior:**  Game freezes with a black screen around 2 times I go through a new area

### Steps to reproduce

  1. dump a cart of Pokémon storm silver
2. Play game
3. Go through one area then wait for black screen appear (usually takes 2 times)

### Other notes

I know this was already an issue but I have tried to follow the steps in those threads and none of them work. Usually I can play the game for about 5- 10 minutes then it will crash but for some reason the game now crashes once I go through a door

**Comment by RocketRobz** [comment]
This is an AP issue.
Try patching the ROM first with DS-Scene ROM Tool, and then patch the AP-patched ROM with the Storm Silver patch.

**Comment by joraws** [comment]
I have tried but it says that it does not support the rom

**Comment by RocketRobz** [comment]
The clean ROM, or the hacked ROM?
You need to patch the clean ROM.

**Comment by joraws** [comment]
So I need to ap patch the game first then I can hack it?

**Comment by RocketRobz** [comment]
Yes.

**Comment by joraws** [comment]
It seems fixed, thank you for your help
