### ISSUE TITLE
Twlmenu++ saying "failed to backup custom Twlbg" after updating and making games in widescreen look horribly pixelated

### ISSUE THREAD

**Issue by IrisHeartCPU** [ahezard/nds-bootstrap#933]
**Your console:** N2DS XL
**Launch Method:** Luma 10.1.3 - TWiLight Menu++. v15.0.1 - Nds-bootstrap 0.35.1  
**Version used:** Release nds-bootstrap v0.35.1

**Game tested/used/applicable:** Super Princess Peach, Pokemon Platinum, Pokemon Black, Pokemon White 1 & 2, Pokemon Heart Gold 

**Expected Behavior:** Games should look in widescreen like in the previous version, more smoothly, like they were filtered. 
**Actual Behavior:** The games when launched in widescreen say "failed to backup custom Twlbg", then they load, and look horribly pixelated, like they having no filters, making difficult to see and play them. This doesn't happened in the previous version (15.0.0 and 0.35.0) so what happens? I patched the widescreen manually some time ago 

### Steps to reproduce

1.Launch a game in widescreen in this latest version of TWLMenu++ (15.0.1) and Nds-bootstrap (0.35.1)
2.See that message.
3.Profit.

**Comment by RocketRobz** [comment]
Delete the TwlBg.cxi files in `sd:/luma/sysmodules/`, then follow the widescreen steps again.

**Comment by IrisHeartCPU** [comment]
@RocketRobz can you give me the link to the easy widescreen steps, please? I don't remember how to do it, and i did the widescreen long time ago (and i can't find the steps)
Thanks.

**Comment by RocketRobz** [comment]
https://github.com/DS-Homebrew/TWiLightMenu/wiki/Playing-in-Widescreen

**Comment by IrisHeartCPU** [comment]
Thank you so much, @RocketRobz ! That solved the problems! ^^

**Comment by RocketRobz** [comment]
You're welcome!

**Comment by IrisHeartCPU** [comment]
err... i have this problem another time, launched Pokémon HeartGold, then another time "failed to backup custom Twlbg" on all my games, and all of them are on forced pixelated widescreen, even the games who don't have widescreen patches/not supported by widescreen.
I think this is a bug @RocketRobz 
I will respond to you tomorrow if you respond me, i'm going to sleep (sorry for my bad english)

**Comment by RocketRobz** [comment]
Yup, I'm getting the same issue.
I'll try fixing it for the next TWLMenu++ version.

**Comment by RocketRobz** [comment]
Ok, I found a solution.
You need to install the latest TWLMenu++ CIAs using FBI.
If this does not fix the issue, delete the TWiLight Menu++ titles in the Title list.

**Comment by IrisHeartCPU** [comment]
But i have to redo the patching of the widescreen?

**Comment by RocketRobz** [comment]
You don't need to do that.

**Comment by IrisHeartCPU** [comment]
@RocketRobz i did the all you told me to do. Nothing, the bug is still here, all is in forced pixelated widescreen, and some of my games keep saying "failed to backup custom Twlbg" (telling it or not, all of my games, even the TWLMenu++ itself is on forced widescreen.

**Comment by RocketRobz** [comment]
Redo the widescreen steps then.

**Comment by RocketRobz** [comment]
Let's move this over to here, btw: https://discord.gg/yD3spjv
