### ISSUE TITLE
Mario vs. Donkey Kong: Mini Land Mayhem

### ISSUE THREAD

**Issue by BowSergio** [ahezard/nds-bootstrap#934]
Console: DSi (normal)
NDS-Bootstrap: v0.35.1
TWLMenu ++ : v15.0.1

In this game, toys, enemies, ítems and doors can't be seen, and are replaced by white sprites. I've had this problem since v11.0

Btw: I really apreciate what you are doing for DS community, along with the creators of GBARUNNER2, I love you guys.

**Comment by RocketRobz** [comment]
Duplicate of https://github.com/ahezard/nds-bootstrap/issues/467
