### ISSUE TITLE
Only one game loading, bootstrap not working on most games

### ISSUE THREAD

**Issue by HotPizzaYT** [ahezard/nds-bootstrap#936]
**Your console:** New 2DS
**Launch Method:** Twilight Menu++, Luma3DS on version 11.13.0-45U
**Version used:** Release v10.3.0
**Flashcart used:** None, using MicroSD on 2DS
**Game tested/used/applicable:** Tomodachi Collection (CCUJ) (works), Super Mario 64 DS (ASME) (white screen), Shrek Super Slam (AS3E) (white screen)
**Expected Behavior:** The NDS Bootstrap logo to show and the rom to load
**Actual Behavior:** Hang on white screen and no NDS Bootstrap logo

### Steps to reproduce

1. Launch TwilightMenu++
2. Go to ROMs menu
3. Load Tomodachi Collection. ROM loads as expected.
4. Load other rom
5. Hangs on white screen. Does not show NDS Bootstrap logo.
### Logs
I have no way to access the MicroSD from my computer at the moment. Sorry.
### Other notes
Other games won't show the debug console before the game is loaded because bootstrap will not load

ROMs work fine on NDS emulator from PC

Games and Apps settings (if needed)
Run in: DS mode
ARM9 CPU speed: 133 MHz
VRAM Boost: Off
Slot-1 SD: Use nds-bootstrap: Yes
Slot-1 SD: save location" Console's SD
Force sleep mode patch: On
SCFG access in Slot-1: On
Slot-1 launch method: Reboot (I even tried direct and it wouldn't work)
Bootstrap: Release
Debug: On
Logging: On

**Comment by HotPizzaYT** [comment]
I am aware the ROMs may be corrupted

**Comment by HotPizzaYT** [comment]
[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4611266/NDSBTSRP.LOG)
Here is the log file

**Comment by RocketRobz** [comment]
It's possible the issue might've got fixed later on.
If it still white screens, turn off heap shrink in the per-game settings.
