### ISSUE TITLE
Nanashi No Game error

### ISSUE THREAD

**Issue by TheGaboefects** [ahezard/nds-bootstrap#941]
**Your console:** 3DS XL

**Game tested/used/applicable:** English Patch

**Actual Behavior:** It crashes before reaching the tittle screen

### Other notes
The english patch of the sequel of this game called Nanashi No Game EYE works perfectly fine using nds bootstrap

**Comment by Kaisaan** [comment]
Which version of nds-bootstrap are you using? Also, are you using any of the "No black screen Fix" cheat codes? On my N2DS XL the game works fine with the first No black screen Fix. Tested on nds-bootstrap version 0.35.1

**Comment by SleepyLark** [comment]
Already a known issue (#787), you need to turn on the "No Black Screen Fix" cheat in order to get to the menu, after that there's no problems.

**Comment by TheGaboefects** [comment]
> Already a known issue (#787), you need to turn on the "No Black Screen Fix" cheat in order to get to the menu, after that there's no problems.

How do i turn on cheats?

**Comment by Kaisaan** [comment]
https://github.com/DS-Homebrew/TWiLightMenu/wiki/FAQs#q-how-do-i-use-cheats

**Comment by SleepyLark** [comment]
Can we close this?
