### ISSUE TITLE
NTR DS Game does not save after Direct Power Off

### ISSUE THREAD

**Issue by codyteamusa** [ahezard/nds-bootstrap#943]
**Your console:** Nintendo DSi and New Nintendo 3DS
**Launch Method:** Unlaunch booting .NDS, Twilight Menu and Luma 3DS, Twilight Menu++
**Version used:** 0.35.1
**Game tested/used/applicable:** Tomodachi Collections (English Patched)(REV1)
Pokemon White 2

**Expected Behavior:** The game would be fully saved after a direct power off
**Actual Behavior:** The game does not update the save data and goes back to the previous save after a direct power off 

### Steps to reproduce
Simply launch a game, save and turn the power directly off

### Logs

Cannot provide these at the moment

### Other notes
When I say Direct power off, I mean like pressing and holding power.

**Comment by RocketRobz** [comment]
This issue is known to happen with Tomodachi Collection, but it shouldn't happen with Pokemon White 2.

**Comment by codyteamusa** [comment]
Oh, sorry for making another issue, I found out it was just Tomodachi Collections

**Comment by RocketRobz** [comment]
So did you fix the issue?
If so, how did you fix it?

**Comment by codyteamusa** [comment]
A workaround/fix would be to save twice and your data is fully saved. Thanks for making such a awesome homebrew also.

**Comment by codyteamusa** [comment]
I found a fix!! It requires the hybrid AP&English patch and a 512KB save file! The game fully works once you save and reload the game!
