### ISSUE TITLE
Black screen when booting DS games from flash card

### ISSUE THREAD

**Issue by onakaxy** [ahezard/nds-bootstrap#944]
**Your console:** N3DS
**Launch Method:** Luma 3DS, Launching from 3ds home menu, Luma 3ds is running version 10.1.3-3143e7e
**Version used:** Release
**Flashcart used:** M3DSreal
**Game tested/used/applicable:** Super mario 64 DS (From flash card) Rayman DS (From actuall game cart)

**Expected Behavior:** Both games should boot (Tested on other new3ds with Twilight menu++ and worked flawlessly
**Actual Behavior:** White screen and freezing on real game carts and black screen and freezing when booting the game from flash card. I can boot into the flash card however.

### Steps to reproduce

Booting any of the games from the DS classic menu will yield this ressult

**Comment by RocketRobz** [comment]
You ran TWiLight Menu++ from a flashcard?

**Comment by onakaxy** [comment]
no, im running my flash card from twilight menu++

**Comment by RocketRobz** [comment]
If you can't run games from your flashcard, try installing TWiLight Menu++ on a flashcard.

**Comment by onakaxy** [comment]
I can run them from my flash card on my other N3DS using twilight menu++ Version 12.1. And my bought game cards won't boot eighter from Twilight menu++ on the 3ds that has the flash card problem. They get the white screen and 4 yellow dots on the lower screen before crashing.

**Comment by RocketRobz** [comment]
This is a TWiLight Menu++ issue, and the issue is already known.
