### ISSUE TITLE
Devkitarm missing specifications file?

### ISSUE THREAD

**Issue by Pixelthegreat** [ahezard/nds-bootstrap#945]
when I try to compile a Nintendo DS project in devkitARM, I get an error saying `ds_arm9.specs: no such file or directory`. When I remove the flag `specs=ds_arm9.specs` from the makefile, I get a number of new errors:
`c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/9.1.0/../../../../arm-none-eabi/bin/ld.exe: warning: cannot find entry symbol _start; defaulting to 0000000000008010
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/9.1.0/../../../../arm-none-eabi/bin/ld.exe: C:/devkitPro/libnds/lib\libnds9.a(interrupts.o): in function `irqInitHandler':
/home/davem/projects/devkitpro/pacman-packages/libnds/src/arm9/../source/common/interrupts.c:125: undefined reference to `__irq_vector'
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/9.1.0/../../../../arm-none-eabi/bin/ld.exe: C:/devkitPro/libnds/lib\libnds9.a(interrupts.o): in function `irqInit':
/home/davem/projects/devkitpro/pacman-packages/libnds/src/arm9/../source/common/interrupts.c:148: undefined reference to `__irq_vector'
c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/9.1.0/../../../../arm-none-eabi/bin/ld.exe: C:/devkitPro/libnds/lib\libnds9.a(interruptDispatcher.o): in function `IntrRet':
/home/davem/projects/devkitpro/pacman-packages/libnds/src/arm9/../source/common/interruptDispatcher.s:55: undefined reference to `__irq_flags'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitARM/ds_rules:54: /opt/devkitpro/examples/nds/hello_world/hello_world.elf] Error 1
make: *** [Makefile:96: build] Error 2`. I did find a very similar question to this one that had the same or near the same errors. However, the fix was simply that in the makefile, he hadn't specified the specs file. What is going on and how can I fix it? Thanks in advance.

PS: I am running a 64-bit version of windows10 update 1909 on an amd64 processor.

**Comment by SuperSaiyajinStackZ** [comment]
And what does it have to do with nds-bootstrap?

**Comment by Pixelthegreat** [comment]
I am new I have no idea why this is in nds bootstrap

**Comment by Pixelthegreat** [comment]
OOOH i see now
