### ISSUE TITLE
Inazuma Eleven roms doesn´t save correctly

### ISSUE THREAD

**Issue by deik134** [ahezard/nds-bootstrap#946]
**Your console:** DSi
**Launch Method:** (No CFW) Unlaunch only (v2.0)
**Version used:** nds-bootstrap Release v0.35.1
**Flashcart used:** SD Card
**Game tested/used/applicable:** 5535 - Inazuma Eleven (Europe)

**Expected Behavior:** The rom saves the game and load the game correctly.
**Actual Behavior:** When you save the game it get stuck in the animation, in some roms that issue doesn´t happen but if you try to load the game it tells you that the save files are corrupted.

### Steps to reproduce

-Start the game
-Save the game
-If the rom does not get stuck or freeze start the game again and try to load the saved game

**Comment by Vivi20910** [comment]
do you use the "normal" or the patched version of inazuma eleven?

**Comment by RocketRobz** [comment]
This is most likely a save size issue.
The next TWLMenu++ version will fix this.
