### ISSUE TITLE
Guru Meditation Error when soft resetting in Pokémon Platinum

### ISSUE THREAD

**Issue by Leeo97one** [ahezard/nds-bootstrap#948]
**Your console:** 2DS (FTR-001)
**Launch Method:** Luma3DS: v10.1.3 ; TWiLight Menu++: v15.1.1
**Version used:** v0.35.1
**Game tested/used/applicable:** Pokémon - Version Platine (CPUF)

**Expected Behavior:** the game soft resets normally by holding L, R, Start, and Select.
**Actual Behavior:**
![image](https://user-images.githubusercontent.com/1344241/83279135-eed07900-a1d4-11ea-9b13-5eed1c2df1c7.png)

### Steps to reproduce

1. Put Pokémon Platinum on the SD card
2. Launch it from TWLMenu++
3. Hold L, R, Start, and Select
4. Observe a Guru Meditation Error after a short while

```ini
[NDS-BOOTSTRAP]
DEBUG = 1
LOGGING = 1
CACHE_FAT_TABLE = 0
ROMREAD_LED = 0
DMA_ROMREAD_LED = -1
CONSOLE_MODEL = 2
EXTENDED_MEMORY = 0
CACHE_BLOCK_SIZE = 0
PRECISE_VOLUME_CONTROL = 0
SOUND_FREQ = 1
NDS_PATH = sd:/nds/pokemon_platine.nds
SAV_PATH = sd:/nds/saves/pokemon_platine.sav
RAM_DRIVE_PATH = sd:/null.img
LANGUAGE = -1
DSI_MODE = 1
BOOST_CPU = 1
BOOST_VRAM = 1
DONOR_SDK_VER = 0
PATCH_MPU_REGION = 0
PATCH_MPU_SIZE = 0
CARDENGINE_CACHED = 1
FORCE_SLEEP_PATCH = 0
```

### Logs

[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4702894/NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
This is likely a TWLMenu++ issue.
idk why this happens, either way.

**Comment by Leeo97one** [comment]
And so? Should I open an issue on the TWiLightMenu repo? Do you want any additional information?

**Comment by RocketRobz** [comment]
Try re-installing TWiLight Menu++.

**Comment by Leeo97one** [comment]
OK, so it occurs when the "Slot-1 microSD access" setting is turned on (tested on old and new 2DS).
