### ISSUE TITLE
Black Screen when waking up Super Mario 64 DS

### ISSUE THREAD

**Issue by Pokemiah** [ahezard/nds-bootstrap#952]
**Your console:** New Nintendo 3DS XL
**Launch Method:** Luma 3DS with Twilight Menu++
**Version used:** Release
**Game tested/used/applicable:** Super Mario 64 DS, TID: ASMP

**Expected Behavior:** Game running normally with complete visibility after waking up 3DS from sleep mode.
**Actual Behavior:** After waking up from sleep mode, the screen is completely black but everything else is working including audio. Buttons still send input and the game is otherwise running fine even without the screen.

### Steps to reproduce

1. Boot up Super Mario 64 DS.
2. Close 3DS.
3. Open 3DS.
4. Now your screen is black, but the game is still running. Buttons are fully operational.

[nds-bootstrap.ini.txt](https://github.com/ahezard/nds-bootstrap/files/4708720/nds-bootstrap.ini.txt)

### Logs

[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4708718/NDSBTSRP.LOG)

### Other notes
It not only happens with a clean ROM but ROM hacks of Super Mario 64 DS are also affected. I have not experienced this issue with other games.

**Comment by RocketRobz** [comment]
You need to run with NTR clock speed for this issue to not occur.
