### ISSUE TITLE
New Super Mario Bros. “Lid Glitch”

### ISSUE THREAD

**Issue by CatsLover2006** [ahezard/nds-bootstrap#954]
**Your console:** New 3DS XL
**Launch Method:** TWiLight Menu++, Luma3DS, Boot9Strap
**Version used:** Release 0.35.1 (Patched in Nightly)
**Game tested/used/applicable:** New Super Mario Bros. USA

**Expected Behavior:**
I can close the lid, hear the “Bye, bye!” and that’s it until I re-open the kid and hear “It’s a me, Mario!”
**Actual Behavior:** When I close the lid, I hear those sounds looping. If it stops, TWL_FIRM has likely crashed.

### Steps to reproduce
**Note:** In TWiLight Menu++, I’ve set DSi mode, though it’s not forced. No cheats.

### Other notes
Like I said earlier, nighly has already patched this. I am just letting you know of an issue I found, so you can keep it from occurring in the future.

**Comment by CatsLover2006** [comment]
Close this issue once you take note of it, please.

**Comment by RocketRobz** [comment]
The issue is caused by certain Slot-1 carts, so the issue could also happen in Nightly.
You can either leave the slot empty, or turn on `Force sleep patch`.

**Comment by CatsLover2006** [comment]
FYI, this happens with 3DS carts.
