### ISSUE TITLE
Console repeatedly wakes and sleeps when closed

### ISSUE THREAD

**Issue by fennectech** [ahezard/nds-bootstrap#955]
**Your console:** N3DS
**Launch Method:** Luma3ds / twilightmenu++   
**Version used:** 11.13.0-45
**Game tested/used/applicable:** Ive tried various games  including pokemon hg/ss and sm64   The roms are trimmed so MD5 is pointless here
**Expected Behavior:** Consol should go to sleep when you close the screen
**Actual Behavior:** The game repeatedly stops and starts  However the display stays off   You even hear the bye and hello on sm64

### Steps to reproduce

Play for a bit
close console
sometimes the console will repeatedly sleep and wake

### Logs
(currently recreating it with debug logging enabled)

**Comment by RocketRobz** [comment]
Certain Slot-1 cards cause this.
Please turn on `Force sleep patch` in TWLMenu++ Settings.

**Comment by fennectech** [comment]
Will this prevent IR carts from working?

**Comment by RocketRobz** [comment]
No, it won't.
To use IR, make sure SELECT is set to SELECT menu, and that Slot-1 microSD access is turned off, in TWLMenu++ Settings.

**Comment by fennectech** [comment]
Thank you  Ill report back if this does not solve the issue :)

**Comment by fennectech** [comment]
Ir is suddenly not working  What do you mean "SD is set to SELECT menu?

**Comment by RocketRobz** [comment]
The SELECT button option for the DSi theme.

**Comment by fennectech** [comment]
Also The select menu thing doesnt need ti be set that way here  If you have it set to boot DSI menu first it will still work if you dont go to the DS classic menu
