### ISSUE TITLE
Touchscreen in snemulds dont working

### ISSUE THREAD

**Issue by nabilhoche** [ahezard/nds-bootstrap#956]
**Your console:** Old 3ds
**Launch Method:** Luma3ds
**Version used:** 11.13.0-45U
**Flashcart used:** I dont using flashcard,Only sd
**Game tested/used/applicable:** Snes games using Snemulds>

**Expected Behavior:** use the touchscreen to enter settings, options etc
**Actual Behavior:** by touching any option in the touchscreen nothing happens

### Steps to reproduce
-Launch any snes game
-Try to enter in any of the options on the touchscreen

Im using twilightmenu RocketRobz birthday version

**Comment by RocketRobz** [comment]
Unfortunately, I don't have this bug, and you seem to be the only one with this bug.
Make sure nds-bootstrap is on version 0.35.1 as well.

Does touch work anywhere else?
