### ISSUE TITLE
TRANSFER PKHEX SAVES TO TWILIGHT MENU

### ISSUE THREAD

**Issue by LordeJoey** [ahezard/nds-bootstrap#957]
I was playing Pokemon HeartGold on Drastic emulator on my cellphone and I edited the game on Pkhex, that I wanted to transfer to TwilightMenu++ on the DSi, in wich I haven't started a play through in Pokemon HeartGold, so I had to start again but my idea was that save I edited on Pkhex would make me start from where I last saved in Drastic, but that didn't happened. The Pkhex file is a .sav file that I copy into the saves folder in .nds ROMS but it doesn't seem to work. Can anyone help me out with this? I would really apreciated.

**Comment by RocketRobz** [comment]
Try pkmn-chest instead.

**Comment by LordeJoey** [comment]
Gonna give it a try and see how it works ^^

**Comment by LordeJoey** [comment]
Great! Is there any guide of how to use Pkmn-chest?

**Comment by Epicpkmn11** [comment]
> Great! Is there any guide of how to use Pkmn-chest?

[The wiki](https://github.com/Universal-Team/pkmn-chest/wiki) covers most stuff I think (I should check through and make sure its up to date...)

**Comment by LordeJoey** [comment]
Thanks, gonna check it.

**Comment by LordeJoey** [comment]
Ok, I managed to save the files on the _nds/pkmn-chest/out, but I don't figure how to inject them in the game, I checked and it took me to the normal intro.

**Comment by RocketRobz** [comment]
Just replace the .sav file in the `saves` folder, which is in the ROM location.

**Comment by SuperSaiyajinStackie** [comment]
if you mean injecting your dumped Pokémon files, then they should be inside the `in` Folder. Also I'd suggest to ask in the [Universal-Server's Discord Server](https://discord.gg/KDJCfGF) for support, since this is not nds-bootstrap related.

**Comment by LordeJoey** [comment]
Got it, thank you very much.

**Comment by RocketRobz** [comment]
I'll assume this has been fixed, so I'll close this.
