### ISSUE TITLE
Settings, game save files, and save states from SNEmulDS do not persist upon reloading with nds-bootstrap.

### ISSUE THREAD

**Issue by WhyModeratorsSuck** [ahezard/nds-bootstrap#958]
**Your console:** Nintendo DSi
**Launch Method:** <!-- TwilightMenu v15.0.1 loaded by Unlaunch 2.0
**Version used:** Release v0.35.1
**Card used:** SD card in DSi SD slot.
**Application used:** SNEmulDS v0.6alpha (MD5: AEDE9187DF0C15EEBA4D788E74346538, Download: https://www.gamebrew.org/images/3/37/SNEmulDSv06a.zip)
**Expected Behavior:** Emulator options, save files from SNES games run with the emulator, as well as save states created by the emulator should persist upon exiting the emulator.
**Actual Behavior:** All emulator settings, SNES save files and save states are gone upon reloading the emulator.

### Steps to reproduce

[nds-bootstrap.ini.txt](https://github.com/ahezard/nds-bootstrap/files/4733513/nds-bootstrap.ini.txt)
1. Load a game with save features in SNEmulDS.
2. Play until you reach a save point in the game.
3. Under "Advanced" in the emulator, hit the "Save SRAM" button as the emulator does not automatically save the SRAM.
4. You may also create some save states in the game and change options in the emulator.
5. Reload the emulator with nds-bootstrapper.
6. All your save states, settings, and game save files are gone.

### Logs

arguments passed
Running fat:/_nds/TWiLightMenu/emulators/SNEmulDS.nds
RAM 
disk: fat:/snes/Super Mario World (USA).sfc
RAM disk size: 80000
Running fat:/SNEmulDS.nds with 2 parameters

### Other notes

The emulator itself appears to load and run fine according to the logs, though the functionality of options, save states, and save files persisting is not present in the current release of nds-bootstrapper.

**Comment by RocketRobz** [comment]
There should already be an issue open for this.

**Comment by WhyModeratorsSuck** [comment]
I tried looking but I couldn't seem to find one that was open, only closed.

**Comment by WhyModeratorsSuck** [comment]
Nevermind, I was searching with the keyword "snes" and not SNEmulDS. I found the two issues open for this, though they seem to have been open for over a year. Guess this is something that is difficult to fix or is not really a priority

**Comment by NightYoshi370** [comment]
Let's keep this to #520
