### ISSUE TITLE
Credits in the end of Sonic's story in Sonic Rush become bugged and stop working.

### ISSUE THREAD

**Issue by IrisHeartCPU** [ahezard/nds-bootstrap#960]
**Your console:**  New Nintendo 2DS XL
**Launch Method:**  Twilight Menu 15.1.1
**Version used:**  nds-bootstrap 0.35.1
**Game tested/used/applicable:**  Sonic Rush

**Expected Behavior:**  The credits showing until the game ends, like in all of the games.
**Actual Behavior:** 
In Sonic Rush (Eur) after beating the final boss on the normal ending of Sonic's story, when the credits appear, they rapidly become bugged (Amy and Sonic become graphically bugged) and all stops moving, the music keeps playing, but the credits stop. I searched in this Github and i have the CPU in NTR to avoid crashing, so i don't know what to do, i cannot end his story because the bug doesn't let's me do it. (The first time they crashed the CPU was in TWL, now has crashed too in NTR)
### Steps to reproduce

 
[nds-bootstrap.zip](https://github.com/ahezard/nds-bootstrap/files/4740838/nds-bootstrap.zip)

(Added nds-bootstrap.ini inside a zip because the github didn't allow me to add the .ini itself)

1. Beat the final boss named as "Unknown" on Sonic's story, in the F-Zone
2. Wait for the credits
3. Profit.

### Logs

[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/4740833/NDSBTSRP.LOG)

**Comment by SleepyLark** [comment]
Can you upload the save file?  I wanna see if the same problem happens on the DSi

**Comment by IrisHeartCPU** [comment]
@SleepyLark here you have it 
[Sonic Rush sav.zip](https://github.com/ahezard/nds-bootstrap/files/4740844/Sonic.Rush.sav.zip)
(The github doesn't allow me to upload the .sav itself, so i uploaded inside of a .zip)

And, i uploaded the nds-bootstrap.ini (inside of a zip, same as the .sav) and the NDSBTSRP.LOG (the debug logging archive (or what i think is the archive of the debug logging) to the issue, hope all of that helps.

**Comment by IrisHeartCPU** [comment]
I've tested it on Desmume with the same rom and the same sav and it works perfectly and that bug doesn't appeared, so i can confirm the bug
 is on nds-bootstrap.
![Captura](https://user-images.githubusercontent.com/61751545/83953829-05657880-a844-11ea-9ea2-58663bf0d2ce.PNG)
![Captura2](https://user-images.githubusercontent.com/61751545/83953830-05fe0f00-a844-11ea-9ebc-a0b47e30dc7b.PNG)

**Comment by IrisHeartCPU** [comment]
I solved it (excepting the graphical glitch, but the credits glitch itself its solved, since i could end Sonic's story and see the full credits) setting  **_Expand ROM space in RAM_** to Yes+512Kb and _**Cache Block Size**_ to 32Kb
And not only that, also the game goes so much smoothly and fluid now.

**Comment by RocketRobz** [comment]
The `Expand ROM space in RAM` setting does not affect this issue.
