### ISSUE TITLE
Wierd artifact on bottom of screen

### ISSUE THREAD

**Issue by fennectech** [ahezard/nds-bootstrap#961]
**Your console:**
New 3ds
**Launch Method:** Luma3DS  11.13.0
**Version used:** 0.35.1
**Game tested/used/applicable:** Pokemon hg/ss and sm64.  All games are trimmed so md5sum is useless

**Expected Behavior:** Screen should look normal when opening a game
**Actual Behavior:** The bottom cm is repeated once. 

### Steps to reproduce

Simply open a game and once in a while the issue will occur

### Other notes
Closing and re opening the clamshell will cause the display to render normaly
![3D5E9F66-6361-482E-AA62-98BEE90F9CB4](https://user-images.githubusercontent.com/11953665/83960660-d6093880-a850-11ea-960c-8c5f6f693113.jpeg)

**Comment by RocketRobz** [comment]
This is a TWL_FIRM bug, not an nds-bootstrap bug.

**Comment by fennectech** [comment]
Is there a way to resolve it other than the workaround?

**Comment by RocketRobz** [comment]
TWL_FIRM itself would have to be hacked.

**Comment by fennectech** [comment]
Mk. So thats a not really.  Thanks for taking the time to answer this for me

**Comment by RinMaru** [comment]
so im guessing this cant be fixed or its somthing we should hope for in the future its also a problerm in AGB Firm

**Comment by piratesephiroth** [comment]
> 
> 
> so im guessing this cant be fixed or its somthing we should hope for in the future its also a problerm in AGB Firm

it's random. It happens on some builds and not on others even without major changes to the code,
Theoretically it could be fixed but I don't think anyone will bother.
Just close and reopen the 3DS and it will be gone.

**Comment by fennectech** [comment]
It happens randomly. Even without changing the build or settings.
