### ISSUE TITLE
Top and bottom screen flicker in Clubhouse Games

### ISSUE THREAD

**Issue by usbadapter** [ahezard/nds-bootstrap#967]
**Your console:** New 3DS
**Launch Method:** Luma3DS, TWiLightMenu++
**Version used:** Release v0.35.1
**Game tested/used/applicable:** Clubhouse Games

**Expected Behavior:** The screens don't flicker
**Actual Behavior:** The top display would flicker what's displayed on the bottom screen and the bottom screen would flicker what's displayed on the top screen

### Steps to reproduce

1. Run Clubhouse Games

**Comment by RocketRobz** [comment]
What region is the ROM?

**Comment by usbadapter** [comment]
(U) and 16,384 KB

**Comment by SleepyLark** [comment]
Have you tired changing the CPU speed to NTR?  I'm pretty that's why it's flickering

**Comment by usbadapter** [comment]
> Have you tired changing the CPU speed to NTR? I'm pretty that's why it's flickering

turning the cpu speed to NTR fixed it
