### ISSUE TITLE
SoulSilver

### ISSUE THREAD

**Issue by tetradog** [ahezard/nds-bootstrap#968]
**Your console:** New 3DS XL
**Launch Method:** Luma lastest versión
**Version used:**Release 

**Expected Behavior:** 
**Actual Behavior:** 

### Steps to reproduce

it happens when you enter a new map through a door, but it doesn't always happen ... the black screen stays and it doesn't advance ...

**Comment by NightYoshi370** [comment]
1) I think there's already an issue open for this
2) You haven't given us any versions beyond "latest" and "release", which isn't helpful.

Please give logs as well.
