### ISSUE TITLE
order of ds games in launcher

### ISSUE THREAD

**Issue by c0d3x7** [ahezard/nds-bootstrap#970]
How can I switch the order of the nds games inside the launcher?

**Comment by RocketRobz** [comment]
This is posted in the nds-bootstrap repo.
Is this a TWiLight Menu++ question, or one for the stock DSi Menu?

**Comment by c0d3x7** [comment]
I don't know...

**Comment by RocketRobz** [comment]
Then it's TWiLight Menu++ question.
You can set `Custom` order in TWLMenu++ Settings.

Closing, as this is not an nds-bootstrap issue.
