### ISSUE TITLE
WarioWare D.I.Y won't save my games

### ISSUE THREAD

**Issue by hatoving** [ahezard/nds-bootstrap#974]
I started normally playing the game, and tried to "save" a game on the shelf.
But when i went to look and play for it, it wasn't there!  The game itself and everything else works perfectly fine! Help!

**Your console:** New 2DS XL
**Launch Method:** I'm using Luma 3DS, Version 10.1.3-3143e7e. I used TwillightMenu++ and i laiunched it pretty nomarly, no errors or anything
**Version used:** Release, v0.35.1. I don't know how to send the hash, i don't even know what it is
**Game tested/used/applicable:** MD5: 04425EC09F2D4AC57051FD67CABD478B Title ID: UORP

**Expected Behavior:** The game should've saved the games on the DIY Games shelves
**Actual Behavior:** When it told me it saved, the game isn't at the shelve at all.

### Steps to reproduce

1: Launch the game
2: Create any game and then ship it
3: Go to the D.I.Y Games section from the shop
4: There's no game

nds-bootstrap.ini: [nds-bootstrap.zip](https://github.com/ahezard/nds-bootstrap/files/4880512/nds-bootstrap.zip)

### Logs

findModuleParamsOffset:
Module params offset restored: 02000BB8
sdk_version: 04027539
This rom is not compressed

Switched to NTR mode BIOS
old heap pointer: 02257600

new heap pointer: 02258E00

Heap Shrink Sucessfull

relocate_ce9
firstCardLocation 02257600 : 02780000

armReadCardLocation 022576F4 : 02780000

thumbReadCardLocation 02257710 : 02780000

armReadCardDmaLocation 02257740 : 02780000

armReadSlot2Location 02257764 : 02780000

armSetDmaCardLocation 02257798 : 02780000

thumbReadCardDmaLocation 022577D0 : 02780000

thumbSetDmaCardLocation 022577F0 : 02780000

armReadNandLocation 0225781C : 02780000

thumbReadNandLocation 02257848 : 02780000

armWriteNandLocation 02257870 : 02780000

thumbWriteNandLocation 02257890 : 02780000

armIrqEnableLocation 022578C0 : 02780000

thumbIrqEnableLocation 022578E0 : 02780000

pdashReadLocation 0225790C : 02780000

thumbReadSlot2Location 02257930 : 02780000

ipcSyncHandlerLocation 02257970 : 02780000

resetLocation 0225799C : 02780000

globalCardLocation 02258CCC : 02780000

 ce9->patches 02257638

patchCardNds

swi12 location : 02000742

cardIrqEnable location : 02093440

startOffset : 02003800

cardRead location : 0209E45C

cardPullOut location : 0209E864

cardId location : 0209E54C

patchCardSetDma
cardReadDma location : 0209E2D0

patchMpuSize: 00000000

ERR_NONE

Arm7 (patch vAll)
forwardedRelocStartAddr
02380204
vAddrOfRelocSrc
0238021C
Relocation src: 0238021C
Relocation dst: 037F8000

JumpTableFunc: 0238B5F0
Eeprom read:	0238B5FC
Eeprom page write:	0238B610
Eeprom page prog:	0238B624
Eeprom verify:	0238B638
Eeprom page erase:	0238B648
swi12 location : 0238BA30

swiGetPitchTable location : 02386FE8

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 0238F780

ERR_NONE
hookLocation arm9: 027E0000

chipID: 80007FC2

**Comment by SleepyLark** [comment]
Already a known issue (#306, #675).  This game has a unique way of saving that not many games use
