### ISSUE TITLE
IR doesn't work in DSi

### ISSUE THREAD

**Issue by sapfel93** [ahezard/nds-bootstrap#976]
**DSi XL** 
**Unlaunch** 
**35.1 Release** 
**Pokemon Black 2 (would likely apply to other games)** 

**Expected Behavior:** An IR connection would be established
**Actual Behavior:** It doesn't

### Steps to reproduce

Tried to connect Pokemon Black 2 w/ ndsbootstrap on dsi with same game on 3ds to exchange keys and it would not link. Also tested it on dsi with ndsbootstrap and 3ds with real cartridge and would not connect. The issue doesn't affect 3ds as it works as intended there. 

### Other notes

I tried it with both Soul Silver and White in DS slot on dsi. Neither worked in ndsbootstrap. Also slot 1 microsd access is off on dsi.

**Comment by RocketRobz** [comment]
Is the SELECT button set to show the SELECT menu, instead of the DS Classic Menu?

**Comment by sapfel93** [comment]
That seemed to have worked. Thank you.

**Comment by Hawkeye1005** [comment]
I've been having the same issue and I can't get it to work. Both black 2 and white 2 are using nds-boostrap, and I've tried with both settings, but I still can't send and receive keys.
