### ISSUE TITLE
Game saves could not be loaded

### ISSUE THREAD

**Issue by ITz-Xeno** [ahezard/nds-bootstrap#977]
**Your console:** O3DS
**Launch Method:** I'm using Luma updated to the latest version and Twilight menu ++ and nds-bootstrap both updated to the latest version
**Version used:** release, latest
**Game tested/used/applicable:** 
3794-Pokemon Platinum (CPUI)
**Expected Behavior:** once saved the game should start again
**Actual Behavior:** when I save the game and reopen it, I get a screen saying: Communication error, press A to continue. But if I press A the problem persists

### Steps to reproduce
1.open Twlight menu++
2.open pokemon platinum
3.pissed off because he doesn't read the game save XD

### Other notes
the rom and game save works perfectly on other emulators, both for pc and android.
other games like inazuma eleven 2, mario kart ds and pokemon white version work perfectly.

**Comment by RocketRobz** [comment]
Make sure you're running in DS mode.
If you don't know how to set that, then I assume you're already running in DS mode.
Also, see if you can connect to WiFi in the DS WiFi settings in those games.

**Comment by ITz-Xeno** [comment]
I'm already in DS mode. When I try to search for a network through the DS settings, it seems that everything hangs and does not go on

**Comment by RocketRobz** [comment]
Does WiFi work outside of TWLMenu++?

**Comment by ITz-Xeno** [comment]
Yeah

**Comment by RocketRobz** [comment]
Go into TWLMenu++ Settings, and see what nds-bootstrap version is displayed.

**Comment by ITz-Xeno** [comment]
0.35.1

**Comment by RocketRobz** [comment]
Try DS WiFi Settings in 3DS System Settings.

**Comment by ITz-Xeno** [comment]
wait .. is there a DS wifi settings in twlmenu ++?XD Because I always tried to connect from the 3DS settings through DS settings

**Comment by RocketRobz** [comment]
Nope, there isn't.
Try deleting `settings.ini` in `sd:/_nds/TWiLightMenu/`.

**Comment by ITz-Xeno** [comment]
Same problem

**Comment by RocketRobz** [comment]
Does this issue happen with your retail DS carts?

**Comment by ITz-Xeno** [comment]
Nope

**Comment by RocketRobz** [comment]
When did you install TWLMenu++?

**Comment by ITz-Xeno** [comment]
the first time I installed it was a year ago, however every time I opened a game, it only showed me a blank screen and so I let it go. A month ago I solved the problem, the games work perfectly, but pokemon platinum continues to give me this problem

**Comment by RocketRobz** [comment]
Try re-installing.

**Comment by ITz-Xeno** [comment]
I've done it many times

**Comment by ITz-Xeno** [comment]
can you try to see if it gives you the same problem?  the game is the italian version of pokemon platinum

**Comment by RocketRobz** [comment]
I don't have this problem.

**Comment by RocketRobz** [comment]
Download and extract the file in [nds-bootstrap-nightly.zip](https://github.com/ahezard/nds-bootstrap/files/4919415/nds-bootstrap-nightly.zip) to `sd:/_nds/`, then switch `Bootstrap` to `Nightly.`

**Comment by ITz-Xeno** [comment]
Same problem

**Comment by RocketRobz** [comment]
Unfortunately, there seems to be no issue for your solution.

**Comment by RocketRobz** [comment]
Unfortunately, there seems to be no solution for your issue.

**Comment by ITz-Xeno** [comment]
No problem, thanks for everything
