### ISSUE TITLE
I keep getting Error 1 on DSi Please Help Me

### ISSUE THREAD

**Issue by VersedRhyme41** [ahezard/nds-bootstrap#979]
**Your console:** Nintendo DSi
**Launch Method:** TWiLightMenu++/Lenny/v15.3.0
**Version used:** I Actually Tried Both Nightly and Release!
**Game tested/used/applicable:** I’m trying ROM-Hacks Such as Super Mario Galaxy DS

**Expected Behavior:** Should or Booted Right Up
**Actual Behavior:** Got Error 1

**Comment by RocketRobz** [comment]
You seem to be missing nds-bootstrap somehow.
Download it from the release page.

**Comment by VersedRhyme41** [comment]
Wdym? I have it, Tell me the name of the file

**Comment by RocketRobz** [comment]
`nds-bootstrap-release.nds` and `nds-bootstrap-hb-release.nds`

**Comment by VersedRhyme41** [comment]
Yes I have those, where should I put them

**Comment by RocketRobz** [comment]
Just told you: `sd:/_nds/`

**Comment by RocketRobz** [comment]
What does the error screen look like, exactly?

**Comment by VersedRhyme41** [comment]
Oh I did that and there’s still errors when I try both release and nightly

**Comment by VersedRhyme41** [comment]
It shows 
Start Failed. Error 1
nds-bootstrap (Nightly) or ( release)
not found

**Comment by RocketRobz** [comment]
Let's continue this in this server: https://discord.gg/yD3spjv
