### ISSUE TITLE
Unable to Launch GBA titles using twilight menu. "start failed error 1 nds-bootstrap not found"

### ISSUE THREAD

**Issue by Jmmartin22** [ahezard/nds-bootstrap#980]
**Your console:**  New Nintento 2DS XL
**Launch Method:** Luma3DS
**Version used:** 2.5
**Flashcart used:** No
**Game tested/used/applicable:**  Any GameBoy Advance Game

**Expected Behavior:**  GBA Games should launch using twilight menu
**Actual Behavior:**  When trying to launch any GBA game using the Twilight Menu, I get a error of "start failed error 1 nds-bootstrap not found". This only occurs for GBA Games. I have tried three different titles and they all produce the same error. I have tried DS titles and GBC titles through Twilight and they launch Successfully

### Other notes
Hey Guys, Im new at this so I apologize if I missed some details. I just modded my New 2DS XL using the guide at https://3ds.hacks.guide. I then installed the Twlight menu so i can play some old GBC and GBA Games. GBC and NDS games are working, however, when I try to launch any GBA game I get a error of "start failed error 1 nds-bootstrap not found". I tried 3 GBA games and they all produced the same error. Would anyone know what the issue could be?

**Comment by RocketRobz** [comment]
You're missing the hb nds-bootstrap build.
Download nds-bootstrap from the release page, and follow instructions there.

**Comment by Jmmartin22** [comment]
Would that be v0.35.1?

**Comment by RocketRobz** [comment]
Yes.

**Comment by Jmmartin22** [comment]
Awesome! It worked. Many thanks for your help ( And  prompt replies!)

**Comment by RocketRobz** [comment]
No problem!
