### ISSUE TITLE
NSMB real hard crash. 3DS firmware also "crashes"?

### ISSUE THREAD

**Issue by Haxorzz** [ahezard/nds-bootstrap#986]
**Your console:** New 3ds
**Launch Method:** Luma CFW running the latest 3ds update and launching via twilight menu++
**Version used:** Release
**Game tested/used/applicable:** New super mario bros.

**Expected Behavior:** Tapping "minigames" should put me in the minigames list
**Actual Behavior:** Game freezes... 3ds goes dark and shows: "An error has occurred please hold down the power button to turn the system off. Please refer to the Operations Manual for details"
After restarting and openin gup twilight menu++ again it will instantly boot up and show the minigames list

### Steps to reproduce
Launch a NSMB rom. Click "Minigames". Wait...

### Logs
findModuleParamsOffset:
Module params offset restored: 02000B64
sdk_version: 03007532
This rom is compressed

Switched to NTR mode BIOS
patchCardNds

swi12 location : 020006CE

cardIrqEnable location : 020434A8

startOffset : 02000000

cardRead location : 020773BC

cardPullOut location : 02077BBC

cardId location : 02077358

patchCardSetDma
cardReadDma location : 020774BC

patchMpuSize: 00300000

Mpu init: 0206EA30

reset location : 0206EE88

ERR_NONE

Arm7 (patch vAll)
forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000

JumpTableFunc: 0238BFC8
Eeprom read:	0238BFD4
Eeprom page write:	0238BFEC
Eeprom page prog:	0238C004
Eeprom verify:	0238C01C
Eeprom page erase:	00000008
swi12 location : 0238C4A0

swiGetPitchTable location : 02387750

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 023902D4

ERR_NONE
hookLocation arm9: 027E0000

ROM loaded into RAM

chipID: 00001FC2

(A bunch of empty space I had to delete)

### Other notes
None

**Comment by RocketRobz** [comment]
Install the TWiLight Menu++ Game booter CIA.

**Comment by Haxorzz** [comment]
What game booter CIA?

**Comment by Haxorzz** [comment]
Aight Ill test that

**Comment by Haxorzz** [comment]
@RocketRobz thanks
