### ISSUE TITLE
How do I switch to DS mode to run a DSi enhanced game

### ISSUE THREAD

**Issue by firemouse4965** [ahezard/nds-bootstrap#987]
I am using the OLD 2ds and I'm wondering on how to switch my mode to DS mode so I can run my DSi enhanced game (pkmn bw2). I heard that you can only play it on DS mode and I have no idea how to switch it.

**Comment by RocketRobz** [comment]
If you never changed a setting called `Run in`, then you're already using DS mode.

**Comment by firemouse4965** [comment]
I trying to use it on my homescreen. All the other games seem to work fine but, whenever I try playing the game it leaves me with a black and white screen.

**Comment by RocketRobz** [comment]
Check the FAQs in the forwarder thread, for your issue.

**Comment by firemouse4965** [comment]
Ok can you leave me with a link?

**Comment by RocketRobz** [comment]
It's the same link you followed to create the forwarders.

**Comment by firemouse4965** [comment]
What does "that the ROM was dragged from the SD card, and not from the PC" mean? Should the rom already be in my SD card?

**Comment by RocketRobz** [comment]
It's saying to drag the ROM from the SD card into the Forwarder3-DS window.

**Comment by firemouse4965** [comment]
Thank you so much it finally worked! Thanks for making all this stuff!

**Comment by RocketRobz** [comment]
You're welcome!
Please visit [this](https://discord.gg/yD3spjv) server, if you want future support.
