### ISSUE TITLE
Black and white screen

### ISSUE THREAD

**Issue by HDJDeadfur** [ahezard/nds-bootstrap#988]
**Your console:** DSi
**Launch Method:** Twilight
**Version used:** o.35.1
**Flashcart used:**
**Game tested/used/applicable:** Pokemon black ver2

**Expected Behavior:** load the game
**Actual Behavior:** loading screen, then black and white, then all white until I turn off the dsi

**Comment by RocketRobz** [comment]
You need to change `Run in` back to `DS mode`.

**Comment by HDJDeadfur** [comment]
It's on run in DS mode, Ive also tried it on DSi mode and forced DSi mode. Also, ver1 works for me and a few other roms, so it's that game specifically

**Comment by RocketRobz** [comment]
Sounds to me like your ROM is corrupted. That, or cheats are turned on.

**Comment by HDJDeadfur** [comment]
How would I turn off cheats? And I thought that too so I tried playing the ROM off the as card on my phone and it did run, just very slowly (my phone isn't very good)
