### ISSUE TITLE
Kung Fu Panda DS not working

### ISSUE THREAD

**Issue by Bezerker7234** [ahezard/nds-bootstrap#992]
**Your console:** New Nintendo 3ds xl
**Launch Method:** Luma3ds
**Version used:** Release
**Game tested/used/applicable:** Kung Fu Panda

**Expected Behavior:** Game loads and shows title screen
**Actual Behavior:** Shows Black screen on top screen and white on the bottom screen

### Steps to reproduce
open ROM in twilight menu++

### Logs

findModuleParamsOffset:
Module params offset restored: 02000B80
sdk_version: 04007531
This rom is not compressed

old heap pointer: 020B3420

new heap pointer: 020B4C20

Heap Shrink Sucessfull

relocate_ce9
firstCardLocation 020B3420 : 02780000

armReadCardLocation 020B3514 : 02780000

thumbReadCardLocation 020B3530 : 02780000

armReadCardDmaLocation 020B3560 : 02780000

armReadSlot2Location 020B3584 : 02780000

armSetDmaCardLocation 020B35B8 : 02780000

thumbReadCardDmaLocation 020B35F0 : 02780000

thumbSetDmaCardLocation 020B3610 : 02780000

armReadNandLocation 020B363C : 02780000

thumbReadNandLocation 020B3668 : 02780000

armWriteNandLocation 020B3690 : 02780000

thumbWriteNandLocation 020B36B0 : 02780000

armIrqEnableLocation 020B36E0 : 02780000

thumbIrqEnableLocation 020B3700 : 02780000

pdashReadLocation 020B372C : 02780000

thumbReadSlot2Location 020B3750 : 02780000

ipcSyncHandlerLocation 020B3790 : 02780000

resetLocation 020B37BC : 02780000

globalCardLocation 020B4AEC : 02780000

 ce9->patches 020B3458

patchCardNds

swi12 location : 020002F8

cardIrqEnable location : 020077B4

startOffset : 02000000

cardRead location : 0200196C

cardPullOut location : 02001EC8

cardId location : 02001A54

patchCardSetDma
cardReadDma location : 02001808

patchMpuSize: 00000000

ERR_NONE

Arm7 (patch vAll)
forwardedRelocStartAddr
02380198
vAddrOfRelocSrc
023801B0
Relocation src: 023801B0
Relocation dst: 037F8000

JumpTableFunc: 0238C54C
Eeprom read:	0238C558
Eeprom page write:	0238C570
Eeprom page prog:	0238C588
Eeprom verify:	0238C5A0
Eeprom page erase:	0238C5B4
swi12 location : 0238C928

swiGetPitchTable location : 00000000

ERR_NONE

hookNdsRetailArm7
hookLocation arm7: 02390480

ERR_NONE
hookLocation arm9: 027E0000

chipID: 80001FC2

### Other notes

turned on debug and logging

**Comment by RocketRobz** [comment]
Removed the link to the ROM side, as it's copyrighted content.
Also, try turning off heap shrink in the per-game settings.

**Comment by Bezerker7234** [comment]
k

**Comment by Bezerker7234** [comment]
worked thanks
