### ISSUE TITLE
nds-boostrap(release) not found

### ISSUE THREAD

**Issue by mrbearatethekids** [ahezard/nds-bootstrap#994]
**Your console:** dsi
**Launch Method:**  latest release
**Version used:**  release
**Game tested/used/applicable:** GbaRunner2

**Expected Behavior:**  Pokemon Fire Red should of booted
**Actual Behavior:**  gave me a white screen telling me nds-boostrap(release) not found press b to go back

**Comment by RocketRobz** [comment]
What guide did you follow to install TWLMenu++?

**Comment by SleepyLark** [comment]
1. This is a support question and should be asked on our Discord instead 
2.  You didn't copy the files correctly, you're missing `nds-bootstrap-hb`.  Try reinstalling.

**Comment by mrbearatethekids** [comment]
tech james guide



Sent from Samsung tablet


-------- Original message --------

**Comment by RocketRobz** [comment]
Regardless of TWLMenu++ version, you should follow [this](https://github.com/DS-Homebrew/TWiLightMenu/wiki/How-to-update-TWiLight-Menu).
