### ISSUE TITLE
TWL Mode not working on nds-bootstrap

### ISSUE THREAD

**Issue by ParodZetec** [ahezard/nds-bootstrap#999]
**Your console:** New 3DS XL and DSi XL (All platforms are suspected)
**Launch Method:** Unlaunch (TWLoader selected to boot when powering on the console) / Luma3DS + Twilight Menu ++ CIA (latest)
**Version used:** Release (latest)
**Game tested/used/applicable:** Any DSi Enhanced games (Tried 5th Gen Pokémon and Alice in Wonderland. EUR versions)
**Expected Behavior:**  Booting the selected game with TWL mode
**Actual Behavior:** "An error has occurred" red text on nds-bootstrap boot screen. Games can work on NTR mode
### Steps to reproduce
[nds-bootstrap.ini.txt](https://github.com/ahezard/nds-bootstrap/files/5098562/nds-bootstrap.ini.txt) (Remove .txt from filename)
Only booting the selected affected game

### Logs

[NDSBTSRP.LOG](https://github.com/ahezard/nds-bootstrap/files/5098550/NDSBTSRP.LOG)

### Other notes

As said before, NTR mode works perfectly and no more unexpected issues happened. I don't know what could be wrong as I did not change any setting (TWL mode was default). Greets and hope I get a solution 😄

**Comment by Epicpkmn11** [comment]
There's already an issue for this fyi, #300 ;P

**Comment by NightYoshi370** [comment]
Closing due to duplicate. Please use #300 instead

**Comment by ParodZetec** [comment]
Didn't see that... my apologies 😞
